### ISSUE TITLE
Scrolling using Magic Keyboard does not work on iPad.

### ISSUE THREAD

**Issue by SJang1** [cdr/code-server#3080] opened 2021-04-09 01:25 UTC
## OS/Web Information

- Web Browser: Safari
- Local OS: iPadOS 14.4.2(18D70) / iPad Pro 2nd gen 11inch
- Remote OS: Ubuntu 20.04
- Remote Architecture: x64
- `code-server --version`: 3.9.3 fe2dc2deb08e378069891b622bb62ad1d261d1b1

## Steps to Reproduce

1. Open Safari, and go into code-server
2. Open any tab that contains something available to scroll (Even Source code area is affected.)
3. Try to scroll using the magic keyboard's touchpad.

## Expected

It should scroll.

## Actual

It doesn't scroll at all.

## Screenshot

Video I am trying to scroll on the source code.
~~This code can be opened, it is just example code that school sent me~~

https://user-images.githubusercontent.com/29011440/114115126-3a879f00-991d-11eb-9b48-c1928097818a.mp4

Video I am trying to scroll on Source Control tab.

https://user-images.githubusercontent.com/29011440/114114902-c4833800-991c-11eb-8ab9-1147f076d3f9.mp4

## Notes

This issue can be reproduced in VS Code: There is no VS Code on iPad.

The "Magic Keyboard" that I am talking here is [This one (apple.com)](https://www.apple.com/shop/product/MXQT2LL/A/magic-keyboard-for-ipad-air-4th-generation-and-ipad-pro-11-inch-2nd-generation-us-english). not the magic keyborad for mac.

**Comment by oxy** [comment] 2021-04-09 04:52
Duplicate of #1455 - closing.
Hopefully iOS 14.5 fixes it, from what is in the other issue :crossed_fingers:

**Closed by oxy** 2021-04-09 04:52 UTC
Labels: browser-safari, bug, os-ios
