### ISSUE TITLE
Unable to paste into terminal using Ctrl + V

### ISSUE THREAD

**Issue by watkinsmatthewp** [cdr/code-server#1113] opened 2019-10-25 19:43 UTC
- `code-server` version: v10.15.1
- OS Version: Red Hat Enterprise Linux Server release 5.3 (Tikanga)

## Description

I just upgraded my installed code-server instance today. It used to be that I could Ctrl+C and Ctrl+V to copy/paste on the terminal. Now when I try to copy with Ctrl+C, the app throws a JS error:

```
workbench.web.api.js:2474 TypeError: Cannot read property 'writeText' of undefined
    at Proxy.writeText (workbench.web.api.js:2803)
    at e.copySelection (workbench.web.api.js:3905)
    at async P.run (workbench.web.api.js:5720)
    at async Object.triggerAndDisposeAction (workbench.web.api.js:2499)
    at :9000/async http:/{my-ip}:9000/static-e7945bea94b5c35f2c3475a9344212c900d4adb1/out/vs/workbench/workbench.web.api.js:2499
```

Likewise when I try to paste, I get the following:

```
workbench.web.api.js:2474 TypeError: Cannot read property 'readText' of undefined
    at Proxy.readText (workbench.web.api.js:2803)
    at e.paste (workbench.web.api.js:3907)
    at re.run (workbench.web.api.js:5729)
    at Object.triggerAndDisposeAction (workbench.web.api.js:2499)
    at :9000/async http:/{my-ip}/static-e7945bea94b5c35f2c3475a9344212c900d4adb1/out/vs/workbench/workbench.web.api.js:2499
```

It looks like Ctrl+Insert and Shift+Insert still work for copying/pasting, though, so it's not the end of the world.

On the previous version, I noticed that Chrome showed a clipboard icon indicating that the app has access to the clipboard. I do not see it in this install.

## Steps to Reproduce

1. Try to copy some text from the terminal with Ctrl+C
1. Try to paste some text to the terminal with Ctrl+V

**Comment by watkinsmatthewp** [comment] 2019-10-25 21:51
Side note, may be relevant: I just got an error trying to paste into the editor window as well: "command 'editor.action.clipboardPasteAction' not found"

**Comment by sr229** [comment] 2019-10-26 00:43
Duplicate of #237

**Closed by sr229** 2019-10-26 00:43 UTC
Labels: bug
