### ISSUE TITLE
Workspaces Not Saving or Opening Properly

### ISSUE THREAD

**Issue by act3602281** [cdr/code-server#490] opened 2019-04-11 21:41 UTC
- Running Coder in docker on a mac and tested on Centos VM

## Description
When I try to create or work in a workspace it is opening like a folder instead of a file. The workspace name shows up for me still as "Untitled" and the workspace below it the has the name of the workspace I tried to open. This causes terminal etc to index in the wrong spots etc.

If i try to save a workspace to create a new one, I see the save issues.
## Steps to Reproduce

1. File
2. Save Workspace as
3. Save File enter a path: /home/test
4. The workspace now shows up properly as "test"
5. Try to add a folder to the workspace
6. The workspace name now changes to "Untitled", with the name of the workspace now in the folder spot. This breaks indexing and plugins etc.

**Comment by act3602281** [comment] 2019-04-11 21:42
<img width="1101" alt="Screen Shot 2019-04-11 at 5 41 34 PM" src="https://user-images.githubusercontent.com/30268775/55994929-2141ae80-5c81-11e9-916d-1b039f6955f4.png">

**Comment by act3602281** [comment] 2019-04-11 21:59
This also causes Project plus to not work as without any root or folders defines it gets a URI error.

**Comment by cy91244** [comment] 2019-04-12 09:09
I believed that the workspaces functionality is not implemented yet.

**Comment by tobiasbeck** [comment] 2019-05-21 06:10
Any news on when this will be solved?
We are still on version 1.604-vsc1.32.0, because we rely on opening multiple folders.

**Comment by deansheather** [comment] 2019-06-09 03:42
Duplicate of #196.

**Closed** 2019-07-12 03:23 UTC
Labels: bug

**Comment by hendersonh** [comment] 2020-01-03 21:59
I was evaluating for my school's computer lab, but will drop it and moved on as work-space functionality is not working: having the ability to have more than one workspace. Code-server can take off (especially in schools teaching environment if this issue can be resolved.
