### ISSUE TITLE
Cant get code-server --link to work in termux

### ISSUE THREAD

**Issue by AirplanegoBrr** [cdr/code-server#3400] opened 2021-05-17 03:39 UTC
## OS/Web Information

- Web Browser:
- Local OS: Andriod 8.1.0 using termux
- Remote OS: Firefox windows10
- Remote Architecture: ??
- `code-server --version`: 3.10.0 f9b6d04cab0463c487e0390fc73e902e1f83a99

## Steps to Reproduce

1. Install with `yarn add global code-server`
2. do code-server --link Get error

## Expected

Code server would start and I would be able to get a code server link

## Actual

I get a error spawn?

## Logs

[2021-05-17T03:31:04.291Z] info  code-server 3.10.0 f9b6d04cab0463c487e0390fc73e902e1f83a99e
[2021-05-17T03:31:04.298Z] info  Using user-data-dir ~/.local/share/code-server
[2021-05-17T03:31:04.385Z] info  Using config file ~/.config/code-server/config.yaml
[2021-05-17T03:31:04.386Z] info  HTTP server listening on http://127.0.0.1:56772/ (randomized by --link)
[2021-05-17T03:31:04.386Z] info    - Authentication is disabled (disabled by --link)
[2021-05-17T03:31:04.387Z] info    - Not serving HTTPS (disabled by --link)
[2021-05-17T03:31:04.419Z] error spawn /data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/coder-cloud-agent ENOENT

## Screenshot
![image](https://user-images.githubusercontent.com/71111395/118429487-a67cc600-b686-11eb-8b46-4017c719b62f.png)

## Notes

I have tried to downgrade to 9.3.0 but Im getting a diff error (and I can post in comments what it was or edit this) 

the normal `code-server` command does work but I would like to be able to acceses it from my computer/outside my network

**Comment by AirplanegoBrr** [comment] 2021-05-17 06:44
And yes I am using termux from f-driod

**Comment by jsjoeio** [comment] 2021-05-17 14:50
I believe this is a duplicate of https://github.com/cdr/code-server/issues/3342

We're aware of the error and working on a fix. Please follow that issue for updates.

**Comment by AirplanegoBrr** [comment] 2021-05-17 16:38
Shouldn't downgrading work? (I'm not home rn so I can't test) The last time I downgraded I was getting a different error... I believe I downgraded to version 9.3 I believe?

**Comment by code-asher** [comment] 2021-05-17 17:09
Does `/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/coder-cloud-agent` exist?

If it does then `coder-cloud-agent` probably doesn't work on Termux. I think there are specific steps we have to take to make it work there.

**Comment by code-asher** [comment] 2021-05-17 17:11
Also, right now it always pulls the latest cloud agent regardless of the version but we should probably pin the version.

**Closed** 2021-05-19 14:50 UTC
Labels: duplicate
