### ISSUE TITLE
Copy and Paste in iPadOS doesn’t work properly.

### ISSUE THREAD

**Issue by FYLSunghwan** [cdr/code-server#1439] opened 2020-03-22 03:35 UTC
## Description
I’m using iPadOS 13.4 latest beta (GM), but copy & paste through keyboard shortcut(cmd+c cmd+v) or right click to copy doesn’t work.
And when I press paste button on the context menu, it always shows the iOS’ native paste button.

## Steps to reproduce
1. Drag some text
2. Right click to the text
3. Press copy or paste button in context menu
3-1. Or Cmd+C and Cmd+V

**Comment by GalacticLion7** [comment] 2020-03-22 05:14
I'm having the same issue here. This is an issue from Apple's port of the macOS Safari WebKit to iPadOS. It's also impossible to use a lot of the other shortcuts of the interface that would otherwise work on a desktop or laptop.

**Comment by nhooyr** [comment] 2020-03-22 16:25
Closing as a duplicate of #1015.

**Comment by nhooyr** [comment] 2020-03-22 16:26
> Also, sometimes I'm not able to write any text into a file. The cursor just stays there and do nothing.

As in no input is registered at all?

**Closed by nhooyr** 2020-03-22 16:25 UTC

**Comment by kennymatic** [comment] 2020-10-16 21:06
> As in no input is registered at all?

No input is registered at all. Switching to another document tab seems to get the input going again.
