### ISSUE TITLE
When accessing to code-server CPU usage goes crazy high on the Server side

### ISSUE THREAD

**Issue by SJang1** [cdr/code-server#3215] opened 2021-04-26 02:08 UTC
## OS/Web Information

- Web Browser: Firefox 88.0
- Local OS:MacOS big sur 11.2.3(20D91)
- Remote OS:Ubuntu 20.04 LTS
- Remote Architecture: x64
- `code-server --version`: 3.9.3 fe2dc2deb08e378069891b622bb62ad1d261d1b1

## Steps to Reproduce

1. run code-server
2. access to code-server

## Expected
Just runs well

## Actual
CPU usage for code-server (node) goes up to over 100% (over 1 cpu full)
If accessing 2 clients, 2 node goes up to over 100%,
Also if 3, 3 node goes up to over 100% (It is 300% for now)
.....And gets bigger and bigger, Server PC fan goes incredibly run fast...

## Screenshot

<img width="1261" alt="screenshot with 1 connected" src="https://user-images.githubusercontent.com/29011440/116059780-2d5c0580-a6bc-11eb-96ee-dbcd50d7d635.png">
<img width="1252" alt="screenshot with 2 connected" src="https://user-images.githubusercontent.com/29011440/116066171-ba09c200-a6c2-11eb-80fe-91449c59cb15.png">

## Notes

This issue can be reproduced in VS Code: maybe no

**Comment by jsjoeio** [comment] 2021-04-26 17:41
I am the same setup:
- code-server 3.9.3
- Firefox 89.0b2 (64-bit)
- macOS Big Sur11.2.2 (20D80)

and I am not seeing similar CPU usage (well checking the Activity Monitor):

## Screenshot

![image](https://user-images.githubusercontent.com/3806031/116126647-bd2d8f80-a67b-11eb-8be1-3ee8dcec735c.png)

A couple thoughts:
- can you try disabling all extensions in code-server and seeing if the same issue occurs?
- have you tried uninstalling and reinstalling code-server?

I'm also happy to check the CPU usage the same way you did if you include those steps in your reproduction steps.

**Comment by SJang1** [comment] 2021-04-27 02:59
Oh, I didn't wrote that CPU usage going high is on the Remote OS, not the Local OS. (Server ubuntu)

After doing both disableing all extensions and reinstalling code-server, it came back to normal. 

And, I found that this happened after enable the python extension.

**Comment by jsjoeio** [comment] 2021-04-27 16:56
Glad to hear it came back to normal. 

> And, I found that this happened after enable the python extension

If that's the case, then it probably makes sense to file an issue upstream. There may be one already though. See [here](https://github.com/microsoft/vscode-python/issues?q=is%3Aissue+is%3Aopen+cpu+usage).

It sounds like it's more of an extension issue than a code-server issue so I think we should close this but let me check with @code-asher - thoughts?

**Comment by code-asher** [comment] 2021-04-27 21:16
Yeah at first glance I would think this is likely an extension issue as well. High CPU load seems to be a common issue in their tracker.

**Closed** 2021-04-28 00:20 UTC
Labels: wontfix

**Comment by SJang1** [comment] 2021-04-28 07:16
Yes, found out that it is a Python Extension bug.
Downgraded to 2020.11.~~ and it now works... Hmmm..

**Comment by demetera** [comment] 2022-12-19 20:34
Fresh installation. 2 extensions are installed (Nim and Code runner). And this happening. Raspberry Pi 4 (automatic installation)

![image](https://user-images.githubusercontent.com/3475944/208516305-70f285bd-09ef-46f9-b37b-2fc653137933.png)

**Comment by sojs-coder** [comment] 2024-04-07 19:15
Same problem for me, extensions installed are github copilot (installed from vsix), HTML snippets and Gitlens.

I believe copilot is the problem.

Everything works fine until I try to visit the extensions panel.
