### ISSUE TITLE
Cannot show image while path has chinese character

### ISSUE THREAD

**Issue by tqtiwvfdn** [cdr/code-server#1539] opened 2020-04-17 06:11 UTC
Hello , i wanna report a question that the code-server version 3.1.0 cannot show image while path has chinese character，like this：

```
https://localhost:8080/webview//vscode-resource/file///home/test/demo/example/%E6%8A%A5%E6%96%87%E6%A0%BC%E5%BC%8F%E9%85%8D%E7%BD%AE.PNG?version=1587102870978
```

**Comment by code-asher** [comment] 2020-04-17 16:35
Thanks for the bug report! I think this is a duplicate of #1514 so we'll track this issue there.

**Closed by code-asher** 2020-04-17 16:35 UTC
