### ISSUE TITLE
[v2] initial press of open folder not working right

### ISSUE THREAD

**Issue by antofthy** [cdr/code-server#1051] opened 2019-10-04 01:35 UTC
- `code-server` version: 2.1523-vsc1.38.1
- OS Version: Docker on RH7 running Debian Buster (php-apache base image)

## Description

Open folder does not seem to work properly...

Example:  I start code-server in "/var/www"
```
code-server --port 8443 --auth password --cert ""
```
Connect to it using a browser... press the blue "Open Folder"
And I get a popup listing the current folder, but with "/var" in input bar, instead of  "/var/www" directory that is displayed.   Press 'OK' does nothing until I correct the input field by adding the missing "www".

Here is a screen shot (firefox browser)
![capture_open_folder](https://user-images.githubusercontent.com/1214656/66174928-c4a4d680-e69a-11e9-8414-4994e59bb081.png)
The situation is confusing and not good for users (students)...

Currently I am resolving this by getting code-server to pre-open '.' as an working directory argument to the code-server startup.
 ```
code-server . --port 8443 --auth password --cert ''
```
Just reporting to let you know of this finding.

**Comment by sr229** [comment] 2019-10-04 03:14
I use this feature a lot and I am not precisely sure what's wrong with it because during pre-alpha builds it was working as intended.

**Comment by code-asher** [comment] 2019-10-22 19:23
I think this is the same issue described in #1063. This issue is older but I'll close it as a duplicate because I think the title of the other issue is a bit more inclusive.

**Closed by code-asher** 2019-10-22 19:23 UTC
Labels: question
