### ISSUE TITLE
code-server terminal sets `LD_LIBRARY_PATH` variable. which breaks other tools

### ISSUE THREAD

**Issue by Merith-TK** [cdr/code-server#1757] opened 2020-06-02 18:27 UTC
- Web Browser: Firefox
- Local OS: Windows
- Remote OS: Arch
- Remote Architecture: X86_64
- `code-server --version`: 3.4 (latest AUR)

the problem is that code-server sets this variable in the terminal `LD_LIBRARY_PATH=/usr/lib/code-server/bin/../lib` which causes programs such as ffmpeg to fail 
```
ffmpeg: /usr/lib/code-server/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/lib/libvmaf.so)
ffmpeg: /usr/lib/code-server/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/libvmaf.so)
ffmpeg: /usr/lib/code-server/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/libmfx.so.1)
ffmpeg: /usr/lib/code-server/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/libmodplug.so.1)
ffmpeg: /usr/lib/code-server/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/libsrt.so.1)
ffmpeg: /usr/lib/code-server/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/libsrt.so.1)
ffmpeg: /usr/lib/code-server/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/libx265.so.188)
```

when i ssh and run the conversion tool i wrote (converting some mp4s to run on my DSi using homebrew)
it runs with out issue and `LD_LIBRARY_PATH` var is not set
![image](https://user-images.githubusercontent.com/10422110/83555985-02752b80-a4c4-11ea-92c3-74928e9d8365.png)

the rest of the terminal is normal ffmpeg output

**Comment by meain** [comment] 2020-06-03 14:54
This is causing a lot of issues, even apt fails to run.
```
$ apt
apt: /usr/local/bin/code-server/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libapt-private.so.0.0)
apt: /usr/local/bin/code-server/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libapt-pkg.so.5.0)
```

**Comment by nhooyr** [comment] 2020-06-03 16:19
Will be fixed in https://github.com/cdr/code-server/pull/1761

Marking this as a duplicate of https://github.com/cdr/code-server/issues/1738

**Closed by nhooyr** 2020-06-03 16:19 UTC
