### ISSUE TITLE
“npm ERR!” during code-server npm install

### ISSUE THREAD

**Issue by GalacticLion7** [cdr/code-server#1906] opened 2020-07-23 02:59 UTC
```
~# npm install -g code-server
npm WARN @coder/logger@1.1.11 requires a peer of @google-cloud/logging@^4.5.2 but none is installed. You must install peer dependencies yourself.

npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path /usr/lib/node_modules/code-server/node_modules/tar-fs/node_modules/chownr
npm ERR! dest /usr/lib/node_modules/code-server/node_modules/tar-fs/node_modules/.chownr.DELETE
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/code-server/node_modules/tar-fs/node_modules/chownr' -> '/usr/lib/node_modules/code-server/node_modules/tar-fs/node_modules/.chownr.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-23T02_52_12_426Z-debug.log
~#
```
[/root/.npm/_logs/2020-07-23T02_52_12_426Z-debug.log](https://hastebin.com/wakafuliye.pl)

**Comment by Adebesin-Cell** [comment] 2020-07-23 14:25
npm WARN deprecated tslint@6.1.2: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

**Comment by Adebesin-Cell** [comment] 2020-07-23 14:26
How do I solve the error?

**Comment by GalacticLion7** [comment] 2020-07-23 14:29
@Adebesin-Cell please open a separate issue for that.

**Comment by nhooyr** [comment] 2020-08-04 11:22
@GalacticLion7 Please try latest master again.

Also, your link doesn't show the logs for me unfortunately.

<img width="907" alt="Screen Shot 2020-08-04 at 7 22 04 AM" src="https://user-images.githubusercontent.com/10180857/89288179-33d4b980-d623-11ea-8c69-051bd98cc753.png">

**Comment by nhooyr** [comment] 2020-08-31 06:14
Any updates @GalacticLion7

**Comment by markpanado** [comment] 2020-09-28 11:42
Having the same issue on Alpine Linux

**Comment by GalacticLion7** [comment] 2020-10-09 12:41
@nhooyr here's a new link: https://transfer.sh/U1MPP/2020-10-09T12_38_39_831Z-debug.log

Sorry for the late response.

**Comment by code-asher** [comment] 2020-10-09 15:43
I've seen this before but I'm not sure what causes it (I think it might
be related to being root). Does it happen if you try again? What if you
use yarn instead of npm?

**Comment by stefanhenseler** [comment] 2020-12-13 20:29
@code-asher having the same issue, using yarn v1.22.5. I'm using the following command `yarn global add code-server@3.7.4`. I've tried it using root and coder user, no difference. I always get the same error:

`
yarn global v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "code-server > @coder/logger@1.1.16" has unmet peer dependency "@google-cloud/logging@^4.5.2".
[4/4] Building fresh packages...
`

My alpine container finishes building, but when I start the application, obviously it crashes due to the missing dependency. I tried installing the peer dependency manually, but the current version is 9.0.0 and yarn crashes when I try to install 4.5.2.

**Comment by code-asher** [comment] 2020-12-14 16:47
The `google-cloud/logging` library is an optional dependency our logger
supports but we don't use it in code-server so it won't be the cause of
this issue unfortunately.

So the installation is completing for you, but when you launch
code-server it crashes, right? Could you post code-server's logs so we
can see what it says during the crash?

**Comment by stefanhenseler** [comment] 2020-12-14 18:20
@code-asher I think I didn't read properly. In my case it was just missing some libraries I guess as explained in the npm install manual. Here what worked for me:

```
RUN apk upgrade -U -a && \
    apk add libxkbfile-dev libsecret-dev libx11-dev \
    && rm -rf /var/cache/* \
    && mkdir /var/cache/apk
RUN yarn global add typescript
RUN yarn global add code-server
```

**Comment by code-asher** [comment] 2020-12-15 16:04
Awesome, glad you got it working! I think we plan to add some code that
will check to make sure system dependencies are installed.

**Comment by nhooyr** [comment] 2020-12-15 20:47
Opened https://github.com/cdr/code-server/issues/2474!

**Closed** 2020-12-15 20:47 UTC
Labels: waiting-for-info

**Comment by stefanhenseler** [comment] 2020-12-15 20:53
I actually switched back to centos... since alpine doesn't seem to be the best choice when it comes to using it as a code-server base image. Just so many things that are just a bit more work compared to other distros, mainly due to musl vs. glibc. For example, getting Tensorflow to work is just not as easy.

**Comment by mrfoxie** [comment] 2021-02-16 17:37
> @code-asher I think I didn't read properly. In my case it was just missing some libraries I guess, as explained in the npm install docs. Here what worked for me on Alpine 3.12:
> 
> ```
> RUN apk upgrade -U -a && \
>     apk add libxkbfile-dev libsecret-dev libx11-dev \
>     && rm -rf /var/cache/* \
>     && mkdir /var/cache/apk
> RUN yarn global add typescript
> RUN yarn global add code-server
> ```
I tried this process but it got stuck on `yarn global add code-server`

![Screenshot_2021_0216_230540](https://user-images.githubusercontent.com/25217451/108100281-b7c82d80-70ab-11eb-94be-9f896ed37b45.png)

**Comment by mudrii** [comment] 2021-06-27 08:01
I have same problem building code-server 3.10.2

I try to update nixpks and getting same error related to @google-cloud/logging@^4.5.2

```
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @coder/logger@1.1.16" has unmet peer dependency "@google-cloud/logging@^4.5.2".
warning " > gulp-tsb@4.0.6" has incorrect peer dependency "typescript@^3.0.0".
[4/4] Building fresh packages...
warning Ignored scripts due to flag.
Done in 13.68s.
error: builder for '/nix/store/2ppw5w73f1f3rmfdd3my4nx89qp8c985-code-server-3.10.2-x86_64-linux-yarn-cache.drv' failed with exit code 123;
       last 10 log lines:
       > Done in 1.21s.
       > yarn install v1.22.10
       > [1/4] Resolving packages...
       > [2/4] Fetching packages...
       > [3/4] Linking dependencies...
       > warning " > @coder/logger@1.1.16" has unmet peer dependency "@google-cloud/logging@^4.5.2".
       > warning " > gulp-tsb@4.0.6" has incorrect peer dependency "typescript@^3.0.0".
       > [4/4] Building fresh packages...
       > warning Ignored scripts due to flag.
       > Done in 13.68s.
       For full logs, run 'nix log /nix/store/2ppw5w73f1f3rmfdd3my4nx89qp8c985-code-server-3.10.2-x86_64-linux-yarn-cache.drv'.
```

**Comment by code-asher** [comment] 2021-06-28 16:59
The @google-cloud/logging warning can be ignored. It's an optional
dependency of our logger that we don't use.

We may need to see the full logs to figure out what went wrong. Please
feel free to open a new issue with the logs!
