### ISSUE TITLE
Windows support is coming soon is not really soon

### ISSUE THREAD

**Issue by victorwitkamp** [cdr/code-server#978] opened 2019-09-13 18:15 UTC
I would be very happy with Windows support :)

**Comment by sr229** [comment] 2019-09-13 23:09
We're gonna be working on it but there's more demand with ARM support so that's one of the focuses I have for now. We'll see if we can get the CI tp build Windows releases as well

**Comment by code-asher** [comment] 2019-10-23 22:05
Closing as a duplicate of #259.

**Closed by code-asher** 2019-10-23 22:05 UTC
Labels: feature
