### ISSUE TITLE
How to change current open files ?

### ISSUE THREAD

**Issue by xiangnanscu** [cdr/code-server#866] opened 2019-07-22 14:19 UTC
## Description
Every time I open code-server, it always opens several fix files : `package.json`, `ide.conf` and so on. I just want the code-server to remember which files I left open when closing the browser tab and open them when I use code-server again. 
I've tried the following but doesn't work:
1.  fresh the page
2. reboot the server

**Comment by deansheather** [comment] 2019-07-24 09:38
Duplicate of #801. This should be fixed pretty soon (as part of our v2).

**Closed by deansheather** 2019-07-24 09:38 UTC
Labels: question
