### ISSUE TITLE
Cannot add folder to create workspace

### ISSUE THREAD

**Issue by HenryHK** [cdr/code-server#724] opened 2019-05-28 06:32 UTC
- `code-server` version: 1.1119-vsc1.33.1
- OS Version: Ubuntu 18.04 LTS, AWS

## Description

![Kapture 2019-05-28 at 16 28 40](https://user-images.githubusercontent.com/3992997/58455816-f2ff2c00-8165-11e9-9c6b-2909884eccda.gif)

## Steps to Reproduce

1. Open a folder
2. Add another folder to workspace

Looks like there is no error logs in console which is really strange.

**Comment by erwinverdonk** [comment] 2019-05-28 09:33
Duplicate of #687

**Closed** 2019-05-28 23:26 UTC
Labels: bug
