### ISSUE TITLE
Can't install python extension

### ISSUE THREAD

**Issue by moxuz** [cdr/code-server#987] opened 2019-09-16 17:55 UTC
- `code-server` version: 1.1156
- OS Version: Digital Ocean deployed with the button.  Ubuntu 18.04
- Extension: https://marketplace.visualstudio.com/items?itemName=ms-python.python

## Description

I am having trouble installing the python vscode extension, it looks like the vscode version is too outdated or something. I've seen people waiting for "v2" is that something coming out soon that would fix this?
Error is unable to find version compatible with `1.33.1`

## Steps to Reproduce

1. Click deploy on DigitalOcean
2. Try to install Python extension once deployed

**Comment by sr229** [comment] 2019-09-17 00:01
Please use v2. v1 is deprecated and will be replaced by v2 soon.

**Comment by sr229** [comment] 2019-09-17 00:02
Duplicate of #697 as well so closing.

**Closed by sr229** 2019-09-17 00:02 UTC

**Comment by shahidul56** [comment] 2019-09-21 01:46
same for the prerelease v2,  python extension is not working,  debug also not working + can't able to change python version also
![fewf](https://user-images.githubusercontent.com/11449967/65366289-a6bf8680-dc43-11e9-8885-6f10b9c7bbe6.PNG)
