### ISSUE TITLE
External mouse on ipad only work partial

### ISSUE THREAD

**Issue by janiversen** [cdr/code-server#3599] opened 2021-06-11 18:30 UTC
When you use an external mouse on an iPad that runs code-server via safari, the mouse is very limited.
The mouse in question is an apple mouse (from my iMac) and works perfectly with all other application (including safari).
problem 1)
Scroll with mouse is ignored (works with touch)
problem 2)
Click+hold to select text with the mouse do not work. It will not allow a selection of more than 1 word (works with touch).

If someone can give me a code pointer, I am ready to do some more detailed testing and at least provide a more technical detailed PR.

## OS/Web Information

- Web Browser:
Safari 
- Local OS:
Raspbian buster
- Remote OS:
IPadOS 14.5
- Remote Architecture:
- `code-server --version`:

3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005

## Steps to Reproduce

1.
Scroll with the mouse (wheel on older mice, and touch on newer ones)
2.
Click + hold to select text 
3.

## Expected

It should be possible to scroll with the mouse and do copy/paster

## Actual
I have a self signed certificate, so that part is not the problem.

## Notes

This issue can be reproduced in VS Code: Yes/No

**Comment by jsjoeio** [comment] 2021-06-15 17:14
Thanks for the issue! 

Closing as a duplicate of https://github.com/cdr/code-server/issues/3203

> If someone can give me a code pointer, I am ready to do some more detailed testing and at least provide a more technical detailed PR

If you post in the other issue, I'd be happy to see what info I can provide for helping fix it!

**Closed by jsjoeio** 2021-06-15 17:14 UTC
