### ISSUE TITLE
Unable to install 'vscodevim.vim' extension because it is not compatible with the current version of VS Code (version 1.51.1).

### ISSUE THREAD

**Issue by hakanu** [cdr/code-server#2554] opened 2021-01-10 03:53 UTC
- Web Browser: Version 87.0.4280.141 (Official Build) (64-bit)
- Local OS: Windows 10
- Remote OS: Raspbian Lite Debian 10
- Remote Architecture: Arm 32 bit.
- `code-server --version`:  code-server 3.8.0

Hello I have a clean installation of the code server recently on my raspberry pi. First thing I need to do is installing vim extension. However, it doesn't seem to be working  with the most recent version of the coder. 

Probably blocking: https://github.com/cdr/code-server/issues/2502

**Comment by code-asher** [comment] 2021-01-11 17:20
Thanks for opening. Duplicate of #2319 I think. Hopefully will have a release this week with the fix!

**Closed by code-asher** 2021-01-11 17:20 UTC
