### ISSUE TITLE
Unable to connect with --link

### ISSUE THREAD

**Issue by accesstechnology-mike** [cdr/code-server#2708] opened 2021-02-10 17:05 UTC
#2704 isn't resolved, sorry.

```
code-server --link
[2021-02-10T16:53:51.032Z] info  HTTP server listening on http://**127.0.0.1**:32947 (randomized by --link)
```

There no way `--link` can access my server at 127.0.0.1, as it's hosted remotely. It _only_ works on 0.0.0.0.

I normally launch code-server using the `--host 0.0.0.0` flag to enable this, however I would like to make use of `--link` which currently only launches with a host of 127.0.0.1 (internal/local network).

**Comment by jsjoeio** [comment] 2021-02-10 18:04
To make sure I'm hearing you correctly, you would like to be able to set the `host` flag with `--link`?

**Comment by accesstechnology-mike** [comment] 2021-02-10 18:13
> To make sure I'm hearing you correctly, you would like to be able to set the `host` flag with `--link`?

Yes, I would expect to run:

`code-server --host 0.0.0.0 --link`

Thanks, Mike

**Comment by code-asher** [comment] 2021-02-11 16:19
Have you accessed the URL that `--link` outputs?

It is not necessary for code-server to bind to 0.0.0.0. The cloud agent
proxies to code-server and runs on the same machine so it's able to
access code-server at 127.0.0.1. I hope that helps explain it!

If you have access the URL that `--link` outputs and it's not working
please post details on the error you're getting. Thanks!

**Comment by code-asher** [comment] 2021-02-11 16:25
One other detail that might help understand how this works is that the agent dials out to the cloud rather than having a request come into the server like how a traditional reverse proxy functions. This is why the cloud agent will work even all incoming ports are firewalled off.

**Comment by accesstechnology-mike** [comment] 2021-02-18 11:08
Well --link doesn't work on my Digital Ocean instance for some reason:

```
Error connecting to your code-server instance
Ensure code-server is running and was properly started with the --link command line flag.

If you would like to talk to a developer, drop a message in our slack channel.
```

'code-server' also doesn't work without --host=0.0.0.0 so I presumed the 2 were related

**Comment by code-asher** [comment] 2021-02-18 16:37
Ahhh yeah I see where you're coming from! Did it give you an error ID? We can use that to investigate why it won't connect. There might also be more information from code-server's output when running with `--log debug`.

**Comment by accesstechnology-mike** [comment] 2021-02-18 16:47
Where can I find the log output please? Terminal says this:
```
code-server --link --log debug
[2021-02-18T16:39:29.914Z] info  code-server 3.8.1 41ad0c0c4c14df78e1bfa3a44d8b633ed2fc26e5
[2021-02-18T16:39:29.921Z] info  Using user-data-dir ~/.local/share/code-server
[2021-02-18T16:39:29.953Z] info  Using config file ~/.config/code-server/config.yaml
[2021-02-18T16:39:29.954Z] info  HTTP server listening on http://127.0.0.1:35163 (randomized by --link)
[2021-02-18T16:39:29.954Z] info    - Authentication is disabled (disabled by --link)
[2021-02-18T16:39:29.955Z] info    - Not serving HTTPS (disabled by --link)
[2021-02-18T16:39:29.956Z] debug running agent with bind,--code-server-addr=127.0.0.1:35163,
[2021-02-18T16:39:32.786Z] info  Proxying code-server to Coder Cloud, you can access your IDE at https://dev-name.cdr.co
```

**Comment by code-asher** [comment] 2021-02-18 17:27
Yes that's the output! If it doesn't output anything while trying to connect with the browser then there won't be any more information on the code-server end and we'll have to try investigating from the cloud side.

**Comment by SamHep0803** [comment] 2021-02-20 16:52
Ok, so after a bit of testing on my end, it seems that you have to be in the same "region" as the server you are trying to connect to. I tried with a droplet running on Lon-1 servers and it wouldn't work until I turned on my VPN and set the region to London. Tried the same thing with New York, and it wouldn't work without a VPN and without setting my region to New York. It could just be a coincidence, but I have a feeling that's not the case.

**Comment by accesstechnology-mike** [comment] 2021-02-20 18:41
Thanks. I'm on Lon1 and in the UK.

I'm 98% certain it's the host IP, as **I cannot connect on 127.0.0.1**:8080 (when launched without --link), I can only connect on 0.0.0.0:8080, but --link will _only_ launch on 127.0.0.1 - so there's absolutely no way any service will be able to connect! 

Please consider that it might be the 127.0.0.1 IP,  and that being able to define the port as 0.0.0.0 on launching with link, as well as fixing this issue, might also open up benefits to other users.

Many thanks.

**Comment by SamHep0803** [comment] 2021-02-21 02:42
I honestly don't think it has much to do with the host IP, as the whole point of the --link flag is to setup all of the TLS, Auth etc... And if you just access the server via 0.0.0.0, you aren't getting all the benefits of setting it up with a domain and a cert. 

I have a feeling that Coder Cloud was made in the same way ngrok works, where it can take any port and tunnel that to another server and then serve that to you as a separate IP/domain and I have a feeling it's this system not working that's making it so that we can't join.

Just my 2 cents on it though ¯\_(ツ)_/¯

**Comment by accesstechnology-mike** [comment] 2021-02-21 11:06
Yes, absolutely. I want to use the TLS Auth etc that the link flag offers,
but if code-server is only run on an inaccessible host IP when using it,
what's the point of it? It can't 'link'!

It's such a simple thing, no idea why no one is listening... I'll try to
break it down simply again:

1. I can't connect remotely when code-server running on the default
127.0.0.1 - *this is very important, as it is the whole issue.*

2. When I set the --host ip to 0.0.0.0 I can connect! Please note, this
isn't my actual IP address, it's the IP the code-server app is running on
within my server.

- *Again, really really important. 127.0.0.1 is for local connections, but
I'm not local. I accessing it remotely. Which is kinda the point of
code-server. 0.0.0.0 allows for remote connections. Super important point. *

*- OK, got it. 127.0.0.1 is useless for remote access, but luckily there's
a super useful host flag option to change the IP to 0.0.0.0*

3. I'd like to use the link flag.

4. When setting the link flag, code-server ignores the host flag and will
*only* run on 127.0.0.1 - so it doesn't work. See point 1 above.

- *oh no! That's madness! Because 127.0.0.1 is only for local connections!
Why oh why does it ignore the --host flag, and not let you set the host IP
to 0.0.0.0 like the non-link instance of code-server? Seems to be a huge
oversight, but presumably really easily fixed. *

- *the console says randomising port (that's OK) and running on
127.0.0.1:port - if only it would say running on 0.0.0.0:port - it would
make no difference to the app running on this IP, but ALL the difference to
accessing this self-hosted app, running in a browser window, remotely! *

5. Therefore, I would really really like link to let me set a host flag so
code-server will run on ip 0.0.0.0 so link has the ability to connect.

Thanks.

**Comment by SamHep0803** [comment] 2021-02-21 13:28
That's not how link works.

When you start code-server with the link flag, it automatically sets a random port on localhost that link can use to tunnel all of the data to one of Coder's servers. Setting --host is redundant as it's sending the data somewhere, not somewhere trying to fetch the data itself.

However what does need to be fixed is the issue with the "Error connecting to your code-server instance" error. Note: this error does not have anything to do with the --host flag.

**Comment by accesstechnology-mike** [comment] 2021-02-21 13:40
OK, let's fix that.

Please can you also advise how the default IP of 127.0.01 is meant to work,
and why my might not be?

**Comment by SamHep0803** [comment] 2021-02-21 14:28
Because when you go to the URL that code-server spits out when you run it with the link flag, the domain is not pointing to the IP of your server but rather a Coder Cloud server that is getting it's data from the server where the code-server instance is running. 

The reason I don't think the error has anything to do with the it running on localhost is the fact that the data is being tunneled FROM your server TO the coder cloud server, NOT the other way around.

**Comment by accesstechnology-mike** [comment] 2021-02-21 14:32
OK, why then does it say:

HTTP server listening on http://127.0.0.1:35163 (randomized by --link)

in the terminal?

Seems to imply I've started an HTTP server, much like it does when I launch
it without --link?

**Comment by SamHep0803** [comment] 2021-02-21 14:34
Because if it were running in a way that you were able to access localhost, you would be able to connect to it via localhost AND link. But it doesn't apply in this case, and link tunnels the information on port 35163 (in your case) to their servers.

**Comment by accesstechnology-mike** [comment] 2021-02-21 14:37
OK.

What can we do to debug the info not flowing from my instance to the link
server?

For reference, this happens consistently on multiple installations (Digital
Ocean, Lon 1): both the standard 127.0.01 install does not work (no Nginx
etc) and link doesn't work.

**Comment by SamHep0803** [comment] 2021-02-21 14:39
I think the only thing we can do is wait for the Coder Cloud devs to take a look at their server and try and have a look as suggested by @code-asher .

**Comment by accesstechnology-mike** [comment] 2021-02-21 14:43
OK.

Would you advising how launching the app is meant to work (not using link)
on the default 127.0.0.1? Is it assumed to be behind a webserver?

**Comment by SamHep0803** [comment] 2021-02-21 14:45
Are you talking about if you wanted to access the server without needing link? 

If so, you would need to follow the docs about setting up nginx/let's encrypt depending on which one you choose.

**Comment by accesstechnology-mike** [comment] 2021-02-21 15:02
OK, so the default is designed to be behind a webserver? When running with
0.0.0.0 I can connect direct.

Does link require a webserver on my instance?

**Comment by SamHep0803** [comment] 2021-02-21 15:08
No, link should do everything for you. By the way, code-server is a webserver.

**Comment by accesstechnology-mike** [comment] 2021-02-21 15:13
Yes, I understand, but the default IP of 127.0.0.1 implies you're expecting
it to be behind another one. Am I mistaken?

**Comment by SamHep0803** [comment] 2021-02-21 15:14
Yes, [read.](https://github.com/cdr/code-server/blob/v3.9.0/docs/guide.md#lets-encrypt)

**Comment by accesstechnology-mike** [comment] 2021-02-21 18:41
Thanks. Just so I'm completely clear, when using --link, is it expected
that code-server will be behind a webserver too?

**Comment by SamHep0803** [comment] 2021-02-22 02:38
In all honesty, I'm not really sure what you mean by "behind a webserver".

Code-server is *the* webserver, it's the thing that serving all of the data to the browser. You run it on localhost so that nginx or whatever can use the port to make a reverse proxy which has a certificate, making the connection secure. Very oversimplified though.

**Comment by accesstechnology-mike** [comment] 2021-02-22 09:04
Sorry, I did mean, when using the --link flag is it also expected that my
installation will be behind a reverse proxy? (Nginx / Caddy etc.)

**Comment by SamHep0803** [comment] 2021-02-22 09:36
No, link is not supposed to be running behind a reverse proxy, it was
created to eliminate the need for one.

**Comment by code-asher** [comment] 2021-02-22 20:32
@accesstechnology-mike This might help: https://github.com/google/inverting-proxy#inverting-proxy-and-agent

We don't use this specific implementation but it explains what an inverting proxy is which is what `--link` is.

In particular the important point is:

> The backends do not need to be exposed to incoming requests from the proxy. In particular, the backends can run in different networks without needing to expose them to incoming traffic from the internet

**Comment by SamHep0803** [comment] 2021-02-23 02:54
This is good and all, but there is no fix to the issue that has been
plaguing both me and the other people trying to use link.

Can we get an update on what has been done to try and figure out what the
issue is?

Thanks, Sam.

**Comment by code-asher** [comment] 2021-02-23 16:14
Does it give you an error ID?

**Comment by accesstechnology-mike** [comment] 2021-02-23 16:15
No

**Comment by SamHep0803** [comment] 2021-02-23 16:18
https://github.com/cdr/code-server/issues/2708#issuecomment-781266503

To be specific, this is the error, with no details left out.

**Comment by accesstechnology-mike** [comment] 2021-02-23 16:26
Yes

**Comment by code-asher** [comment] 2021-02-23 18:52
Although we don't know yet if everyone's issues are caused by the same problem I'm going to close this in favor of https://github.com/cdr/code-server/issues/2734 for now so we can track progress in one place.

**Closed by code-asher** 2021-02-23 18:52 UTC
Labels: bug
