### ISSUE TITLE
I want open a file when code-server startup

### ISSUE THREAD

**Issue by synuwxy** [cdr/code-server#851] opened 2019-07-15 12:14 UTC
I want open a file when code-server startup
but i can not find any command about that
where should I need to find these commands?

**Comment by debuggermalhotra** [comment] 2019-08-04 09:40
You figured it out?

**Comment by deansheather** [comment] 2019-08-05 03:23
This is currently not supported.

**Comment by frank-dspeed** [comment] 2019-09-17 16:19
i think now it is supported via ?file= @deansheather ?

**Comment by nhooyr** [comment] 2020-01-28 01:39
Duplicate of #164

**Closed by nhooyr** 2020-01-28 01:39 UTC
Labels: enhancement
