### ISSUE TITLE
Login page AND proxy redirection to a subpath

### ISSUE THREAD

**Issue by StudioEtrange** [cdr/code-server#875] opened 2019-07-27 22:41 UTC
- `code-server` version: 1.1156-vsc1.33.1
- OS Version: bare metal, linux, centos7

## Description

There is a problem when I combine a setup behind a proxy AND when I use the password feature.

My nginx setup redirect `http://host/vscode` to `http://host:port/` of vscode.

If I launch the server with `--no-auth` everything is ok, but without it I am always redirected to `host:port/login` like if `/login` was hardcoded.

**Comment by deansheather** [comment] 2019-07-28 23:10
Unfourtunately this is currently not supported, but there's a feature request for supporting it. Duplicate of #241.

**Closed by deansheather** 2019-07-28 23:10 UTC
Labels: bug
