### ISSUE TITLE
No file encoding button display

### ISSUE THREAD

**Issue by xiaoyun94** [cdr/code-server#1437] opened 2020-03-21 16:42 UTC
VS code has a button at the bottom to switch file encode type, such as gbk, utf8, but it does not show up tn code server. i have tried in my os deepin 15.10, open suse 15.1, suse server 12 sp3, all of them were missing this func. but i found ur shortcuts have this button, so i am wondering why this func is missing in my OSs.

**Comment by xiaoyun94** [comment] 2020-03-21 17:56
V3 matters.
V1 works well

**Comment by kylecarbs** [comment] 2020-03-23 18:33
Thanks for the report. We should definitely support multiple file-encoding types.

**Comment by gnouts** [comment] 2020-04-03 10:28
This is a blocker for me.
If I try to use v1 I'm stuck with this bug https://github.com/cdr/code-server/issues/338
And v2 and v3 doesn't offer to change encoding.
I try changing the settings.json with `"files.encoding": "windows1252"` but it doesn't seem to do anything.
Is there a workaround to change encoding ? (I really need to open files with special char like ¤ )

**Comment by code-asher** [comment] 2020-04-07 21:51
https://github.com/microsoft/vscode/issues/79275

**Comment by kylecarbs** [comment] 2020-04-09 01:26
@gnouts sorry to hear. We can definitely fix this if enough interest arises. For now, unfortunately it's a pretty low-priority issue.

Feel free to take a stab at it thought, we'd happily merge your contribution :)

**Comment by xiaoyun94** [comment] 2020-04-23 12:08
a sad story for Chinese developers

**Comment by Shagrat2** [comment] 2020-05-08 09:01
UTF-8 open as Layout U.S. and kill not english  chars

**Comment by gyzerok** [comment] 2020-05-12 01:53
I'd like to contribute to this issue by specifying my use-case, so you can keep it in mind once it gets unblocked.

I need to be able to specify encoding on a per-language basis.

**Comment by nhooyr** [comment] 2020-05-14 23:04
Duplicate of #1017

**Closed by nhooyr** 2020-05-14 23:04 UTC
Labels: blocked, bug, upstream
