### ISSUE TITLE
Ensure telemetry is not sent when telemetry is disabled

### ISSUE THREAD

**Issue by immanuelfodor** [cdr/code-server#1116] opened 2019-10-26 04:37 UTC
## Description

Why is code-server (v2 latest Docker) trying to access `dc.services.visualstudio.com` when telemetry is being disabled? I've found [this question](https://social.technet.microsoft.com/Forums/Lync/en-US/14949b13-a1b5-49aa-84b8-69e6022abdb9/what-is-the-service-of-dcservicesvisualstudiocom?forum=MTCWin8)  online that tells it's application insights. It might not be true anymore but do you know what it's used for? Shouldn't it be disabled by the telemetry disabler flag if it's analytics? As far as I can tell from the DNS logs, it seems to be requested around `docker-compose up -d`.

**Comment by immanuelfodor** [comment] 2019-10-26 04:46
Well, after further thought, it seems it's included in some extensions. Shouldn't these be affected by the "global" telemetry disable flag? 
```
❯ grep -o -R 'dc.services.visualstudio.com' .
./settings/extensions/ms-python.python-2019.9.34911/out/client/extension.js.map.disabled:dc.services.visualstudio.com                                         
./settings/extensions/ms-python.python-2019.9.34911/out/client/extension.js:dc.services.visualstudio.com                                                      
./settings/extensions/ms-python.python-2019.9.34911/out/client/debugger/debugAdapter/main.js.map.disabled:dc.services.visualstudio.com                        
./settings/extensions/ms-python.python-2019.9.34911/out/client/debugger/debugAdapter/main.js:dc.services.visualstudio.com                                     
./settings/extensions/peterjausovec.vscode-docker-0.6.2/dist/extension.bundle.js:dc.services.visualstudio.com                                                 
./settings/extensions/bmewburn.vscode-intelephense-client-1.2.3/node_modules/intelephense/lib/intelephense.js:dc.services.visualstudio.com
```

**Comment by sr229** [comment] 2019-10-26 23:29
@immanuelfodor we'll investigate. But I think we were already passing that since we just proxy VSCode flags.

**Comment by code-asher** [comment] 2019-11-07 17:18
I'm not entirely certain if the `--disable-telemetry` flag is supposed to affect extensions. It seems to only affect the main VS Code process by design but I might be wrong about that. 

We were missing the telemetry option in the settings though so I added it. Extensions appear to read that setting so disabling it should stop extensions from sending telemetry. Should have a new release out some time today with that change.

**Comment by immanuelfodor** [comment] 2019-11-07 17:33
Thanks for the update, sounds good! I think we can close this issue if you no longer need it open for workflow purposes.

**Comment by code-asher** [comment] 2019-11-07 20:06
If you're able to find some time to test the new release once it comes
out and verify that disabling the setting works for you before we close
this that would be fantastic but if not we can go ahead and close it
now, nbd.

**Comment by immanuelfodor** [comment] 2019-11-08 06:02
Well, it seems the issue still exists but in a weirder way. After upgrading to the latest version, the global telemetry option is checked even though the app is started with disable telemetry option. I'm pretty sure this was unchecked before the upgrade. 
My compose file is below, and I removed then reinstalled the "PHP Intelephense" plugin after the docker update, this is what I got in the VSCode settings and in the DNS logs:

![image](https://user-images.githubusercontent.com/21174107/68453081-d1b26980-01f4-11ea-98b9-74bdd272d6b6.png)

![image](https://user-images.githubusercontent.com/21174107/68453186-28b83e80-01f5-11ea-8a82-dec7f734b9bf.png)

Since I blocked the telemetry domain on the DNS level, it couldn't phone home but still annoying that it doesn't do what it should.

```yaml
version: "3"

services:
  code-server:
    container_name: code-server
    image: codercom/code-server:v2
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - "./settings:/home/coder/.local/share/code-server"
      - "./project:/home/coder/project"
    environment:
      - PASSWORD=hello
    command: --allow-http --disable-telemetry --auth=password
    dns:
      - 192.168.1.2
      - 192.168.1.3
```

**Comment by immanuelfodor** [comment] 2019-11-08 06:18
For another test, I've just unchecked the main telemetry option, did a simple local docker compose down and up, then removed and reinstalled the PHP plugin. The unchecked main telemetry option after the container recreation it's still unchecked (as it should be, it might read the persisted settings JSON), but there is another telemetry DNS log entry as the latest call probably from the plugin. It says its setting is inherited but somehow it's still leaking. And adding the main telemetry option becoming enabled on upgrade in the previous comment is weird.

![image](https://user-images.githubusercontent.com/21174107/68453796-edb70a80-01f6-11ea-8c06-37be49edff38.png)

![image](https://user-images.githubusercontent.com/21174107/68453936-4b4b5700-01f7-11ea-805d-3ac77a9bde2e.png)

**Comment by code-asher** [comment] 2019-11-14 18:35
Thank you for testing this!

I think we might want to modify `--disable-telemetry` to force that main setting and any sub-settings to off. It seems like VS Code just doesn't do that by default for some reason even though to me that's confusing.

Does it only make the one request? I think when telemetry is disabled it might still send
one request saying that telemetry is disabled (which is pretty lame IMO).

**Comment by immanuelfodor** [comment] 2019-11-15 04:06
Well, I can't be sure as I don't know the internals on this depth but I've just opened it in a new tab with a PHP file and there is another blocked entry in the DNS log.

**Comment by code-asher** [comment] 2019-11-18 17:50
OK, thanks for the report. :+1: I'll check it out and see if I can figure out what's going on.

**Closed** 2020-03-13 17:39 UTC
Labels: bug
