### ISSUE TITLE
How to upgrade code-server

### ISSUE THREAD

**Issue by TristanBrotherton** [cdr/code-server#2221] opened 2020-10-21 21:47 UTC
I installed code-server using its install script on Ubuntu, and setup NGINX as server. However I can not find any documentation on how to upgrade code-server to the latest release. I am suggesting this is added to the documentation, and if you could help me figure out how to do it I'd love to know! (i thought and `sudo apt-get upgrade` might do it, but no joy.

**Comment by code-asher** [comment] 2020-10-22 16:59
Since you used the install script you can run it again and it'll install
the latest version.

In case you're wondering, `apt` won't do anything for you since you
didn't install it with `apt`. It could be neat to have code-server
available that way though. I'm not sure how hard it is to get into the
package repositories.

Duplicate of https://github.com/cdr/code-server/issues/2131.

**Closed** 2020-10-22 16:59 UTC
Labels: docs
