### ISSUE TITLE
Source control push command error 404 page not found

### ISSUE THREAD

**Issue by ansarizafar** [cdr/code-server#1805] opened 2020-06-13 11:21 UTC
When I use source control push command it stuck on singing in to github after asking permission to allow and showing 404 page for github callback.

**Comment by 3ehzad** [comment] 2020-06-18 06:46
Hi, I have the same issue and I tried to generate token and OAuth application with callback URL with no luck!

**Comment by code-asher** [comment] 2020-06-29 20:25
Yeah I haven't been able to get the oauth stuff working at all yet with code-server. :( 

For now I think the only workaround is to authenticate once with local VS Code and copy or use the configuration files.

**Comment by nhooyr** [comment] 2020-12-08 15:26
Closing as a duplicate of #1883

**Closed by nhooyr** 2020-12-08 15:26 UTC
