### ISSUE TITLE
How to download files and folders from code-server to my Host Machine?

### ISSUE THREAD

**Issue by shujaatak** [cdr/code-server#791] opened 2019-06-18 14:09 UTC
## Description

I have installed code-server in the Guest Ubuntu inside VMWare, from my Host Machine I can easily drag and drop files/folders to code-server's Explorer region to upload them but when I drag and drop files/folders from code-server's Explorer to my Host Machine, it simply gives me this error: 

`Failed - Network error  `

![image](https://user-images.githubusercontent.com/14161646/59691295-3cd6b180-91fc-11e9-8fc6-9a20107de989.png)

As one can see in the above snapshot that the link is also wrong.

I have noticed that [Theia-IDE](https://github.com/theia-ide/theia) has  dedicated download and upload options which are extremely helpful and similar functionality is much needed in **code-server**. 

![image](https://user-images.githubusercontent.com/14161646/59720100-72e55700-9237-11e9-8077-5fd6156223ed.png)

Personally I like the code-server's drag and drop method but currently only upload works but download doesn't work. By the way, I use code-server even though downloading doesn't work in it. I like what it offers although some improvements are needed.

My Guest OS is Ubuntu Server 18.04 and Host OS is Windows 10.

**Comment by shujaatak** [comment] 2019-06-18 15:38
May be it qualify as a bug?

**Comment by shujaatak** [comment] 2019-06-18 15:39
Isn't it qualifies as a bug?

**Comment by deansheather** [comment] 2019-06-20 02:25
From what I can tell this is a feature request for downloading files from the IDE, which is a duplicate of #233. I think the point about dragging and dropping FROM code-server to the desktop is an idea that should be mentioned in that issue.

Apparently it's possible: https://www.thecssninja.com/javascript/gmail-dragout.

**Comment by shujaatak** [comment] 2019-06-20 11:38
Typescript is new for me otherwise I could have contributed in upload/download extension/code development. 

I think an IDE accessible through the browser should have at least proper upload and download functionality. By the way, it **SEEMS** that there **_is_** implementation for the drag & drop download but with erratic **download functionality** which results in **Network error** which gave me a feeling that it's a bug.

**Comment by bulgedition** [comment] 2019-06-24 07:18
From https://github.com/cdr/code-server/issues/623#issuecomment-488617513 it seems like you could download any file via the /resource endpoint. And if you drag out a file from the file tree you get the path of that file. So it will be easy just to prepend /resource and make the browser download it. It seems easy but I am not that good at typescript so it may be not that easy.

[HTML5Rocks' casestudy on drag out](https://www.html5rocks.com/en/tutorials/casestudies/box_dnd_download/)

If this is not possible, may be the simplest solution will be just to add a option in the right click context menu to download the file using that /resource endpoint.

**Comment by shujaatak** [comment] 2019-06-24 14:20
@bulgedition I tested it and it worked but it works on single file, what if one need to download multiple files or the entire folder? 
[ Theia-IDE](https://github.com/theia-ide/theia) is also written in typescript which provides the option in the right click context menu to download the file/files/folders. Just like you I am also not that good at typescript, hence, not able to get the idea from the Theia-IDE related the download functionality.

**Comment by shujaatak** [comment] 2019-07-13 21:18
Any progress?

**Comment by code-asher** [comment] 2019-10-23 23:30
Gonna close this since it's a duplicate of #233. There's no timeline on this feature yet.

**Closed by code-asher** 2019-10-23 23:30 UTC
Labels: question
