### ISSUE TITLE
Error when building on RaspberryPi

### ISSUE THREAD

**Issue by deerangle2** [cdr/code-server#712] opened 2019-05-23 18:42 UTC
- `code-server` version: 1.1119-vsc1.33.1
- OS Version: Ubuntu Core 16 (On RaspberryPi 3B)

## Description

I am getting a warning during `$ ts-node -r tsconfig-paths/register build/tasks.ts build:server:binary` which seems to fail the build completely. Here is the content of the warning:

npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1558634599908-0.08137105400888878/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

Full log here: https://pastebin.com/WeyTnuZA

Why is this warning crashing the build process and what can I do to prevent it from crashing?

## Steps to Reproduce

1. `sudo docker build .` (On a RaspberryPi 3)

**Comment by sr229** [comment] 2019-05-24 02:39
Duplicate of #35

**Comment by coadler** [comment] 2019-05-24 15:19
ARM support still WIP, closing in favor of #35

**Closed by coadler** 2019-05-24 15:19 UTC
Labels: bug, duplicate

**Comment by gt945** [comment] 2019-09-13 08:14
@rehwinkel 
I tried to build code-server on Fedora 30 aarch64 platfom.
I meet this error too. you can use this command to avoid this error.
```
npm config set scripts-prepend-node-path true
```
