### ISSUE TITLE
Unable to view HTML files

### ISSUE THREAD

**Issue by CreptThrust** [cdr/code-server#396] opened 2019-04-01 13:50 UTC
Currently there is no way to preview HTML files that I know of.
When using 'Open in Browser', nothing happens.

Hopefully a way to preview these files will be released soon.

(If there is a way, please tell me.)

**Comment by KannaDev** [comment] 2019-04-01 15:28
You can try downloading the extension "Live Server". It allows you to open a port and view your previews in realtime, without having to refresh.

**Comment by nol166** [comment] 2019-04-01 16:31
@CreptThrust AFAIK Native VSCode also doesn't have an HTML previewer. In terms of features, we try to offer what VSCode has out of the box. Anything beyond that would be done with extensions. Live server is pretty great

**Comment by nhooyr** [comment] 2020-01-28 00:39
Duplicate of #1292

**Closed by nhooyr** 2020-01-28 00:39 UTC

**Comment by lei1996** [comment] 2022-02-26 13:10
Hello， I have a problem. I use docker code server And caddy proxy, but I can't preview my react project on the server

**Comment by jsjoeio** [comment] 2022-02-28 20:53
@lei1996 please take a look at [our docs](https://coder.com/docs/code-server/latest/guide#proxying-to-create-a-react-app)
