### ISSUE TITLE
How can I debug (C / C++)？

### ISSUE THREAD

**Issue by XLJ-CN** [cdr/code-server#3643] opened 2021-06-21 03:06 UTC
## OS/Web Information

- Web Browser: Chrome 91.0.4472.101（正式版本） （32 位）
- Local OS:Windows 10
- Remote OS:CentOS Linux release 7.6.1810 (Core)
- Remote Architecture: docker  and port in 8086
- `code-server --version`: 3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005

## Steps to Reproduce

1. intall extension and create main.c
```
#include <stdio.h>
void main(){
    
int x=20;

    printf("XLJ666\n");

}
```
2. 
![图片](https://user-images.githubusercontent.com/30283517/122701080-0b779d00-d27f-11eb-8b59-abc14ce69f28.png)
 
3.config launch.json
```
{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "启动调试",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/bin/${fileBasenameNoExtension}.debug.out -g",//该项填写生成的可执行文件的实际路径，注意后缀名
            "preLaunchTask": "build",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "为 gdb 启用整齐打印",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```
3.config task.json 
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
           
            "type": "shell", 
            "label": "build",
            "command": "gcc ${file} -o ${fileDirname}/bin/${fileBasenameNoExtension}.debug.out -g"
        }
    ]
}
```

## Expected

should print in terminal and print 
XLJ666
应该在终端里面打印出 XLJ666
## Actual

actually , when i press F5 it flash and doesn't work, just run command in task.json ,cmd in launch.json 
"program": "${fileDirname}/bin/${fileBasenameNoExtension}.debug.out -g" doesn't work
实际上，我调试按F5他一闪而过，并没有打印信息，只是执行了task.json中的command,而launch.json 中的program命令根本没有执行。
## Logs
nothing！

## Screenshot
![图片](https://user-images.githubusercontent.com/30283517/122701783-9016eb00-d280-11eb-9692-3df28438a2de.png)

## Notes

This issue can be reproduced in VS Code: No，i try it in vscode(ubuntu 18),it works
在ubuntu 18中安装vscode  是可以调试的。

**Comment by jsjoeio** [comment] 2021-06-21 17:56
Is this a duplicate of https://github.com/cdr/code-server/issues/1616?

**Comment by XLJ-CN** [comment] 2021-06-22 00:22
> Is this a duplicate of #1616?

yes！
by the way ,the problem seems like debugger program does`n execute the laugch.json`s program .
Just like  when you build it manual but don`t  run command [./main.out]
 Please let me know if you need anything else.
-----------------------
是的，跟这个bug类似
顺便说下，这个问题看起来就是调试器没有执行laugch.json里面的program行参数
就像当你手动编译了程序之后但是没执行./main.out命令
如果还需要什么其他bug信息，请告诉我

**Comment by jsjoeio** [comment] 2021-06-22 17:50
Thanks @XLJ-CN! We'll close this issue and track in the other one. Thanks for the repro steps!

**Closed** 2021-06-24 17:49 UTC
Labels: duplicate
