### ISSUE TITLE
Document what can cause NODE_MODULE_VERSION errors

### ISSUE THREAD

**Issue by manish9363** [cdr/code-server#1794] opened 2020-06-10 20:36 UTC
- Web Browser: safari and chrome
- Local OS: mac 10.15.4
- Remote OS:
- Remote Architecture:
- `code-server --version`: 3.4.0
<img width="1680" alt="Screen Shot 2020-06-10 at 1 37 08 PM" src="https://user-images.githubusercontent.com/46613725/84318250-f6701600-ab22-11ea-8980-a7d94606828b.png">

**Comment by esmondmissen** [comment] 2020-06-11 00:11
I am having the same experience with the following error in the console: Extension host terminated unexpectedly. Code:  – 0 – " Signal: " – null

**Comment by shisoft** [comment] 2020-06-11 03:26
Having the same problem in ARM64, x86 is all fine

**Comment by nhooyr** [comment] 2020-06-11 03:36
Should be fixed in the latest release.

Please upgrade!

https://github.com/cdr/code-server/releases/tag/v3.4.1

**Comment by shisoft** [comment] 2020-06-11 03:43
Problems remains in 3.4.1

**Comment by nhooyr** [comment] 2020-06-11 03:44
Try verbose logging: https://github.com/cdr/code-server/blob/master/doc/FAQ.md#how-do-i-debug-issues-with-code-server

**Comment by shisoft** [comment] 2020-06-11 03:58
Here is my obversation:
It does not fail every time and every time it fails, there is no logs on server side. Every time it fails, plugins does not respond.
info  Using config file ~/.config/code-server/config.yaml
debug parsed command line {"args":{"_":[],"bind-addr":"0.0.0.0:8080","auth":"none","password":"325cf28c15008fd586c24a62"}}
debug spawned inner process 6128
debug parsed command line {"args":{"_":[],"log":"debug"}}
debug parsed command line {"args":{"_":[],"bind-addr":"0.0.0.0:8080","auth":"none","password":"325cf28c15008fd586c24a62"}}
debug wrapper 6109 received message from 6128 {"message":{"type":"handshake"}}
debug inner process 6128 received message from 6109 {"message":{"type":"handshake"}}
info  Using user-data-dir ~/.local/share/code-server
info  code-server 3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259
info  HTTP server listening on http://0.0.0.0:8080
info- No authentication
info- Not serving HTTPS
debug forking vs code...
debug got message from vs code {"message":{"type":"ready"}}
debug setting up vs code...
debug vscode got message from code-server {"message":{"type":"init","id":"UiPZ2rb60dd9u0XQc5CG7klY","options":{"args":{"_":[],"bind-addr":"0.0.0.0:8080","auth":"none","password":"325cf28c15008fd586c24a62","log":"debug","verbose":false,"config":"/home/shisoft/.config/code-server/config.yaml","user-data-dir":"/home/shisoft/.local/share/code-server","extensions-dir":"/home/shisoft/.local/share/code-server/extensions"},"remoteAuthority":"192.168.1.215:8080","startPath":{"url":"/home/shisoft/Code/bifrost","workspace":false}}}}
debug got message from vs code {"message":{"type":"options","id":"UiPZ2rb60dd9u0XQc5CG7klY","options":{"workbenchWebConfiguration":{"folderUri":{"$mid":1,"path":"/home/shisoft/Code/bifrost","scheme":"vscode-remote","authority":"192.168.1.215:8080"},"remoteAuthority":"192.168.1.215:8080","logLevel":1,"workspaceProvider":{"payload":[["userDataPath","/home/shisoft/.local/share/code-server"]]}},"remoteUserDataUri":{"$mid":1,"path":"/home/shisoft/.local/share/code-server","scheme":"vscode-remote","authority":"192.168.1.215:8080"},"productConfiguration":{"nameShort":"Code - OSS","nameLong":"Code - OSS","applicationName":"code-oss","dataFolderName":".vscode-oss","win32MutexName":"vscodeoss","licenseName":"MIT","licenseUrl":"https://github.com/Microsoft/vscode/blob/master/LICENSE.txt","win32DirName":"Microsoft Code OSS","win32NameVersion":"Microsoft Code OSS","win32RegValueName":"CodeOSS","win32AppId":"{{E34003BB-9E10-4501-8C11-BE3FAA83F23F}","win32x64AppId":"{{D77B7E06-80BA-4137-BCF4-654B95CCEBC5}","win32UserAppId":"{{C6065F05-9603-4FC4-8101-B9781A25D88E}","win32x64UserAppId":"{{C6065F05-9603-4FC4-8101-B9781A25D88E}","win32AppUserModelId":"Microsoft.CodeOSS","win32ShellNameShort":"C&ode - OSS","darwinBundleIdentifier":"com.visualstudio.code.oss","linuxIconName":"com.visualstudio.code.oss","licenseFileName":"LICENSE.txt","reportIssueUrl":"https://github.com/cdr/code-server/issues/new","urlProtocol":"code-oss","extensionAllowedProposedApi":["ms-vscode.vscode-js-profile-table","ms-vscode.references-view"],"builtInExtensions":[{"name":"ms-vscode.node-debug","version":"1.44.5","repo":"https://github.com/Microsoft/vscode-node-debug","metadata":{"id":"b6ded8fb-a0a0-4c1c-acbd-ab2a3bc995a6","publisherId":{"publisherId":"5f5636e7-69ed-4afe-b5d6-8d231fb3d3ee","publisherName":"ms-vscode","displayName":"Microsoft","flags":"verified"},"publisherDisplayName":"Microsoft"}},{"name":"ms-vscode.node-debug2","version":"1.42.2","repo":"https://github.com/Microsoft/vscode-node-debug2","metadata":{"id":"36d19e17-7569-4841-a001-947eb18602b2","publisherId":{"publisherId":"5f5636e7-69ed-4afe-b5d6-8d231fb3d3ee","publisherName":"ms-vscode","displayName":"Microsoft","flags":"verified"},"publisherDisplayName":"Microsoft"}},{"name":"ms-vscode.references-view","version":"0.0.51","repo":"https://github.com/Microsoft/vscode-reference-view","metadata":{"id":"dc489f46-520d-4556-ae85-1f9eab3c412d","publisherId":{"publisherId":"5f5636e7-69ed-4afe-b5d6-8d231fb3d3ee","publisherName":"ms-vscode","displayName":"Microsoft","flags":"verified"},"publisherDisplayName":"Microsoft"}},{"name":"ms-vscode.js-debug-companion","version":"1.0.0","repo":"https://github.com/microsoft/vscode-js-debug-companion","metadata":{"id":"99cb0b7f-7354-4278-b8da-6cc79972169d","publisherId":{"publisherId":"5f5636e7-69ed-4afe-b5d6-8d231fb3d3ee","publisherName":"ms-vscode","displayName":"Microsoft","flags":"verified"},"publisherDisplayName":"Microsoft"}},{"name":"ms-vscode.js-debug-nightly","version":"2020.4.2917","repo":"https://github.com/Microsoft/vscode-js-debug","metadata":{"id":"7acbb4ce-c85a-49d4-8d95-a8054406ae97","publisherId":{"publisherId":"5f5636e7-69ed-4afe-b5d6-8d231fb3d3ee","publisherName":"ms-vscode","displayName":"Microsoft","flags":"verified"},"publisherDisplayName":"Microsoft"}},{"name":"ms-vscode.vscode-js-profile-table","version":"0.0.2","repo":"https://github.com/Microsoft/vscode-js-debug","metadata":{"id":"7e52b41b-71ad-457b-ab7e-0620f1fc4feb","publisherId":{"publisherId":"5f5636e7-69ed-4afe-b5d6-8d231fb3d3ee","publisherName":"ms-vscode","displayName":"Microsoft","flags":"verified"},"publisherDisplayName":"Microsoft"}}],"commit":"48f7c2724827e526eeaa6c2c151c520f48a61259","date":"2020-06-04T10:39:14Z","version":"1.45.1","extensionsGallery":{"serviceUrl":"https://extensions.coder.com/api","itemUrl":"","controlUrl":"","recommendationsUrl":""}},"nlsConfiguration":{"locale":"en","availableLanguages":{}},"commit":"48f7c2724827e526eeaa6c2c151c520f48a61259"}}}
debug vscode got message from code-server {"message":{"type":"socket","query":{"type":"Management","reconnectionToken":"3ff95085-7351-4b3f-b172-f0f8ea3a7524","reconnection":"false","skipWebSocketFrames":"false"}}}
debug vscode got message from code-server {"message":{"type":"socket","query":{"type":"ExtensionHost","reconnectionToken":"adf5f796-2325-4c94-aa1d-6d4be17daa6d","reconnection":"false","skipWebSocketFrames":"false"}}}

**Comment by esmondmissen** [comment] 2020-06-12 14:45
I managed to get my installation working. I re-installed Xcode-cli tools and had to do an npm rebuild on the vscode folder. I'm not sure which of these led to the fix but I'm not getting the error anymore. The error I was getting before the nom rebuild was:

Error: The module '/usr/local/Cellar/code-server/3.4.1/libexec/lib/vscode/node_modules/spdlog/build/Release/spdlog.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

**Comment by nhooyr** [comment] 2020-06-12 14:51
Very weird, I just installed `v3.4.1` from brew and it works fine for me. That error indicates your node is out of date but if you installed from homebrew it should be using the latest unless you pinned it yourself.

**Comment by flolanger** [comment] 2020-06-12 15:42
It always happens to me after I did a fresh installation. I can work normally for the first time after I run the install script. But as soon as I reload once this error keeps happening until I run the install script again...

**Comment by nhooyr** [comment] 2020-06-13 11:20
@flolanger you're on macOS as well?

**Comment by storm2513** [comment] 2020-06-19 13:05
@nhooyr happens to me as well. In my case, it is caused by NVM usage. Latest node 12 LTS installed via nvm and used by default in system and node 14 installed via brew. Looks like code-server also uses node from NVM.

The only working solution for me is usage of standalone release. But macOS asked about 5 times for permission because of untrusted developer (binary version of nodejs and so on).

**Comment by mtm20176** [comment] 2020-06-20 11:30
I'm getting same problem as esmondmissen - but reinstall of xcode clt didn't fix. I did npm rebuild, but didn't know where vs code folder is.  Still have error ( see screenshot ). I'm on macOS Mojave
<img width="1115" alt="Screen Shot 2020-06-20 at 6 28 49 AM" src="https://user-images.githubusercontent.com/2022166/85200727-8a7a7400-b2bf-11ea-8a80-ae9383f655e6.png">

**Comment by nhooyr** [comment] 2020-06-22 05:09
@mtm20176 How are you running and using code-server?

**Comment by mtm20176** [comment] 2020-06-22 11:13
@nhooyr Installed with Homebrew, and run with: brew services start code-server

**Comment by storm2513** [comment] 2020-06-22 12:02
Same issue with installing via yarn.

**Comment by nhooyr** [comment] 2020-06-23 12:02
If you install with brew, your version of node in `$PATH` needs to be the latest brew formula.

I guess we can change the formula to use the brew version of node regardless.

**Comment by nhooyr** [comment] 2020-06-23 12:02
When you install with `yarn` and upgrade your node version, you'll need to reinstall to recompile native modules. We should document this.

**Comment by nhooyr** [comment] 2020-06-23 12:18
Opened https://github.com/Homebrew/homebrew-core/pull/56748 to take care of the Homebrew formula.

**Comment by pbnj** [comment] 2020-10-23 17:34
I just ran into this issue as well. 

I don't have any other node installations on my system. I had code-server installed previously and it was updated today via `brew update && brew upgrade`, then it broke.

Running `code-server` launches the editor in the browser, but a few native extensions are not building correctly:

```text
The terminal process failed to launch: A native exception occurred during launch (The module '/usr/local/Cellar/code-server/3.6.0_1/libexec/lib/vscode/node_modules/spdlog/build/Release/spdlog.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 83. This version of Node.js requires NODE_MODULE_VERSION 88. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`).).
```

and

```text
The terminal process failed to launch: A native exception occurred during launch (The module '/usr/local/Cellar/code-server/3.6.0_1/libexec/lib/vscode/node_modules/node-pty/build/Release/pty.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 83. This version of Node.js requires NODE_MODULE_VERSION 88. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`).).
```

I tried the following:

- brew uninstall node and code-server and reinstall code-server, which installed node v15.0.1. _Unsuccessful._
- `npm rebuild` offending modules. _Unsuccessful._
- `npm install` offending modules. _Resolved the problem._

I would have thought uninstalling and reinstalling code-server rebuilds native extensions.

Is there a better way to rebuild native extensions?

**Comment by code-asher** [comment] 2020-10-27 21:27
Hmmm maybe reinstalling code-server is reusing a cached copy and not
reinstalling the modules.

But I'm surprised to see `npm rebuild` didn't work; that usually does
the trick for me.

It does seem worth documenting.

**Closed** 2021-07-01 22:36 UTC
Labels: docs

**Comment by cangetright** [comment] 2021-07-02 02:53
What’s that mean?
