### ISSUE TITLE
Vscode extension does not work on code-server

### ISSUE THREAD

**Issue by hakimehmordadi** [cdr/code-server#3048] opened 2021-04-06 14:43 UTC
Hi there! 👋

I created a vs-code extension for code sharing. For running extension I'm using code-server. I'm using web socket for real-time sending and receiving messaged (In this case users mouse position or text highlights). 

I open every files which I want to share in browser as tabs.

BUT

When I closed all tabs, my extension goes deactivated, web socket is stopped and I got error.

## OS/Web Information

- Web Browser: chrome, firefox
- Local OS: centos
- Remote OS: centos
- Remote Architecture: code-server
- `code-server --version`: code-server-3.9.1-linux-amd64

## Steps to Reproduce

1. Run code-server with ( ./code-server ) command
2. Copy my extension into ( .local/code-server/extensions ) folder
3. Open two browser (chrome/firefox) with (http://localhost:8080) address
4. Open share folder in browsers
5. Open files inside share folder as tab in browsers

## Expected

When user1(chrome) select part of text, user2(firefox) should see that in it's own browser with different color, this should happens for user2 (Like micro-soft live share)

## Actual

Users can select code and other user can see selection of other users BUT when closing all files error accures

## Screenshot

![2021-04-06T14_35_39](https://user-images.githubusercontent.com/31950758/113729242-13a64e80-970c-11eb-9916-21f9c0ac1594.png)
![2021-04-06T14_35_391](https://user-images.githubusercontent.com/31950758/113729262-1739d580-970c-11eb-9e46-5c3d7c2cbd39.png)
![2021-04f-06T14_35_39](https://user-images.githubusercontent.com/31950758/113729269-186b0280-970c-11eb-846a-8c25761939b1.png)

This issue can be reproduced in VS Code: Yes

**Comment by jsjoeio** [comment] 2021-04-06 17:28
Hi @hakimehmordadi - thanks for opening an issue!

If you can reproduce this in VS Code, then you should open this upstream as it's not specific to code-server.  Let me know if you have any questions!

**Comment by hakimehmordadi** [comment] 2021-04-06 17:58
Hi **@jsjoeio** 
Thank you for answering.

Please take a look to below link:
http://localhost:8080/static/e0203f2a36c9b7036fefa50eec6cf8fa36c5c015/home/student1/Desktop/code-server-3.9.1-linux-amd64/lib/vscode/out/vs/workbench/workbench.web.api.js

This is link of error, please see the pictures, it is related to code-server, because code-server is responsible for activating vs-code extension, when i close all text-files(tabs) in browser, extension became deactivated.

Thanks.

**Comment by jsjoeio** [comment] 2021-04-06 18:13
Ah, I misunderstood. You marked "Yes" here:

> This issue can be reproduced in VS Code: Yes

If this can also be reproduced in VS Code, then it should be filed upstream. If not, then it's a code-server issue.

> Please take a look to below link:
> http://localhost:8080/static/e0203f2a36c9b7036fefa50eec6cf8fa36c5c015/home/student1/Desktop/code-server-3.9.1-linux-amd64/lib/vscode/out/vs/workbench/workbench.web.api.js

That link won't work for me because it's running on your machine. 

> extension became deactivated

When the browser disconnects, VS Code kills the entire extension host (and therefore all running extensions). This is how VS Code works (and not something in our control). Please see [this discussion](https://github.com/cdr/code-server/issues/2882). There may be a solution in there that helps you.

**Comment by hakimehmordadi** [comment] 2021-04-07 05:26
Thank you so much @jsjoeio for your answer.

**Comment by jsjoeio** [comment] 2021-04-07 17:14
No problem! I'm going to close this then. Feel free to file upstream and/or open a separate issue if you encounter issues with code-server.

**Closed by jsjoeio** 2021-04-07 17:14 UTC
Labels: upstream:vscode
