### ISSUE TITLE
Add ability to zoom in/out the whole view, not only the editor font.

### ISSUE THREAD

**Issue by maximMalofeev** [cdr/code-server#2164] opened 2020-10-07 06:48 UTC
I use code-server from my tablet, so each inch of space is very important. The default activity bar and status bar looks too large, it would be great if you add an ability to zoom in/out whole view, not only editor font.

**Comment by code-asher** [comment] 2020-10-07 17:33
Thanks for the feature request! It's good to know there are more people who want this. Gonna close as a duplicate of https://github.com/cdr/code-server/issues/2009.

**Closed by code-asher** 2020-10-07 17:33 UTC
Labels: feature
