### ISSUE TITLE
Open file-link in markdown preview

### ISSUE THREAD

**Issue by HenningCash** [cdr/code-server#996] opened 2019-09-18 08:56 UTC
- `code-server` version: happens in v1 and v2 (see description)
- OS Version: irrelevant

## Description
If you put a file-link into a markdown like `Please open [file.js](./file.js)` and open the preview code-server will produce links like:
* v1: http://localhost:8080/resource/home/coder/project/README.md
* v2: http://localhost:8080/webview/vscode-resource/home/coder/project/README.md

The original VSCode desktop handles these links like expected and opens the file in the current workspace.

**Comment by sr229** [comment] 2019-09-18 14:17
@code-asher

**Comment by code-asher** [comment] 2020-02-28 18:51
It appears to work now in 2.1698; probably fixed when we upgraded VS Code. Please let me know if that's not the case for you.

**Comment by code-asher** [comment] 2020-02-28 18:53
Ahh, I misunderstood. It should open in the current workspace from the preview. It still doesn't do that.

**Comment by onilton** [comment] 2020-03-19 17:59
I am also facing this issue, is it a good first issue/PR? I am willing to help. :)

**Comment by onilton** [comment] 2020-03-20 16:39
Ok, so far I managed to compile, understand some of the patchs, and look a lot at the code. I managed to understand that at 

`node/server.ts` we capture the /webview link.

If I understand correctly I would have to intercept the link and decide if it is an internal or external resouce.

What I am failing to understand is how can I pass this captured info from this code to the editor itself. I see that `?folder` and/or `?workspace` is stored with `writeSettings(` but I couldn't find where this info is retrieved in the editor side. I got the feeling this is an existing vscode code, not code-server, but couldn't find it.

I thinking dealing with opening a file maybe similar to this strategy, but since I don't understand it fully yet, couldn't avance further. 

Also, I was working in the v2 branch (since I couldn't make the master work withou getting reconnect issues).

**Comment by onilton** [comment] 2020-03-20 18:10
Ok, more progress, I found what I want but it seems to no be working as intended:

It seems like WORKBENCH_WEB_CONFIGURATION is being interpolated in browser/workbench.html, and folder info is passed through folderUri: property. The problem is that seems that startPath is never filled (undefined), since this.getFirstValidPath fails with:

`ENOENT: no such file or directory, stat '...`

The issue is that using `?folder=` is still working despite that issue, so I don't know HOW it is working :sweat:

**Comment by code-asher** [comment] 2020-03-23 16:17
In v2 we had a bug in some cases when parsing `folder` but it should be
fixed in latest master. It probably still works (in v2) because VS Code
also looks at the query parameter. That code was removed in v3 though
because it conflicted with ours.

I'm not sure `server.ts` is where this issue would be fixed. The preview
outputs a link but there needs to be some JavaScript that captures the
click on the link and opens the file in the workspace instead.

I haven't done any digging yet to see exactly what the problem is but it
might need to be fixed in the builtin markdown extension itself?

**Comment by onilton** [comment] 2020-03-24 00:31
@code-asher  I dig into the markdown extension itself, but it seems it just set all relative links to /webview , so that's why I tried to intercept /webview at least for testing.

I couldn't make v3 work. It gave me "please reconnect" errors. That's why I fallback to v2 since it is the docker version (which also worked). Maybe I will try to run v3 to see if the code is easier for me to parse. 

What you think? Should I try to go for v3?

**Comment by onilton** [comment] 2020-03-24 00:52
Ok, checked out V3 and managed to make it work (I think it was an issue with node version). Got what you said about the folder query parameter handling happening both in code-server and vscode. Found in patch that code-server removed some code about this. I will proceed my investigation. Thanks.

**Comment by onilton** [comment] 2020-03-24 04:53
@code-asher ok, now I managed to find a very very ugly, but working solution:

```
diff --git a/extensions/markdown-language-features/src/markdownEngine.ts b/extensions/markdown-language-features/src/markdownEngine.ts
index 33cb220b44..b94e2bc35c 100644
--- a/extensions/markdown-language-features/src/markdownEngine.ts
+++ b/extensions/markdown-language-features/src/markdownEngine.ts
@@ -256,7 +256,7 @@ export class MarkdownEngine {
                                                        fragment: this.slugifier.fromHeading(uri.fragment).value
                                                });
                                        }
-                                       return normalizeLink(uri.toString(true).replace(/^markdown-link:/, ''));
+                                       return normalizeLink(uri.toString(true).replace(/^markdown-link:/, 'file:'));
                                }
                        } catch (e) {
                                // noop
@@ -311,8 +311,13 @@ export class MarkdownEngine {
                        const token = tokens[idx];
                        const hrefIndex = token.attrIndex('href');
                        if (hrefIndex >= 0) {
-                               const href = token.attrs[hrefIndex][1];
-                               token.attrPush(['data-href', href]);
+                               const href: string = token.attrs[hrefIndex][1];
+                               if (href.startsWith("file:")) {
+                                       token.attrs[hrefIndex][1] = "command:workbench.action.files.openFile";
+                                       token.attrPush(['data-href', href.replace(/^file:/, '')]);
+                               } else {
+                                       token.attrPush(['data-href', href]);
+                               }
                        }
                        return old_render(tokens, idx, options, env, self);
                };
```

I found the href="command:..." by accident looking at the initial Help page of vscode, but I don't know if this a documented method or a hack.


I would be glad if anyone could give me any tips or instructions if (and how) I can improve on this basic solution/hack.

**Comment by code-asher** [comment] 2020-04-16 22:07
Hey @onilton I'm sorry I let this fall by the wayside. I gave your code a test and it works great. I think this is a solid way to go since it seems to be the same method used in the welcome page as you noticed.

If you'd like to submit a PR I'd be happy to accept; if not lemme know and I'll get it in.

**Comment by code-asher** [comment] 2020-09-11 22:51
It looks like some changes have been made around this area. They handle links from the previe but only markdown links and external links. I checked with local VS Code (1.48.2) and it has the same behavior so it looks like we actually have parity here now.

**Closed by code-asher** 2020-09-11 22:51 UTC
Labels: bug
