### ISSUE TITLE
Syntax highlight not working [Termux]

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [cdr/code-server#2749] opened 2021-02-20 20:15 UTC
In termux everything seem to work except syntax highlighting, does syntax highlight require some x86 dependant code?

**Comment by mrfoxie** [comment] 2021-02-21 05:36
@DanielMazurkiewicz is code-server working properly in termux of urs

**Comment by DanielMazurkiewicz** [comment] 2021-02-22 17:36
As was having background starter for code-server wasn't aware of any errors but actually there was an error of missing module "spdlog". Did reinstall code-server with yarn flag --check-files and that seem to solve a problem of missing module, but still no syntax highlight

**Comment by jsjoeio** [comment] 2021-02-22 18:39
Hmm...I haven't used Termux ever but I can take a look if you provide your code-server/browser info and steps to reproduce this locally!

**Comment by DanielMazurkiewicz** [comment] 2021-02-22 20:25
> Hmm...I haven't used Termux ever but I can take a look if you provide your code-server/browser info and steps to reproduce this locally!

Checked Firefox and Kiwi browsers, issue on both of them. Code server ver. 3.9.0.

Install termux on non rooted android (through F-droid) and then:
```sh
pkg upgrade
pkg install nodejs
pkg install yarn
yarn global add code-server
code-server
```

**Comment by DanielMazurkiewicz** [comment] 2021-02-23 09:42
Update: removed user-data-dir content, downgraded to 3.7.4 and syntax highlighting works

**Comment by jsjoeio** [comment] 2021-02-23 16:50
Thanks for the reproduction instructions! I don't have an Android tablet so  I don't think I'll be able to reproduce unfortunately.

Well, glad to hear you got it working! I wonder what the root issue could be.

**Comment by jsjoeio** [comment] 2021-04-05 21:38
It's been over 30 days since we've last heard from you. Going to close this issue for now. If you run into it again or need further assistance, please open another issue!

**Closed by jsjoeio** 2021-04-05 21:38 UTC
Labels: bug, waiting-for-info
