### ISSUE TITLE
vetur extension problem

### ISSUE THREAD

**Issue by syntaxhacker** [cdr/code-server#1260] opened 2020-01-08 06:51 UTC
- `code-server` version: latest linux release
- OS Version: ubuntu 18.04 on azure vm 
- Extension: https://marketplace.visualstudio.com/items?itemName=octref.vetur

## Description
i had installed vue-cli and created basic hello world app , installed vetur for syntax highlighting but it doesnt work and shows this error 👇

![image](https://user-images.githubusercontent.com/30970495/71955236-c1773480-320d-11ea-88e7-fd01e89bebb5.png)

**Comment by nhooyr** [comment] 2020-01-27 06:44
@sr229 have you been able to reproduce?

**Comment by sr229** [comment] 2020-01-27 06:45
Looks like it doesn't persist anymore. I think we can close this off.

**Comment by nhooyr** [comment] 2020-01-27 06:46
@syntaxhacker please reopen if this still occurs and I'll investigate.

**Closed by nhooyr** 2020-01-27 06:46 UTC
Labels: bug, extension
