### ISSUE TITLE
Incorrect password, local config.yaml not used

### ISSUE THREAD

**Issue by jingw222** [cdr/code-server#3426] opened 2021-05-20 07:43 UTC
## OS/Web Information

- Web Browser: Chrome
- Local OS: Windows / MacOS
- Remote OS: Ubuntu
- Remote Architecture: amd64
- `code-server --version`: 3.10.1

## Steps to Reproduce

1. Create a config.yaml and fill in the fields like this

```
bind-addr: 0.0.0.0:8080
auth: password
hashed-password: xxxx
cert: false
```
The hashed password was generated with `printf "thisismypassword" | sha256sum | cut -d' ' -f1`
2. Setup Nginx proxy conf file, and launch with docker compose
```
 code-server:
    image: codercom/code-server:latest
    container_name: "code-server"
    hostname: "code-server"
    restart: unless-stopped
    user: root
    environment: 
      - DOCKER_USER=${USER}
    expose:
      - "8080"
    volumes:
      - ${WORK_DIR}:/home/coder/project
      - ${HOME}/.vscode:/home/coder/.local/share/code-server
      - ${HOME}/.config/code-server:/home/coder/.config/code-server

```
3. Go to my browser and type in the password, but always receive a "Incorrect password" error.
4. I checked the config file `~/.config/code-server/config.yaml` inside the container and it was the same as the local one.

## Expected
Login page leads to coder workspace upon entering the password specified in local config.yaml
## Actual
Login page shows "Incorrect password". Container logs output "Failed login attempt".
## Logs
This were the logs from the container
```
[2021-05-20T14:20:59.093Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2021-05-20T14:20:59.548Z] info  code-server 3.10.1 421237f499079cf88d68c02163b70e2b476bbb0d
[2021-05-20T14:20:59.549Z] info  Using user-data-dir ~/.local/share/code-server
[2021-05-20T14:20:59.570Z] info  Using config file ~/.config/code-server/config.yaml
[2021-05-20T14:20:59.570Z] info  HTTP server listening on http://0.0.0.0:8080
[2021-05-20T14:20:59.570Z] info    - Authentication is enabled
[2021-05-20T14:20:59.570Z] info      - Using password from ~/.config/code-server/config.yaml
[2021-05-20T14:20:59.571Z] info    - Not serving HTTPS
Failed login attempt {"xForwardedFor":"x.x.x.x","remoteAddress":"x.x.x.x","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36","timestamp":1621520562}
```

**Comment by jsjoeio** [comment] 2021-05-20 18:51
I could not reproduce this locally. Here are the steps I followed:
1. `printf "thisismypassword" | sha256sum | cut -d' ' -f1` - copy value
2. paste in `~/.config/code-server/config.yaml` after `hashed-password: `
3. launch code-server with `code-server`
4. see login page
5. type in "thisismypassword"

## Screenshot

https://user-images.githubusercontent.com/3806031/119032311-e54d9d00-b960-11eb-859b-b9267fdd1e05.mov

Do you mind posting your `config.yaml`? Maybe @code-asher sees something obvious I'm not seeing

**Comment by code-asher** [comment] 2021-05-20 19:11
Oddly enough I seem to have the same issue if I use Docker.

```
docker run -p 8081:8080 -v ~/.local/share/code-server:/home/coder/.local/share/code-server codercom/code-server:latest         
```   

Then on localhost:8081I have the issue. But I also have code-server running locally on 8080 and it works fine (using the same config file).

**Comment by code-asher** [comment] 2021-05-20 19:13
Whoops I mounted the wrong directory. Should be `~/.config/code-server`.

**Comment by code-asher** [comment] 2021-05-20 19:16
All right now that I have the right directory it works for me. I generated my password the same way. Nothing looks out of place to me. 

Does the login page say that the password is from the config file?

**Comment by jingw222** [comment] 2021-05-21 16:49
Thanks for the quick reply. Since the environment variable `$HASHED_PASSWORD` always takes precedence I finally managed to login that way. Not sure if it was caused by some of sort cache by container volumes.

**Comment by jsjoeio** [comment] 2021-05-21 17:45
Interesting! Well glad to hear you managed to make it work. Sorry for the trouble. Can we close this?

**Closed** 2021-05-22 01:41 UTC
Labels: needs-investigation
