### ISSUE TITLE
How to access host:port service running inside code-server via WebView

### ISSUE THREAD

**Issue by anixon604** [cdr/code-server#1949] opened 2020-08-07 11:44 UTC
- Web Browser: Chrome
- Local OS: OS X
- Remote OS: Ubuntu
- Remote Architecture: x64 
- `code-server --version`: 3.0.0

On creation of a code-server instance I have a springboot server auto-launch in the embedded terminal of VSCode, serving port 8580. This services is used by a custom extension.

In a local version of VSCode (non code-server) I can just have the extension WebView make calls to http://localhost:8580, but when using this base URL - `export const SERVER_BASE_URL = "http://localhost:8580";` - through the code-server browser client, it **doesn't direct to the `INSTANCE`/Container localhost - but rather to the USER's localhost.**

Is there an easy method to have this service contained in the docker instance and accessed via a WebView in code-server?

My next step would be to expose 8580 externally and direct WebView calls to <instance>.domain.net:8580, but wondering if this is avoidable or if it can just all be contained. Thanks

**Comment by code-asher** [comment] 2020-08-07 15:48
code-server has a built-in proxy you could use to proxy port 8580. See https://github.com/cdr/code-server/blob/master/doc/FAQ.md#how-do-i-securely-access-web-services. That would at least let you avoid opening another port.

We have some open issues to make this easier: https://github.com/cdr/code-server/issues/1936 https://github.com/cdr/code-server/issues/1510

**Comment by nhooyr** [comment] 2020-08-17 17:59
Yup, closing as a duplicate of #1936 and #1510

**Closed by nhooyr** 2020-08-17 17:59 UTC
