### ISSUE TITLE
gitgraph and jupyter not work on v3.12.0

### ISSUE THREAD

**Issue by vipwp** [cdr/code-server#4180] opened 2021-09-16 04:01 UTC
## OS/Web Information

- Web Browser: chrome@91.0
- Local OS:windows 10 x64
- Remote OS: centos 7.2
- Remote Architecture: x64
- `code-server --version`: 3.12.0

jupyter version: 2012.8.12
git graph version: 1.30.0

## Steps to Reproduce

1. 
2.
3.

## Expected

The extension works well.

## Actual

git graph: blank view.
jupyter: show an error message "Command 'Jupyter: Create New Blank Notebook' resulted in an error (command 'jupyter.createnewnotebook' not found)"

## Logs
git graph error in browser console:
![image](https://user-images.githubusercontent.com/1547414/133547299-2ed5a85f-a3c5-425d-bc2f-5234eb31ad00.png)

jupyter error in browser console:
![image](https://user-images.githubusercontent.com/1547414/133547326-d743cf89-cdea-49a4-a365-735f03056f47.png)

This issue can be reproduced in VS Code: Yes

**Comment by jsjoeio** [comment] 2021-09-16 17:03
Thanks for the report!

Duplicate of https://github.com/cdr/code-server/issues/3874

**Closed** 2021-09-18 17:03 UTC
Labels: duplicate
