### ISSUE TITLE
instructions for non-localhost docker

### ISSUE THREAD

**Issue by ljubomirb** [cdr/code-server#1569] opened 2020-04-28 13:51 UTC
Maybe, if possible, to change instructions to allow this to work out of the box, on remote docker.
I followed instructions to install in remote docker server (not localhost), however, this does not work:

`docker run -it -p 127.0.0.1:8080:8080 -v "$PWD:/home/coder/project" -u "$(id -u):$(id -g)" codercom/code-server:latest`

The problem is - it is not accesible at _<remote_ip>:8080_
I'm guessing it is this docker line that needs to be changed, if that would be the case.

However, not being that familiar with docker, I added simple nginx proxy to try it from _<remote_ip>82/vs_:
```
server {
        listen 82;
        listen [::]:82;

        index index.html;

location /vs/ {
      proxy_pass http://localhost:8080/;
      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection upgrade;
      proxy_set_header Accept-Encoding gzip;
  }
}
```
And now it works, although here we have another problem (non secure, copy paste does not work), but that is another issue.

**Comment by cmoog** [comment] 2020-04-28 15:22
Thank you for bringing this to our attention. We are aware that the setup documentation is confusing and lacking at the moment. #1447 #1396 should help to improve this. 

The intent of the `docker run` quick start is to demo `code-server` for users on their local machine. In this case, `127.0.0.1:8080` makes sense.

**Comment by nhooyr** [comment] 2020-04-28 18:40
Yes, closing as duplicate of the other issues. You want to change the `127.0.0.1` to `0.0.0.0`.

**Closed by nhooyr** 2020-04-28 18:40 UTC

**Comment by ljubomirb** [comment] 2020-04-28 18:43
@nhooyr , what can you, please, change instructions. Thank you!
