### ISSUE TITLE
Docker: Settings/extensions not saved

### ISSUE THREAD

**Issue by Merith-TK** [cdr/code-server#703] opened 2019-05-20 18:51 UTC
- `code-server` version: Latest Docker as of may 20, 2019. 1145am PST-8
- OS Version: Ubuntu Server 18.04 <selfhosted>
## Description

Does not save settings/extensions at all

## Steps to Reproduce
fresh docker image, (`sudo apt install docker.io`, `docker run -it -p 127.0.0.1:8443:8443 -v "${PWD}:/home/coder/project" codercom/code-server --allow-http --no-auth`)

open terminal in code-server
then `touch ~/persistence_test`

then stop the docker image, and relaunch it, `~/persistence_test` does not exist

**Comment by Merith-TK** [comment] 2019-05-20 21:40
##Updated text for specifics

**Comment by Merith-TK** [comment] 2019-05-21 17:59
bump?

**Comment by deansheather** [comment] 2019-05-22 03:47
The `docker run` command you're running is mounting the current directory on the host to `/home/coder/project` in the container (`-v "${pwd}:/home/coder/project"`). This means that only the content in `/home/coder/project` will be persisted across sessions.

You can add more `-v` flags when using `docker run` to mount more directories if you need, like the following to persist settings and extensions between containers (untested):

```
-v "$HOME/.config/Code/User:/home/coder/.local/share/code-server/User" -v "$HOME/.vscode/extensions:/home/coder/.local/share/code-server/extensions"
```

**Comment by Merith-TK** [comment] 2019-05-22 03:54
alright, so it was me not knowing how to use docker properly, thanks for the information!

So if i wanted the docker container to hold the same config/extensions as the binary setup, the command would be something like this?

```
docker run -it -p 127.0.0.1:8443:8443 -v "/opt/code-server/workspace:/home/coder/project" -v "/opt/code-server/extensions:/home/code/extensions" -v /opt/code-server/data:/home/coder/data" codercom/code-server -e /home/coder/extensions -d /home/coder/data --allow-http --no-auth
```

**Comment by deansheather** [comment] 2019-05-22 04:55
Yeah, that should work if you add the missing double quote.

**Comment by Merith-TK** [comment] 2019-05-22 15:23
Okay, now im getting the samegrey screen error as my last issue (websockets are open)

**Comment by Merith-TK** [comment] 2019-05-23 03:53
@deansheather using the docker method we just described, all I am getting is a grey screen

Websockets are open on my web server so I know that's not the issue, I think

![image](https://user-images.githubusercontent.com/10422110/58224731-ab931e80-7cd3-11e9-849d-228ae6471631.png)

**Comment by Merith-TK** [comment] 2019-05-23 03:56
```
merith-admin@merith-tk:~$ sudo docker run -it -p 127.0.0.1:8443:8443 -v "/opt/code-server/workspace:/home/coder/project" -v "/opt/code-server/extensions:/home/code/extensions" -v "/opt/code-rkspace:/home/coder/project" -v "/opt/code-server/extensions:/home/code/extensions" -v "/optdata --allow-http --no-auth/code-server/data:/home/coder/data" codercom/code-server -e /home/coder/extensions -d /home/coder/data --allow-http --no-auth
[sudo] password for merith-admin:
(node:6) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability 
issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
INFO  code-server development
INFO  Additional documentation: http://github.com/codercom/code-server
INFO  Initializing {"data-dir":"/home/coder/data","extensions-dir":"/home/coder/extensions","working-dir":"/home/coder/project","log-dir":"/home/coder/.cache/code-server/logs/20190523035516671"}
INFO  Starting webserver... {"host":"0.0.0.0","port":8443}
WARN  No certificate specified. This could be insecure.
WARN  Documentation on securing your setup: https://github.com/codercom/code-server/blob/master/doc/security/ssl.md
WARN  Launched without authentication.
INFO  
INFO  Started (click the link below to open):
INFO  http://localhost:8443/
INFO  
INFO  Starting shared process [1/5]...
WARN  stderr {"data":"(node:18) [DEP0005] DeprecationWarning: Buffer() is deprecated due to 
security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"}
INFO  Connected to shared process
Error: ENOENT: no such file or directory, open '/src/packages/server/build/web/favicon.ico'
INFO  WebSocket opened / {"client":1,"ip":"172.17.0.1"}
```

**Comment by deansheather** [comment] 2019-05-27 06:42
Not sure what the cause of the grey screen is, could you check if there's anything in the browser console?

**Comment by Merith-TK** [comment] 2019-05-27 13:48
Nope!

**Comment by Merith-TK** [comment] 2019-05-28 15:32
There is absolutely nothing
just shows normal output

**Comment by Merith-TK** [comment] 2019-05-28 15:46
~~How i test this is by uninstalling docker, and then reinstalling it with absolutely nothing persistant

## WORKING Code-Server (binary)
https://i.imgur.com/q4u8ZkF.png

## DOCKER~~

For some stupid reason, it wants to work now... WELP!

**Comment by Merith-TK** [comment] 2019-05-28 15:55
```
How i test this is by uninstalling docker, and then reinstalling it with absolutely nothing persistant

## WORKING Code-Server (binary)
https://i.imgur.com/q4u8ZkF.png

## DOCKER (UNSPECIFIED/DEFAULT RUN COMMAND)
https://pastebin.com/D5iUh6DJ

## DOCKER (Specified)
https://pastebin.com/Fw1SL7di
```
(what i was gonna say)

**Comment by palp** [comment] 2019-06-02 23:45
I was able to get this working by copying the entire /home/coder/.local/code-server directory from a working container using docker cp, then changing the owner on that to 1000:1000 (the uid used inside the coder container) and mounting that. I haven't tested to see if you can mount individual folders with the correct permissions - this works well enough for me.

**Comment by sr229** [comment] 2019-11-07 15:19
Requesting further information. Failure to reply means it was fixed in your end and I'll close this automatically after 3 days.

**Comment by Merith-TK** [comment] 2019-11-07 15:21
I actually gave up with docker

**Closed** 2019-11-07 15:21 UTC
Labels: bug
