### ISSUE TITLE
install-extension errored with `error vscode Server returned 500`

### ISSUE THREAD

**Issue by ifduyue** [cdr/code-server#2431] opened 2020-12-09 12:07 UTC
Reproduce:

```bash
root@d8dd8b87eb1d:/code-server-3.7.4-linux-amd64# wget -q 'https://open-vsx.org/api/ms-python/python/2020.10.332292344/file/ms-python.python-2020.10.332292344.vsix'
root@d8dd8b87eb1d:/code-server-3.7.4-linux-amd64# sha256sum ms-python.python-2020.10.332292344.vsix 
aa0aff593f5eb8f310a2df9dcc666a9bee73f0a631decbce7ed0bcb5beb48330  ms-python.python-2020.10.332292344.vsix
root@d8dd8b87eb1d:/code-server-3.7.4-linux-amd64# ./bin/code-server --install-extension ms-python.python-2020.10.332292344.vsix Installing extensions...
Extension 'ms-python.python-2020.10.332292344.vsix' was successfully installed.
error vscode Server returned 500
error vscode Error: Server returned 500
    at Object.t.asJson (/code-server-3.7.4-linux-amd64/lib/vscode/out/vs/server/entry.js:373:933)
    at j.queryGallery (/code-server-3.7.4-linux-amd64/lib/vscode/out/vs/server/entry.js:393:695)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async j.query (/code-server-3.7.4-linux-amd64/lib/vscode/out/vs/server/entry.js:392:642)
    at async j.getExtensions (/code-server-3.7.4-linux-amd64/lib/vscode/out/vs/server/entry.js:390:251)
    at async /code-server-3.7.4-linux-amd64/lib/vscode/out/vs/server/entry.js:541:148
    at async Promise.all (index 0)
    at async J.getGalleryExtensions (/code-server-3.7.4-linux-amd64/lib/vscode/out/vs/server/entry.js:541:117)
    at async Promise.all (index 0)
    at async J.installExtensions (/code-server-3.7.4-linux-amd64/lib/vscode/out/vs/server/entry.js:540:13)
    at async J.run (/code-server-3.7.4-linux-amd64/lib/vscode/out/vs/server/entry.js:538:205)
    at async /code-server-3.7.4-linux-amd64/lib/vscode/out/vs/server/entry.js:545:678
    at async process.<anonymous> (/code-server-3.7.4-linux-amd64/lib/vscode/out/vs/server/entry.js:553:669)
root@d8dd8b87eb1d:/code-server-3.7.4-linux-amd64# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

- Web Browser: none
- Local OS: ubuntu 20.04
- Remote OS:
- Remote Architecture:
- `code-server --version`:  3.7.4 11f53784c58f68e7f4c5b3b8dae9407caa41725b

**Comment by ifduyue** [comment] 2020-12-09 12:43
More tests:

- 3.6.2: OK
- 3.7.0: OK
- 3.7.1: OK
- 3.7.2: Error
- 3.7.3: Error
- 3.7.4: Error

**Comment by code-asher** [comment] 2020-12-09 17:29
Thank you for opening. This looks like a duplicate of https://github.com/cdr/code-server/issues/2355. Please check there for more information!

**Closed by code-asher** 2020-12-09 17:29 UTC
