### ISSUE TITLE
Login redirect does not work with Nginx named locations

### ISSUE THREAD

**Issue by sshantt** [cdr/code-server#884] opened 2019-08-03 23:57 UTC
## Versions

- `code-server` version: code-server1.1156-vsc1.33.1-linux-x64.tar.gz
- OS Version: Ubuntu 18.04.2 LTS

## Description

code-server works fine with Nginx with location set as "location /". However, when location is set to "location /vscode/" code-server fails to properly redirect to the password entry page. It redirects me to `<IPv4 Public IP>/login/` which contains `404 Not Found nginx/1.14.0 (Ubuntu)`. Location "location /vscode/" works fine when code-server -N flag is included. Is there additional arguments I can give Nginx that can help it redirect?

## Steps to Reproduce

1. SSH into EC2 instance

2. Install Nginx and set configuration as follows 
```
# Server configuration
#
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;

	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location /vscode/ {
		proxy_pass http://localhost:1500/;
		rewrite ^/vscode/(.)$ /$1 break;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
	 	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header Upgrade $http_upgrade;
	       	proxy_set_header Connection upgrade;
		proxy_redirect http://localhost:1500 https://<IPv4 Public IP>;
	}
}
```

3. Download code-server stable and run 
`./server/code-server -p 1500 -H`

4. Go to web address 
`<IPv4 Public IP>/vscode/` 
example 
`12.345.67.891/vscode/`

**Comment by sr229** [comment] 2019-08-04 05:50
We're already fixing this on #857. If you want to please help us test the upcoming changes.

**Comment by sshantt** [comment] 2019-08-04 07:36
I would love to... How do I do that?

**Comment by sr229** [comment] 2019-08-04 07:42
I made some [LKGR Builds](https://github.com/sr229/cdr-web-lkgr/releases) which should allow you to test daily builds of the web branch. Check that out if you don't want to build from source.

**Comment by deansheather** [comment] 2019-08-04 08:20
Duplicate of #241.

**Closed by deansheather** 2019-08-04 08:20 UTC
Labels: bug

**Comment by daTourist** [comment] 2019-09-01 03:35
It appears this login redirect is still an issue on the current release [1.1156-vsc1.33.1] but have found a _workaround_ when using NGINX and the following _proxy_redirect_ configurations in a location, eg:
```
location /vscode/ {
	proxy_pass https://localhost:8443/;
	rewrite ^/vscode/(.)$ /$1 break;
	proxy_redirect https://localhost:8443/ https://code.example.com/vscode/;
	proxy_redirect ~^/(.*)$ https://code.example.com/vscode/$1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection upgrade;
	proxy_set_header Accept-Encoding gzip;
}
```
The _first directive_ rewrites _localhost_ redirects while the _second directive_ rewrites redirects with _absolute paths_ which catches the redirects to "/login" and then "/login/" correctly for me!

Hope this helps out someone else until the next release!

**Comment by projx** [comment] 2019-12-12 00:05
Looks like this is still occurring. When running nginx under http://<host>/cs/  the login always redirects to http://<host>/login. This is occuring using the template provided in the self-hosted quickstart: https://github.com/cdr/code-server/blob/master/doc/quickstart.md

**Comment by deansheather** [comment] 2019-12-12 03:55
Are you using code-server v2? I believe this was fixed in v2.

**Comment by vanducng** [comment] 2020-02-01 07:11
Hi all,
Per latest version [2.1698-vsc1.41.1](https://github.com/cdr/code-server/releases/tag/2.1698), the below setting works as expected by passing `--base-path` argument (fixed #241). 

Here is the setting hope it is useful for people encountered same issue.

1. Nginx conf
```bash
location /vscode/ {
      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection upgrade;
      proxy_set_header Accept-Encoding gzip;

      proxy_pass http://localhost:8441/;
  }
```
2. Code-server execution command:
```bash
./code-server --port 8441 --auth password --base-path /vscode
```

**Comment by edouardtheron** [comment] 2020-03-13 18:40
Hello @vanducng 

Despite correct nginx settings, the code-server page fails to load when I try to setup the `--base-path` parameter...

Instead, I just have a blank page. From the dev console Network tab, all static files seem to be downloaded as expected, but the JS console has errors:

![image](https://user-images.githubusercontent.com/16775821/76650087-e64e9780-652f-11ea-99ba-d56d724cd8df.png)

Then, inspecting the guilty sources, it looks like it loads HTML files instead of javascript:

![image](https://user-images.githubusercontent.com/16775821/76650139-f8303a80-652f-11ea-90c1-e3d54397d51d.png)

Any idea of what is going on here?

Thanks!

NB: if I keep the default root as the base path, everything works as expected.
NB2: I'm running version `2.1698`

**Comment by edouardtheron** [comment] 2020-03-13 18:55
Nevermind, I just noticed the latest release `3.0.0`, and the problem disappeared after the upgrade :raised_hands:
