### ISSUE TITLE
Jupyter Extension Can Not Find Kernel

### ISSUE THREAD

**Issue by ashvinnihalani** [cdr/code-server#4505] opened 2021-11-13 19:38 UTC
## OS/Web Information

- Web Browser: Microsft Edge Stable
- Local OS: localhost
- Remote OS: Arch Linux
- Remote Architecture: x86_64
- `code-server --version`: 3.12.0 4cd55f94c0a72f05c18cea070e10b969996614d2

## Steps to Reproduce

1. Install code-server from AUR
2. Install python extension w/ code-server --install-extension ms-python.python. The jupyter extension seems to be installed automatically. 
3. Try to open up ipynb file
4. Run cell

## Logs 
[vscode_jupyter_extension.log](https://github.com/cdr/code-server/files/7532636/vscode_jupyter_extension.log)

## Expected

It should run the cell

## Actual
It asks for a kernel and then directs to me the extension panel where no kernels show up

## Logs

Find the attached log file

## Notes

This issue can be reproduced in VS Code: No

I have been running into this issue on a different Debian-based system as well where I just untared the latest release. The current OS is a brand new fresh install with miniconda installed. I also run into #4271 as well so maybe similar. I also tried out Firefox to see if it was a browser issue.

**Comment by emmandecena** [comment] 2021-11-14 23:47
Duplicate of  #3874

**Comment by jsjoeio** [comment] 2021-11-15 21:36
thanks @emmandecena!

This should be fixed in the next release (4.0.0)

**Closed by jsjoeio** 2021-11-15 21:36 UTC
