### ISSUE TITLE
when the code-server killed or has error, the website has no attentions

### ISSUE THREAD

**Issue by bnulwh** [cdr/code-server#1080] opened 2019-10-16 14:46 UTC
- `code-server` version: 
- OS Version: 
version: all
os version: mac os, linux
## Description

when the code-server was killed ,the websites at the front not work without any attentions
## Steps to Reproduce

1. 
step 1 :start the code-server
1. 
step 2: open the code-server website

step 3: kill the code-server

step 4: create file or do something at the website, not work and no attentions

**Comment by sr229** [comment] 2019-10-16 15:33
This is intended by design. Again, VS Code Web is in its early days so there's no indication that it's offline. Closing as upstream issue.

**Closed by sr229** 2019-10-16 15:33 UTC
Labels: bug

**Comment by code-asher** [comment] 2019-10-16 15:51
1.39.1 has an indicator for this so we just need to update. Also see https://github.com/cdr/code-server/issues/1046 since it's essentially the same thing.
