### ISSUE TITLE
Searching does not work with EACCES error

### ISSUE THREAD

**Issue by jpmsilva** [cdr/code-server#1666] opened 2020-05-18 11:09 UTC
Reproduced with docker installation in version 3.3.0.
When trying to search (Ctrl+Shift+F) an error appears:

`spawn /usr/lib/code-server/lib/vscode/node_modules/vscode-ripgrep/bin/rg EACCES`

Looking inside the container I see that the binary under the path mentioned does not have execute permissions:
<pre>
root@708059e3622c:~# ls -la /usr/lib/code-server/lib/vscode/node_modules/vscode-ripgrep/bin/rg
-rw-r--r-- 1 root root 5037104 May 17 23:01 /usr/lib/code-server/lib/vscode/node_modules/vscode-ripgrep/bin/rg
</pre>

Granting the necessary execute permissions fixes the issue:
`chmod +x /usr/lib/code-server/lib/vscode/node_modules/vscode-ripgrep/bin/rg`

**Comment by penuts7644** [comment] 2020-05-18 13:04
Can confirm, having the same issue using the NPM installed version of code-server. This also certain extensions like Todo Tree...

**Comment by kylecarbs** [comment] 2020-05-18 16:49
Fixing now, sorry about this!

**Comment by nhooyr** [comment] 2020-05-18 17:10
Duplicate of #1665

**Closed by nhooyr** 2020-05-18 17:10 UTC

**Comment by jpmsilva** [comment] 2020-05-21 14:27
Hi, sorry for the duplicate.
I can confirm that using 3.3.1 the issue is fixed.
Thanks for the very fast response!
