### ISSUE TITLE
iPad: Korean input isn't combined properly

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#1314] opened 2020-01-29 00:35 UTC
See https://github.com/cdr/code-server/issues/1277

**Comment by nhooyr** [comment] 2020-01-29 00:38
Only happens on iPad, works fine on my Mac.

**Comment by rightones** [comment] 2020-12-17 16:40
Any updates here?

**Comment by code-asher** [comment] 2021-01-11 20:47
@jsjoeio I'm curious if you're able to replicate this?

If it's still an issue we might be better off raising it upstream.

**Comment by jsjoeio** [comment] 2021-01-11 21:21
@code-asher I will take this on and check

**Comment by jsjoeio** [comment] 2021-01-19 22:34
Okay trying to reproduce here:

## Reproduce
1. Add Korean keyboard under General > Keyboard > Keyboards > Add New Keyboard > Korean
2. Open code-server 
3. Open file (e.g. markdown file)
4. Switch to Korean keyboard  
5. Start typing

**Comment by jsjoeio** [comment] 2021-01-20 00:02
Opened an issue upstream ^

**Comment by jsjoeio** [comment] 2021-01-20 18:06
Closing this since the issue has been captured upstream.

**Closed by jsjoeio** 2021-01-20 18:06 UTC
Labels: browser-safari, os-ios, upstream
