### ISSUE TITLE
command 'python.setInterpreter' not found

### ISSUE THREAD

**Issue by binfeng** [cdr/code-server#1911] opened 2020-07-25 17:08 UTC
Cannot change python interpreter. Has error: command 'python.setInterpreter' not found

**Comment by fallenhitokiri** [comment] 2020-07-26 09:04
@binfeng seems to be the same issue as this one https://github.com/cdr/code-server/issues/1897

**Comment by code-asher** [comment] 2020-07-27 16:26
Closing as a duplicate of #1897. I've also seen this on the latest version of the extension but I haven't had a chance to debug it yet.

**Closed by code-asher** 2020-07-27 16:26 UTC
