### ISSUE TITLE
Can’t scroll on iPad with a trackpad.

### ISSUE THREAD

**Issue by awahlig** [cdr/code-server#1455] opened 2020-03-25 19:07 UTC
On an iPad running iPadOS 13.4 (which added full trackpad/mouse support), two-finger-scrolling on a trackpad doesn’t work (nothing happens).

Tested in different panels (editor, terminal, settings).
Tested using Magic Trackpad 2 (Apple’s iPad Pro keyboard with trackpad is not yet available).
Tried both the :latest (About window shows 1.41.1) and :3.0.1 docker images.

**Comment by dvelopin** [comment] 2020-03-25 19:46
Magic Mouse also doesn't "scroll" it seems to simulate "up" and "down" from the keyboard instead. There may be behavior settings we need to adjust?

**Comment by mjsamberg** [comment] 2020-03-26 02:22
Also, the scroll wheel on a mouse scrolls the entire window instead of just the text editor area.

**Comment by TheWindyMan** [comment] 2020-03-28 16:55
On a Logitech MX Vertical, binding Scroll Up and Scroll Down in Assistive Touch settings to the forward and back buttons allows for scrolling in the terminal/code windows separately. I haven’t found a way to bind those actions to the gesture of scrolling on the Magic Trackpad 2

**Comment by kylecarbs** [comment] 2020-03-30 14:15
We're making this a priority. Thanks for the upvotes everyone, shows us it's in high demand 👀.

**Comment by neilalexander** [comment] 2020-04-06 15:21
@mjsamberg The app container scrolling should be fixed in the code-server 3.0 releases — certainly it appears to be better for me now in code-server 3.0.2. 

I can confirm though that neither the Magic Mouse 2 nor the Magic Trackpad 2 scrolling works in 3.0.2 though. Scrolling using the touchscreen does work, although it feels slow due to the fact that there is no scroll momentum.

**Comment by mjsamberg** [comment] 2020-04-06 20:00
@neilalexander App container scrolling still occurs with my logitech mouse and the scroll wheel.

**Comment by cmoog** [comment] 2020-04-21 19:34
_Another update_
Please reference this [WebKit issue](https://bugs.webkit.org/show_bug.cgi?id=210071) for progress towards a patch.

**Comment by diegosucaria** [comment] 2020-05-28 11:46
Hello, has somebody found any other workaround for this? (even if it is buggy) I mean, other than using the scrollbars.

code-server and an Ipad pro with magic keyboard (which includes trackpad) is awesome!

**Comment by mjsamberg** [comment] 2020-06-06 20:24
I did notice, FWIW, that scrolling does work as expected in Google Docs website on iPad in multiple directions and even when there are multiple scrollable elements on the screen.

**Comment by perelin** [comment] 2020-06-07 09:39
@mjsamberg the faulty interaction between iPad trackpad and the code-server editor view seems to be an edge case. I see a lot of complex web apps handling scrolling stuff without any issue (gdocs, office356, dropbox, etc). The mentioned WebKit issue linked by @cmoog also has no movement at all so far.

**Comment by nhooyr** [comment] 2020-06-09 18:22
@perelin VS Code's editor handles scrolling manually so that it doesn't have to load the entire file into memory all at once syntax highlighted. The ability to control scrolling manually is what's unsupported by webkit on iOS.

**Comment by danielscottjames** [comment] 2020-06-24 23:19
Curious, has anyone played around with this on iOS 14 beta yet and noticed a difference?

**Comment by mjsamberg** [comment] 2020-06-25 00:05
@danielscottjames Just tried it, no difference.

**Comment by diegosucaria** [comment] 2020-06-25 15:00
Oh, that is heartbreaking @mjsamberg. I was hoping it would work.

**Comment by chenshuyang83123** [comment] 2020-07-19 11:17
I hope any improvement of this case.

**Comment by stahldom** [comment] 2020-08-04 07:19
Don’t we all...

**Comment by jasonjurotich** [comment] 2020-09-14 00:00
I am also using iPad OS 14 and no scrolling whatsoever with the magic keyboard, not even the page. Nothing happens at all.

**Comment by mjsamberg** [comment] 2020-09-16 12:39
So it does look like the people that do Gitpod and Theia have been able to fix this. https://github.com/gitpod-io/gitpod/issues/1703#issuecomment-690002867

Confirmed working in GitPod.

**Comment by kamaln7** [comment] 2020-09-17 16:34
@mjsamberg Did you test it with a trackpad? I just spun up a gitpod (at gitpod.io) and I see the same issue as with code-server—scrolling with touch works but not with a trackpad 😕

**Comment by mjsamberg** [comment] 2020-09-25 19:51
@kamaln7 Yeah. Looks like it only works with certain content frames :/

**Comment by KR-78** [comment] 2020-09-27 02:41
This indeed makes code-server almost unusable on the iPad + magic keyboard, and there seems to be no activity on the webkit-linked issue :( Anything that we can do to prioritize / help with this issue? I am not familiar at all with the technologies involved here, so I can’t really help on the coding side unfortunately....

**Comment by perelin** [comment] 2020-10-08 13:59
As a (rather heavyweight) workaround I installed XFCE and XRDP on my development VM and use the iOS RDP/VNC app "Jump" to connect to the XFCE desktop. There I installed VSCode and can use the MagicKeyboard trackpad  without issues. Not quite as elegant or efficient as using Coder in the browser, but it gets the job done. I can use my iPad for quick coding session while Im on the road (or in bed :). Took a bit of configuration (and googeling) to get everything working but I can give some pointers if anyone is interested.

**Comment by truePhilipp** [comment] 2020-10-10 16:39
> _Another update_
> 
> Please reference this [WebKit issue](https://bugs.webkit.org/show_bug.cgi?id=210071) for progress towards a patch.

Since it does not look like anything is moving there, i'll just put an idea here. The WebKit issue seems to be that
"Trackpad and Mouse scroll events on iPad only fire "pointermove" -- not "wheel" ".
When playing around a bit i noticed that they indeed don't fire wheel, but scroll events. Is it maybe possible to support "scroll" events?

**Comment by TobiaszCudnik** [comment] 2020-10-10 16:57
What about including a polyfill for those in some global file from code-server? Or fwding them manually.

**Comment by danielsteiner** [comment] 2020-10-12 11:54
@TobiaszCudnik if you mean to rewrite the pointermove events to mousewheel events: That won't work, wheel events are read only and can't be fired from JS.

**Comment by perelin** [comment] 2020-10-21 07:46
For everybody that is not monitoring the Webkit bugtracker issue: https://bugs.webkit.org/show_bug.cgi?id=210071#c13

> Also, do know that while I can't comment on the timing of fixes, I am absolutely aware of this and know that it is important.

So there is hope :)

**Comment by mfujinami** [comment] 2020-11-03 02:35
Is it possible to scroll the editor pane with JS? I tried with element.scrollBy(x, y). But it could be scroll only downward direction. If it's possible, the issue will be solved for me.

**Comment by mgguinne** [comment] 2020-11-15 06:38
+1 just moved to iPad only workflow and this is one of those little things that is a pain, but can see there does appear to be some others having issue and it’s bigger than just VSCode.

**Comment by pierremtb** [comment] 2020-11-21 04:15
Has anyone here gotten an invite to GitHub Codespaces? I assume that if they don’t yet support iPad OS’ scrolling then they’ll have to when it goes public

**Comment by TobiaszCudnik** [comment] 2020-11-21 05:55
@pierremtb the scrolling also doesnt work in codespaces (I checked), so Im sure the fix will come from the upstream eventually...

**Comment by pierremtb** [comment] 2020-11-21 10:41
@TobiaszCudnik thanks for checking, feels like good news to me!

**Comment by JPyke3** [comment] 2020-11-21 10:43
The VSCode Issue: https://github.com/microsoft/vscode/issues/106232

**Comment by forairan** [comment] 2020-12-12 02:13
Looks like the patch has landed in upstream WebKit - hopefully it's only a matter of time before this is fixed in new iOS builds! https://trac.webkit.org/changeset/270712/webkit

**Comment by SIXSIXSIXX** [comment] 2021-01-06 12:23
Any update?

**Comment by petemill** [comment] 2021-01-06 15:22
It isn't contained in the latest iOS beta 14.4, so looks like we will have to wait a bit longer.

**Comment by imownbey** [comment] 2021-01-06 15:33
Its possible also teh WebKit fix will fix for some pages but not vscode if this comment is still correct https://bugs.webkit.org/show_bug.cgi?id=210071#c22

**Comment by pollux2015** [comment] 2021-01-07 08:53
Any update?

**Comment by BalmaBrian** [comment] 2021-01-24 18:46
Is there any linked issues that I can read related to this issue?

**Comment by spatinolang-vtr** [comment] 2021-01-24 20:47
There was a follow up on the Webkit bugtracker today: https://bugs.webkit.org/show_bug.cgi?id=210071#c34 
Looks like the coming Webkit patch will also fix the VSCode / code-server issue!

@BalmaBrian: subscribe to https://bugs.webkit.org/show_bug.cgi?id=210071 and https://github.com/microsoft/vscode/issues/106232 for future upstream updates. But the important thing is probably: when will the Webkit patch be released for in an iOS version? Apple does not make their roadmaps public or comment on stuff like this. So welcome to the waiting game :)

**Comment by ambichetan** [comment] 2021-02-01 20:08
Hooray!, I can confirm that the scrolling issue is fixed on the latest ipadOS 14.5 beta 1. Welcome to true coding on iPad fellas. Super happy 😃 


https://user-images.githubusercontent.com/16759509/106512091-ff34a400-6485-11eb-91b0-5909e8e3cdd9.mov

**Comment by danielsteiner** [comment] 2021-02-01 22:24
Yup. Can confirm - works fine on 14.5 :) 

Now I can finally replace my laptop for on the go sessions!

**Comment by Dids** [comment] 2021-02-02 16:52
Does this require a new version of code-server?

Updated my iPad Air 2020 to 14.5, but still can't scroll with my Magic Keyboard. Clicking now works consistently though.

**Comment by Dids** [comment] 2021-02-02 17:07
> No. This was not a bug at code-Server (or vs-code to be precise) but safari.

Interesting (and thanks for confirming), wonder why I can't get it to work then. Will try a few reboots and reattaching the keyboard, but also wondering if there's an experimental Safari setting or something that enables/disables it.

I can use the trackpad to scroll everywhere else as usual (outside of code-server), but in code-server scroll events don't seem to register at all. Touch screen scrolling works as expected.
Additionally, both left and right click seem to work on the trackpad using single/two finger tapping.

**Comment by lboller** [comment] 2021-02-02 20:36
> Interesting (and thanks for confirming), wonder why I can't get it to work then. Will try a few reboots and reattaching the keyboard, but also wondering if there's an experimental Safari setting or something that enables/disables it.

I had the same problem, but scrolling works if you save the site to the desktop and open as a PWA.

**Comment by clsx524** [comment] 2021-02-02 21:23
Can confirm it works in the PWA but not working in a tab in safari.

Also @Dids I don’t have any settings for Settings -> Safari

**Comment by danielsteiner** [comment] 2021-02-02 22:02
Works fine for me in a browser tab as well.

**Comment by izewang** [comment] 2021-02-03 14:23
Works for me as PWA. While in browser, scroll works only when the URL bar is hidden. It doesn't matter whether the "Wheel" settings are on or off.

**Comment by bbruenings** [comment] 2021-02-18 10:34
> > No. This was not a bug at code-Server (or vs-code to be precise) but safari.
> 
> Interesting (and thanks for confirming), wonder why I can't get it to work then. Will try a few reboots and reattaching the keyboard, but also wondering if there's an experimental Safari setting or something that enables/disables it.
> 
> I can use the trackpad to scroll everywhere else as usual (outside of code-server), but in code-server scroll events don't seem to register at all. Touch screen scrolling works as expected.
> Additionally, both left and right click seem to work on the trackpad using single/two finger tapping.
> 
> EDIT: Can anyone confirm if they have these two settings enabled under Settings -> Safari -> Experimental features?
> ![Screenshot](https://camo.githubusercontent.com/7ced8b59f4c0917a84a2ea24fb21d01da93d01101ea28931865c00ee24fd620a/68747470733a2f2f692e696d6775722e636f6d2f4d4664757737302e6a7067)

Yes. Just updated to iPadOS 14.5 beta 2. Both flags are visible and enabled. Scrolling now works as expected using the Magic Keyboard Trackpad

**Comment by Dids** [comment] 2021-02-22 06:34
I can confirm that scrolling with a Magic Keyboard + latest iPad Air only works when a) using PWA or b) specifically hiding the address bar in Safari.

Does anyone actually know why this happens and are some of the reports here truly saying it "just works" for them in Safari, while the address bar is visible and not running as a PWA?

I've even tried rolling my own web view wrapper apps, enabling app domains for increased API support, but nothing seems to work outside of the two solutions above. As it currently is, this seems very janky and hacky, but at this point I can't even tell if this is intended behavior or something the WebKit or iOS/iPadOS developers should fix?

**Comment by chenshuyang1203** [comment] 2021-02-22 11:49
Me too. Only works in PWA of safari.

________________________________
发件人: Pauli Jokela <notifications@github.com>
发送时间: 2021年2月22日 6:35
收件人: cdr/code-server <code-server@noreply.github.com>
抄送: 陈大羊 <chenshuyang.cn@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [cdr/code-server] Can’t scroll on iPad with a trackpad. (#1455)


I can confirm that scrolling with a Magic Keyboard + latest iPad Air only works when a) using PWA or b) specifically hiding the address bar in Safari.

Does anyone actually know why this happens and are some of the reports here truly saying it "just works" for them in Safari, while the address bar is visible and not running as a PWA?

I've even tried rolling my own web view wrapper apps, enabling app domains for increased API support, but nothing seems to work outside of the two solutions above. As it currently is, this seems very janky and hacky, but at this point I can't even tell if this is intended behavior or something the WebKit or iOS/iPadOS developers should fix?

―

**Comment by danielsteiner** [comment] 2021-02-22 12:28
> I can confirm that scrolling with a Magic Keyboard + latest iPad Air (iPadOS 14.5 b2) only works when a) using PWA or b) specifically hiding the address bar in Safari.
> 
> Does anyone actually know why this happens and are some of the reports here truly saying it "just works" for them in Safari, while the address bar is visible and not running as a PWA?
> 
> I've even tried rolling my own web view wrapper apps, enabling app domains for increased API support, but nothing seems to work outside of the two solutions above. As it currently is, this seems very janky and hacky, but at this point I can't even tell if this is intended behavior or something the WebKit or iOS/iPadOS developers should fix?

Ever imagined, that there are people where „it just works“? 
For me it works: 
*) In a Browser Tab with Adressbar shown
*) In a Browser Tab with Adressbar hidden
*) As PWA 
*) In thirdparty apps

Since the first developer beta of 14.5

Maybe its an iPad Air issue. Works fine for anyone using an iPad Pro here…

**Comment by izewang** [comment] 2021-02-22 14:23
> > I can confirm that scrolling with a Magic Keyboard + latest iPad Air (iPadOS 14.5 b2) only works when a) using PWA or b) specifically hiding the address bar in Safari.
> > Does anyone actually know why this happens and are some of the reports here truly saying it "just works" for them in Safari, while the address bar is visible and not running as a PWA?
> > I've even tried rolling my own web view wrapper apps, enabling app domains for increased API support, but nothing seems to work outside of the two solutions above. As it currently is, this seems very janky and hacky, but at this point I can't even tell if this is intended behavior or something the WebKit or iOS/iPadOS developers should fix?
> 
> Ever imagined, that there are people where „it just works“?
> For me it works:
> *) In a Browser Tab with Adressbar shown
> *) In a Browser Tab with Adressbar hidden
> *) As PWA
> *) In thirdparty apps
> 
> Since the first developer beta of 14.5
> 
> Maybe its an iPad Air issue. Works fine for anyone using an iPad Pro here…
> 
> Edit: and this is still not an issue of code-server but an Safari bug.

I am having the issue that cannot scroll in browser tab with address bar shown on my iPad Pro 12.9''. Since the first beta of 14.5 and the latest version of code-server. :( Seems not a issue only on ipad air.

**Comment by wil-code** [comment] 2021-03-21 23:00
I can confirm that issue will be solved with iPadOS 14.5 on my iPad Air (4th generation).

**Comment by jkcoxson** [comment] 2021-04-26 18:36
This issue does not seem to be fixed in the iOS 14.5 release. It must have not made it from the beta.

**Comment by mcmans** [comment] 2021-04-26 20:35
Works on 14.5 now using PWA/Adding to home screen.

**Comment by awahlig** [comment] 2021-04-26 22:19
For me it works on iPadOS 14.5 (iPad Pro 2018) both in Safari and in PWA. 🎉

Menu / Help / About:
code-server: v3.9.3
VS Code: v1.54.2

**Comment by jsjoeio** [comment] 2021-04-28 21:09
Confirmed as well. 

Working on iPadOS 14.5 when you add code-server to your home screen/PWA. Tested with code-server 3.9.3

## Screenshot
https://user-images.githubusercontent.com/3806031/116472542-de80ae00-a82a-11eb-909a-a6824e896228.MP4

Given that iPadOS 14.5 was released to the public on April 26 (see [release notes](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14_5-release-notes)) and we know this is working, I'm going to close this.

**Closed by jsjoeio** 2021-04-28 21:09 UTC
Labels: blocked, browser-safari
