### ISSUE TITLE
Using Proxy gives a "Maximum call stack size exceeded" error page

### ISSUE THREAD

**Issue by metalshanked** [cdr/code-server#2867] opened 2021-03-12 08:21 UTC
Sure. Here is the info

- **Web Browser:** Chrome (Mac and Windows) Version 88.0.4324.192 (Official Build) (x86_64)
- **Local OS**: Tried on both Mac and Windows
- **Remote OS**: Official Coder Docker Image (Debian) (codercom/code-server:3.9.x)
- **Remote Architecture:** : Linux x64
- `code-server --version`: 3.9.0 and 3.9.1

![image](https://user-images.githubusercontent.com/57646596/110982638-0329d080-8326-11eb-88ab-0e0ea81ad9b2.png)

**Steps to Reproduce**
1. Pull image and instantiate container [codercom/code-server:3.9.1] with bind address 0.0.0.0 and port
2. Open Coder via browser and go to URL --> domain-host/proxy/anyport/ 
3. Max call stack exceeded error in the chrome page. (It should ideally be connection refused or similar error is nothing is running on the port
4. Try it with an actual web app such as "Live Server" or any small test server program
5. Go to URL --> domain-host/proxy/5500/ (for liveserver) or 8000 for custom test server
6. The same Max call stack exceeded error in the chrome page.
7. Revert back to the 3.7.4 image
8. Proxy pages above open normally or show the standard connection refused error if no service is running on the port

**Issue Description:**
Hello, I recently upgraded to the latest versions 3.9.0 and 3.9.1 (Docker) and see that the proxying is no longer working.
It worked fine in the v3.7.4 image.
The error i get is a page with : Maximum call stack size exceeded and the browser console log just says "500 internal server error".

I deleted all extensions and just pulled the base image docker pull codercom/code-server:3.9.1 and the issue persisted.

As soon as i use the 3.7.4 image, the issue goes away.
I use myurl/proxy/port/

Any advise?

Thanks in advance.

**Comment by jsjoeio** [comment] 2021-03-12 17:40
Hi @metalshanked sorry to hear that you're having issues. In order to best help you, we need a few things:
- update the description and fill out the fields that were in the issue template (OS info, etc).
- provide steps to reproduce your issue

Thanks!

**Comment by metalshanked** [comment] 2021-03-12 18:38
Sure. Here is the info



- **Web Browser:** Chrome (Mac and Windows) Version 88.0.4324.192 (Official Build) (x86_64)
- **Local OS**: Tried on both Mac and Windows
- **Remote OS**: Official Coder Docker Image (Debian) (codercom/code-server:3.9.x)
- **Remote Architecture:** : Linux x64
- `code-server --version`: 3.9.0 and 3.9.1


![image](https://user-images.githubusercontent.com/57646596/110982638-0329d080-8326-11eb-88ab-0e0ea81ad9b2.png)

**Steps to Reproduce**
1. Pull image and instantiate container [codercom/code-server:3.9.1] with bind address 0.0.0.0 and port
2. Open Coder via browser and go to URL --> domain-host/proxy/anyport/ 
3. Max call stack exceeded error in the chrome page. (It should ideally be connection refused or similar error is nothing is running on the port
4. Try it with an actual web app such as "Live Server" or any small test server program
5. Go to URL --> domain-host/proxy/5500/ (for liveserver) or 8000 for custom test server
6. The same Max call stack exceeded error in the chrome page.
7. Revert back to the 3.7.4 image
8. Proxy pages above open normally or show the standard connection refused error if no service is running on the port

**Issue Description:**
Hello, I recently upgraded to the latest versions 3.9.0 and 3.9.1 (Docker) and see that the proxying is no longer working.
It worked fine in the v3.7.4 image.
The error i get is a page with : Maximum call stack size exceeded and the browser console log just says "500 internal server error".

I deleted all extensions and just pulled the base image docker pull codercom/code-server:3.9.1 and the issue persisted.

As soon as i use the 3.7.4 image, the issue goes away.
I use myurl/proxy/port/

Any advise?

Thanks in advance.

**Comment by metalshanked** [comment] 2021-03-12 18:48
Sure! updated with requested info

**Comment by jsjoeio** [comment] 2021-03-12 19:04
Perfect! Thanks for being so thorough. We'll see if we can take a look

**Comment by metalshanked** [comment] 2021-03-12 20:09
Apologies, i see I had two environment variables for no_proxy and http_proxy setup which I believe was required for v3.7.4.
When i removed those two environment variables on v3.9.1 it seems to be working fine.

Will investigate further if I have lost any functionality by removing the no_proxy and http_proxy environment variables from the coder container.

**Comment by jsjoeio** [comment] 2021-03-12 20:29
@metalshanked no worries at all! Glad you figured it out. I'm going to close this for now then since it's resolved. If you see other errors, @ me here and we can reopen!

**Closed by jsjoeio** 2021-03-12 20:29 UTC
Labels: help-wanted, needs-investigation
