### ISSUE TITLE
Reverse Proxy Issue

### ISSUE THREAD

**Issue by AmansRevenger** [cdr/code-server#770] opened 2019-06-13 18:48 UTC
- `code-server` version: v1.1156-vsc1.33.1
- OS Version: Ubuntu 18.04 

## Description

Reverse Proxy doesnt work at all.

It either results in failed SSL Handshake or

this:

![image](https://user-images.githubusercontent.com/18306225/59458684-41c1ec80-8e1b-11e9-9c9e-a4fcdc235e66.png)

![image](https://user-images.githubusercontent.com/18306225/59458746-66b65f80-8e1b-11e9-9a2d-3447f7a2cbe0.png)

Reverse Proxy Settings with working grafana above:

![image](https://user-images.githubusercontent.com/18306225/59458842-a4b38380-8e1b-11e9-8893-4735ae4befc5.png)

What am I missing?

**Comment by RyoshiKayo** [comment] 2019-06-13 23:58
Your proxy pass needs to be `http://localhost:8443` not `http://giovanni:8443` I believe. I'm not sure where you got `giovanni` from.

**Comment by AmansRevenger** [comment] 2019-06-14 04:16
giovanni is the hostname of the server in the network where the docker containers and services run, nginx itself is a docker container, so localhost wont work...

**Comment by fbartels** [comment] 2019-06-14 04:57
To me it seems the issue is that you are trying to proxy Code-Server as a subfolder. AFAIK it has to run in root of the domain.

**Comment by AmansRevenger** [comment] 2019-06-14 05:02
So mywebsite.com/vscode would never work?

**Comment by fbartels** [comment] 2019-06-14 05:29
No, at least not how it is currently designed. You would need to setup vscode.mywebsite.com.

A lot of programs are designed this way today. With sni and free certs from let's encrypt this is also not much work. Only potential roadblock would be DNS providers not allowing additional DNS entries.

**Comment by AmansRevenger** [comment] 2019-06-14 07:07
I already use letsEncrypt, but I dont think I can setup a whole subdomain...

**Comment by deansheather** [comment] 2019-06-15 13:13
At the moment (until #722 is merged), code-server doesn't work when it's not mounted at root (`/`) in your reverse proxy.

You should be able to easily issue a new certificate for a subdomain on your domain through letsencrypt very easily, and then create a new virtual host in nginx.

**Comment by abubakar-bilal** [comment] 2019-06-27 07:45
@deansheather I just created a subdomain and added configuration for proxy. But it gives me following error

Nginx conf

```
server {
  listen 443 ssl;
  server_name ide.mysite.com;

  location / {
    proxy_pass http://localhost:8443;
    proxy_set_header Host            $host:$server_port;
    proxy_set_header X-Forwarded-For $remote_addr;
    add_header 'Access-Control-Allow-Origin' 'https://console.codehelper.com';
    add_header 'Access-Control-Allow-Origin' 'http://localhost';
    add_header 'Access-Control-Allow_Credentials' 'true';
  }
}
```

Error
```WebSocket connection to 'wss://ide.2-angg-2.vce.codehelper.com/' failed: Error during WebSocket handshake: Unexpected response code: 200```

https://ide.mysite.com

**Comment by deansheather** [comment] 2019-06-27 08:02
@abubakar-bilal Add the following to your `location` block:
```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection upgrade;
proxy_set_header Accept-Encoding gzip;
```

**Comment by abubakar-bilal** [comment] 2019-07-02 12:34
Hey @deansheather 

Here is an issue, sub_filter is not working with above https://github.com/cdr/code-server/issues/770#issuecomment-506238855 proxy settings. People are saying that because you have gzip enabled therefore it's not working. And when I do this 
`proxy_set_header Accept-Encoding "";`

Code server starts giving me `Not Found` and console inspect says this 
```
Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-jKkgppGJ08cqS5XKPdlf/Mdph8lsIR979iy7r3fw7Mw='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

A bad HTTP response code (404) was received when fetching the script.
```

Can you please guide me how can I achieve this. I want to use sub_filter on nginx level with proxy pass of code server.

**Comment by DarkIrata** [comment] 2019-07-04 22:34
Hey!
Having a running server behind a reverse proxy through nginx. 
`server {

  listen 443 ssl;
  server_name code.MYDOMAIN.TLD;

  location / {
        # redirect all HTTP traffic
        proxy_pass http://10.0.2.5:8443/;
        proxy_set_header  Host 10.0.2.5:8443;

        proxy_set_header  X-Real-IP $remote_addr;
        proxy_set_header  X-Forwarded-Proto https;
        proxy_set_header  X-Forwarded-For $remote_addr;
        proxy_set_header  X-Forwarded-Host $remote_addr;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

#CERTBOT SSL THINGS
`

this configuration (even with less proxy_set_header works fine). The reason i have them all is that my problem is that while the reverse proxy works fine, could it be that the forwarded headers gets ignored?
In the code-server log i only see the IP from the nginx server (10.0.2.2).
`INFO  WebSocket opened / {"client":5,"ip":"10.0.2.2"}`

**Comment by deansheather** [comment] 2019-07-07 03:26
@abubakar-bilal GH-826 should fix the `Accept-Encoding` issue you have and allow you to use substitution filters in your reverse proxy.

@DarkIrata code-server doesn't have any mechanism to trust reverse proxies, nor is it needed since code-server doesn't do anything with remote IP addresses (except for logging them). If you'd like to log access to your code-server instance with nginx (or any other reverse proxy), I'd recommend using the access_log.

**Comment by yihengli** [comment] 2019-07-07 09:59
> @abubakar-bilal [GH-826](https://github.com/cdr/code-server/pull/826) should fix the `Accept-Encoding` issue you have and allow you to use substitution filters in your reverse proxy.
> 

Cannot wait to test this fix, as using substitution filters may allow users to add customized styles and fonts resources directly into the browser, potentially a hackaround for https://github.com/cdr/code-server/issues/760 .

(Or let me know if there are more native ways for code-server to customized fonts etc.)

**Comment by abubakar-bilal** [comment] 2019-07-08 05:39
@deansheather Thanks so much for this fix. I would like to hear how can I test this on my side. Because currently I download the release and running that on my machine. How can I test this PR to see if my issue fixed. 

@yihengli Yes if this works, then definitely custom styling issues will be fixed.

Thanks so much for all the support provided by you guys. Really appreciate that.

**Comment by deansheather** [comment] 2019-07-08 10:01
You can compile it by checking out my branch and running:
```
yarn install
NODE_ENV=production VERSION=local-dev yarn task build:server:binary
./packages/server/cli-linux-x64 --help
```

**Comment by deansheather** [comment] 2019-07-08 10:08
BTW, I did end up creating a PR with a `--trust-proxy` arg: GH-835.

**Comment by abubakar-bilal** [comment] 2019-07-08 11:59
> You can compile it by checking out my branch and running:
> 
> ```
> yarn install
> NODE_ENV=production VERSION=local-dev yarn task build:server:binary
> ./packages/server/cli-linux-x64 --help
> ```

ERROR BUILD:WEB failed {"exitCode":1,"stdout":"\n> @coder/web@ build /home/code-server/packages/web\n> ../../node_modules/.bin/cross-env UV_THREADPOOL_SIZE=100 node --max-old-space-size=32384 ../../node_modules/webpack/bin/webpack.js --config ./webpack.config.js\n\nHappy[ts]: Version: 5.0.1. Threads: 1\nHappy[ts]: All set; signaling webpack to proceed.\n","stderr":"npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1562586803937-0.6531972737635816/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! @coder/web@ build: `../../node_modules/.bin/cross-env UV_THREADPOOL_SIZE=100 node --max-old-space-size=32384 ../../node_modules/webpack/bin/webpack.js --config ./webpack.config.js`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the @coder/web@ build script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /root/.npm/_logs/2019-07-08T11_57_42_562Z-debug.log\n"}


@deansheather  I'm getting this error on second step.

**Comment by abubakar-bilal** [comment] 2019-07-10 17:47
@deansheather Can you please let me know about this issue. How can I complete this setup. Because on mac it's working fine. and build is getting created.

**Comment by deansheather** [comment] 2019-07-11 02:24
@abubakar-bilal Please post a link to the log file at the end of the error message as a gist. The log doesn't really tell me much except that it exited early.

Make sure the node version installed is `10.15.1`, and the node version  yarn is using is the same one (apparently yarn is using a different instance of node). Try running the yarn commands with `--scripts-prepend-node-path`.

**Comment by abubakar-bilal** [comment] 2019-07-11 06:01
Here is the gist link attached of log file.
https://gist.github.com/abubakar-bilal/15e415d5388f0540e198bec1ac8d638e

**Comment by deansheather** [comment] 2019-07-11 07:32
Try again with node 10.15.1 and with the `--scripts-prepend-node-path` on the yarn commands.

**Comment by abubakar-bilal** [comment] 2019-07-11 19:15
I updated node to 10.16.0 and again tried with scripts prepend added. Now that npm node warning went away. But still it gives error. Here is the gist of attached log file https://gist.github.com/abubakar-bilal/db47a5354e6e7c03abae04e401ee7b6c

**Comment by code-asher** [comment] 2019-11-01 21:29
v2 has changed quite a bit surrounding all this so I'm uncertain how much if any still applies. I suppose for now I'll close this since it references v1 and if there are reverse proxy issues in v2 I'd love to hear them (either here or a new issue).

**Closed by code-asher** 2019-11-01 21:29 UTC
Labels: bug

**Comment by datsabk** [comment] 2020-01-13 17:45
@code-asher  Having the same issue with v2 as well. I saw that you tried to do some patching for the same. Has it been pushed and is it working?

**Comment by code-asher** [comment] 2020-01-13 19:02
It should be working; I do most of my testing through a reverse proxy.
If you're hosting at a subpath and using the login page then make sure
you've set the `--base-path` flag so code-server can redirect to
properly.

**Comment by krjw** [comment] 2020-03-29 15:11
I cannot find the "--base-path" option. Is there some kind of documentation of all the flags?

**Comment by jiayiliu** [comment] 2021-08-19 03:56
The flag is not in the latest release yet. I got the error below
error Unknown option --base-path=/vscode

version info.
code-server 3.11.1 c680aae973d83583e4a73dc0c422f44021f0140e

> It should be working; I do most of my testing through a reverse proxy. If you're hosting at a subpath and using the login page then make sure you've set the `--base-path` flag so code-server can redirect to properly.

**Comment by code-asher** [comment] 2021-08-23 16:44
--base-path was removed, actually. code-server should work behind a base
path even without this flag.
