### ISSUE TITLE
Unable to install any extension on macOS

### ISSUE THREAD

**Issue by trigun539** [cdr/code-server#1007] opened 2019-09-20 00:40 UTC
- code-server version: 2.1523-vsc1.38.1
- OS Version: MacOS Mojave 10.14.6
- Extension:https://v1.extapi.coder.com/publishers/vscodevim/vsextensions/vim/1.10.2/vspackage

## Description

Unable to install any extension. Tried eslint, prettier, vim. None worked with same steps.

## Steps to Reproduce

1. Click extensions, find an extension and click install.
![image](https://user-images.githubusercontent.com/508205/65290425-3e768500-db1d-11e9-9c9e-308e7641f08e.png)
1. Click download manually
![image](https://user-images.githubusercontent.com/508205/65290436-4b937400-db1d-11e9-8ba2-c5975ef5c228.png)

**Comment by Ehco1996** [comment] 2019-09-20 06:42
same problem , 
<img width="495" alt="屏幕快照 2019-09-20 下午2 41 51" src="https://user-images.githubusercontent.com/24697284/65305060-ccea1580-dbb4-11e9-88f3-f1dcfa0fa644.png">

**Comment by frank-dspeed** [comment] 2019-09-20 08:28
the error does not exist on linux only for information

**Comment by sr229** [comment] 2019-09-20 11:19
@trigun539 As a workaround, use a Ubuntu VM and mount your workspace folder in the VM for now while we try to solve this. I provide [daily builds](https://github.com/sr229/cdr-web-lkgr) so you can test out the changes once we have it in place.

**Comment by trigun539** [comment] 2019-09-20 18:07
@sr229 Will do, thanks.

**Comment by cottongin** [comment] 2019-09-21 01:38
I am experiencing this issue as well with code-server running on Fedora 30. I've tried enabling `--log debug` and `--verbose` when running the server but nothing is shown in stdout when I try (and fail) to install an extension.
- code-server version: `2.1523-vsc1.38.1`
- OS Version: Fedora 30
- Extension: any

**Comment by sr229** [comment] 2019-09-21 14:08
> I am experiencing this issue as well with code-server running on Fedora 30. I've tried enabling `--log debug` and `--verbose` when running the server but nothing is shown in stdout when I try (and fail) to install an extension.
> 
> * code-server version: `2.1523-vsc1.38.1`
> * OS Version: `Fedora 30`
> * Extension: **any**

I use Fedora 30 in my end and I have never encountered this. perhaps your `xdg-home-dir` is not accessible?

**Comment by cottongin** [comment] 2019-09-21 14:39
After digging in I found this in the logs directory (it'd be nice if this were printed to stdout while the server is running if the `--verbose` flag is used):

```
[2019-09-20 20:35:12.087] [remoteagent] [info] Installing extension: ms-python.python                                                                                     
[2019-09-20 20:35:12.223] [remoteagent] [error] Failed to install extension: ms-python.python unable to get local issuer certificate 
```

**Comment by bihuchao** [comment] 2019-09-22 08:09
Same error.
log:
![image](https://user-images.githubusercontent.com/12815229/65384299-56cfe500-dd53-11e9-80dc-fc5d320d36e1.png)

**Comment by sr229** [comment] 2019-09-22 14:44
@code-asher looks like we're getting signature issues

**Comment by cottongin** [comment] 2019-10-07 17:22
any update on this?

**Comment by AppleEducate** [comment] 2019-10-07 17:27
Still broken for me

**Comment by frank-dspeed** [comment] 2019-10-07 19:38
you can expect up to 2 month till this is fixed. @AppleEducate @cottongin  but you can use the workaround

**Comment by frank-dspeed** [comment] 2019-10-07 19:39
This should get renamed as only MacOS is affected by this.

**Comment by cottongin** [comment] 2019-10-08 17:31
This is not limited to macOS, I am using ChromeOS, and thus the work around is not usable

**Comment by frank-dspeed** [comment] 2019-10-08 19:23
@cottongin your right they get installed to the directorys on server that you choose or home by default

**Comment by frank-dspeed** [comment] 2019-10-08 19:28
@cottongin as you mentoined fedora there are many security features that could prevent you from using this.you can use the workaround you can simply use docker on fedora

**Comment by cottongin** [comment] 2019-10-09 16:54
Alright, using `docker` worked, but how do I pass in my environment? It doesn't see Python installed and git doesn't work.  I don't really use docker so this is all new to me, and not a great workaround.

**Comment by frank-dspeed** [comment] 2019-10-09 18:35
@cottongin you need to create your own modifyed image base on the code-server image.
and add there instructions like apt-get install python git and so on

**Comment by cottongin** [comment] 2019-10-09 19:19
@frank-dspeed well this seems like quite a lot of work when my environment is already established on the fedora box and the appeal, at least to me, is that code-server runs in said environment so everything just works™. Having to essentially clone the already existing environment into the docker image is not ideal (this gets complicated with things like github ssh keys).

I guess I'll wait the 2 months for whatever is broken to be fixed

**Comment by glasgowm148** [comment] 2019-10-10 10:35
Same issue in Centos7

**Comment by sr229** [comment] 2019-10-10 11:56
> Same issue in Centos7

Can't confirm that. Running a Eclipse Che server and I can install extensions fine.

**Comment by glasgowm148** [comment] 2019-10-14 12:57
Tried running as my own user & root, reinstalling. No joy. Also not sure where the log outputs to? 

`➜  code-server2.1523-vsc1.38.1-linux-x86_64 ./code-server --port 9999 --verbose --log debug
info  Server listening on http://localhost:9999
info    - No authentication
info    - Not serving HTTPS`

`[root@li666-14]~# wget https://v1.extapi.coder.com/publishers/ms-python/vsextensions/python/2019.9.34911/vspackage
--2019-10-14 12:51:19--  https://v1.extapi.coder.com/publishers/ms-python/vsextensions/python/2019.9.34911/vspackage
Resolving v1.extapi.coder.com (v1.extapi.coder.com)... 2a00:1450:4009:818::2013, 172.217.169.51
Connecting to v1.extapi.coder.com (v1.extapi.coder.com)|2a00:1450:4009:818::2013|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-10-14 12:51:19 ERROR 404: Not Found.

[root@li666-14]~# wget https://v1.extapi.coder.com/publishers/vscode-icons-team/vsextensions/vscode-icons/9.3.0/vspackage
--2019-10-14 12:51:39--  https://v1.extapi.coder.com/publishers/vscode-icons-team/vsextensions/vscode-icons/9.3.0/vspackage
Resolving v1.extapi.coder.com (v1.extapi.coder.com)... 2a00:1450:4009:818::2013, 172.217.169.51
Connecting to v1.extapi.coder.com (v1.extapi.coder.com)|2a00:1450:4009:818::2013|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-10-14 12:51:40 ERROR 404: Not Found.
[root@li666-14]~# curl -IL https://v1.extapi.coder.com/publishers/ms-python/vsextensions/python/2019.9.34911/vspackage
HTTP/1.1 404 Not Found
Date: Mon, 14 Oct 2019 12:52:40 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 203
Vary: Accept-Encoding
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'self'
X-Content-Type-Options: nosniff
Via: 1.1 google`

**Comment by glasgowm148** [comment] 2019-10-17 11:40
Fixed/Workaround. It works via Docker with some modifications to the path - but as another user pointed out, pretty useless for this kind of application. 

Seems to be some sort of permission error but can't get any meaningful out the logs.  Still can't install via the browser UI but this method makes it a lot clearer where your data and extensions are stored. 

1. Run with this command. This creates a directory for your files and extensions.
`./code-server  --user-data-dir user-data --extensions-dir user-ext`
2. Search for desired extension here https://marketplace.visualstudio.com/vscode & download (right-hand link pane) 
3. Upload via SFTP to /user-ext
4. Navigate to the instance of vscode running in the browser
5. Extensions -> three dots --> Install from VSIX

**Comment by waclaw66** [comment] 2019-10-25 18:06
It helped me to set `NODE_EXTRA_CA_CERTS` environment variable.
I have added the variable to code-server.service file of systemd.
```
[Service]
Environment=NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
```

It seems like a bug, according help...
_NODE_EXTRA_CA_CERTS - path to additional CA certificates file_
So the code-server cannot use the default system CA file for some reason.

Fedora 30
code-server2.1638-vsc1.39.2-linux-x86_64

**Comment by yndi** [comment] 2019-10-26 04:53
Inspired by @waclaw66's workaround, I just confirmed it also fixes the issue on macOS if you have openssl installed from Homebrew:
```
NODE_EXTRA_CA_CERTS=/usr/local/etc/openssl/cert.pem ./code-server [your parameters]
```

**Comment by glasgowm148** [comment] 2019-10-31 09:42
Can confirm this also worked for me on CentOS

Full service file

`[Unit]
Description=Code Server IDE
After=network.target

[Service]
Environment=NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-bundle.crt
Type=simple
User=mark
EnvironmentFile=/etc/profile.d/pass.sh
WorkingDirectory=/home/mark/vscode/code-server
Restart=always
RestartSec=20
ExecStart=/home/mark/vscode/code-server/code-server --auth password --user-data-dir /home/mark/vscode/user-data --extensions-dir /home/mark/vscode/user-ext $(pwd)


StandardOutput=file:/var/log/code-server-output.log
StandardError=file:/var/log/code-server-error.log

[Install]
WantedBy=multi-user.target`

**Comment by JoeFirmament** [comment] 2019-11-05 13:17
@glasgowm148  Thx!  Same issue on CentOS7. After read your comments, add a new line to /etc/profile
`export NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-bundle.crt`
and  
`source /etc/profile`
Everything goes well~~~

**Comment by frank-dspeed** [comment] 2019-11-06 06:00
i think we could export that ENV? Maybe by default or Alert if it is not set?

**Comment by glasgowm148** [comment] 2019-11-06 22:08
env can vary from user to user based on shell and OS. Would be clearer to just put it in the instructions for setting up the .service file or readme.md.

**Comment by frank-dspeed** [comment] 2019-11-07 11:52
@glasgowm148 no i think we should simply look if that var exists and if not we throw a error thats it.

**Comment by vishalmhjn** [comment] 2019-12-27 20:35
Any update on this? same problem

**Comment by nhooyr** [comment] 2020-02-03 16:51
Confirmed.

**Comment by nhooyr** [comment] 2020-04-16 21:40
Does not seem to be a problem anymore, just tested.

**Closed by nhooyr** 2020-04-16 21:40 UTC
Labels: bug
