### ISSUE TITLE
cpp extension installs but throws an error

### ISSUE THREAD

**Issue by spidLL** [cdr/code-server#2393] opened 2020-12-02 18:32 UTC
I have code-server running on a vps with Ubuntu 20.04 LTS

This is the error that appears:
/home/spider/.local/share/code-server/extensions/ms-vscode.cpptools-1.1.2/bin/cpptools: 7: Syntax error: word unexpected (expecting ")")

I also tried to downgrade to extension version 1.1.1, same result (and same error).

- Web Browser: Safari Version 14.0.1 (15610.2.11.51.10, 15610)
- Local OS: macOS 10.15.7
- Remote OS: Ubuntu 20.04.1 LTS
- Remote Architecture: x86_64
- `code-server --version`: 3.7.4 11f53784c58f68e7f4c5b3b8dae9407caa41725b

**Comment by JammSpread** [comment] 2020-12-03 03:48
I recommend you refer to this. #2120 A rather temporary fix is to manually download the "cpptools-linux.vsix" from the [cpptools releases page](https://github.com/microsoft/vscode-cpptools/releases) and install it from there.

**Comment by code-asher** [comment] 2020-12-03 17:02
Closing as a duplicate of https://github.com/cdr/code-server/issues/2120.

**Closed by code-asher** 2020-12-03 17:02 UTC
