### ISSUE TITLE
Arrow keys don't work in terminal, neither does control + v

### ISSUE THREAD

**Issue by Xenfo** [cdr/code-server#2667] opened 2021-02-03 12:56 UTC
http://images.xenfo.rocks/u/y9MXzO.png

- Web Browser: Firefox
- Local OS: Ubuntu
- Remote OS: Ubuntu
- Remote Architecture: amd64
- `code-server --version`: 3.8.0

**Comment by jsjoeio** [comment] 2021-02-03 17:13
Unfortunately, I wasn't able to reproduce this using the following:

- code-server: v3.8.0
- VS Code: v1.51.1
- Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:86.0) Gecko/20100101 Firefox/86.0
- Web Browser: Firefox Developer Edition
- Local OS: macOS v11.1

![2021-02-03 10 11 13](https://user-images.githubusercontent.com/3806031/106783293-624e4400-6608-11eb-9372-ee872de312d8.gif)

**Comment by jsjoeio** [comment] 2021-02-03 17:13
What shell are you using? I tried both `/bin/zsh` and `/bin/bash` and couldn't reproduce.

**Comment by Xenfo** [comment] 2021-02-03 17:51
I am using bash.

**Comment by jsjoeio** [comment] 2021-02-03 18:05
So is it working now? Can we close this?

**Comment by Xenfo** [comment] 2021-02-03 19:10
No I meant I was wrong with my first comment. I said I was using bash.

**Comment by code-asher** [comment] 2021-02-03 21:12
Should work if you switch from sh to bash.

Some more info: https://github.com/cdr/code-server/discussions/2410

**Comment by Xenfo** [comment] 2021-02-04 13:14
Yes that seems to be it but I'm not sure how to switch from shell to bash as I'm not using Docker.

**Comment by Xenfo** [comment] 2021-02-04 13:14
Oops accidentally closed

**Comment by code-asher** [comment] 2021-02-04 16:40
The easiest way might be to set `terminal.integrated.shell.linux` in the
VS Code settings to `/bin/bash`.

I think it should also work to set the `SHELL` environment variable to
`/bin/bash` before running code-server.

And if you use `chsh` to change your user's shell and spawn code-server
with your user I think that should also work.

**Closed** 2021-02-04 17:01 UTC
Labels: needs-investigation
