### ISSUE TITLE
Extensions for running applications other than Node.js do not work

### ISSUE THREAD

**Issue by PrzemyslawSamsel** [cdr/code-server#2391] opened 2020-12-02 15:03 UTC
Hi, started using your app recently and I tried today to add extension for running/debugging C/C++ applications. The extension installs alright, both from inside the app list and installing manually via .vxsix file. However, it does not edit the launch.json file and the vs code does not see it on the list of installed extensions either. What is the problem here? Is it that vs code server does only help with running node.js so far, or are other languages supported as well? If so, there should be some documentation from you saying how to add these extensions, 'cause my "thorough" 2hrs research just simply didn't work. 
Btw great app. Apart from minor issues, my main development env on iPad Pro (vs code runs on Linux Centos VPS)

**Comment by code-asher** [comment] 2020-12-02 17:28
You might be running into this: https://github.com/cdr/code-server/issues/2120

If that's not it in your case, please post logs!
https://github.com/cdr/code-server/blob/v3.7.4/doc/FAQ.md#how-do-i-debug-issues-with-code-server

It's odd that it's not appearing in the extension list at all though.
That's definitely not expected behavior. Logs might help to figure this
out as well.

**Comment by PrzemyslawSamsel** [comment] 2020-12-04 16:11
Hi, thank you for the help. I tried with to run vs with --debug trace option. After opening vs again on my iPad i received a notification saying that extension ms-vscode.cpptools-1.1.2 did not install correctly, and asking whether I'd like to install it again. I did so, and received: 
```
/home/coder/.local/share/code-server/extensions/ms-vscode.cpptools-1.1.2/bin/cpptools: /home/coder/.local/share/code-server/extensions/ms-vscode.cpptools-1.1.2/bin/cpptools: cannot execute binary file
```
I also tried downloading and installing cpptools-linux-aarch64.vsix. It installed successfully, however for some reason no change is visible. On the tab "Run and Debug" there is still default text "To customize Run and Debug create a launch.json file (...)". I even did so manually, and it is still not visible in this tab, just like vs code still does not see it. Installing and launching Node.js, Edge, Chrome extensions work, in terms that I chose the extension, installed it, and it was automatically written to launch.json file. However, I did not test whether any of these actually work, as I usually don't develop anything in js. As for the logs, I attached ms-vscode-cpptools.txt from the ~/.local/share/code-server/logs dir. 

Is there anything else I can do? I tried your IDE, it works well for me, apart from minor issues with using Magic Keyboard on my iPad (but I've already seen you work on it, as there were some existing issues here relating to the topic). I'd really like to make these Extensions thing work, though. 
[ms-vscode-cpptools.txt](https://github.com/cdr/code-server/files/5643887/ms-vscode-cpptools.txt)

**Comment by code-asher** [comment] 2020-12-04 18:25
Ohhh, it looks like this is causing the crash:

````
telemetry/C_Cpp/LanguageServer/missingBinary {"properties":{"source":"mono.linux-x86_64"}}
```

You might be running into this issue then: https://github.com/cdr/code-server/issues/2263

Did you install `cpptools-linux-aarch64.vsix` from the cpptools repository or from our marketplace?

**Comment by code-asher** [comment] 2020-12-05 04:20
Also keep in mind you'll need `cpptools-linux.vsix` (not `aarch64`) if you're not using arm.

**Comment by PrzemyslawSamsel** [comment] 2020-12-05 13:51
Thank you very much for the help, using ```cpptools-linux.vsix``` manually resolved the issue and now I can use the extension with no problems. I am extremely sorry for the trouble, if only I'd read that aarch64 extends to ARM-arch64, not just "arch64" (which I thought at a first glance), I would've probably resolved the issue on my own. 
Anyway, the manual install worked for me, but the automatic installation from your marketplace is still an issue I think. I won't need any more help, and can close the issue, since I can now run this extension, but is there anything I can do (like provide more logs), so that you'll be able to figure out why automatic installation didn't work? I mean if some others stumble over this problem in the future

**Comment by code-asher** [comment] 2020-12-07 20:43
No worries! I actually made the same mistake. :P

We can go ahead and close this issue since we have this tracked and we
know what the cause is here: https://github.com/cdr/code-server/issues/2120

**Closed** 2020-12-07 20:43 UTC
Labels: docs
