### ISSUE TITLE
Add docker manifest for armv71

### ISSUE THREAD

**Issue by pnatel** [cdr/code-server#1776] opened 2020-06-05 20:47 UTC
Hi, 
When trying to run the code-server in a Raspberry Pi 4 running the latest Raspberry OS (32bits), it does not find a correct version in the manifest and fail (see below).
I noticed that you only build arm64 docker version.
Any chance that you could expand the scope of the manifest to include arm71?
Thanks

> Unable to find image 'codercom/code-server:latest' locally
> latest: Pulling from codercom/code-server
> docker: no matching manifest for linux/arm/v7 in the manifest list entries.
> See 'docker run --help'.

**Comment by nhooyr** [comment] 2020-06-05 20:48
Duplicate of #1337

**Comment by nhooyr** [comment] 2020-06-05 20:48
@pnatel Stay tuned, this is an important issue for us this next week.

**Closed by nhooyr** 2020-06-05 20:48 UTC
Labels: feature

**Comment by pnatel** [comment] 2020-06-05 21:00
Thanks for the quick reply. I will keep an eye in #1337
