### ISSUE TITLE
ms-python extension does not run

### ISSUE THREAD

**Issue by Pugio** [cdr/code-server#1922] opened 2020-07-29 04:08 UTC
- Web Browser: Chrome Version 83.0.4103.106 (Official Build) (64-bit)
- Local OS: macOS High Sierra 10.13.6
- Remote OS: Ubuntu 18.04
- Remote Architecture: x65
- `code-server --version`: `3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259`

Just installed code server. I tried it about a month ago and got full ms-python language support, but now (after a fresh machine/install) I get the following errors in console:

```
Error Python Extension: 2020-07-29 03:55:52: Failure during activation. [Error: The number of constructor arguments in the derived class o must be >= than the number of constructor arguments of its base class.
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261081
	at Array.forEach (<anonymous>)
	at e (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:260644)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261118
	at Array.forEach (<anonymous>)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261097
	at Array.forEach (<anonymous>)
	at e (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:260644)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261118
	at Array.forEach (<anonymous>)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261097
	at Array.forEach (<anonymous>)
	at e (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:260644)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261118
	at Array.forEach (<anonymous>)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261097
	at Array.forEach (<anonymous>)
	at e (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:260644)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261118
	at Array.forEach (<anonymous>)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261097
	at Array.forEach (<anonymous>)
	at e (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:260644)
	at Object.t.plan (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261159)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:257812
	at e._get (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:257721)
	at e.get (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:256432)
	at a.get (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:48:1001920)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:280985
	at processTicksAndRejections (internal/process/task_queues.js:97:5)]
t.log @ console.ts:112
console.ts:137 [Extension Host] Error Python Extension: 2020-07-29 03:55:52: sendStartupTelemetry() failed. [Error: The number of constructor arguments in the derived class o must be >= than the number of constructor arguments of its base class.
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261081
	at Array.forEach (<anonymous>)
	at e (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:260644)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261118
	at Array.forEach (<anonymous>)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261097
	at Array.forEach (<anonymous>)
	at e (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:260644)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261118
	at Array.forEach (<anonymous>)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261097
	at Array.forEach (<anonymous>)
	at e (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:260644)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261118
	at Array.forEach (<anonymous>)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261097
	at Array.forEach (<anonymous>)
	at e (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:260644)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261118
	at Array.forEach (<anonymous>)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261097
	at Array.forEach (<anonymous>)
	at e (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:260644)
	at Object.t.plan (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261159)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:257812
	at e._get (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:257721)
	at e.get (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:256432)
	at a.get (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:48:1001920)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:280985
	at processTicksAndRejections (internal/process/task_queues.js:97:5)] {  vslsStack: [    CallSite {}, CallSite {}, CallSite {},    CallSite {}, CallSite {}, CallSite {},    CallSite {}, CallSite {}, CallSite {},    CallSite {}, CallSite {}, CallSite {},    CallSite {}, CallSite {}, CallSite {},    CallSite {}, CallSite {}, CallSite {},    CallSite {}, CallSite {}, CallSite {},    CallSite {}, CallSite {}, CallSite {},    CallSite {}, CallSite {}, CallSite {},    CallSite {}, CallSite {}, CallSite {}  ]}
t.log @ console.ts:112
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: The number of constructor arguments in the derived class o must be >= than the number of constructor arguments of its base class.
t.log @ console.ts:112
console.ts:137 [Extension Host] stack trace: Error: The number of constructor arguments in the derived class o must be >= than the number of constructor arguments of its base class.
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261081
	at Array.forEach (<anonymous>)
	at e (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:260644)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261118
	at Array.forEach (<anonymous>)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261097
	at Array.forEach (<anonymous>)
	at e (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:260644)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261118
	at Array.forEach (<anonymous>)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261097
	at Array.forEach (<anonymous>)
	at e (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:260644)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261118
	at Array.forEach (<anonymous>)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261097
	at Array.forEach (<anonymous>)
	at e (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:260644)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261118
	at Array.forEach (<anonymous>)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261097
	at Array.forEach (<anonymous>)
	at e (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:260644)
	at Object.t.plan (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:261159)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:257812
	at e._get (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:257721)
	at e.get (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:256432)
	at a.get (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:48:1001920)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39:280985
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
t.log @ console.ts:112
mainThreadExtensionService.ts:65 [[object Object]]The number of constructor arguments in the derived class o must be >= than the number of constructor arguments of its base class.
$onExtensionRuntimeError @ mainThreadExtensionService.ts:47
mainThreadExtensionService.ts:66 Error: The number of constructor arguments in the derived class o must be >= than the number of constructor arguments of its base class.

	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39
	at Array.forEach (<anonymous>)
	at e (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39
	at Array.forEach (<anonymous>)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39
	at Array.forEach (<anonymous>)
	at e (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39
	at Array.forEach (<anonymous>)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39
	at Array.forEach (<anonymous>)
	at e (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39
	at Array.forEach (<anonymous>)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39
	at Array.forEach (<anonymous>)
	at e (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39
	at Array.forEach (<anonymous>)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39
	at Array.forEach (<anonymous>)
	at e (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39)
	at Object.t.plan (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39
	at e._get (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39)
	at e.get (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39)
	at a.get (/home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:48)
	at /home/myuser/.local/share/code-server/extensions/ms-python.python-2020.6.91350/out/client/extension.js:39
	at processTicksAndRejections (/<path>/internal/process/task_queues.js:97)
```

After these message I get a whole stream of successful "info" messages of the style:
```
[Extension Host] Info Python Extension: 2020-07-29 03:56:10: Rule = settings, result = runNextRule
```

The extension then proceeds to correctly detect my python installation (`3.7.6 64-bit {'base': conda}`) and display it in the bottom status bar. None of the Python features work – not intellisense, linting, etc., and trying to run any of the `> Python:` commands results in:
```
Command 'Python: Start REPL' resulted in an error (command 'python.startREPL' not found)
```

Running with `--log debug` produces no output on loading the extension.

Thank you.

**Comment by code-asher** [comment] 2020-07-29 15:53
Ah yeah I haven't looked into it to be sure if it's not something on our side but it looks like the latest version of the Python extension has some issues. See https://github.com/cdr/code-server/issues/1837#issuecomment-653800193 for the last known version that works.

I'll close this as a duplicate of #1837.

**Closed by code-asher** 2020-07-29 15:53 UTC
