### ISSUE TITLE
arm64: Cannot reconnect. Please reload window.

### ISSUE THREAD

**Issue by fchazal** [cdr/code-server#1511] opened 2020-04-10 16:29 UTC
Since v3, having a popup appearing 10-30sec after loading the studio in my browser with the error "Cannot reconnect. Please reload window."

Seems to be linked to the following closed issue on vs-code side : https://github.com/microsoft/vscode-remote-release/issues/1464

This makes the studio unusable, going back to the v2.9 that worked well...

**here's my configuration :** code-server running on arm64 with node v13 but tried also with the node v12 shipped with the tarball, browser used : Chrome on macOS (last version), Safari on macOS and Safari on iPadOS

**Comment by arvati** [comment] 2020-04-13 14:48
same problem here running on x64 machine inside lxc container.

**Comment by kylecarbs** [comment] 2020-04-14 14:37
Could you provide some more details on your setup? I can't reproduce.

**Comment by fchazal** [comment] 2020-04-14 16:03
Just running the binary on a arm64 based chip (rock64) with no-auth option
and connecting on a local network with my macbook pro on Chrome or Safari
and getting this error after 10-60 seconds.

**Comment by anker2000** [comment] 2020-04-26 16:49
I’m getting the same error running on MacOS Catalina. Running Node 12, tested running on both local IP without SSL certificate and custom domain with SSL certificate and the same thing happens.

**Comment by rohitranjan1991** [comment] 2020-05-02 12:52
i am also facing the same issue in v3.2.0. for me having the developer tools open and reloading the tab and then closing the developer tools seems to work... This does not make any sense to me as to why that is.

**Comment by zwzhao** [comment] 2020-05-18 12:31
Getting the same issue here, with version 3.3.0 (Ubuntu 18.04, x64).
The console prompts an error: 
> Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/code-server/lib/vscode/node_modules/spdlog/build/Release/spdlog.node)

**Comment by zwzhao** [comment] 2020-05-18 13:56
> Getting the same issue here, with version 3.3.0 (Ubuntu 18.04, x64).
> The console prompts an error:
> 
> > Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/code-server/lib/vscode/node_modules/spdlog/build/Release/spdlog.node)

I tried docker and it works fine now. 
you could save the following code to ''docker-compose.yml''.
`version: '2.2'
services:
    code-server:
        restart: always
        image: codercom/code-server:latest
        container_name: code-server
        privileged: true
        ports:
            - 8080:8080
        volumes:
            - /home/zwzhao/:/home/coder/
`

and then execute:

`sudo docker-compose up -d`

**Comment by nhooyr** [comment] 2020-05-19 05:00
Please let me know if this still occurs on the latest release and I'll reopen. None us on the core team have been able to reproduce.

**Closed by nhooyr** 2020-05-19 05:00 UTC
Labels: waiting-for-info
