### ISSUE TITLE
Host of issues after upgrading to v3.6.1

### ISSUE THREAD

**Issue by agneevX** [cdr/code-server#2232] opened 2020-10-25 13:08 UTC
- Web Browser: Safari
- Local OS: macOS
- Remote OS: Raspberry Pi OS Debian Buster
- Remote Architecture: armv7l
- Version: `3.6.1 62735da69466a444561ab9b1115dc7c4d496d455`

Ever since I upgraded to v3.6.1, I've not been able to use code-server properly. 

1. Most of the time I get `Activating Extensions` in the status bar
2. `Open Preview to the side` won't open
3. Color theme get randomly reset upon refresh (#2231)

<img width="463" alt="image" src="https://user-images.githubusercontent.com/19761269/97108079-0ca4fa00-16f1-11eb-93c7-b29f9881043c.png">

Browser console log:

<img width="900" alt="image" src="https://user-images.githubusercontent.com/19761269/97108081-0f075400-16f1-11eb-95bf-76ef2922f0dc.png">

**Comment by agneevX** [comment] 2020-10-26 09:23
Meanwhile, downgrading to v3.6.0.

```bash
sudo npm install -g code-server@3.6.0 --unsafe-perm
```

**Comment by Talent30** [comment] 2020-10-29 10:33
same issue

**Comment by ghokun** [comment] 2020-11-01 21:53
Most of the reported problems applies for me. One thing I might add:
.vscode/launch.json is not recognized in 3.6.1 and can not create new one.

**Comment by Talent30** [comment] 2020-11-02 06:51
#2262

**Comment by Talent30** [comment] 2020-11-02 08:09
#2259

**Comment by agneevX** [comment] 2020-11-02 08:52
I'm quite surprised as to why 3.6.1 hasn't been pulled yet. @code-asher

**Comment by code-asher** [comment] 2020-11-02 17:17
It seems these issues are related to Safari and how VS Code now loads
the web worker extension host.

It looks like they have a fix in the works which I think should be out
with the next version (probably the next week or two).

I'm hesitant to pull the release since it doesn't affect other browsers
and because the last time I did that I broke things downstream. >.<

**Comment by ykazakov** [comment] 2020-11-17 13:30
Looks like the issues are still there in v3.7.1

**Comment by code-asher** [comment] 2020-11-18 20:42
Yeah, unfortunately. :( I think they'll be resolved once we upgrade to
VS Code 1.51.1 though which I'm currently working on. I'll update this
issue once that's merged.

**Comment by code-asher** [comment] 2020-11-19 23:15
It seems there are still issues after the upgrade (different ones though). Will need to dig further.

**Comment by izewang** [comment] 2020-11-23 07:48
issues are still there in v3.7.2

**Comment by ghokun** [comment] 2020-11-25 05:00
My issues seem to be fixed with the 3.7.3. Thanks
- Settings are persistent
- launch and tasks files under .vscode are visible to debugger

**Comment by ykazakov** [comment] 2020-11-25 08:40
My plugin activation issues #2243 have been fixed as well! :thumbsup:

**Comment by agneevX** [comment] 2020-12-03 05:43
Reopening this since there’s an active milestone.

**Comment by oxy** [comment] 2020-12-08 14:59
It's closed even though the milestone is active because the issue is technically fixed on the latest development version - it helps because it shows up as a completed task on the milestone.

Closing again!

**Closed by oxy** 2020-12-08 14:59 UTC
Labels: browser-safari, upstream
