### ISSUE TITLE
Digital Ocean droplet doesn't work on Chrome/Safari on iPadOS

### ISSUE THREAD

**Issue by nsadeh** [cdr/code-server#1518] opened 2020-04-12 00:21 UTC
Hello, I tried creating a droplet on Digital Ocean via https://marketplace.digitalocean.com/apps/code-server. I ssh'd in and grabbed the password, then went to http://<IP> and types the password. After that I always get a blank white screen. This is on both Chrome and Safari. I don't have the right keys on laptop so did not test.

**Comment by kylecarbs** [comment] 2020-04-14 14:38
Were you able to access on your computer? Just wanna make sure.

**Comment by amit-feldman** [comment] 2020-04-17 13:08
It works on mine. Didn’t experience the same issue that you’re describing.

**Comment by blakekrone** [comment] 2020-04-24 03:35
I tried to use the marketplace image today. Couldn't get my SSH keys to load so I was partially locked out, once I rebuilt and was able to SSH in when I tried to access via my iPad it would get stuck in a redirect loop constantly using Safari on iOS. macOS worked just fine.

**Comment by ilyagrishkov** [comment] 2020-04-25 10:51
Got the same issues on the iPad. Installed code-server from the Marketplace. SSH-ed to it from Mac, found a password, logged in from Mac Safari - everything worked perfectly. Tried logging in from my iPad - the server asks for a password and then I get a white screen (in both Safari and Chrome)

**Comment by ilyagrishkov** [comment] 2020-04-26 23:46
Not the most elegant solution, but I have found something that worked. Marketplace on DigitalOcean has version 3.0.2 of code-server. If you just create an Ubuntu droplet, ssh to it, and follow code-server installation instruction (https://www.howtoforge.com/how-to-install-code-server-ide-on-ubuntu-1804/ && https://medium.com/@edwinbrowwn/how-to-host-vs-code-on-a-vps-using-coder-aka-code-server-d519767fb52c) you setup a 3.11.0 version which works fine with iPadOS.

**Comment by blakekrone** [comment] 2020-04-26 23:49
Yup, that's what I ended up doing as well. I did also notice some issues connecting to it with pihole as my DNS servers. That seemed to cause some strange redirect loops even on my own built image with SSL certificates from LE.

**Comment by nhooyr** [comment] 2020-05-19 05:01
Closing as duplicate of https://github.com/cdr/code-server/issues/1566

**Comment by nhooyr** [comment] 2020-05-19 05:01
Also see our https://github.com/cdr/code-server/blob/master/doc/guide.md on setting up lets encrypt!

**Closed by nhooyr** 2020-05-19 05:01 UTC
Labels: waiting-for-info
