### ISSUE TITLE
Jupyter notebook shortcut issue

### ISSUE THREAD

**Issue by Aperture77** [cdr/code-server#2171] opened 2020-10-08 12:57 UTC
Hi,

- Web Browser: Firefox / Chrome, latest update
- Local OS: Pop_OS (ubuntu) 20.04
- Remote OS: Ubuntu 18.04
- Remote Architecture: x86
- `code-server --version`: 3.5.0

I use code-server on my laboratory server.
I launch it using nohup ./code-server --auth none --disable-telemetry --bind-addr localhost:35678 & 
As I am not a sudoer I am not able to install it.
I forward 35678 port to my 8888 port that I then open in any browser (Firefox or Chrome).
Shortcut are working fine in the menu and most files.
However when I open a Jupyter Notebook, I cannot use my shortcut inside the cells.

For example, F1 open and close the menu quickly, F5 refresh the page, CTRL+C/CTRL+V does nothing.
This kind of weird shortcut bug only happens in jupyter notebooks, in regular files, browser's shortcut are correctly suppressed, copy/paste works fine.

Any idea why, anyone have seen the same thing ?

Thanks

**Comment by code-asher** [comment] 2020-10-09 18:06
I think this is because it uses iframes and there's a problem capturing
key presses inside those iframes. I've ran into similar problems with
keybindings in an extension readme, for example.

With that in mind, I think this is a duplicate of
https://github.com/cdr/code-server/issues/1219. I renamed that issue to
make it clear it's not just the extension readmes that have the problem.

**Closed by code-asher** 2020-10-09 18:06 UTC
