### ISSUE TITLE
[v2] "Visual Studio Code is unable to watch for file changes in this large workspace" - v2.0 docker

### ISSUE THREAD

**Issue by loganto** [cdr/code-server#1078] opened 2019-10-16 12:08 UTC
I get following error:
"Visual Studio Code is unable to watch for file changes in this large workspace" when launching vs code server 2.0 branch using docker.

Could dockerfile be updated with followin change to  /etc/sysctl.conf:

```
The limit can be increased to its maximum by editing /etc/sysctl.conf and adding this line to the end of the file:

fs.inotify.max_user_watches=524288

The new value can then be loaded in by running sudo sysctl -p. 
```

**Comment by code-asher** [comment] 2019-10-23 20:21
Wouldn't this be closer to a feature than a bug? Everything is operating as expected.

**Comment by sr229** [comment] 2019-10-24 04:31
After a bit more debugging I can concur this has to deal with your system's allowed maximum handles. Closing as intended-by-design on the system.

**Closed by sr229** 2019-10-24 04:31 UTC
Labels: bug

**Comment by loganto** [comment] 2019-10-24 12:06
@sr229 
> with your system's allowed maximum handles. Closing as intended-by-design on the system.  
  
on what system? docker host?
I dont believe that's the case.

**Comment by sr229** [comment] 2019-10-24 13:49
Apparently it is on your container

[read more here](https://stackoverflow.com/questions/50901127/vsc-unable-to-watch-for-file-changes-in-this-large-workspace-weird)

**Comment by loganto** [comment] 2019-10-28 13:29
@sr229 Right - but container is built from this Dockerfile:  
https://github.com/cdr/code-server/blob/master/Dockerfile 
So the right place to fix this would be by changing Dockerfile where we would we set higher handles limit.
I mean - unless im missing something this has nothing to do with my dev box.
