### ISSUE TITLE
Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by B4TT3RY** [cdr/code-server#1280] opened 2020-01-18 06:04 UTC
- `code-server` version: code-server:2.1698-arm64 (docker)
- OS Version: Ubuntu 18.04.3 LTS

## Description

![image](https://user-images.githubusercontent.com/12368101/72659493-bd17fc00-3a03-11ea-8b9f-f443bdc8037b.png)

## Steps to Reproduce

1. F1 -> Configure Display Language
1. Click 'ko'

**Comment by nhooyr** [comment] 2020-01-27 06:38
I can't install language packs, I get an error the extension could not be installed.

Very weird issue.

**Comment by nhooyr** [comment] 2020-01-27 18:07
Confirmed this is an issue with the Korean language pack.

**Comment by nhooyr** [comment] 2020-01-27 18:10
Confirmed with other language packs as well.

**Comment by B4TT3RY** [comment] 2020-02-10 09:18
On Windows, when I change the language, it writes "locale": "ko" in the .vscode\argv.json file.

**Comment by codejam1024** [comment] 2020-02-11 11:16
@B4TT3RY 
Try this maybe works, if you just want change language:
> ./code-server --install-extension (your-language-pack-extension).vsix  
> Chinese example
> ./code-server --install-extension MS-CEINTL.vscode-language-pack-zh-hans-1.41.0.vsix  

And start with:
> ./code-server --locale (your language)  
> Chinese example  
> ./code-server --locale zh-cn  

Enjoy!

**Comment by B4TT3RY** [comment] 2020-02-11 14:20
> @B4TT3RY
> Try this maybe works, if you just want change language:
> 
> > ./code-server --install-extension (your-language-pack-extension).vsix
> > Chinese example
> > ./code-server --install-extension MS-CEINTL.vscode-language-pack-zh-hans-1.41.0.vsix
> 
> And start with:
> 
> > ./code-server --locale (your language)
> > Chinese example
> > ./code-server --locale zh-cn
> 
> Enjoy!

Thank you! i'll check that

**Comment by code-asher** [comment] 2020-02-20 18:53
https://github.com/cdr/code-server/pull/1338 will look in the new `argv.json` file for the locale. The locale used to be in a file called `locale.json` but since it's no longer in there the locale never gets set. `--locale` works since it sets the locale directly and code-server doesn't have to search for it.

The undefined error seems like a separate matter; I think it might be a problem with how it gets built in our marketplace.

**Comment by code-asher** [comment] 2020-04-07 22:48
These extensions have been fixed in our marketplace. :tada:

**Closed by code-asher** 2020-04-07 22:48 UTC
Labels: bug
