### ISSUE TITLE
Code-Server for Windows 10

### ISSUE THREAD

**Issue by ansarizafar** [cdr/code-server#1833] opened 2020-06-25 10:37 UTC
Is it possible to run amazing code-server on Windows 10?

**Comment by allez-allez-allez** [comment] 2020-06-25 19:11
@ansarizafar, I'm using Docker to run my code-server on windows 10. It seems to be working fine. Not sure if you have thought about that route yet.

**Comment by ansarizafar** [comment] 2020-06-26 10:28
I don't want to use docker.

**Comment by nhooyr** [comment] 2020-06-26 14:29
Duplicate of #1397 


@ansarizafar Should work if you install from npm but we haven't tested it yet. See the linked issue for details.

**Closed by nhooyr** 2020-06-26 14:29 UTC
Labels: feature
