### ISSUE TITLE
Add arm32v7 builder

### ISSUE THREAD

**Issue by gleich** [cdr/code-server#1337] opened 2020-02-04 19:37 UTC
Create a new file called `arm.Dockerfile` that allows you to run it on arm32v7 CPUs such as the Raspberry Pi's CPU.

**Comment by nhooyr** [comment] 2020-02-04 20:06
Could you elaborate on what the current problem is and how this helps?

**Comment by Matt-Gleich** [comment] 2020-02-04 21:47
At the moment the docker image for code-server only works on x86 processors (desktop processor) and returns the following error when you try to run on an arm32v7 processor (such as the Raspberry Pi):

`standard_init_linux.go:211: exec user process caused "exec format error"`

This is due to the fact that the docker image is built on an x86 processor. In this case, we don't even need to change the base image thanks to the fact that node has an arm image already available. So, in theory, this adds support for running code-server on a Raspberry Pi!

One problem with this is that in order for it to work on a arm32v7 processor it needs to be built on an arm32v7 processor. Sadly github-actions and travis-ci both don't support you to run your CI on arm32 CPUs. There are a few solutions to this tough:

1. Run a Jenkins server on a Raspberry Pi that you or someone on the team buys. I made a docker image that comes with Jenkins and docker installed https://hub.docker.com/repository/docker/mattgleich/arm32v7jenkins-docker
2. Try building it on an x86 with a CPU arm emulation tool such as QEMU

I am going to work to get this working and will submit a PR once done

**Comment by sr229** [comment] 2020-02-05 16:39
@nhooyr we tried building it over at Drone but it keeps OOMing, we're still investigating what we can do with the build toolchain since it should work under normal circumstances since we run with 128GB RAM in Drone Cloud

**Comment by nhooyr** [comment] 2020-02-05 17:13
That is unfortunate news. Not sure what we can do.

**Comment by nhooyr** [comment] 2020-02-05 17:13
https://discourse.drone.io/t/drone-cloud-arm32-ooms-when-building/6622

**Comment by nhooyr** [comment] 2020-02-05 17:19
Ah so we need to compile for ARM32 on ARM64.

**Comment by sr229** [comment] 2020-02-06 02:20
I'll see on how to compile the project using 32-bit libs but AFAIK documentation to do it for Node.js is quite scarce but I'll keep looking.

**Comment by sr229** [comment] 2020-02-08 01:45
@nhooyr AFAIK we should be compiling this on a 32-bit capable container, preferrably Raspbian, in a ARM64 environment (Raspbian can run 32-bit userland against a 64 bit kernel so it shouldn't be an issue).

**Comment by aptalca** [comment] 2020-02-11 22:36
@sr229 I'm with linuxserver.io and we publish a [code-server image](https://github.com/linuxserver/docker-code-server). We use native builders with our jenkins and have a bunch of arm32v7 devices. If you point me to your specific build instructions, I'll try to build it and let you know.

**Comment by aptalca** [comment] 2020-02-12 15:34
I tried a build on an odroid xu4, running armbian buster (arm32v7), kernel 4.14.165.
Ran in an ubuntu bionic docker container with node 12.15.0 and yarn 1.21.1
Followed the steps from https://github.com/cdr/code-server#development
`yarn watch` resulted in the following error:
```
root@3d29582a8c4c:/tmp/vscode/src/vs/server# yarn watch
yarn run v1.21.1
$ cd ../../../ && yarn watch
$ gulp watch --max_old_space_size=4095
[15:29:46] Node flags detected: --max_old_space_size=4095
[15:29:46] Respawned to PID: 8612

<--- Last few GCs --->

[8612:0x1e47950]     2561 ms: Mark-sweep 20.7 (29.5) -> 20.7 (29.5) MB, 52.8 / 0.0 ms  (average mu = 0.606, current mu = 0.001) allocation failure GC in old space requested
[8612:0x1e47950]     2614 ms: Mark-sweep 20.7 (29.5) -> 20.7 (22.0) MB, 53.4 / 0.0 ms  (average mu = 0.437, current mu = 0.001) last resort GC in old space requested
[8612:0x1e47950]     2669 ms: Mark-sweep 20.7 (22.0) -> 20.7 (22.0) MB, 54.6 / 0.0 ms  (average mu = 0.278, current mu = 0.001) last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x35b0e235 <JSObject>
    0: builtin exit frame: compileFunction(this=0x2b042315 <JSGlobal Object>,0x2fd0a595 <JSArray[5]>,0x2fd0a585 <JSArray[0]>,0x25340275 <undefined>,0x253403bd <false>,0x25340275 <undefined>,0,0,0x2fd1f5e9 <String[#53]: /tmp/vscode/node_modules/typescript/lib/typescript.js>,0xb0580089 <Very long string[7797825]>,0x2b042315 <JSGlobal Object>)

    1: _compile [0x4407861d] [internal/modules/cjs/loader....

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Aborted (core dumped)
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nhooyr** [comment] 2020-02-12 17:14
@aptalca yea thats the same error @sr229 was getting. We need to cross compile on 64bit arm for 32bit arm.

**Comment by aptalca** [comment] 2020-02-12 18:42
Oh I see now, my mistake. I hadn't read the linked thread on drone and incorrectly assumed drone was using arm64 builders for arm32 work and that cross compile was the issue. That's why I tried on native arm32.

**Comment by nhooyr** [comment] 2020-02-13 00:43
Some discussion at https://github.com/cdr/code-server/issues/35

**Comment by deftdawg** [comment] 2020-02-13 02:45
My process for cobbling together builds is as follows:

1. Build Code Server on aarch64 docker container on a X86_64 host using qemu-aarch64-static via binfmt (linking needs ~**12GB of RAM**;  impossible on a 32-bit arch which can address a max of 4GB per process)
2. Shipping the compiled directory to a native arm6 system (steps are the same for arm32v7); in my case an RPi Zero W / RPi 2
3. Going into code-server-*-built and running npm rebuild on everything ([node arm6 unofficial build needed](https://unofficial-builds.nodejs.org/))

That produces something that can be run via the node arm6 unofficial build via ```node ./build/code-server*/out/vs/server/main.js --auth none```    

The packing can't be done on a RPi2(1GB), because build.ts is trying to [pass the entire packed binary to fs.writeFile as a buffer](https://github.com/cdr/code-server/blob/master/scripts/build.ts#L359) which easily exceeds the 1GB; from what I've read it should be possible to use streams to reduce that footprint to something more sane (streams -> https://medium.com/dev-bits/writing-memory-efficient-software-applications-in-node-js-5575f646b67f)

I'm not sure if streams could also help with the 12GB ram footprint of the build phase; I don't even know where to start investigating that one as build has way more going on.

**Comment by sr229** [comment] 2020-03-02 21:45
I'm going to assume the build script is passing the entire thing as a buffer hence the OOM errors. I think this is something @code-asher would likely be happy to investigate to optimize the builds.

**Comment by code-asher** [comment] 2020-03-03 16:31
The next version will be out soon and it no longer packages into a
single binary so that should simplify building a bit.

**Comment by jsco2t** [comment] 2020-03-15 21:39
Question (and if this needs to be a new issue just let me know):

I noticed that _some_ `arm` binaries are being produced as part of the official releases. Ex: https://github.com/cdr/code-server/releases/tag/2.1698

I grabbed the ARM64 versions and deployed them onto a RaspberryPi just to see if they would work. I'm getting a bad image format style error:

```
code-server2.1698-vsc1.41.1-linux-arm64 $ ./code-server
-bash: ./code-server: cannot execute binary file: Exec format error
```

This leads me to believe that the current ARM binaries aren't compiled for the version of ARM the raspberryPi I am using runs (I have access to a Pi Zero W, as well as a Pi 4). Is there any chance we can get full build instructions for ARM if we want to try to compile and run the server on a raspberry pi.

* I know that running the server on a RaspberryPi device, especially the 2.x code versions, will result in an OOM error - even if I managed to get the binary to run. I also understand the experience will be substandard. That being said - I still love the idea of being able to run this on ARM devices.

**Comment by code-asher** [comment] 2020-03-16 16:13
Hopefully with v3 we'll be able to distribute arm64 releases that work a bit better but in the meantime check out https://github.com/cdr/code-server/blob/master/doc/CONTRIBUTING.md#build for how to build.

**Comment by skabber** [comment] 2020-03-26 19:20
I tried building on my RaspberryPi 4 according to the CONTRIBUTING.md file but ran into this error.

```
pi@raspberrypi:~/Projects/code-server $ yarn build
yarn run v1.22.4
$ yarn runner build
$ cd ./ci && NODE_OPTIONS=--max_old_space_size=32384 ts-node ./build.ts build
[default] rootPath is "/home/pi/Projects/code-server"
[default] codeServerVersion is "3.0.1"
[build] cleaning up old build...took 8ms
[build] building vs code...failed
Command failed: yarn gulp compile-build
/usr/bin/node[16083]: ../src/node_platform.cc:414:std::shared_ptr<node::PerIsolatePlatformData> node::NodePlatform::ForIsolate(v8::Isolate*): Assertion `data' failed.
Aborted
error Command failed with exit code 134.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 
```

**Comment by code-asher** [comment] 2020-03-27 20:17
That's a new one. Are you building with Node 12?

**Comment by encombhat** [comment] 2020-03-28 00:24
> That's a new one. Are you building with Node 12?

Same problem, node 10.17.0, yarn 1.22.4, debian buster armhf

**Comment by skabber** [comment] 2020-03-28 13:34
Once I switched from node 10 to 12, I get a JavaScript heap out of memory error.

**Comment by b00giZm** [comment] 2020-03-30 00:20
> Once I switched from node 10 to 12, I get a JavaScript heap out of memory error.

Same for me.

Node: v12.16.1
Yarn: 1.22.4

**Comment by deftdawg** [comment] 2020-03-30 02:37
Gents, kindly read the entire thread before "me too" posting...  Per previous posts (https://github.com/cdr/code-server/issues/1337#issuecomment-585522283), it requires 12GB of RAM to build.

**Comment by nhooyr** [comment] 2020-05-01 16:25
Ya'll can test the npm package: `yarn global add @coder/code-server`. 🎉

**Comment by jguittard** [comment] 2020-05-01 17:30
@nhooyr can you elaborate on this great news please? ^^

**Comment by nhooyr** [comment] 2020-05-01 18:10
You can install node on a arm32v7 CPU and then run `npm install -g @coder/code-server` to install and use code-server.

**Comment by jguittard** [comment] 2020-05-01 18:25
Awesome! Which _exact_ sem-ver of node is required?

**Comment by nhooyr** [comment] 2020-05-01 18:28
There is no restriction, the native modules are recompiled against whatever version of node you have installed :)

**Comment by jguittard** [comment] 2020-05-01 18:30
I’ll finally be able to use my iPad as a dev device with my pi4 🎉

**Comment by skabber** [comment] 2020-05-01 21:23
Works for me!
Thanks

**Comment by dreamorosi** [comment] 2020-05-02 11:46
For future reference, the installation process requires also `yarn` and if you don’t have `libx11-dev`, `libxkbfile-dev` and `libsecret-1-dev` it won’t compile.

Other than that it works great, finally we can run it on Raspberry Pi!

**Comment by jguittard** [comment] 2020-05-02 11:48
@dreamorosi came up to first two dependencies, thanks for the third ;)

**Comment by Sebobo** [comment] 2020-05-02 13:51
Works great thanks !

**Comment by dreamorosi** [comment] 2020-05-02 14:55
Has anyone been able to run this version on raspberry pi via HTTPS and use it on iPadOS?

The HTTP without certificate works fine but as we know with limitations (no clipboard). If I add certificates or I use reverse proxy it works until the login screen but then it shows a blank screen.

I think the issue is localized to iPadOS because if I had some up to access thru laptop it works fine also with HTTPS.

**Comment by nhooyr** [comment] 2020-05-03 19:59
@dreamorosi See #1541

**Comment by dreamorosi** [comment] 2020-05-03 20:03
> @dreamorosi See https://github.com/cdr/code-server/issues/715

What should I look at exactly? In that thread there are mentions to an inexistent app, a paid 3rd party service and ssh access.

**Comment by nhooyr** [comment] 2020-05-03 20:21
Sorry linked the wrong issue at first. #715 is what I meant to link. You need a certificate signed by a real CA for iPadOS, can't use a self signed certificate.

**Comment by nhooyr** [comment] 2020-05-06 23:58
The npm package is now just code-server. https://www.npmjs.com/package/code-server

We were able to acquire it from the previous owner.

**Comment by nhooyr** [comment] 2020-05-18 00:04
The npm PR is now official, see https://github.com/cdr/code-server#npm for docs.

Keeping this issue open until we have a armv7 builder for static releases.

**Comment by radokristof** [comment] 2020-05-20 17:21
@nhooyr Thanks it works great on Raspberry. Wonder if you could publish containers on Docker built for armv6 as well?

Thanks!

**Comment by aptalca** [comment] 2020-05-20 20:35
If anyone's still interested, the linuxserver.io image is now multi-arch, supporting amd64, arm32v7 and arm64v8.
It also has a bunch of mods you can install for things like docker&docker-compose, python2&3, nodejs, powershell, golang, etc.
https://github.com/linuxserver/docker-code-server

**Comment by nhooyr** [comment] 2020-05-21 14:54
@aptalca That's awesome!

I'll be sure to add to the README under the docker section.

Any ideas why 3.3.1 doesn't work on ARM? The release is tested on arm64 by CI so it should be good.

And I've responded re #1704

**Comment by aptalca** [comment] 2020-05-21 14:58
@nhooyr Thanks. I'll open a new issue with logs from the arm image of 3.3.1

**Comment by aptalca** [comment] 2020-05-21 21:01
With a little bit of help from @nhooyr we fixed up the images and pushed a new build of 3.3.1 to https://github.com/linuxserver/docker-code-server
This one works on arm (passed basic gui tests)

**Comment by nhooyr** [comment] 2020-05-21 21:06
@aptalca Congrats! Did you manually test or do you have some automated tests? I'd love to check them out if possible.

**Comment by nhooyr** [comment] 2020-05-21 21:12
And do you guys host your own arm32 builders?

**Comment by aptalca** [comment] 2020-05-21 21:14
Our jenkins does automated checks, just a basic docker run, take a screenshot and get the logs and packages, but for some reason in this case I guess it took the screenshot a little too early, before the gui came up: https://lsio-ci.ams3.digitaloceanspaces.com/linuxserver/code-server/v3.3.1-ls43/index.html

Yes, we have arm32 and arm64 builders: https://ci.linuxserver.io/
It also spins up some aws slaves (x86_64 and arm64) when there is a backlog

**Comment by nhooyr** [comment] 2020-05-21 21:17
That's awesome, we'd love to adopt that test in our CI with credit of course. Can you share the source?

**Comment by aptalca** [comment] 2020-05-21 21:29
Sure it's all open on github
This is the overview of our CI: https://github.com/linuxserver/pipeline-triggers
The jenkinsfiles are templated and this is the builder: https://github.com/linuxserver/docker-jenkins-builder
It takes in jenkins-vars.yml (and others) and generates the `Jenkinsfile`
In the Jenkinsfile, this is the part that does the test: https://github.com/linuxserver/docker-code-server/blob/master/Jenkinsfile#L483-L531
And it basically runs this tester script: https://github.com/linuxserver/docker-ci/blob/master/ci/ci.py
and that uses this image to take the screenshot: https://github.com/linuxserver/docker-tester

**Comment by nhooyr** [comment] 2020-05-21 21:43
@aptalca Thank you so much! That will be incredibly useful. Currently our CI only installs an extension and confirms that worked but the screenshot approach is far more robust.

**Comment by aptalca** [comment] 2020-05-21 21:55
Sure, let us know if we can help in any way. You can pop into our discord to discuss further or if you have questions: https://discord.gg/YWrKVTn

**Comment by Rathna-K** [comment] 2020-05-22 14:05
Hi @aptalca @nhooyr trying to pull a docker image for coder to run RPi4. Where should I go for an “official image” ? Meaning one will be supported in the future? is it Linux Server io? Or something else? I saw a lot of threads around this in here but still unclear on which one to use. TIA

**Comment by aptalca** [comment] 2020-05-22 14:28
@Rathna-K 
linuxserver.io is third party, not official.
If your pi is running a 64 bit OS, you can use either image. But if it is running a 32 bit OS like the stock raspbian image, then linuxserver one is your only choice for docker image at the moment.

The container port for the linuxserver one is 8443 because we published that image before code-server changed their default port from 8443 to 80. We didn't want to break anything for our existing users so we kept it as 8443. But you can map that port to whatever port you like on your host anyway since it's docker.
It serves `http` by default and we recommend a reverse proxy like this one: https://github.com/linuxserver/docker-letsencrypt it comes with a preset proxy conf that you can easily enable: https://github.com/linuxserver/reverse-proxy-confs/blob/master/code-server.subdomain.conf.sample

One cool thing about the linuxserver image is the list of mods we provide, that install popular dev packages in the container: https://mods.linuxserver.io/?mod=code-server
They are enabled by a simple env var when creating the image and thus are persistent through container recreation unlike things that are manually installed inside a running container (they disappear along with the container during update/recreation)

**Comment by nhooyr** [comment] 2020-05-24 05:42
Yes, in terms of an arm32 docker image, your only choice at the moment is linuxserver.io.

For an officially supported solution you can use the NPM package and follow our setup guide. https://github.com/cdr/code-server/blob/master/doc/guide.md

**Comment by tidux** [comment] 2020-06-01 19:30
The Pi 4 has full aarch64 support coming with Raspbian, and it already exists via Ubuntu and Gentoo, so it might be easier to just replace the hardware.

**Comment by nhooyr** [comment] 2020-06-02 20:55
Yea but most users will still be using arm32v7 so we'll be sure to add a builder in the next few weeks.

**Comment by sr229** [comment] 2020-06-24 17:12
If it helps you @nhooyr, Docker has native cross building support in Beta, so you just need to install the Edge version to use the BuildKit project.

**Comment by nhooyr** [comment] 2020-06-24 17:16
I gave that a shot a few weeks ago @sr229 

Unfortunately, qemu's user mode emulation kept erroring out when building code-server :(

Don't remember the specifics right now. I'll give it a shot again at some point.

**Comment by imgmatt** [comment] 2020-07-01 20:55
> Ya'll can test the npm package: `yarn global add code-server`. 🎉

Hey, apologies for the bump... not sure if I'm being a complete bozo but this has me stumped. Tried this a few times on my Pi 3B + running node v12 and all dependencies. I'm getting a successful install (success Installed "code-server@3.4.1" with binaries) but code-server doesn't run. Not sure the install even did anything, even with --unsafe-perm added.

**Comment by code-asher** [comment] 2020-07-02 15:59
Does it give any errors? If it's something like "command not found" then you might just need to add the `yarn` binary directory to your `PATH` environment variable. I think by default it's `~/.yarn/bin`.

**Comment by imgmatt** [comment] 2020-07-02 17:44
> Does it give any errors? If it's something like "command not found" then you might just need to add the `yarn` binary directory to your `PATH` environment variable. I think by default it's `~/.yarn/bin`.

That worked, thanks! code-server is now running without throwing any errors in terminal but getting 'refused to connect' in the browser when loading the default address. Seems like default Raspbian install might need some firewall/port forward updating.

**Comment by code-asher** [comment] 2020-07-02 17:48
Are you connecting directly to code-server? If that's the case you might need to add `--host 0.0.0.0`. By default it listens on localhost which is not accessible externally.

**Comment by imgmatt** [comment] 2020-07-02 18:00
> Are you connecting directly to code-server? If that's the case you might need to add `--host 0.0.0.0`. By default it listens on localhost which is not accessible externally.

I'm connecting from another machine on my local network, but it was running @ 127.0.0.1:8080. Also tried 0.0.0.0 but still refused. 

If I VNC into the Pi, I can connect to code-server in that browser though - not ideal.

**Comment by code-asher** [comment] 2020-07-02 19:05
Hmm yeah if you're just accessing from another local machine via the ip then `0.0.0.0` will be necessary. But if that's still not working then it could definitely be a firewall issue.

**Comment by code-asher** [comment] 2020-07-02 19:08
I'm not super familiar with Raspbian but a cursor search seems to suggest it doesn't have a firewall enabled by default. Have you enabled iptables or ufw or something?

**Comment by sr229** [comment] 2020-07-05 11:54
I think we should still supply prebuilt binaries and have postinstall download them (fallback to compilation if cannot find a prebuilt) to save time for them.

**Comment by 7HE-W0R1D** [comment] 2021-02-16 06:24
> My process for cobbling together builds is as follows:
> 
> 1. Build Code Server on aarch64 docker container on a X86_64 host using qemu-aarch64-static via binfmt (linking needs ~**12GB of RAM**;  impossible on a 32-bit arch which can address a max of 4GB per process)
> 2. Shipping the compiled directory to a native arm6 system (steps are the same for arm32v7); in my case an RPi Zero W / RPi 2
> 3. Going into code-server-*-built and running npm rebuild on everything ([node arm6 unofficial build needed](https://unofficial-builds.nodejs.org/))
> 
> That produces something that can be run via the node arm6 unofficial build via `node ./build/code-server*/out/vs/server/main.js --auth none`
> 
> The packing can't be done on a RPi2(1GB), because build.ts is trying to [pass the entire packed binary to fs.writeFile as a buffer](https://github.com/cdr/code-server/blob/master/scripts/build.ts#L359) which easily exceeds the 1GB; from what I've read it should be possible to use streams to reduce that footprint to something more sane (streams -> https://medium.com/dev-bits/writing-memory-efficient-software-applications-in-node-js-5575f646b67f)
> 
> I'm not sure if streams could also help with the 12GB ram footprint of the build phase; I don't even know where to start investigating that one as build has way more going on.

Thanks for your package @deftdawg! In fact it is the only one that runs on my pi zero w. However, I'd like to try the latest build of code-server but I'm totally new to docker and binfmt. I tried googling for results but cannot find the right way to go. Could you elaborate a bit more on how to "Build Code Server on aarch64 docker container on a X86_64 host using qemu-aarch64-static via binfmt"? I'm on a windows 10 64bit laptop with docker and qemu installed, but I cannot figure out what to do next :(
Thanks in advance!

**Comment by deftdawg** [comment] 2021-02-16 07:10
@7HE-W0R1D  - Going from memory as my machine died; waiting for a NUC11 replacement to come in a few weeks hopefully.

You need a Linux machine (or VM) running X86_64 intel kernel with lots of RAM.   Trying to do this with a docker/VM on Windows is probably going to be painfully slow (though it should be possible if you are able to allocate tonnes of memory to docker).

On your linux machine/VM, you need to install qemu-user-static and possibily qemu-user-binfmt if it doesn't install as a dep.

What it does is essentially register some scripts with the binfmt kernel module that when it sees an ARM executable (by looking at the magic line of the file) it automatically emulates arm64.

Then run an ARM64 distro using qemu-aarch64-static and then follow the build steps to compile code-server.

It's not worth the effort tbqh...  Like what would you plan to do on a Pi Zero that a newer version of VS Code is going to make any difference?

**Comment by 7HE-W0R1D** [comment] 2021-02-16 07:24
Thanks for the timely reply! Well the last line is real good question, I guess I will give the VM/Docker a shot but if it fails(probably will) I'll stick to your prebuild package.

**Comment by 7HE-W0R1D** [comment] 2021-02-16 07:38
@deftdawg also I saw someone saying https://github.com/cdr/code-server/issues/1337#issuecomment-622457413 this `yarn add` command can do the thing. I tried it and it does build the package successfully, like for 2000 or 3000 seconds. But when I run code-server, the welcome password screen appears and then there will be a 500 error with no extra messages. Does that mean its impossible to use the `yarn install` (or `yarn add `now) on rpi or it is something that is fixable?

**Comment by RobertCNelson** [comment] 2021-02-16 14:42
I've kinda just jumped into this project for beagleboard.org , we had been shipping "cloud9" for the last 5 or 6 years as our default ide.. It's been un-maintined for last few years with me just hacking on it keep it building on debian's default version of nodejs.

So i started looking at this project last week.. I've been successful on building it a Raspberry Pi 4 8GB model running in armhf mode. Currently 3.8.1/3.9.0 run great on our BeagleBone Blacks' (AM335x) Cortex-A8 with 512MB of ram..

Only 2 patches are required..

First there is an arfifcal stop in ci/lib.sh:

https://github.com/cdr/code-server/blob/v3.9.0/ci/lib.sh#L37-L50

```
arch() {
  case "$(uname -m)" in
  aarch64)
    echo arm64
    ;;
  x86_64 | amd64)
    echo amd64
    ;;
  *)
    echo "unknown architecture $(uname -a)"
    exit 1
    ;;
  esac
}
```

I just added an armhf option, it's not really used anywhere, more then likely to just stop the build with an exit 1..

```
From 51644af7dbe139d3f8db4170c7a6da18e2072051 Mon Sep 17 00:00:00 2001
From: Robert Nelson <robertcnelson@gmail.com>
Date: Wed, 10 Feb 2021 10:20:51 -0600
Subject: [PATCH] bbb.io: ci/lib.sh lets not stop when detecting armv7l

Signed-off-by: Robert Nelson <robertcnelson@gmail.com>
---
 ci/lib.sh | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/ci/lib.sh b/ci/lib.sh
index 96a413f1c..179c27688 100755
--- a/ci/lib.sh
+++ b/ci/lib.sh
@@ -42,6 +42,9 @@ arch() {
   x86_64 | amd64)
     echo amd64
     ;;
+  armv7l)
+    echo armhf
+    ;;
   *)
     echo "unknown architecture $(uname -a)"
     exit 1
```

Second, there is a gulp call in lib/vscode/package.json that requires 8GB of memory for JavaScript, i backed this down to 6GB which allows it to run on the 8GB Pi 4.. While watching a build in TOP, i'm really wondering what the point of this 8GB setting was..

https://github.com/cdr/code-server/blob/v3.9.0/lib/vscode/package.json#L32

```
"gulp": "gulp --max_old_space_size=8192",

```

```
From 00cf8a3d8a5d95183e7fd251d65cbd368e8c0c3e Mon Sep 17 00:00:00 2001
From: Robert Nelson <robertcnelson@gmail.com>
Date: Wed, 10 Feb 2021 12:35:22 -0600
Subject: [PATCH] bbb.io: lib/vscode/package.json: limit memory from 8gb to 6gb

Signed-off-by: Robert Nelson <robertcnelson@gmail.com>
---
 lib/vscode/package.json | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/lib/vscode/package.json b/lib/vscode/package.json
index d4efccba3..4e4e5060f 100644
--- a/lib/vscode/package.json
+++ b/lib/vscode/package.json
@@ -29,7 +29,7 @@
     "kill-watch-extensionsd": "deemon --kill yarn watch-extensions",
     "mocha": "mocha test/unit/node/all.js --delay",
     "precommit": "node build/hygiene.js",
-    "gulp": "gulp --max_old_space_size=8192",
+    "gulp": "gulp --max_old_space_size=6144",
     "electron": "node build/lib/electron",
     "7z": "7z",
     "update-grammars": "node build/npm/update-all-grammars.js",
```

anyways to build i grabbed nodejs' armv7l build from: https://nodejs.org/dist/latest-v12.x/  (as debian buster's nodejs is v10...)

Installed yarn 1.22.5 with nodejs's npm/nodejs build, then just ran (and waited about an hour..)

```
yarn
yarn build
yarn build:vscode
yarn release
yarn release:standalone
```

Here are my packaged build i'm testing for BeagleBoard.org, they do require a pure Debian userspace for armhf (ARMV7-A..)

http://repos.rcn-ee.net/debian/pool/main/b/bb-code-server/

For reference here is my full tree: https://github.com/rcn-ee/code-server/tree/v3.9.0-bbb.io (i nuked a few git calls as i'm building it in a debian sbuild with no git installed..)

Regards,

**Comment by eh8** [comment] 2021-03-16 10:45
Are there still any plans to release the armhf binaries to accompany x86 and arm64 in the future?

**Comment by sr229** [comment] 2021-03-16 14:34
> Are there still any plans to release the armhf binaries to accompany x86 and arm64 in the future via GitHub? The linuxserver docker images are neat but I'm hoping for a bare metal installation if possible.

There isn't that large demand if you ask me, plus most of the development happens in ARM64 or x86_64 hosts, so there won't be any demand for this.

**Comment by eh8** [comment] 2021-03-16 20:00
> There isn't that large demand if you ask me, plus most of the development happens in ARM64 or x86_64 hosts, so there won't be any demand for this.

I can't speak beyond my own circumstances, but as I understand there many use Raspberry Pi/ODroid/etc either as standalone units or in k8'ed configuration as build servers which would suit code-server. It would be a presupposition to discount these platforms for lack of computing power/memory simply because there are small Raspberry Pis that exist.

It also looks like @RobertCNelson was able to tweak the build scripts trivially to produce viable 32-bit ARM builds, so I would hope that code-server can reproduce the builds officially.

**Comment by jsjoeio** [comment] 2021-03-16 21:51
If it's trivial to add + maintain, then we'd be happy to support this.

@eh8 we'd happily review a PR if you submitted one (same goes to you @RobertCNelson). You two probably more than we do (or me at least). 

Otherwise, we can try and take a look at this in the near future.

**Comment by sr229** [comment] 2021-03-18 18:11
> > There isn't that large demand if you ask me, plus most of the development happens in ARM64 or x86_64 hosts, so there won't be any demand for this.
> 
> I can't speak beyond my own circumstances, but as I understand there many use Raspberry Pi/ODroid/etc either as standalone units or in k8'ed configuration as build servers which would suit code-server. It would be a presupposition to discount these platforms for lack of computing power/memory simply because there are small Raspberry Pis that exist.
> 
> It also looks like @RobertCNelson was able to tweak the build scripts trivially to produce viable 32-bit ARM builds, so I would hope that code-server can reproduce the builds officially.

This is a valid reason though it's pretty hard to compile for ARMv32 considering there aren't any more public builders offering this, and the fact it's a little hard to configure the CI to do the compile steps for it (only for it to break really horribly).

**Comment by oxy** [comment] 2021-04-19 15:18
Now that we have arm64-on-x64 cross compile, it should be fairly simple to also do armv7-on-x64 builds; if there's no PRs for this, I'll look into it in the future, but there are currently other issues that are higher priority.

**Closed** 2021-08-09 18:35 UTC
Labels: enhancement
