### ISSUE TITLE
[V2] Can't copy text from terminal

### ISSUE THREAD

**Issue by Merith-TK** [cdr/code-server#1058] opened 2019-10-07 03:13 UTC
- `code-server` version: 1.15.1
- OS Version: Archlinux
- Client: Google Chrome, Windows 10 pro, BUILD 18362.338

## Description
Unable to copy selected text from the terminal to my clipboard
I can copy/paste text from the editor, but not terminal

## Steps to Reproduce
1. select text from the terminal
2. right-click copy
3. attempt to paste somewhere

**Comment by sr229** [comment] 2019-10-07 14:39
Duplicate of #985

**Closed by sr229** 2019-10-07 14:39 UTC
