### ISSUE TITLE
Add --enable-proposed-api

### ISSUE THREAD

**Issue by JayDoubleu** [cdr/code-server#1981] opened 2020-08-18 17:04 UTC
I'm trying to pass the --enable-proposed-api flag to vscode
I'm using this patch https://github.com/cdr/code-server/pull/1779/commits/9fb33dce3d8f4854163c978ef02bdd06f1983722
I've also added  ```myextension.id```  to  ```extensionAllowedProposedApi```.

Tried executing via below however it doesn't look like that argument is passed to vscode.
```
code-server --enable-proposed-api myextension.id
code-server --enable-proposed-api=myextension.id
```

Is there a quick/other way to pass this argument to vscode?

**Comment by nhooyr** [comment] 2020-08-20 19:46
See https://github.com/cdr/code-server/pull/1779

**Comment by code-asher** [comment] 2020-08-24 16:19
fwiw I suspect #1779 is a different issue since that's for enabling the proposed API in the client/web worker host rather than the server-side host. The error also looks unusual and I think it might be specific to the remote extensions so there might not be anything we can do about it, but I think it's worth a check to make sure it's not a bug on our end.

**Comment by code-asher** [comment] 2020-08-24 16:21
A bit more context, @JayDoubleu got this error after including the changes in #1779. (Correct me if I'm wrong though!)

**Comment by code-asher** [comment] 2020-08-24 16:27
nvm, I completely misremembered, it's just that the web handles it differently than the local version and has nothing to do with the extension hosts. #1744 (comment)

Very possible that resolving #1744 via #1779 will fix this then, apologies for the noise. It's still odd that the error is different but we'll see how it goes.

**Comment by nhooyr** [comment] 2020-08-31 10:56
[v3.5.0 with VS Code v1.48.2 has been released, fixing this issue!](https://github.com/cdr/code-server/releases/tag/v3.5.0) 🍻

**Closed by nhooyr** 2020-08-31 10:56 UTC
