### ISSUE TITLE
Ctrl + Shift + {Left, Right, Home, End} is broken after a terminal is opened & closed

### ISSUE THREAD

**Issue by peat-psuwit** [cdr/code-server#3504] opened 2021-05-28 16:24 UTC
## OS/Web Information

- Web Browser: Mozilla Firefox 88.0.1 (`88.0.1+build1-0ubuntu0.20.04.2`)
- Local OS: Ubuntu 20.04
- Remote OS: Ubuntu 20.04
- Remote Architecture: AMD64
- `code-server --version`: `3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005`

## Steps to Reproduce

1. With a freshly opened window, open a file with some text in it.
    - Try using Ctrl + Shift + Right, text should be selected at word boundaries.
2. Open a terminal, then close it using `exit` command.
3. Try using Ctrl + Shift + Right again.

## Expected

Text should be selected at word boundaries.

## Actual

No text is selected. Cursor doesn't move at all.

## Logs

- [code-server-stderr.log](https://github.com/cdr/code-server/files/6562082/code-server-stderr.log)
- [code-server-stdout.log](https://github.com/cdr/code-server/files/6562083/code-server-stdout.log)
- [console-export-2021-5-28_23-16-18.txt](https://github.com/cdr/code-server/files/6562085/console-export-2021-5-28_23-16-18.txt)
- [code-server_Archive [21-05-28 23-14-41].zip](https://github.com/cdr/code-server/files/6562089/code-server_Archive.21-05-28.23-14-41.zip) (contains HAR file)
- The output of "Log (Window)", with "Toggle Keyboard Shortcuts Troubleshooting" enabled: [window.log](https://github.com/cdr/code-server/files/6562097/window.log)

## Notes

This issue can be reproduced in VS Code: No (Version: 1.57.0-insider, Commit: 1082913dd012e21cc5f35a06f15c480ca447f67f)

**Comment by jsjoeio** [comment] 2021-06-01 17:32
Thank you for diligently posting all the logs (and more)! 

Assuming I understood the expected correctly, I couldn't reproduce locally on macOS + Firefox

## Screenshot

https://user-images.githubusercontent.com/3806031/120366397-765b3700-c2c4-11eb-944a-74c0b8d6acfb.mov

Is there a chance you have a conflicting keybinding or maybe an extension causing this issue?

**Comment by peat-psuwit** [comment] 2021-06-01 18:13
I've retested with an empty `--user-data-dir`; the problem still persists. So it can't be extensions or custom keybindings.

But from the window log, this looks suspicious:
```
[2021-05-28 23:13:16.294] [window] [info] [KeybindingService]: | Resolving ctrl+shift+[ArrowRight]
[2021-05-28 23:13:16.300] [window] [info] [KeybindingService]: \ From 2 keybinding entries, matched workbench.action.terminal.resizePaneRight, when: terminalFocus && terminalProcessSupported, source: built-in.
```
The terminal is not opened at that point.

On macOS, I think the fact that there's some kind of Ctrl -> Cmd keybinding difference might cause the issue to not appear. You may have better luck reproducing it on Windows.

**Comment by jsjoeio** [comment] 2021-06-01 18:21
Thanks for checking extensions! How about custom keybindings? Can you go to `Command Palette > Preferences: Open Keyboard Shortcuts (JSON)` and paste that here? 

Also, can you see if there are multiple keybindings for `ctrl+shift+arrowRight`? Here's how you can check (if you didn't know):

## Screenshot


https://user-images.githubusercontent.com/3806031/120371954-6f83f280-c2cb-11eb-93b0-d66ecd677506.mov



@code-asher is on Linux. Maybe he can try reproducing it.

**Comment by code-asher** [comment] 2021-06-01 18:48
I'm able to reproduce. Maybe it's because of the `Terminal: Resize Pane Right` keybinding that's bound to `ctrl+shift+right` in the terminal.

On Firefox when the terminal is closed there's a bug where the close isn't actually registered so maybe it still thinks the `terminalFocus` condition is true.

One workaround is to unbind it for now:
```
// Place your key bindings in this file to override the defaultsauto[]
[
    {
        "key": "ctrl+shift+right",
        "command": "-workbench.action.terminal.resizePaneRight",
        "when": "terminalFocus && terminalProcessSupported"
    }
]
```

Possibly related: https://github.com/cdr/code-server/issues/1615

**Comment by peat-psuwit** [comment] 2021-12-02 07:29
On code-server `3.12.0 4cd55f94c0a72f05c18cea070e10b969996614d2` and Firefox `94.0+build3-0ubuntu0.20.04.1`, issue is still reproducible with empty `keybinding.json`.

As pointed out in mentioned #1615, I've re-tested this on GitPod (I don't have a GitHub Codespace subscription). Turns out, the issue is reproducible there too, so this may be actually an upstream issue. But because there's no "VSCode server" from upstream, I'm not sure it's appropriate to file an issue at [microsoft/vscode](https://github.com/microsoft/vscode). I guess I'll try filing the same issue with GitPod; maybe they know better.

Although, I think a workaround at the moment is to modify the default keybinding so that it reads (for example):

```json
    {
        "key": "ctrl+shift+up",
        "command": "workbench.action.terminal.scrollUp",
        "when": "terminalIsOpen && terminalFocus && terminalProcessSupported"
    },
```

That is, wherever `terminalFocus` exists, augment it with `terminalIsOpen`. I has this workaround inside my `keybinding.json` and it seems to work.

**Comment by jsjoeio** [comment] 2021-12-06 17:11
Since this is upstream, I'm going to close this!

**Closed** 2021-12-06 17:11 UTC
Labels: upstream:vscode
