### ISSUE TITLE
Reload window to reconnect to code-server

### ISSUE THREAD

**Issue by nooobcoder** [cdr/code-server#3018] opened 2021-04-02 02:52 UTC
Whenever the docker container or the host machine is restarted, the browser tab cant reconnect to code-server in the last state. It forces the user to reload the window.
This is not an issue when i do not restart the container or reboot the host machine. Rest of the time it connects as usual.

Also, the terminal's state is lost when the browser tab is reloaded, this needs to be fixed. I have tried coder (Enterprise platform), there is no problem at all with the terminal, when you relaunch the workspace, it just loads where you last left it. Please fix this as this has been a much requested feature in the past. Running npm scripts on the terminal of code-server is a headache due to this reason.

Thank You,
Ankur Paul

**Comment by code-asher** [comment] 2021-04-02 15:56
Thank you for the feature requests!

The terminal request is a duplicate of https://github.com/cdr/code-server/issues/2276.

The requirement to refresh when the code-server process or host machine restarts is unfortunately not something we can resolve since it's how upstream works. However, we do want to make it obvious you need to refresh because right now I think it just keeps trying to reconnect. See https://github.com/cdr/code-server/issues/2697 for that.

**Closed by code-asher** 2021-04-02 15:56 UTC
