### ISSUE TITLE
Code-Server on Ubuntu 18.04 not working.

### ISSUE THREAD

**Issue by MrHelloSir** [cdr/code-server#1801] opened 2020-06-12 11:28 UTC
Hello. My last case was closed, asked for open since my issue was not resolved but I didn't get it. It's an urgent issue since my website can't be updated by my devs now, and I don't have time to wait, so I'm sorry if I break any rules for opening this again.

My issue is the following:
I run code-server on my port (I have allowed the port with ufw) and when I try to access it, it doesn't reach it.

![Screenshot_31](https://user-images.githubusercontent.com/63464262/84498220-dffbc300-acb8-11ea-9d38-42b4f9f09790.png)
Above is a photo of what It looks like. How can I fix this issue? I'm running the latest version:
`3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259`

**Comment by nhooyr** [comment] 2020-06-13 01:51
Please read give https://github.com/cdr/code-server/blob/master/doc/guide.md

You're running it on localhost still. Try `--bind-addr 0.0.0.0:8446`.

**Comment by nhooyr** [comment] 2020-06-13 01:51
Duplicate of #1800

**Closed by nhooyr** 2020-06-13 01:51 UTC
