### ISSUE TITLE
Terminal names not displayed when shown as tabs after reloading

### ISSUE THREAD

**Issue by sestegra** [cdr/code-server#3454] opened 2021-05-24 11:38 UTC
## OS/Web Information

- Web Browser: Chrome (90.0.4430.212 (Official Build) (x86_64)
- Local OS: macOS 11.3.1
- Remote OS: macOS 11.3.1
- Remote Architecture: macOS 11.3.1
- `code-server --version`: 3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005

## Steps to Reproduce

1. Launch Chrome and open code-server URL 
2. Open **Terminal** panel
3. Open few **New Terminal**
4. In terminal dropdown list, select **Show tabs**
5. Reload code-server URL

## Expected

Terminal names should be displayed after realoding

## Actual

Terminal names aren't displayed after realoding

## Logs

```
[2021-05-24T11:20:29.702Z] info  code-server 3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005
[2021-05-24T11:20:29.703Z] info  Using user-data-dir ~/.local/share/code-server
[2021-05-24T11:20:29.715Z] info  Using config file ~/.config/code-server/config.yaml
[2021-05-24T11:20:29.715Z] info  HTTP server listening on http://127.0.0.1:8080
[2021-05-24T11:20:29.716Z] info    - Authentication is enabled
[2021-05-24T11:20:29.716Z] info      - Using password from ~/.config/code-server/config.yaml
[2021-05-24T11:20:29.716Z] info    - Not serving HTTPS
[2021-05-24T11:20:33.135Z] debug forking vs code...
[2021-05-24T11:20:33.483Z] debug setting up vs code...
[2021-05-24T11:20:33.486Z] debug vscode got message from code-server {"type":"init"}
[2021-05-24T11:20:34.397Z] debug vscode got message from code-server {"type":"socket"}
[2021-05-24T11:20:34.399Z] debug protocol Initiating handshake... {"token":"0413b0a7-be02-4648-9bf9-8035b28666db"}
[2021-05-24T11:20:34.414Z] debug protocol Handshake completed {"token":"0413b0a7-be02-4648-9bf9-8035b28666db"}
[2021-05-24T11:20:34.414Z] debug management Connecting... {"token":"0413b0a7-be02-4648-9bf9-8035b28666db"}
[2021-05-24T11:20:34.415Z] debug vscode 1 active management connection(s)
[2021-05-24T11:20:34.637Z] debug Making request {"uri":"https://api.github.com/repos/cdr/code-server/releases/latest"}
[2021-05-24T11:20:34.653Z] debug vscode got message from code-server {"type":"socket"}
[2021-05-24T11:20:34.653Z] debug protocol Initiating handshake... {"token":"b3ea6fde-b86c-44e6-8590-76fd23a7979e"}
[2021-05-24T11:20:34.701Z] debug got latest version {"latest":"3.10.2"}
[2021-05-24T11:20:34.701Z] debug comparing versions {"current":"3.10.2","latest":"3.10.2"}
[2021-05-24T11:20:34.792Z] debug protocol Handshake completed {"token":"b3ea6fde-b86c-44e6-8590-76fd23a7979e"}
[2021-05-24T11:20:34.792Z] debug exthost Connecting... {"token":"b3ea6fde-b86c-44e6-8590-76fd23a7979e"}
[2021-05-24T11:20:34.793Z] debug exthost Getting NLS configuration... {"token":"b3ea6fde-b86c-44e6-8590-76fd23a7979e"}
[2021-05-24T11:20:34.793Z] debug vscode 1 active exthost connection(s)
[2021-05-24T11:20:34.793Z] debug exthost Spawning extension host... {"token":"b3ea6fde-b86c-44e6-8590-76fd23a7979e"}
[2021-05-24T11:20:34.800Z] debug exthost Waiting for handshake... {"token":"b3ea6fde-b86c-44e6-8590-76fd23a7979e"}
[2021-05-24T11:20:35.392Z] debug exthost Handshake completed {"token":"b3ea6fde-b86c-44e6-8590-76fd23a7979e"}
[2021-05-24T11:20:35.392Z] debug exthost Sending socket {"token":"b3ea6fde-b86c-44e6-8590-76fd23a7979e"}

# Reload

[2021-05-24T11:21:02.555Z] debug management Disposing... {"token":"0413b0a7-be02-4648-9bf9-8035b28666db"}
[2021-05-24T11:21:02.556Z] debug management Closed {"token":"0413b0a7-be02-4648-9bf9-8035b28666db"}
[2021-05-24T11:21:02.596Z] debug setting up vs code...
[2021-05-24T11:21:02.598Z] debug vscode got message from code-server {"type":"init"}
[2021-05-24T11:21:02.622Z] debug exthost Got disconnected message {"token":"b3ea6fde-b86c-44e6-8590-76fd23a7979e"}
[2021-05-24T11:21:02.622Z] debug exthost Disconnected {"token":"b3ea6fde-b86c-44e6-8590-76fd23a7979e"}
[2021-05-24T11:21:03.584Z] debug exthost Exited {"code":0,"token":"b3ea6fde-b86c-44e6-8590-76fd23a7979e"}
[2021-05-24T11:21:03.584Z] debug exthost Disposing... {"token":"b3ea6fde-b86c-44e6-8590-76fd23a7979e"}
[2021-05-24T11:21:03.585Z] debug exthost Closed {"token":"b3ea6fde-b86c-44e6-8590-76fd23a7979e"}
[2021-05-24T11:21:03.614Z] debug vscode got message from code-server {"type":"socket"}
[2021-05-24T11:21:03.615Z] debug protocol Initiating handshake... {"token":"48c13a01-cc18-47ad-bc89-633dbf653fba"}
[2021-05-24T11:21:03.632Z] debug protocol Handshake completed {"token":"48c13a01-cc18-47ad-bc89-633dbf653fba"}
[2021-05-24T11:21:03.633Z] debug management Connecting... {"token":"48c13a01-cc18-47ad-bc89-633dbf653fba"}
[2021-05-24T11:21:03.633Z] debug vscode 1 active management connection(s)
[2021-05-24T11:21:04.010Z] debug got latest version {"latest":"3.10.2"}
[2021-05-24T11:21:04.011Z] debug comparing versions {"current":"3.10.2","latest":"3.10.2"}
[2021-05-24T11:21:04.023Z] debug vscode got message from code-server {"type":"socket"}
[2021-05-24T11:21:04.024Z] debug protocol Initiating handshake... {"token":"6d9a13b8-08b7-4b4c-8114-9bbd2304d2af"}
[2021-05-24T11:21:04.315Z] debug protocol Handshake completed {"token":"6d9a13b8-08b7-4b4c-8114-9bbd2304d2af"}
[2021-05-24T11:21:04.315Z] debug exthost Connecting... {"token":"6d9a13b8-08b7-4b4c-8114-9bbd2304d2af"}
[2021-05-24T11:21:04.316Z] debug exthost Getting NLS configuration... {"token":"6d9a13b8-08b7-4b4c-8114-9bbd2304d2af"}
[2021-05-24T11:21:04.316Z] debug vscode 1 active exthost connection(s)
[2021-05-24T11:21:04.316Z] debug exthost Spawning extension host... {"token":"6d9a13b8-08b7-4b4c-8114-9bbd2304d2af"}
[2021-05-24T11:21:04.323Z] debug exthost Waiting for handshake... {"token":"6d9a13b8-08b7-4b4c-8114-9bbd2304d2af"}
[2021-05-24T11:21:04.957Z] debug exthost Handshake completed {"token":"6d9a13b8-08b7-4b4c-8114-9bbd2304d2af"}
[2021-05-24T11:21:04.958Z] debug exthost Sending socket {"token":"6d9a13b8-08b7-4b4c-8114-9bbd2304d2af"}
[IPC Library: Pty Host]  INFO Persistent process "3": Replaying 4869 chars and 4 size events
[IPC Library: Pty Host]  INFO Persistent process "1": Replaying 4809 chars and 4 size events
[IPC Library: Pty Host]  INFO Persistent process "2": Replaying 4809 chars and 4 size events
```

## Screenshot

![May-24-2021 13-34-16](https://user-images.githubusercontent.com/109060/119342190-fb2acd00-bc94-11eb-8804-06558e5a3558.gif)

## Notes

This issue can be reproduced in VS Code: No

**Comment by code-asher** [comment] 2021-05-24 16:23
I think this might be a duplicate of https://github.com/cdr/code-server/issues/3340 although that one doesn't specifically mention tabs so I'll close this one and edit the other. Thank you for reporting!

**Closed by code-asher** 2021-05-24 16:23 UTC
