### ISSUE TITLE
Integrated GIT cant use SSH?

### ISSUE THREAD

**Issue by bdodroid** [cdr/code-server#372] opened 2019-03-28 22:17 UTC
- `code-server` version:1.408-vsc1.32.0
- OS Version: ChromeOS 73

## Description

For SSH git repos: When trying to push/pull through the built in Source Control I get "Permission Denied (publickey)" popup. 
I can run git commands in terminal just fine but the actual editor dosen't seem to use the ssh-agent?

Git does work for HTTP requests but forces me to put in my user name and password in the terminal every time and certain projects are ssh access only.

## Steps to Reproduce

1. git clone a repo into a directory
2. open directory in vscode
3. click on Source Control (ctrl+shift+G)
4. click the three dots menu icon and click Pull

**Comment by NavinNavi19** [comment] 2019-03-29 16:13
Same here @bdodroid I have set up ssh agent to at startup. git ssh works fine in Terminal. But not in Source Control. 
I searched for the solution in VS code repo. 
The solution I got is to startup vscode from a git bash where ssh key added agent is running.
But I guess that cannot be done in our case.

**Comment by sr229** [comment] 2019-03-30 22:54
@bdodroid quick question, this is ran inside Crostini, correct?

**Comment by bdodroid** [comment] 2019-03-31 04:08
@sr229 correct

**Comment by NavinNavi19** [comment] 2019-03-31 04:22
@sr229 I am using Ubuntu 18.04 and the latest code server release 1.408

**Comment by bdodroid** [comment] 2019-04-01 18:48
Ok so I found that starting a new ssh agent and adding my key to it before starting the code server all in the same terminal works until I close the terminal or reboot the computer. Then I have to enter it again.
Not a big deal but more steps then I would like. 
Maybe its something weird with Crostini?

**Comment by nol166** [comment] 2019-04-03 19:14
@bdodroid Did you ever find out if this was an issue with Crostini?

**Comment by bdodroid** [comment] 2019-04-05 15:20
@nol166 Unfortunately not, I still cant get the code-server to run well enough on my Debian 8 server to get to the point where I can test ssh

**Comment by sr229** [comment] 2019-04-05 15:41
There will be environment differences as Crostini runs Debian 9 in a LXC container, inside the Termina VM, its vendor neutral so you can replicate the environment quickly

**Comment by NavinNavi19** [comment] 2019-04-08 14:42
@bdodroid I fixed this issue by making a small change to ~/.ssh/config

---

Previous Code

```shell
Host github
    Hostname github.com
    user git
    PreferredAuthentications publickey
    IdentityFile ~/.ssh/id_rsa_github
```

---

Resolved by changing the host to *

```shell
Host *
    Hostname github.com
    user git
    PreferredAuthentications publickey
    IdentityFile ~/.ssh/id_rsa_github
```

---

Hope this info will be usefull.

**Comment by sr229** [comment] 2019-04-08 16:22
My configuration by default has this predone for me when I added it on the list of hosts so I'm willing to learn about how you added your host. Did you do it via CLI via a `git push`?

**Comment by NavinNavi19** [comment] 2019-04-08 18:14
@sr229 I added the Host github previously for a different application. And now I edited the same file directly to allow all hosts. For me the configuration was not predone.

**Comment by sr229** [comment] 2019-04-08 23:49
That would explain why code-server wouldn't recognize it, this may be the case for VSCode as well

**Comment by allan-walpy** [comment] 2019-08-27 06:00
I have similar problem

`code-server` v2 preview 9 vsc1.37.0
`my host` Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-58-generic x86_64) on Vultr

# Description

For SSH git repos when clicking sync (Git:Synchronize changes in bottom blue nav) I've got `Permission Denied (publickey)`

For commits with GPG signing when commiting in Source Control I've got `Permission Denied (publickey)`

# Steps to Reproduce

0. Have ssh keys in ~/.ssh folder, and configured config for github/gitlab keys.
Have gpg key generated and git configured to sing commits with generated key in `~/.gitconfig`
1. Clone ssh repository
2. Open code-server in browser and open a folder with cloned repository
3. Synch repository, or try change smth and commit changes

# Workaround

I've got my server code on my vultr server behind cloudflare. On every start up I have following system daemon configured:

```
[Unit]
Description=VsCode.WebService.Daemon

[Service]
WorkingDirectory=/home/username/git
ExecStart=/home/username/app/vscode/start
Restart=always
RestartSec=130
KillSignal=SIGINT
SyslogIdentifier=vscode-web-service
User=username

[Install]
WantedBy=multi-user.target
```

And at `/home/username/app/vscode/start` following script:
```bash
#!/bin/bash

export GPG_TTY=$(tty)

export PASSWORD="vscode_some_password"

GPG_TTY=$(tty) /home/username/app/vscode/code-server         \
  --auth password                                         \
  --port=1234                                             \
  --cert=/etc/ssl/my.domain/certificate.pem               \
  --cert-key=/etc/ssl/mydomain/private.key                \
  /home/username/git
```

That still won't work for me as my ssh and gpg keys required password. I could open terminal inside code-server, enter `export GPG_TTY=$(tty)` and then push/commit to repository.

__I regenerate ssh and gpg keys for my server without password__, and then magically everything works. I can commit/branch etc. with repository and push/sync changes without problems. So I think, for me problem was in code-server couldn't handle ssh and gpg keys with password

I don't know is it a bug (code server not being able to working with ssh & gpg keys with password) or I am doing something wrong, so I leave it here

**Comment by sr229** [comment] 2019-08-27 07:28
> I have similar problem
> 
> `code-server` v2 preview 9 vsc1.37.0
> `my host` Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-58-generic x86_64) on Vultr
> # Description
> 
> For SSH git repos when clicking sync (Git:Synchronize changes in bottom blue nav) I've got `Permission Denied (publickey)`
> 
> For commits with GPG signing when commiting in Source Control I've got `Permission Denied (publickey)`
> # Steps to Reproduce
> 
>     1. Have ssh keys in ~/.ssh folder, and configured config for github/gitlab keys.
>        Have gpg key generated and git configured to sing commits with generated key in `~/.gitconfig`
> 
>     2. Clone ssh repository
> 
>     3. Open code-server in browser and open a folder with cloned repository
> 
>     4. Synch repository, or try change smth and commit changes
> 
> 
> # Workaround
> 
> I've got my server code on my vultr server behind cloudflare. On every start up I have following system daemon configured:
> 
> ```
> [Unit]
> Description=VsCode.WebService.Daemon
> 
> [Service]
> WorkingDirectory=/home/username/git
> ExecStart=/home/username/app/vscode/start
> Restart=always
> RestartSec=130
> KillSignal=SIGINT
> SyslogIdentifier=vscode-web-service
> User=username
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> And at `/home/username/app/vscode/start` following script:
> 
> ```shell
> #!/bin/bash
> 
> export GPG_TTY=$(tty)
> 
> export PASSWORD="vscode_some_password"
> 
> GPG_TTY=$(tty) /home/username/app/vscode/code-server         \
>   --auth password                                         \
>   --port=1234                                             \
>   --cert=/etc/ssl/my.domain/certificate.pem               \
>   --cert-key=/etc/ssl/my.domain/private.key                \
>   /home/username/git
> ```
> 
> That still won't work for me as my ssh and gpg keys required password. I could open terminal inside code-server, enter `export GPG_TTY=$(tty)` and then push/commit to repository.
> 
> **I regenerate ssh and gpg keys for my server without password**, and then magically everything works. I can commit/branch etc. with repository and push/sync changes without problems. So I think, for me problem was in code-server couldn't handle ssh and gpg keys with password
> 
> _I don't know is it a bug (code server not being able to working with ssh & gpg keys with password) or I am doing something wrong, so I leave it here_

It's clearly not a bug in our end, its how VSCode handles the SSH keys, and your sharing a fix for v2 which we have minimal patches only. At this point, you should raise it to Microsoft, not us.

**Closed** 2020-01-28 01:13 UTC
Labels: bug
