### ISSUE TITLE
Logout does not work behind reverse proxy

### ISSUE THREAD

**Issue by code-asher** [cdr/code-server#4503] opened 2021-11-12 19:53 UTC
_Updated by @jsjoeio_

## What's the problem I'm solving?

With the [latest changes](https://github.com/cdr/code-server/pull/4414) to use the upstream server in code-server, we're now running into issues with our reverse proxy not using the correct URL for the Log out functionality.. The specific code we're talking about lives [here](https://github.com/cdr/vscode/blob/main/src/vs/server/webClientServer.ts#L317).

When using a reverse proxy (i.e. [Caddy](https://caddyserver.com/)/[NGINX](https://nginx.org/en/)), the /logout endpoint is incorrect because it has the wrong base path and protocol.

## What are some ways to go about it?

The most ideal way to solve this is to use _relative endpoints_. This way, code-server doesn't care about the base path or protocol. It only knows and uses relative paths.

## How will things change/what is the need for maintenance?

I am not sure if there is historical context I may be missing which would explain why we didn't use a relative path from the start (or rather why upstream didn't). Patching this in `vscode` means it's something we'll need to keep an eye on as we continue staying in line with upstream.

I can't imagine this introducing any breaking changes but it could potentially break in specific environments if they don't support using relative paths for some reason 🤔 (though none specifically come to mind).

## How to reproduce

Asher outlined steps below to reproduce this issue locally. To do so, follow these steps:
1. install [Caddy](https://caddyserver.com/) (`brew install caddy`)
2. start code-server locally with `yarn watch`
3. serve it at as base path like `/code` with Caddy
```Caddyfile
http://localhost:8082/code/* {
	uri strip_prefix /code
	reverse_proxy 127.0.0.1:8080
}
```
4. navigate to [http://localhost:8082/code/](http://localhost:8082/code/) (trailing slash is important!) 
5. Open the Menu and click Logout

### Expected

You are redirected to `http://mydomain.com/logout`

### Actual 

You should be redirected to `http://mydomain.com/code/logout`

Should be similar to the fix for [this issue](https://github.com/cdr/code-server/issues/4476). See PR [here](https://github.com/cdr/vscode/pull/17).

**Comment by jsjoeio** [comment] 2021-11-18 17:27
I think this will be similar to https://github.com/cdr/code-server/issues/4476

**Comment by jsjoeio** [comment] 2021-12-06 22:06
We reopened this to test a specific use case. 

## How to reproduce

Asher outlined steps below to reproduce this issue locally. To do so, follow these steps:
1. install [Caddy](https://caddyserver.com/) (`brew install caddy`)
2. start code-server locally with `yarn watch`
3. serve it at as base path like `/vscode` with Caddy
```Caddyfile
http://localhost:8082/vscode/* {
	uri strip_prefix /vscode
	reverse_proxy 127.0.0.1:8080
}
```
4. navigate to [http://localhost:8082/vscode/](http://localhost:8082/vscode/) (trailing slash is important!) 
5. Open the Menu and click Logout
6. Refresh the page

### Expected

You should be logged out and redirected to `/login`.

### Actual

We _think_ you won't be logged out since "it will (un)set the cookie at /vscode/ which will not log you out since the cookie would have been initially set at /." See [comment](https://github.com/cdr/code-server/pull/4548#discussion_r760367697)

**Comment by jsjoeio** [comment] 2021-12-07 20:16
It appears to be working as expected - you are indeed brought to the right login page and you cannot access the editor

https://user-images.githubusercontent.com/3806031/145099797-128ec34b-9d4c-4112-9c87-45e934568787.mov

@code-asher - I think we can close this then unless you want to try reproducing

**Comment by jsjoeio** [comment] 2021-12-07 21:33
Update: we were missing a step in the reproduction. You need to logout from a non-root path. I will update the comment above.

**Closed** 2021-12-08 21:52 UTC
Labels: bug
