### ISSUE TITLE
update npm installation docs with node requirements

### ISSUE THREAD

**Issue by mrfoxie** [cdr/code-server#2745] opened 2021-02-19 15:20 UTC
- Web Browser: Chrome 
- Local OS: Android 8.1
- Remote OS: Android 8.1
- `code-server --version`: 3.9.0 fc6d123da59a4e5a675ac8e080f66e032ba01a1b

I tried to install on termux using falling commands
```
pkg install nano yarn
yarn global add code-server
```
after then when I execute the command `code-server` or `code-server --auth none` and then I open url in chrome browser I get this error
![Screenshot_20210219_202138](https://user-images.githubusercontent.com/25217451/108523324-c6088a80-72f3-11eb-803d-92225f6b1d64.jpg)

this is the log of termux while running `code-server`
![Screenshot_2021_0219_202202](https://user-images.githubusercontent.com/25217451/108523430-e59fb300-72f3-11eb-9db1-261200240be5.jpg)

**Comment by lucki1000** [comment] 2021-02-19 20:03
I also face this problem, but without this line "error VS Code exited unexpectedly with code 0".

**Comment by jsjoeio** [comment] 2021-02-22 18:25
Hmm...I wish I had an Android device to try and reproduce this. 

Usually when you see this error, it means VSCode isn't done building. I see the "error VS Code exited unexpectedly with code 0". 

Even if you wait, say maybe 5-10 minutes, does it finish building and work? That's what I have to do sometimes when I get this error.

**Comment by jsjoeio** [comment] 2021-02-22 21:06
There might be some helpful info here: https://stackoverflow.com/questions/55834349/what-is-the-path-to-yarn-error-log-files

**Comment by Playit3110** [comment] 2021-02-28 15:49
I tried to install it code-server over codeserver.dev/install.sh and noticed a lot of old or broken dependencies. I tried to run it as well and got a simular result. The only difference is my remote OS. It is a Raspberry Pi 4 4GB

**Comment by jsjoeio** [comment] 2021-03-01 17:27
> noticed a lot of old or broken dependencies

Well that's no good!

Can you try following [these steps](noticed a lot of old or broken dependencies) and let me know if the result is the same?

**Comment by Playit3110** [comment] 2021-03-01 19:48
Im not quiet sure which steps i should follow. Could you link the threat or the comment here?

**Comment by jsjoeio** [comment] 2021-03-01 20:55
Sorry looks like the link didn't get added! Updated the comment

**Comment by Playit3110** [comment] 2021-03-01 21:05
I already tried that too but i got the error global is not a file when i executed yarn global ...

**Comment by jsjoeio** [comment] 2021-03-01 22:48
Hmm..strange. Can you please post the logs or a screenshot so I can see if I can reproduce your error?

**Comment by Playit3110** [comment] 2021-03-01 23:09
Here is the process:

Last login: Tue Mar  2 01:04:12 2021 from 192.168.2.xxx
pi@server:~ $ sudo apt update && apt upgrade
Get:1 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Hit:3 https://deb.nodesource.com/node_14.x buster InRelease
Fetched 15.0 kB in 1s (11.8 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
pi@server:~ $ sudo apt install build-essential python git nodejs yarn
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'cmdtest' instead of 'yarn'
build-essential is already the newest version (12.6).
git is already the newest version (1:2.20.1-2+deb10u3).
python is already the newest version (2.7.16-1).
nodejs is already the newest version (14.16.0-1nodesource1).
The following additional packages will be installed:
  libyaml-0-2 python-cliapp python-markdown python-pygments
  python-ttystatus python-yaml
Suggested packages:
  python-markdown-doc python-pygments-doc ttf-bitstream-vera
The following NEW packages will be installed:
  cmdtest libyaml-0-2 python-cliapp python-markdown
  python-pygments python-ttystatus python-yaml
0 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
Need to get 892 kB of archives.
After this operation, 4,565 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://ftp.agdsn.de/pub/mirrors/raspbian/raspbian buster/main armhf libyaml-0-2 armhf 0.2.1-1 [38.8 kB]
Get:2 http://ftp.agdsn.de/pub/mirrors/raspbian/raspbian buster/main armhf python-yaml armhf 3.13-2 [118 kB]
Get:3 http://ftp.agdsn.de/pub/mirrors/raspbian/raspbian buster/main armhf python-cliapp all 1.20180812.1-2 [42.2 kB]
Get:4 http://ftp.agdsn.de/pub/mirrors/raspbian/raspbian buster/main armhf python-ttystatus all 0.38-2 [15.4 kB]
Get:5 http://ftp.agdsn.de/pub/mirrors/raspbian/raspbian buster/main armhf python-markdown all 3.0.1-3 [60.6 kB]
Get:6 http://ftp.agdsn.de/pub/mirrors/raspbian/raspbian buster/main armhf cmdtest all 0.32-3 [21.9 kB]
Get:7 http://ftp.agdsn.de/pub/mirrors/raspbian/raspbian buster/main armhf python-pygments all 2.3.1+dfsg-1 [596 kB]
Fetched 892 kB in 2s (405 kB/s)
Selecting previously unselected package libyaml-0-2:armhf.
(Reading database ... 111866 files and directories currently installed.)
Preparing to unpack .../0-libyaml-0-2_0.2.1-1_armhf.deb ...
Unpacking libyaml-0-2:armhf (0.2.1-1) ...
Selecting previously unselected package python-yaml.
Preparing to unpack .../1-python-yaml_3.13-2_armhf.deb ...
Unpacking python-yaml (3.13-2) ...
Selecting previously unselected package python-cliapp.
Preparing to unpack .../2-python-cliapp_1.20180812.1-2_all.deb ...
Unpacking python-cliapp (1.20180812.1-2) ...
Selecting previously unselected package python-ttystatus.
Preparing to unpack .../3-python-ttystatus_0.38-2_all.deb ...
Unpacking python-ttystatus (0.38-2) ...
Selecting previously unselected package python-markdown.
Preparing to unpack .../4-python-markdown_3.0.1-3_all.deb ...
Unpacking python-markdown (3.0.1-3) ...
Selecting previously unselected package cmdtest.
Preparing to unpack .../5-cmdtest_0.32-3_all.deb ...
Unpacking cmdtest (0.32-3) ...
Selecting previously unselected package python-pygments.
Preparing to unpack .../6-python-pygments_2.3.1+dfsg-1_all.deb ...
Unpacking python-pygments (2.3.1+dfsg-1) ...
Setting up libyaml-0-2:armhf (0.2.1-1) ...
Setting up python-ttystatus (0.38-2) ...
Setting up python-markdown (3.0.1-3) ...
Setting up python-pygments (2.3.1+dfsg-1) ...
Setting up python-yaml (3.13-2) ...
Setting up python-cliapp (1.20180812.1-2) ...
Setting up cmdtest (0.32-3) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...
pi@server:~ $ yarn global add code-server
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'global'
pi@server:~ $

**Comment by jsjoeio** [comment] 2021-03-01 23:24
Okay these might be dumb questions but bear with me.

> E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
> E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

1. Does `apt upgrade` need to be run with `sudo`?

> Note, selecting 'cmdtest' instead of 'yarn'

2. Could that be an issue? Guessing it's using `cmdtest` which doesn't have a `global` command?

I found this potential fix that might work? ([source](https://github.com/Joystream/helpdesk/issues/16)): 
```shell
sudo apt remove cmdtest
sudo apt remove yarn
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn
```

**Comment by Playit3110** [comment] 2021-03-01 23:40
Wow thanks a lot. Till now no error

**Comment by jsjoeio** [comment] 2021-03-01 23:41
Sure thing! If it ends up working, feel free to close this issue!

**Comment by Playit3110** [comment] 2021-03-02 00:06
Sadly it still breaks when i try to log in

**Comment by jsjoeio** [comment] 2021-03-02 16:58
Dang it! We were too optimistic too soon. Run code-server like so:
```
code-server --log debug
```

More info [here](https://github.com/cdr/code-server/blob/v3.9.0/docs/FAQ.md#how-do-i-debug-issues-with-code-server) in the docs.

**Comment by jsjoeio** [comment] 2021-03-02 17:34
Those logs aren't very helpful. They don't tell us too much :( 

If VS Code is exiting, then I have to guess that there's a missing dependency or something. Honestly, we should have something like a `doctor` command which checks for all the dependencies needed to run `code-server`.

Hmm...a few things:
- can you post your system info?
  - OS, browser, application (i.e. Termux version)
- can you post the dependency versions for the following:
  - build-essential python git nodejs yarn

That might help us get to the bottom of this

**Comment by code-asher** [comment] 2021-03-02 18:02
Full list of required dependencies to build with yarn: https://github.com/cdr/code-server/blob/v3.9.0/docs/npm.md#npm-install-requirements

It might help to to re-install VS Code Node modules and post the log if there are any failures. Maybe something like:

```
$ cd $(yarn global dir)/node_modules/code-server/lib/vscode
$ yarn --check-files
```

**Comment by Playit3110** [comment] 2021-03-02 18:31
Here is the install process of the libaries:

```
Last login: Tue Mar  2 18:27:32 2021 from 192.168.2.xxx
pi@server:~ $ sudo apt-get install build-essential pkg-config libx11-dev libxkbfile-dev libsecret-1-dev python3
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.6).
libsecret-1-dev is already the newest version (0.18.7-1).
libx11-dev is already the newest version (2:1.6.7-1+deb10u1).
libxkbfile-dev is already the newest version (1:1.0.9-2).
pkg-config is already the newest version (0.29-6).
python3 is already the newest version (3.7.3-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@server:~ $ npm config set python python3
pi@server:~ $
```

**Comment by jsjoeio** [comment] 2021-03-02 18:54
Great. All that looks fine to me. What version of `node` and `yarn` are you using? 
```
node --version
yarn --version
```

And have you tried the suggestion by @code-asher ?

**Comment by Playit3110** [comment] 2021-03-02 18:57
I have. It is the first log i commented above.

Here the versions:
```
Last login: Tue Mar  2 18:32:09 2021 from 192.168.2.xxx
pi@server:~ $ yarn --version
1.22.5
pi@server:~ $ node --version
v14.16.0
pi@server:~ $
```

**Comment by jsjoeio** [comment] 2021-03-02 19:02
Ah, sorry missed that!

Hmm...I wonder if it could be an issue with your node version. I know I've run into funky errors with local development and [vscode itself recommends](https://github.com/microsoft/vscode/wiki/How-to-Contribute#prerequisites) `<= 14.x`

Can you try downgrading node versions to either something that is` >= 10.x` and `<= 14.x` and then reinstalling `code-server`?

**Comment by Playit3110** [comment] 2021-03-02 19:05
Im sorry to ask but how can i downgrade. I dont work that much with node

**Comment by jsjoeio** [comment] 2021-03-02 19:36
No worries at all! I usually use a tool called `nvm`. Here's a ~1min video about using `nvm`: [link](https://egghead.io/lessons/node-js-install-node-with-nvm)

What you'll do is something like:
1. install `nvm`
2. install an older version of node: `nvm install 12.16.1`
3. set the default to that version: `nvm alias default 12.16.1`
4. restart your shell

**Comment by Playit3110** [comment] 2021-03-02 19:56
It works now. Thanks a lot. :)

**Comment by Playit3110** [comment] 2021-03-02 19:58
I think we need to install the right version of node to make it working for other people.

**Comment by Playit3110** [comment] 2021-03-02 20:13
One thing, is there a easy way to rebuilt code-server if it is already installed?

**Comment by jsjoeio** [comment] 2021-03-02 20:45
Yes, we should update the docs. I'll change this issue to match that.

**Comment by jsjoeio** [comment] 2021-03-02 20:48
> One thing, is there a easy way to rebuilt code-server if it is already installed?

Hmm... sorry can you elaborate a little bit on what you mean? If you have it installed with `yarn`, you should have to rebuild it hopefully, only stop/restart.

**Comment by Playit3110** [comment] 2021-03-02 21:08
If that works then it is ok

**Comment by jsjoeio** [comment] 2021-03-02 22:49
Should we close this now?

**Comment by Playit3110** [comment] 2021-03-03 07:24
Sure

**Comment by Playit3110** [comment] 2021-03-03 07:31
But i cant close it

**Comment by jsjoeio** [comment] 2021-03-03 17:57
ha! no worries, i can!

**Comment by jsjoeio** [comment] 2021-03-03 17:57
actually, i still want us to update the docs. so we'll close after we do that!

**Comment by Playit3110** [comment] 2021-03-03 18:15
Thats a good idea

**Closed** 2021-03-10 19:26 UTC
Labels: docs, help-wanted

**Comment by Vishalrakse** [comment] 2023-03-27 05:06
![Screenshot_2023-03-27-10-32-36-36_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/128638365/227845252-7abf1791-7efe-4da7-8439-10dc7a935071.jpg)

**Pleas help me 
help me 
help me 
I am vishal 
I belong to bhopal.**
      And 
_Thank so much 
Pleas replay
Tha setuation._

**Comment by code-asher** [comment] 2023-03-27 16:09
You will need to use Node v16 with code-server, not v19.
