### ISSUE TITLE
Cannot authenticate with extension github.vscode-pull-request-github 

### ISSUE THREAD

**Issue by Orybon** [cdr/code-server#2253] opened 2020-10-30 07:32 UTC
Hi,

Authentification for the extension is failling with this message: 

```
Oh no! An error occurred!
Please restart the sign in process from the editor.

Forbidden
```

Any idea why ?

- Web Browser: Version 75.0.3770.142 (Build officiel) (64 bits)
- Local OS:  Windows 10 Pro 64bits
- Remote OS: Ubuntu 18.04
- Remote Architecture: x86_64
- `code-server --version`: 3.6.1 62735da69466a444561ab9b1115dc7c4d496d455

**Comment by code-asher** [comment] 2020-11-02 17:52
There are some issues with authenticating with the built-in GitHub extension which probably are affecting the pull request extension as well (https://github.com/cdr/code-server/issues/1883). Hopefully I will be able to find the time to fix them soon.

**Comment by Orybon** [comment] 2020-11-03 08:57
Thank you. I didn't find the issue ([#1883](https://github.com/cdr/code-server/issues/1883)) while opening this one.

**Comment by nhooyr** [comment] 2020-12-08 18:52
Closing as duplicate of #1883 then!

**Closed by nhooyr** 2020-12-08 18:52 UTC
