### ISSUE TITLE
Extensions details are not displayed

### ISSUE THREAD

**Issue by ChristianWeyer** [cdr/code-server#323] opened 2019-03-23 06:41 UTC
When searching for extensions in the marketplace and trying to read the Details pane, nothing is shown. For any extension, that is.#

E.g.:
![image](https://user-images.githubusercontent.com/888718/54862719-14dfcb00-4d3f-11e9-9321-bd59b6d34998.png)

**Comment by ab00a** [comment] 2019-03-25 15:51
It's caused by the server settings that are hosting the app blocking iFrame displays (https://github.com/codercom/bugs/issues/360)

**Comment by code-asher** [comment] 2019-10-23 22:09
This should be resolved in v2. We had some CSP issues in v1 but they're all resolved now.

**Closed by code-asher** 2019-10-23 22:09 UTC
Labels: bug

**Comment by DAddYE** [comment] 2020-07-23 23:04
This is happening for me on latest master and Safari on Catalina.

**Comment by code-asher** [comment] 2020-07-24 15:15
Yeah unfortunately they don't show up on Safari at the moment. We're tracking it here: https://github.com/cdr/code-server/issues/1317
