### ISSUE TITLE
Copy is unavailable on iPadOS

### ISSUE THREAD

**Issue by chocoford** [cdr/code-server#1589] opened 2020-05-01 09:16 UTC
I can’t do copy operation on iPadOS safari.
I try to connect via HTTPS. But only got a whole white screen(show nothing). 
And if I access `http://localhost:port` from my computer (which is the machine running `code-server`), I can do copy and paste operation.

**Comment by cblavier** [comment] 2020-05-01 09:46
I am using lastest version of code-server but I can’t cmd-c, cmd-x, cmd-v, cmd-w, cmd-z ... either

**Comment by pr1metine** [comment] 2020-05-01 11:10
Duplicate of #1015

**Comment by cmoog** [comment] 2020-05-01 15:49
Closing. Please track this in 1015 ^^

**Closed by cmoog** 2020-05-01 15:49 UTC
