### ISSUE TITLE
Does not work with C++ extensions

### ISSUE THREAD

**Issue by Riku32** [cdr/code-server#2305] opened 2020-11-15 00:11 UTC
The Microsoft official C++ extension does not work with code-server. Here is the output from the `output` tab in vscode
```
[Error - 12:07:38 AM] Connection to server got closed. Server will not be restarted.
/home/delta/.local/share/code-server/extensions/ms-vscode.cpptools-1.1.1/bin/cpptools: 7: Syntax error: word unexpected (expecting ")")
```
After this message appears I am unable to use my terminal window within vscode.
This extension works on a local installation of vscode.

- Web Browser:
- Local OS: PopOS 20.04
- Remote OS: Ubuntu server 20.04
- Remote Architecture: x86-64
- `code-server version`: 3.6.2 9bde62fbd611a7a91c5f327fa43e0d06f1379169

**Comment by mengoreo** [comment] 2020-11-15 12:07
same problem here🥲

**Comment by appmlk** [comment] 2020-11-16 11:40
same 😫

**Comment by wormtooth** [comment] 2020-11-16 14:49
The problem is that code-server somehow installs the arm version of the C/C++ extension. To install the correct version, go to [https://github.com/microsoft/vscode-cpptools](https://github.com/microsoft/vscode-cpptools) to download and install the correct .vsix for your server.

**Comment by code-asher** [comment] 2020-11-16 19:35
Closing as a duplicate of https://github.com/cdr/code-server/issues/2120. I think our marketplace has some issues with extensions that have multi-architecture releases. :crying_cat_face:

**Closed by code-asher** 2020-11-16 19:35 UTC
