### ISSUE TITLE
OCI runtime create failed: container_linux.go:345

### ISSUE THREAD

**Issue by huahuayu** [cdr/code-server#813] opened 2019-06-27 07:51 UTC
## env
os:ubuntu 16.04
docker: 18.09.4
code-server version: latest version in Jun 27, 2019

## problem
can't get it run in ubuntu server, error occurs(but in my local mac it's ok): 
```
$  docker run -it -p 127.0.0.1:8443:8443 -v "${PWD}:/home/coder/project" codercom/code-server --allow-http --no-auth
Unable to find image 'codercom/code-server:latest' locally
latest: Pulling from codercom/code-server
6abc03819f3e: Pull complete
05731e63f211: Pull complete
0bd67c50d6be: Pull complete
42645f7afa6f: Pull complete
353bd2a3bccd: Pull complete
898e646af7f6: Pull complete
5c5dc0bf677e: Pull complete
ada54e852158: Pull complete
Digest: sha256:281d40d92634057c2bb30edfe33a91517f865b4b5e0edd95ec3f81aba10ddf36
Status: Downloaded newer image for codercom/code-server:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "chdir to cwd (\"/home/coder/project\") set in config.json failed: permission denied": unknown.
```

**Comment by brotherko** [comment] 2019-06-29 09:11
I got the same error from my digital ocean server

**Comment by sr229** [comment] 2019-07-03 01:10
You tried to bind mount of a directory you do not own? we had a discussion about this on #679 but it seems they're still having a debate about the permissions inside the container (which should be irrelevant)

**Comment by BeOleg** [comment] 2019-08-16 07:25
+1

**Comment by sr229** [comment] 2019-08-16 17:48
Figured this might be a bug with how we wrote the Dockerfile. Will do a check later.

**Comment by sr229** [comment] 2019-08-16 17:54
As a temporary workaround, try running `chinodesuuu/coder:ubuntu` and volume mount to your PWD.

```sh

$ docker run  -p 9000:9000 -v ${PWD}:/home/coder/projects chinodesuuu/coder:ubuntu
```

**Comment by samayo** [comment] 2019-10-09 19:28
Not working for me. I tried both options. @sr229 I also tried yours but I get 404 when I check my domain.tld:9000 but at least the service seems to be running: 


```
....
INFO  Starting shared process [1/5]...
INFO  Starting webserver... {"host":"0.0.0.0","port":"9000"}
WARN  No certificate specified. This could be insecure.
WARN  Documentation on securing your setup: https://github.com/cdr/code-server/blob/master/doc/security/ssl.md
WARN
WARN  Launched without authentication.
INFO
INFO  Started (click the link below to open):
INFO  http://localhost:9000/
INFO
WARN  stderr {"data":"(node:20) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"}
INFO  Connected to shared process

```

**Comment by samayo** [comment] 2019-10-09 19:30
I also don't know why there is a permission issue, I am running this as root

**Comment by saurshaz** [comment] 2019-10-24 11:56
In my case an un-ncecessarily pasted `cmd: npm start` in `docker-compose.ym` was the cause :)

**Comment by sr229** [comment] 2019-10-24 13:44
This is more of a misconfiguration so I'll close this off now.

**Closed by sr229** 2019-10-24 13:44 UTC
Labels: bug
