### ISSUE TITLE
Git Graph extension empty

### ISSUE THREAD

**Issue by vipwp** [cdr/code-server#3774] opened 2021-07-14 13:36 UTC
## OS/Web Information

- Web Browser: Chrome/91.0.4472.77
- Local OS: win 10
- Remote OS:  codercom/code-server:latest with docker 20.10.7 on centos 7.6
- Remote Architecture: x86_64
- `code-server --version`:3.10.2

## Steps to Reproduce

1. run container of codercom/code-server:latest
2. install git graph extension (version:1.30.0)
3.  open git graph view

## Expected

git history view

## Actual

empty view

## Notes

This issue can be reproduced in VS Code: Yes/No

**Comment by jsjoeio** [comment] 2021-07-14 16:52
Hmm...I am not able to reproduce on Brave + macOS

## Screenshot

![image](https://user-images.githubusercontent.com/3806031/125661496-23e5c8e9-20dd-4db4-914f-052ae3ed5b38.png)

Can you check if there are any logs in the browser?

## Notes

We have had issues with this in the past:
- https://github.com/cdr/code-server/issues/3399
- https://github.com/cdr/code-server/issues/2317

**Comment by vipwp** [comment] 2021-07-14 17:59
Here's the errors in web debug console when opening the git graph tab.
![image](https://user-images.githubusercontent.com/1547414/125666349-f53751ca-66ab-448d-ae1b-a36ab3e1c251.png)

http://{host}:8080/webview/out-vscode/vs/workbench/contrib/webview/browser/pre/main.js
http://{host}:8080/webview/out-vscode/vs/workbench/contrib/webview/browser/pre/host.js


No other errors in other logs.

**Comment by jsjoeio** [comment] 2021-07-14 22:34
Hmm...I found this 

> In Chrome there is no built-in flag to disable service workers specifically. But service workers count as "cookies/site data" at chrome://settings/cookies so blocking those disables service worker.
[Source](https://groups.google.com/a/chromium.org/g/service-worker-discuss/c/Cohd-TKG8so?pli=1)

Are you disabling cookies by chance? 

Actually wait do service workers work on `http`? What happens if you access your code-server instance on `https`?

**Comment by jsjoeio** [comment] 2021-07-14 22:35
It seems like using `https` may solve the issue. See [here](https://github.com/cdr/code-server/issues/2500#issuecomment-750691479)

**Comment by vipwp** [comment] 2021-07-15 04:11
I upgrade the code-server to 3.11.0 but the extension still not work.
On https, I got this error on chrome when I open git graph tab.
![image](https://user-images.githubusercontent.com/1547414/125727306-6f32ee48-99c5-4d22-8dc5-43b0a4e0d72a.png)

this error on firefox
![image](https://user-images.githubusercontent.com/1547414/125727711-8acc8e2b-e3ff-4cf5-bbea-cc2c330e2802.png)

**Comment by jsjoeio** [comment] 2021-07-15 18:23
Hmm... Do you know how we can enable service workers in your browser?

**Comment by vipwp** [comment] 2021-07-16 02:29
> Hmm... Do you know how we can enable service workers in your browser?

Sorry I don't know.A document?

**Comment by jsjoeio** [comment] 2021-07-19 16:57
What does your code-server setup look like? Where is it hosted?

**Comment by balesz** [comment] 2021-07-20 07:43
I think this issue is related: https://github.com/mhutchie/vscode-git-graph/issues/535

**Comment by mateuszkitlas** [comment] 2021-07-20 10:16
I think I have the same problem. I'm on code-server 3.10.2 and I'm developing my own extension. Sometimes (like 1 in 5 times) webviews just don't load leaving js script with `host.js` 
![obraz](https://user-images.githubusercontent.com/14885572/126306158-b34c0ce6-8f3c-4f2a-b37d-0c5c03330f5d.png)
![obraz](https://user-images.githubusercontent.com/14885572/126306424-c4aa187f-1be2-4c6c-81bb-c47509275dfe.png)

This affects both webviews `window.registerWebviewViewProvider` and `window.createWebviewPanel`. I tried to detect this situation, then `dispose()` badly registered webview and register it again - but it does nothing.

Does this seem related? In my case no HTML is loaded.

**Comment by vipwp** [comment] 2021-07-20 12:53
> What does your code-server setup look like? Where is it hosted?

The codeserver is installed in docker container(centos 7.2 x86_64) with code-server-3.11.0-linux-amd64.tar.gz.
The host info is: centos 7.6 x86_64

**Comment by jsjoeio** [comment] 2021-07-20 18:10
> I think this issue is related: mhutchie/vscode-git-graph#535

I think @balesz is right. Looks to be upstream in vscode. Might be worth raising an issue there. Here is a similar one: https://github.com/microsoft/vscode/issues/127770

**Comment by jsjoeio** [comment] 2021-07-20 18:11
Closing for now, but I suggest opening upstream and/or subscribing to both the issue in git-graph and vscode. Let's hope they fix soon!

**Closed** 2021-07-20 18:10 UTC
Labels: upstream:vscode, waiting-for-info
