### ISSUE TITLE
Typing not working

### ISSUE THREAD

**Issue by cTatu** [cdr/code-server#328] opened 2019-03-24 09:31 UTC
- `code-server` version: **1.32.0-310**
- OS Version: **Ubuntu 18.04.1 LTS & Kernel 4.15.0-1036-azure**

## Description

Firstly, sometimes when I open a new terminal the editor stop recording my keystrokes (it's not because focusing), no matter what I type it's not doing anything, I can still select the code and even delete it but I cannot add nothing. Sometimes the problem is solved by closing the terminal.

I had running it on an azure container for like 3-4 days and I connected to it several times since then.

## Steps to Reproduce
**(Not sure at 100%, sometimes it stops registering the keys suddenly)**

1. Create new terminal
2. Type whatever in there
3. Click back to text editor
4. Try to type anything and doesn't work. Only the backspace bar

**Comment by nol166** [comment] 2019-03-24 21:30
I found this issue when working with the search field in extensions. The workaround was to right click i the search field for extensions, the left click and typing goes back to normal. As a side note, it seems that the extension search field grabs focus and doesn't let go even when you switch back to (as in your situation) the code editor.

**Comment by ShannonMasters** [comment] 2019-03-25 00:42
Image from dockerhub (https://hub.docker.com/r/codercom/code-server) (no version tags.. last updated 9 days ago at time of this post).

I have the same problems as described by others above, but also noticed if you highlight any text in the actual code editor you also lose the ability to type as well.  The cursor still blinks to indicate focus, but until you deselect the text you cannot resume typing.

**Comment by ShannonMasters** [comment] 2019-03-25 05:30
This also appears to only affect Chrome.  I just tested in Firefox Quantum 65.0.2 (64-bit) and it works fine, no loss of ability to type so far.

**Comment by sr229** [comment] 2019-03-26 02:40
Can confirm this bug as well. Sometimes the editor does not accept input when I was process of making #225 in Crostini.

**Comment by frenck** [comment] 2019-03-26 12:02
This seems to workaround this issue:

![image](https://user-images.githubusercontent.com/195327/54995623-6a2e0d80-4fc7-11e9-8345-98ad7fc4c98b.png)

If I disable selection clipboard, this issue seems to be gone.

**Comment by buckley310** [comment] 2019-04-18 03:25
I am running into same/similar behavior in the settings screen (UI version). Whenever I open the settings screen, several keys stop working (enter, down arrow key, etc). I can usually convince it to go back to normal by right-clicking in the search box in settings, and then closing the settings tab.
The JSON settings screen doesn't do this, only the UI settings screen.
Firefox 66.0.3 is affected for me. Cannot reproduce in Chromium 73.0.3683.103.

**Comment by ShannonMasters** [comment] 2019-04-18 04:10
can confirm the workaround that frenck posted for disabling selection clipboard works.  In the interim of this getting fixed, I have just included in my docker file a line to copy a settings.json file with:

{
  "editor.selectionClipboard": false
}

**Comment by buckley310** [comment] 2019-04-18 04:49
`"editor.selectionClipboard": false` did not resolve the settings screen issue in my test.

**Comment by sr229** [comment] 2019-05-24 02:54
I don't think this is persistent on newer versions. Let me know if there are other people still getting this.

**Comment by buckley310** [comment] 2019-05-24 02:59
I am still getting this issue in the latest docker image with firefox 67.

**Comment by buckley310** [comment] 2019-05-24 03:01
The only place I can seem to reproduce it now is the search box on the settings screen though. None of the other places seem to trigger it anymore.

**Comment by ilizarragadev** [comment] 2019-06-13 04:27
Worked for me, thanks so much! 

> This seems to workaround this issue:
> 
> ![image](https://user-images.githubusercontent.com/195327/54995623-6a2e0d80-4fc7-11e9-8345-98ad7fc4c98b.png)
> 
> If I disable selection clipboard, this issue seems to be gone.

**Comment by sr229** [comment] 2019-06-14 05:16
I think we can close this off @coadler?

**Comment by coadler** [comment] 2019-06-14 15:16
Actually kyle had this assigned, will let him close

**Comment by buckley310** [comment] 2019-06-14 15:19
I can still recreate this issue

**Comment by code-asher** [comment] 2019-10-30 21:09
I attempted to recreate this on v2 but it seems to work as expected with or without the selection clipboard. If anyone has issues on v2 lemme know and we can reopen.

**Closed by code-asher** 2019-10-30 21:09 UTC
Labels: bug

**Comment by buckley310** [comment] 2019-10-31 04:13
@code-asher I can still recreate the typing issues i mentioned earlier. seems to affect firefox, but not chrome in my testing. on a fresh instance of code-server:v2, i can open a new document and type just fine, but if i do Ctrl+, to open the UI settings screen, then close the settings tab with the mouse, not all my keys work in the text editor now. notably, down arrow key and Enter. it happens with or without selection keyboard enabled. If nobody else can recreate it, i can document more thoroughly. If it's thought to be a similar but separate bug i can leave this thread alone.

**Comment by code-asher** [comment] 2019-10-31 21:35
Ah thanks for those steps! I was able to replicate. I opened #1135 for this.
