### ISSUE TITLE
Control-C not recognized from iPadOS

### ISSUE THREAD

**Issue by valenvb** [cdr/code-server#1343] opened 2020-02-05 22:44 UTC
- `code-server` version: 2.1698-vsc1.41.1 x64 Linux binary on Ubuntu 18.04
- OS Version: iPadOS 13.3

## Description

When connected via Safari on iPadOS, control-c is not recognized by the integrated terminal, it simply prints a newline. Other control sequences work fine (eg, control-d, control-z). Control-c works fine in Safari (13.0.5) on my Mac.

(This was raised in the discussion of #128 but that issue was originally about the arrow keys and was closed.)

## Steps to Reproduce

1. Start any long-running program in the terminal (`python` is a good example)
2. Type control-c to exit, a newline will be printed (as if return had been pressed)
3. Interpreters can be exited with control-d (obviously, this does not work for all programs).

**Comment by sr229** [comment] 2020-02-05 22:57
@code-asher

**Comment by nhooyr** [comment] 2020-02-05 23:44
@sr229 You need to stop tagging @code-asher on issues, it's very spammy.

**Comment by nothingto** [comment] 2020-02-14 17:50
Can confirm this is happening, although there is a workaround [here](https://stackoverflow.com/questions/45257525/make-ctrlc-copy-and-ctrlshiftc-interrupt-in-vscode-terminal)

**Comment by valenvb** [comment] 2020-02-15 00:36
Thanks @nothingto, that works great - so far I’ve had no problems just mapping Ctrl-C to Ctrl-C, which makes it so weird that this bug exists - it captures Ctrl-C from the keyboard just fine, but for some reason doesn’t pass it through to the terminal.

**Comment by Marcel2508** [comment] 2020-08-13 19:16
I came across this issue today too. 
The terminal looks a bit buggy at all to me (interpreting keys).
I can't use ctrl+c or the arrow keys (up & down).

**Comment by sr229** [comment] 2020-08-31 02:56
ATM looks like Microsoft's priorities are getting everything working properly first for VS Code so I don't think safari support is not really in high priority/

**Comment by jsjoeio** [comment] 2021-01-07 21:18
I was able to successfully reproduce this in the following browsers on iPadOS:
- [x] Chrome
- [x] Safari
- [x] Firefox

Next, I’m going to check if this is also an issue in Codespaces. If it is, then it may be an upstream issue.

**Comment by jsjoeio** [comment] 2021-01-07 21:28
The same issue is occurring on Codespaces so I assume it’s upstream. I will open an issue and link it here.


https://user-images.githubusercontent.com/3806031/103946778-4e402100-50f4-11eb-8d87-61d33f03f95a.MP4

**Comment by jsjoeio** [comment] 2021-01-08 20:53
As a temporary workaround, you can add shortcut like so:
1. Open Command Palette 
2. Look for "Preferences: Open Keyboard Shortcuts (JSON)"
3. Add this:
```json
{
    "key": "ctrl+shift+c",
    "command": "workbench.action.terminal.sendSequence",
    "args": {
      "text": "\u0003"
    },
    "when": "terminalFocus"
}
```
Source: [StackOverflow](https://stackoverflow.com/a/52735954/3015595)

**Comment by momikiii** [comment] 2021-01-18 20:18
You can press **Control + Z** to stop your program

I tried on **NodeJS** and it worked

**Comment by jsjoeio** [comment] 2021-01-28 23:33
The workaround has been added to our docs and an issue has been opened upstream. Closing.

**Closed by jsjoeio** 2021-01-28 23:33 UTC
Labels: browser-safari, os-ios, upstream
