### ISSUE TITLE
-- link exposes Coder without authentication

### ISSUE THREAD

**Issue by Jtshn** [cdr/code-server#3184] opened 2021-04-21 13:55 UTC
## OS/Web Information

- Web Browser: Firefox
- Local OS: Windows 10 x64
- Remote OS: Ubuntu 20.04.2 LTS
- Remote Architecture: GNU/Linux 5.4.0-29-generic x86_64
- `code-server --version`: 3.9.3 fe2dc2deb08e378069891b622bb62ad1d261d1b1

## Steps to Reproduce

1. run `code-server --link`
![image](https://user-images.githubusercontent.com/24493762/115565711-e6d06a80-a2b9-11eb-8907-ddf517b57244.png)
## Expected

After using the option `code-server --link` for running code-server:

- coder can now be accessed via xxx.cdr.co
- coder is secured by authentication (by default Github as far as I understood)

## Actual

- coder can now be accessed via xxx.cdr.co
- coder is secured by authentication **only** when accessed via xxx.cdr.co URL
- coder's authentication is disabled when accessed via http on original Server:

after running `sudo ss -tulpn`
and one of the returned values being:
`tcp        LISTEN      0           4096                               *:44481                        *:*          users:(("coder-cloud-age",pid=1266891,fd=7)) `

from any machine Coder is now accessible using http://XXX.XXX.XXX:44481/

## Notes

In case this is caused by misconfiguration on my end, I'd be glad to be hear how I can fix this
hoping there is a simple fix

**Comment by Jtshn** [comment] 2021-04-21 14:06
as it turns out, after thinking about this issue a bit, Coder being accessible was caused by my disabled firewall.
I think this fixes my issue but maybe it would be worth a shot to not turn off authentication when using Coder using --link. due to if the firewall is disabled (or from a local address) it can easily be accessed

**Comment by code-asher** [comment] 2021-04-21 15:33
It listens on localhost so it should only be accessible from within that machine unless something is proxying external requests to it. That limits the attack surface somewhat but I think we can do better.

One of the thoughts i had was to use a socket to communicate between code-server and the agent instead of listening on a port.

That way you could only access code-server if you have the right permissions which would mean you already have access to the machine anyway.

**Comment by code-asher** [comment] 2021-04-21 15:41
Closing as a duplicate of https://github.com/cdr/code-server/issues/2484

**Closed by code-asher** 2021-04-21 15:41 UTC
