### ISSUE TITLE
[v2] Crashes seemingly at random

### ISSUE THREAD

**Issue by Merith-TK** [cdr/code-server#1066] opened 2019-10-09 16:27 UTC
- `code-server` version: 
- OS Version: archlinux

## Description
occasionally crashes for little reason, ( i am not even on, it always crashes overnight for me)

## Steps to Reproduce
[code-logs.zip](https://github.com/cdr/code-server/files/3708431/code-logs.zip)
[systemctl.log](https://github.com/cdr/code-server/files/3708432/systemctl.log)
[code-server.txt](https://github.com/cdr/code-server/files/3708458/code-server.txt)

Unknown, attached are logs and output of `systemctl status code-server.service`, and the actual service file

The logs are pretty much the entirety of logs from when i moved to V2. it has done this once before, in which i thought it w
as a fluke and could be ignored, but this is the second time this has happened,

**Comment by wpitallo** [comment] 2019-10-31 20:13
Hi @Merith-TK any updates on this? I am getting this as well. I am using node and it seems to happen frequently when i run: npm install

**Comment by wpitallo** [comment] 2019-10-31 20:16
Its actually happening every time I run an npm install now on the exact same spot. Where can we see the crash logs?

**Comment by Merith-TK** [comment] 2019-10-31 20:19
Have not had any random crashes since this

**Comment by sr229** [comment] 2019-10-31 21:44
Since OP confirmed there's no more crashes, I'll be closing this down.

**Closed by sr229** 2019-10-31 21:44 UTC
Labels: bug

**Comment by Merith-TK** [comment] 2019-10-31 21:46
other guy may have issues however

**Comment by code-asher** [comment] 2019-11-01 16:41
I say we pile on here: https://github.com/cdr/code-server/issues/1009
