### ISSUE TITLE
v3.3.1 Extensions installed via code-server --install-extension in incorrect path

### ISSUE THREAD

**Issue by nathanrpage97** [cdr/code-server#1713] opened 2020-05-22 18:20 UTC
So when install extension on code-server via cli

```bash
code-server --install-extension ms-python.python
```
It is installing those extensions to ~/.vscode-oss/extensions/.

I can still install successfully via the graphical interface. They correctly show up in ~/.local/share/code-server/extensions/

**Comment by nathanrpage97** [comment] 2020-05-22 19:26
This issue only shows up in static release install method, it works correctly using debian packaging.

**Comment by nhooyr** [comment] 2020-05-22 20:01
Ah this is due to #1676 

Will fix ASAP.

**Comment by nhooyr** [comment] 2020-05-24 05:45
That's bizarre though, Debian package should reproduce it.

🤷 

Either way will be fixed soon.

**Closed** 2020-05-27 19:48 UTC
Labels: bug
