### ISSUE TITLE
python extension is not working v2

### ISSUE THREAD

**Issue by shahidul56** [cdr/code-server#1016] opened 2019-09-21 06:07 UTC
- `code-server` version: 
2.1523-vsc1.38.1
2.1478-vsc1.38.1

- OS Version: Ubuntu 18 
- Extension: 

## Description
 python extension is not working, debug also not working + can't able to change python version also

![fewf](https://user-images.githubusercontent.com/11449967/65368862-1c3d4e00-dc68-11e9-8c05-ad757444221d.PNG)

**Comment by sr229** [comment] 2019-09-21 14:50
Duplicate of #697

**Closed by sr229** 2019-09-21 14:50 UTC

**Comment by code-asher** [comment] 2019-10-29 17:03
FYI the `open` error is due to service workers not being supported due to being on an insecure domain. It's possible the absence of service workers is also affected the Python extension.

**Comment by davezhouwa** [comment] 2019-10-29 18:00
@code-asher  when can this be fixed?  the python extension works for me on Mac OS, but not on linux ubuntu 16.04

**Comment by code-asher** [comment] 2019-10-29 20:22
Are you accessing it over HTTP? There isn't any way to make service
workers work over HTTP (since its a browser restriction) so
HTTPS/localhost is a hard requirement.

If you are accessing over HTTPS/localhost then I'd love to get some more
information on how to replicate the issue because I haven't been able to
(except for when I use HTTP).

**Comment by davezhouwa** [comment] 2019-10-30 00:20
I do use http.  But why could I use it in codeserver V1. in particular, release 1.1156-vsc1.33.1?
