### ISSUE TITLE
can not open terminal 3.4.0

### ISSUE THREAD

**Issue by roccqqck** [cdr/code-server#1743] opened 2020-05-28 15:39 UTC
I can not open a new terminal

- Web Browser: firefox 76.0.1
- Local OS: mac 10.13
- Remote OS: ubuntu18.04
- Remote Architecture: x64
- `code-server --version`: 3.4.0

**Comment by opoloko** [comment] 2020-05-28 22:25
yeah same problem, also extensions (at least some) are installed but not working, as reported also in https://github.com/cdr/code-server/issues/1742

**Comment by nhooyr** [comment] 2020-06-04 08:50
Duplicate of https://github.com/cdr/code-server/issues/1742

**Closed by nhooyr** 2020-06-04 08:50 UTC
