### ISSUE TITLE
[V2] Documentation - Breaking change for Reverse proxy

### ISSUE THREAD

**Issue by NickBolles** [cdr/code-server#1089] opened 2019-10-22 17:49 UTC
- `code-server` version: v10.15.1
- OS Version: docker:latest
- VS Code Version: 
```
Version: 1.39.2
Commit: f133b00851c6c05aedaf78ff139443a46cd8d036
Date: 2019-10-21T22:06:51.355Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
```

## Description

I have a similar issue to #997 after upgrading to V2, but it's different enough to warrent a separate issue. 

I'm getting a 404, not found after upgrade for all web views (extension readme's, markdown preview etc.). But I don't think it's code-server's fault it's my reverse proxy config. I'm not sure the exact changes, but I think because I have some path matchers on my reverse proxy it's rejecting `/webview` paths as not found. because something obviously changed between v1 and v2, it should probably be documented.

**Comment by sr229** [comment] 2019-10-23 06:09
Duplicate of #997

**Closed by sr229** 2019-10-23 06:09 UTC
Labels: bug

**Comment by code-asher** [comment] 2019-10-23 19:23
This was my fault; I accidentally excluded the webview HTML from the final build. It should be fixed in the latest v2 Docker image.

**Comment by NickBolles** [comment] 2019-10-24 04:20
@code-asher confirmed! Thank you for all of the awesome work!!
