### ISSUE TITLE
Can I disable the terminal now

### ISSUE THREAD

**Issue by lsc196** [cdr/code-server#2498] opened 2020-12-21 07:20 UTC
Can I disable the terminal now? Or disable the terminal by modifying that file。

**Comment by oxy** [comment] 2020-12-21 15:10
Which file are you talking about? I'm not too sure.

**Comment by SPGoding** [comment] 2020-12-30 04:34
:eyes: #1937

**Comment by code-asher** [comment] 2021-01-04 21:09
Closing as a dupe of https://github.com/cdr/code-server/issues/1937.

**Closed by code-asher** 2021-01-04 21:09 UTC
Labels: feature
