### ISSUE TITLE
Offline installation

### ISSUE THREAD

**Issue by rwanito** [cdr/code-server#3562] opened 2021-06-07 19:54 UTC
Hi !

I'm searching for the simplest working solution to install extensions in offline environment.
I use this [VSCode downloader](https://sotnikov-link.github.io/get-vscode-extension-for-offline-install/) to download and install my extension from the marketplace.

But when I try to install in offline mode, I have :
```bash
# code-server --install-extension Téléchargements/jupyter.VSIXPackage
Installing extensions...
[2021-06-03T19:50:50.534Z] error vscode getaddrinfo EAI_AGAIN extensions.coder.com
[2021-06-03T19:50:50.534Z] error vscode Error: getaddrinfo EAI_AGAIN extensions.coder.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
```

I've also tried in online : 
```bash
Installing extensions...
[2021-06-03T19:54:46.793Z] error vscode Unexpected end of JSON input:

[2021-06-03T19:54:46.796Z] error vscode SyntaxError: Unexpected end of JSON input:

    at JSON.parse (<anonymous>)
    at D (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:24:74905)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async x.queryGallery (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:27:10711)
    at async x.query (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:27:9654)
    at async x.getExtensions (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:27:7344)
    at async /usr/lib/code-server/lib/vscode/out/vs/server/entry.js:19:670
    at async Promise.all (index 0)
    at async O.getGalleryExtensions (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:19:639)
    at async O.installExtensions (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:18:26265)
    at async /usr/lib/code-server/lib/vscode/out/vs/server/entry.js:36:90861
    at async M (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:36:94206)
    at async process.<anonymous> (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:36:103823)
```

The problem is maybe the way I downloaded extensions. 
Do I need to get extension only from open-vsx.org or not ?
Why code-server hits extensions.coder.com to install the package ?

Thanks for your work, it's very useful !

## OS/Web Information

- Web Browser: Edge/FF...
- Local OS: W10
- Remote OS: Debian
- Remote Architecture: amd64
- `code-server --version`: The latest

**Comment by jsjoeio** [comment] 2021-06-07 22:10
Hmm...I'm going to see if I can reproduce by following these steps:
1. Go to [an extension page](https://open-vsx.org/extension/pyxel/runic-theme) on Open VSX and download
2. Go offline (discount wifi)
3. Inside code-server, click "Install from VSIX"
4. Use extension

This is working as expected.

I also tested it using the code-server CLI like you show and it worked as expected.


https://user-images.githubusercontent.com/3806031/121093735-4cad7e80-c7a2-11eb-942f-0e3d4b60f8ee.mov



## Screenshot

https://user-images.githubusercontent.com/3806031/121093287-ac575a00-c7a1-11eb-8203-06d820e91e84.mov

I'm not familiar with the website/tool you show, but you'll want to make sure you're installing a `.vsix` file. Maybe it's different on Windows? But I would check there.

Since this is working as expected, I'm going to close this. Feel free to follow up with comments if you need more help though!

**Closed by jsjoeio** 2021-06-07 22:10 UTC

**Comment by rwanito** [comment] 2021-06-08 06:25
Thanks for your reply !
Can you try with python and jupyter ?

In fact, I must to download python and jupyter in the windows market place because open-vsx.org shows an outdated version of python.

It's true that the website I've put on my first post, I download .VSIXPackage not .vsix. Maybe the format is different ? 
Today, I'll try to continue to install python properly !

**Comment by jsjoeio** [comment] 2021-06-08 16:56
I tried with Python from open-vsx and it appears to be working as well!

https://user-images.githubusercontent.com/3806031/121226750-c21b5c80-c83f-11eb-91be-e9542adca761.mov


> Maybe the format is different ?

Definitely could be, I'm not sure. 

Good luck!
