### ISSUE TITLE
It seems to be not working with java extension pack on 3.3.0

### ISSUE THREAD

**Issue by ikisis** [cdr/code-server#1660] opened 2020-05-18 07:44 UTC
I tried setting up with new version 3.3.0 by docker today.

but java extension pack is not working. 

there's no code assist, no junit test launcher(also main class run)

I've got this message when i tried to run junit test
------------------------------------------------------
ENOENT: no such file or directory, mkdir '/home/coder/.local/share/code-server/User/globalStorage/redhat.java'

-----------------------------------------------------

could i get some information why it's not working after 3.3.0?

my docker execution script is

docker run -it -d -p 80:8080 \
-v "/home/ikisis/dev/projects:/home/coder/project" \
-v "/usr/lib/jvm/java-8-openjdk-amd64:/home/coder/java-8-openjdk" \
-u "$(id -u):$(id -g)" \
-e "PASSWORD=mypassword" \
--name vscode \
codercom/code-server:latest \

**Comment by nhooyr** [comment] 2020-05-18 17:22
Are you running `junit test` on the CLI?

**Comment by ikisis** [comment] 2020-05-19 01:34
No. I used vscode's "Run and Debug". At the previous version I used(maybe 3.2.0), it works. but not at 3.3.0

**Comment by nhooyr** [comment] 2020-06-03 19:34
Looks like it might be related to #1693

**Comment by ikisis** [comment] 2020-06-04 02:19
ah, I see. so I could try to make globalSetting directory, and re-setup java extension if I wanna use java right now.

**Comment by nhooyr** [comment] 2020-06-04 08:57
It's possible yes, not 100% sure.

If it does work, please lmk so I can close as a duplicate of #1693

**Comment by ikisis** [comment] 2020-06-05 02:09
yea. It's working for me. everything is ok. and I will wait fixing for #1693 also at next version.
you can close this I think. thanks. code-server is very useful for me when I'm with my ipad only.

**Comment by nhooyr** [comment] 2020-06-05 02:16
Awesome.

The new release is already out!

https://github.com/cdr/code-server/releases/tag/v3.4.1

**Closed by nhooyr** 2020-06-05 02:16 UTC
Labels: waiting-for-info
