### ISSUE TITLE
"Insufficient permission" error on save

### ISSUE THREAD

**Issue by yusukeoshiro** [cdr/code-server#454] opened 2019-04-07 05:31 UTC
- `code-server` version: 1.621
- OS Version: Ubuntu 18.04.2 LTS (on GCP)

## Description

Files cannot be saved nor folders cannot be created from the editor. 
This problem only started to occur on the latest release. (I think)

## Steps to Reproduce

1. Start the server with `docker run -it -p 127.0.0.1:8443:8443 -v "${PWD}:/home/coder/project" codercom/code-server:1.621 --allow-http --no-auth`
1. Open the editor on another page and try to make change to any file or folder. You will get this error `Failed to save 'README.md': Insufficient permissions. Select 'Retry as Sudo' to retry as superuser.`.

![image](https://user-images.githubusercontent.com/11641437/55679156-609a9300-5941-11e9-841a-faefa887d236.png)

**Comment by evemorgen** [comment] 2019-04-08 11:03
Setting wider access settings on those files/directories worked for me - from `664` to `666`. 
I believe it's due to trying to edit files by user 'docker' or something similar (since we're operating from inside of the container) and it is not issue with code-server itself.

**Comment by michaelgao8** [comment] 2019-04-08 17:45
Reverting back to the `1.604-vsc1.32.0` Dockerfile resolves the issue for me, which means it was potentially introduced in the new release.

**Comment by coadler** [comment] 2019-04-08 17:55
Yeah, we recently changed the dockerfile to run as a regular user rather than root, so any previous files created as root will have to fixed. You should be able to just `chown -R` the projects folder to the user inside the docker container

**Comment by sr229** [comment] 2019-04-08 23:54
@yusukeoshiro due to recent changes I proposed that are merged, you will need to fix the permissions. Your files are owned by root so you need to recursively own all files to the user.

**Comment by DavisAre** [comment] 2019-04-15 10:49
> Your files are owned by root so you need to recursively own all files to the user.

To which user? What user/group is the coder-server running?

**Comment by DavisAre** [comment] 2019-04-15 11:03
Ok, I circumvented this by passing `-u` variables and running as current user. In my case - root. You can also specify other user's/group's IDs like `-u 1000:1000`
`docker run -it -p 127.0.0.1:8443:8443 -u $(id -u):$(id -g) -v "${PWD}:/home/coder/project" codercom/code-server:1.621 --allow-http` 

Might not be the best approach but may be helpful for someone.

**Comment by sr229** [comment] 2019-04-15 12:30
@DavisAre that’s redundant. UID/GID is already 1000 when you exec the container

**Comment by cstoneham** [comment] 2019-04-19 01:36
I think @DavisAre's solution seems like the best path forward here, typically when I've needed to edit files from inside a container this has been the recommended approach. The alternative seems to be changing host file permissions which isn't great...

I will note though that in my case when I try to run it with a forwarded user I get:
```
ERROR { Error: EACCES: permission denied, mkdir '/.cache'
  [stack]: 'Error: EACCES: permission denied, mkdir \'/.cache\'',
  [message]: 'EACCES: permission denied, mkdir \'/.cache\'',
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/.cache' }
free(): invalid pointer
```

**Comment by jmiller-to** [comment] 2019-06-16 15:26
@cstoneham I'm dealing with the same situation. How do you deal with the errors you get with a forwarded user?

**Comment by sr229** [comment] 2019-06-17 15:22
I already logged a fix but its stuck at pending for god knows how long.

#679

**Comment by acondura** [comment] 2019-06-23 12:09
I have the same permission issue described in the top screenshot and my set up is as follows.

I use a host user with IDs 1007:1007 which launches a coder container through docker compose. When I bash into the coder container, the coder user has 1000:1000 IDs and the /home/coder/project dir is owned by 1007:1007 thus, anything I change in the Coder UI is halted by the permission issue error in the top description.

I tried to 'usermod -u 1007 coder' and 'groupmod -g 1007 coder' and then set ownership of /home/coder to 1007:1007 but then the Coder UI is blank and the coder container logs say:

coder_1  | INFO  WebSocket opened / {"client":4,"ip":"[IP_REMOVED_BY_ME]"}
coder_1  | (node:6) UnhandledPromiseRejectionWarning: SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
coder_1  |     at Object.userInfo (os.js:249:11)
coder_1  |     at new t.Server (/src/packages/server/out/cli.js:340:122627)
coder_1  |     at e.exports.k.on (/src/packages/server/out/cli.js:340:118974)
coder_1  |     at e.exports.emit (events.js:194:15)
coder_1  |     at handleUpgrade.t (/src/packages/server/out/cli.js:504:29992)
coder_1  |     at e.exports.completeUpgrade (/src/packages/server/out/cli.js:504:32439)
coder_1  |     at e.exports.handleUpgrade (/src/packages/server/out/cli.js:504:31556)
coder_1  |     at upgrade (/src/packages/server/out/cli.js:504:29963)
coder_1  |     at u.emit (events.js:189:13)
coder_1  |     at onParserExecuteCommon (_http_server.js:552:14)
coder_1  |     at onParserExecute (_http_server.js:500:3)
coder_1  | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

Any hints here would be greatly appreciated!

**Comment by kasperschnack** [comment] 2019-07-04 08:38
@acondura 
1. Instantiate your code server e.g.: `docker run -d -p 127.0.0.1:8443:8443 -v "${PWD}:/home/coder/project" codercom/code-server --allow-http --disable-telemetry --no-auth` 
2. Attach to the running container `docker exec -it <container_name> /bin/bash`
3. Give write permission to any user `sudo chmod o+w -R .` (this is a bad idea, but it works  ¯\_(ツ)_/¯)
now you should be able to edit files

**Comment by acondura** [comment] 2019-07-04 09:54
I already have it as o+w, the trouble is every time I update a file through VS and try to save, it still says 'insufficient permission' because it changes the UID of the dir to 1007, the local user.

I've currently forked the coder github repo and I'm building an image of my own in order to fix the permission denied because I need it to work for 2 of my customers.

**Comment by nhooyr** [comment] 2019-08-19 14:28
The problem is the default user inside the container has UID 1000 but outside you've got 1007 @acondura, you just need to `chown -R 1000:1000 myfolder` to get it to work.

This needs to be a documented limitation of using a non root docker container.

TBH I'm thinking we just switch back to root as this is very confusing I'm sure and there is no real good workaround.

**Comment by nhooyr** [comment] 2019-08-19 14:30
There is https://github.com/cdr/code-server/pull/640/files but iirc we tried that and `fixuid` slows down the container startup.

**Comment by acondura** [comment] 2019-08-19 16:07
I've created an image of my own which uses the coder binary + fixuid and it is working great! I combine that with docker compose commands and I'm able to spin up lots of coder instances for myself and colleagues. Image at https://hub.docker.com/r/acondura/code-server.

**Comment by Leopere** [comment] 2019-10-05 17:33
```YAML
services:
  visual:
    image: codercom/code-server:latest
    restart: always
    user: "0:0"
```

**Comment by nhooyr** [comment] 2020-01-28 20:40
I'll fix in https://github.com/cdr/code-server/issues/1307

**Closed by nhooyr** 2020-01-28 20:40 UTC
Labels: docs
