### ISSUE TITLE
startup script

### ISSUE THREAD

**Issue by antofthy** [cdr/code-server#753] opened 2019-06-06 05:17 UTC
The following is a script I wrote to start code-server in the background,
or if already running, to report the current password needed to connect to it.
With options to KILL or WATCH and KILL  the code-server on shell exit.

Ideas and suggestions are welcome...

[start-code-server](https://github.com/cdr/code-server/files/3260097/start-code-server.txt)

**Comment by fbartels** [comment] 2019-06-06 06:09
Hi @antofthy,

small initial suggestion, maybe you could put your script in a [Gist](https://gist.github.com/) instead of attaching it as a file to this issue.

**Comment by sr229** [comment] 2019-06-06 13:13
Also my suggestion:

- I don't think there's a necessity for this, especially for Linux systems, init systems serves as service managers and serves the same purpose as well. You just need to register code-server as a service, making the script pointless.

- your script is just needlessly wrapping  what code-server can already do. Making it even more pointless. I say we just put this into upstream instead of abstracting it further.

**Comment by antofthy** [comment] 2019-06-07 04:58
The reason for this is that code-server is being run by students in a docker environment (one per user), as necessary. The password information was being output with a lot of other information that is not really useful to the user.  It also continuously logs to std-out other unwanted information, making it very horrible to simply run in background.

Even if we start code-server automatically as a service (which we did not want), the student still needs to be able to get the password they will be using.  So even then, a script to report that password easily was needed.

And finally localhost was not the correct URL for the student to put into their browser! 

@fbartels  Thanks for the tip about Gist didn't know about it.

**Comment by deansheather** [comment] 2019-06-07 06:49
If you're looking to run code-server for many students at once, I'd recommend generating a random password yourself and then passing it as an environment variable to code-server. Then the password would be consistent between runs. If you also kept the hostname/port details the same for each student, then you could just email the student their details one-time or something instead of them having to get a new password each time.

**Comment by sr229** [comment] 2019-06-07 15:34
That's what I exactly thought as well @deansheather, I also recommend using VMs if your systems are designed to be type 1 hypervisors for your students.

**Comment by Josh-Uvi** [comment] 2019-06-08 22:59
> If you're looking to run code-server for many students at once, I'd recommend generating a random password yourself and then passing it as an environment variable to code-server. Then the password would be consistent between runs. If you also kept the hostname/port details the same for each student, then you could just email the student their details one-time or something instead of them having to get a new password each time.

@deansheather @sr229 
please I need help to setup a Custom Systemd Service for code-server on Ubuntu 18.0.4
Here is my code 
[Unit]
Description=Code Server AutoStart
After=http://network.target 

[Service]
Type=simple
User=$USER
WorkingDirectory=/path/to/start/your/working/directory/inside/vscode
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
Restart=on-failure

ExecStart=/path/to/codeserver/binary --allow-http --password=xxxxxxx cert=/path/fullchain.pem cert-key=/path/fullchain.pem

[Install]
WantedBy=http://multi-user.target

But it doesn't work with the password. How can I improve this code to make it work? Also, I would like to add my letsencrypt certificate to secure it. Thanks

**Comment by deansheather** [comment] 2019-06-09 03:45
@Josh-Uvi please open a new issue as this is unrelated.

**Comment by antofthy** [comment] 2019-06-10 02:44
@Josh-Uvi thank you for the systemd service file.
Though we prefer students to start code-server when they want it, with a random password.
Better security, and no need to do though the creation and distribution of a FIXED password.

**Comment by Merith-TK** [comment] 2019-06-11 19:28
@Josh-Uvi I have my service file free to download at https://merith.tk/vscode.service

just tweak it to your needs and you should do well
this will start a code-server instance on port 8443 without a password, as user `vscode` with rw perms only on `/opt/code-server/` and `/home/vscode` as i didnt know how to change home directories on users at the time

**Comment by arvati** [comment] 2019-06-14 19:03
I used [this script](https://gist.github.com/arvati/b5170a6c6048b0ea55e77f52cde2b396) to start on alpine linux machine.
I liked the idea of showing address and password when you run "service status" and will improve my gist soon.

**Comment by antofthy** [comment] 2019-07-25 11:46
The start-code-server script is now used to start code-server in a php:7.3-apache container, extracting and reporting the random password it generates to the "docker service logs" for that container.   The Container control program pick up the password from there to pass on to the containers owner as needed.

**Comment by nhooyr** [comment] 2020-01-28 01:08
We're gonna take care of this soon. Duplicate of https://github.com/cdr/code-server/issues/164

**Closed by nhooyr** 2020-01-28 01:08 UTC
Labels: enhancement
