### ISSUE TITLE
python debug is not working in codeserver2

### ISSUE THREAD

**Issue by davezhouwa** [cdr/code-server#1120] opened 2019-10-28 08:28 UTC
- `code-server` version: 2.1650-vsc1.39.2
- OS Version: Ubuntu 16.04
- Extension:  Python ms-python.python 2019.9.34911
## Description
Python debug UI not working, cannot add configuration
## Steps to Reproduce
1. set a breakpoint in a py file
2. click the Debug tab
3. click add configuration
4. No configuration json file created.  
5. Click Start Debug, nothing happen

![image](https://user-images.githubusercontent.com/25450218/67663079-ef90ec00-f921-11e9-8297-0e5318502c8a.png)

**Comment by sr229** [comment] 2019-10-28 13:14
Duplicate of #276

**Closed by sr229** 2019-10-28 13:14 UTC

**Comment by davezhouwa** [comment] 2019-10-28 15:20
@sr229, how come is this closed so soon? did you ever compare the errors with #276

**Comment by sr229** [comment] 2019-10-28 15:27
It seems related, and it seems that its a extension issue as well based on the errors. Something we don't have in control.

**Comment by davezhouwa** [comment] 2019-10-28 21:44
The bug you linked to has been closed, but this issue is now on latest build.  It seems weird to have closed bug resolved on new build.

Are you saying the team can not do anything on  all extension related bugs?
