### ISSUE TITLE
Settings.json autosuggestion broken in v3.3.0

### ISSUE THREAD

**Issue by nathanrpage97** [cdr/code-server#1667] opened 2020-05-18 15:42 UTC
Code server autosuggestions for settings.json is broken in v3.3.0. It just provides an empty suggestion box:
![image](https://user-images.githubusercontent.com/33010515/82232391-9360da00-98fc-11ea-9dc4-67810546f337.png)

I'm not sure if it is settings.json specific or a schema level issue.

**Comment by biplobsd** [comment] 2020-05-18 16:28
why he's added extra `v` with version tag.. v3.3.0 ?

**Comment by kylecarbs** [comment] 2020-05-18 16:50
Looking into this now.

**Comment by biplobsd** [comment] 2020-05-18 16:54
> Looking into this now.
I think your maybe read release Breaking Changes point.. i found!

**Comment by nhooyr** [comment] 2020-05-18 17:18
@nathanrpage97 Are you using windows? If so this is a duplicate of https://github.com/cdr/code-server/issues/1659

**Comment by nathanrpage97** [comment] 2020-05-18 17:48
No, I'm running on a dockerized rpi4 w/ arm64 build. When I revert to v3.2.0 autosuggestion works fine:

![image](https://user-images.githubusercontent.com/33010515/82243786-2bb38a80-990e-11ea-970b-f1fc53dd408b.png)

**Comment by nhooyr** [comment] 2020-05-18 17:49
@nathanrpage97 Sorry, to clarify I meant if you're accessing from windows.

**Comment by nathanrpage97** [comment] 2020-05-18 17:50
Oh, no Im accessing from a mac.

**Comment by nhooyr** [comment] 2020-05-18 17:51
Thanks for the quick responses, just confirmed, seeing this issue as well.

Oddly if you remove the second quote, autocomplete shows up.

Not sure if this is a VS Code bug.

**Comment by nathanrpage97** [comment] 2020-05-18 17:56
Just to confirm you mean a non-empty list of autocomplete?

**Comment by nhooyr** [comment] 2020-05-18 17:57
Yup

<img width="823" alt="image" src="https://user-images.githubusercontent.com/10180857/82244611-7f72a380-990f-11ea-978c-e895bd801e9d.png">

**Comment by nathanrpage97** [comment] 2020-05-18 18:07
So I just checked, it works without quotes and with one quote but not with fully surrounding quotes. I don't see this issue in vscode 1.45.1 and it doesn't show up as a fix in that patch.

**Closed** 2020-05-18 22:09 UTC
Labels: bug

**Comment by sterlinm** [comment] 2020-07-14 14:38
I'm just checking in and really appreciate the project. It looks like code-server has been pinned to VS Code 1.45.1 since encountering this issue. Will future plans catch back up to VS Code (currently on 1.47.0 I believe)? Just curious. Thanks!

**Comment by nhooyr** [comment] 2020-07-14 16:52
@sterlinm See #1874 

Will tag a release some point soon.

**Comment by sterlinm** [comment] 2020-07-14 20:01
@nhooyr Thanks so much for the reply! Appreciate it.
