### ISSUE TITLE
No Permissions running in Docker

### ISSUE THREAD

**Issue by SlateDave** [cdr/code-server#673] opened 2019-05-10 21:52 UTC
- `code-server` version: Latest from Docker (codercom/code-server)
- OS Version: Ubuntu 18.04

## Description

When I create any file through the web, I get the error `Permission denied writing to file (file:///home/coder/project/test.txt)`

I've also tried appending `:z` to the Volume and even tried using the unsafe paramenter `--privileged`

## Steps to Reproduce

1. Run `docker run --name Coder -it -p 8008:8443 -v ${PWD}:/home/coder/project codercom/code-server --allow-http --no-auth`

2. Go to 127.0.0.1:8008

3. Create a file

**Comment by sr229** [comment] 2019-05-12 14:06
@SlateDave I already slated a fix for this, because said mountable path seems to not allow writes, but @nhooyr didn't like the mode change, so this bug persisted.

**Comment by liuyanhang** [comment] 2019-05-13 07:21
use `--user root`

**Comment by sr229** [comment] 2019-05-13 10:23
@liuyanhang that is not recommended. I'm working on a fix right now

**Comment by liguobao** [comment] 2019-06-20 08:41
@liuyanhang --user root is docker command

**Comment by nhooyr** [comment] 2019-08-19 14:23
@sr229 There is no indication that the cause of the issue seen by @SlateDave is the same as the one you are fixing in #679 

@SlateDave What are the permissions on the mounted in folder and what user are you inside the container?

**Comment by nhooyr** [comment] 2020-01-28 21:14
Duplicate of https://github.com/cdr/code-server/issues/1307

**Closed by nhooyr** 2020-01-28 21:14 UTC
Labels: bug, waiting-for-info
