### ISSUE TITLE
Fix CI release step for linux-arm64

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#2480] opened 2020-12-17 19:32 UTC
As discussed briefly with @code-asher, we'd like to make some improvements to the CI workflow, specifically in the release step for `linux-arm64`. 

## Problem
The ci / linux-arm64 workflow is failing at the “Run ./ci/steps/release-packages.sh build step.

## Reason
The machine has no space left.

## Potential Solutions
- doing a shallow clone with the repo in the checkout step
- delete the asset we download (if it build successfully)
- deleting the `node_modules` directory on machine

## Relevant
- [GitHub Actions failing with no space left on device](https://github.community/t/github-actions-failing-with-errno-28-no-space-left-on-device/18164/7)
- #2476

**Comment by code-asher** [comment] 2020-12-18 19:59
We worked out this was caused by an accumulation of Docker images which was resolved by deleting them. Will need some kind of cleanup or a way to prevent this accumulation.

**Comment by jsjoeio** [comment] 2021-02-26 16:55
> last time i think i just added a docker rm $(docker ps -aq) to ci and ran that once then removed it lol
> and a docker rmi $(docker images -q) as well i think

From Asher.

**Comment by vapurrmaid** [comment] 2021-03-02 18:59
Fixed in d48a74c317f59d4a467ba004dcbe38abfefbf73f

**Closed by vapurrmaid** 2021-03-02 18:59 UTC
Labels: enhancement
