### ISSUE TITLE
ESLint extensions not work in code-server

### ISSUE THREAD

**Issue by l1shu** [cdr/code-server#4435] opened 2021-11-03 12:22 UTC
## OS/Web Information

- Web Browser: Chrome 95.0.4638.54
- Local OS: Mac10.15.7 
- Remote OS: Linux version 5.4.119-1-tlinux4-0005 (root@VM_197_173_centos) (gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)) 
- `code-server --version`: latest

## Expected
the code has eslint tips

## Actual
the code has no tips,  but it is wrong to run the command line

## Screenshot
![image](https://user-images.githubusercontent.com/48285873/140058773-6cd2289b-9dbd-42d8-a6ee-bf46cf1debc3.png)

![image](https://user-images.githubusercontent.com/48285873/140058867-9689a22a-23ce-401b-815e-109b4558b356.png)

## Notes
has tips in local vscode

eslint is enable 
![image](https://user-images.githubusercontent.com/48285873/140059298-53d05b60-67b1-49c5-af33-cf00e75aa565.png)

![image](https://user-images.githubusercontent.com/48285873/140059321-b7497407-7d7f-4918-a8a3-3ca805f331c5.png)

**Comment by l1shu** [comment] 2021-11-03 17:00
eslint 7 is working, but eslint8 not work!!

**Comment by jsjoeio** [comment] 2021-11-03 17:48
Hmm...can you please add repro steps? Then I'm happy to test locally

**Comment by AriPerkkio** [comment] 2021-11-11 15:58
The version of `dbaeumer.vscode-eslint` is too low. We'll need at least `2.1.25` in order to run `eslint@8`. The support was added by https://github.com/microsoft/vscode-eslint/pull/1317.
Latest version of this plugin available in code-server's extensions is `2.1.10`.

@jsjoeio is it possible to get latest version of this plugin into code-server?
 
https://github.com/microsoft/vscode-eslint/commits/release/2.1.25

**Comment by jsjoeio** [comment] 2021-11-12 17:17
@AriPerkkio we are no longer manually updating extensions in our marketplace. Can you try downloading it from [Open VSX](https://open-vsx.org/extension/dbaeumer/vscode-eslint)? 

2.2.2 is available there so you should be good.

**Comment by AriPerkkio** [comment] 2021-11-13 11:25
When installing `dbaeumer.vscode-eslint-2.2.2.vsix` I'm seeing following error: 

```
Command 'Extensions: Install from VSIX...' resulted in an error (Unable to install extension 'dbaeumer.vscode-eslint' as it is not compatible with VS Code '1.60.0'.)
```

With latest version of `code-server`:

```
code-server: v3.12.0
VS Code: v1.60.0
Commit: b37ff28a0a582aee84a8f961755d0cb40a4081db
Date: 2021-09-16T20:08:09Z (1 mo ago)
Browser: Mozilla/5.0 (X11; CrOS x86_64 14150.74.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36
```

**Comment by jsjoeio** [comment] 2021-11-15 21:29
Hmm...that's very very strange. Based on their [package.json](https://github.com/microsoft/vscode-eslint/blob/release/2.1.10/package.json#L24-L26), it should be fine. How are you installing the extension?

**Comment by AriPerkkio** [comment] 2021-11-16 09:24
In VSCode I hit CTRL+SHIFT+P to run commands, and select `>Extensions: Install from VSIX..` from the list. Then select `/home/x/dbaeumer.vscode-eslint-2.2.2.vsix` from the list and press OK.
Is this the correct flow?

**Comment by jsjoeio** [comment] 2021-11-16 16:39
Yeah, that should be fine. Let me see if I can reproduce.

**Comment by jsjoeio** [comment] 2021-11-16 16:44
I'm getting the same error 🤔

```js
  ERR Unable to install extension 'dbaeumer.vscode-eslint' as it is not compatible with VS Code '1.60.0'.: Error: Unable to install extension 'dbaeumer.vscode-eslint' as it is not compatible with VS Code '1.60.0'.
    at A.install (/usr/local/Cellar/code-server/3.12.0/libexec/vendor/modules/code-oss-dev/out/vs/server/entry.js:42:51324)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

![image](https://user-images.githubusercontent.com/3806031/142027922-0ae86f07-1080-4d48-a31b-9b17e1ffeda5.png)

It should work so this is a bug.

**Comment by AriPerkkio** [comment] 2021-12-04 08:31
@jsjoeio I would be happy to help with this issue. However I'm quite unsure where to start debugging this. If you have any tips or pointers I would appreciate. 👍

**Comment by AriPerkkio** [comment] 2021-12-05 09:53
The `dbaeumer.vscode-eslint-2.2.2.vsix` requires VSCode `^1.61.0` which is higher than `code-server`'s `1.60.0`: https://github.com/microsoft/vscode-eslint/blob/release/2.2.2/package.json#L24-L26.

By manually changing the required version from the extension `.vsix` I was able to install it. However there was a runtime error describing invalid language server version or something.

It is still possible to run `dbaeumer.vscode-eslint-2.1.25.vsix` with latest `code-server`. This version is compatible with `eslint@8`. It can be downloaded from https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint by selecting the Version History tab. IDE is now successfully reporting linting errors. 🎉

**Comment by jsjoeio** [comment] 2021-12-06 17:32
> By manually changing the required version from the extension .vsix I was able to install it. 

Wow, nice work! I've had to do that before myself. 

> It is still possible to run dbaeumer.vscode-eslint-2.1.25.vsix with latest code-server

Awesome! 🙌

> The dbaeumer.vscode-eslint-2.2.2.vsix requires VSCode ^1.61.0 which is higher than code-server's 1.60.0

When v4 comes out, this should no longer be an issue.

Since there is a workaround and you've reported the IDE is reporting linting errors, is it okay if we close this?

**Comment by AriPerkkio** [comment] 2021-12-07 04:48
I think it's safe to close this issue now. 

@l1shu use `dbaeumer.vscode-eslint-2.1.25.vsix` from https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint with `eslint@^8.0.0`.

**Closed** 2021-12-07 19:40 UTC
Labels: bug, needs-investigation

**Comment by l1shu** [comment] 2021-12-13 07:51
> I think it's safe to close this issue now.
> 
> @l1shu use `dbaeumer.vscode-eslint-2.1.25.vsix` from https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint with `eslint@^8.0.0`.

@AriPerkkio  thats works for me, thx !!🎉
