### ISSUE TITLE
Python file is not running - Code-server: 3.10.1

### ISSUE THREAD

**Issue by RahulML2505GitHub** [cdr/code-server#3425] opened 2021-05-20 04:54 UTC
## OS/Web Information

- Web Browser: Edge
- Local OS: Linux - Ubuntu 20.04 LTS
- Remote OS: Ubuntu 20.04 LTS
- Remote Architecture: VM
- `code-server --version`: 3.10.1 421237f499079cf88d68c02163b70e2b476bbb0d Latest

## Steps to Reproduce

1. Run a python file in terminal

## Expected

It should run my python file.

## Actual

- The terminal is not opening!
- Throwing two errors:
  - command : `'python.execlnTerminal'` not found
  - command : `'python.execlnTerminal-icon'` not found

## Logs

[backend.log](https://github.com/cdr/code-server/files/6513351/newfile.txt)

## Screenshot

![Screenshot_2021-05-20-09-55-38-390_com microsoft emmx](https://user-images.githubusercontent.com/80871183/118921147-4b342780-b955-11eb-99a4-a32e52b35254.png)

## Notes

This issue can be reproduced in VS Code: Yes

**Comment by code-asher** [comment] 2021-05-20 17:42
It's possible this is because our Python extension is broken. Uninstalling Python and Jupyter and installing Python from Open VSX might fix the issue (the Python extension on Open VSX is bundled with Jupyter).

See https://github.com/cdr/code-server/issues/3364#issuecomment-840513845

**Comment by KingXyr18** [comment] 2021-05-22 02:21
I have exactly the same issue as you. But I figured it out that it was simply a bug of ms-python extension. Just choose an old version and hopefully the problem will be solved.

**Comment by jsjoeio** [comment] 2021-05-24 16:48
Interesting...I could not reproduce this issue locally. I'm using the Python extension v2021.5.842923320 with code-server 3.10.1 on macOS + Chrome.

## Screenshot


https://user-images.githubusercontent.com/3806031/119380134-2b627380-bc75-11eb-9a51-8ef96213b92b.mov

**Comment by ericct** [comment] 2021-05-27 20:00
I have exactly the same issue, with 3.10.1 and 3.10.2. It's not just for Python execution, but also when I try to select the interpreter, I have this error:
```
Command 'Python: Select Interpreter' resulted in an error (command 'python.setInterpreter' not found)
```

**Comment by Sangwidge** [comment] 2021-05-28 23:05
> 
> 
> Interesting...I could not reproduce this issue locally. I'm using the Python extension v2021.5.842923320 with code-server 3.10.1 on macOS + Chrome.
> ## Screenshot
> Screen.Recording.2021-05-24.at.9.47.10.AM.mov

I have this same issue, appears to only be an issue when clicking the play button in the top right, if I type out my command as you did then it runs as expected. 

I am a total novice so cannot speculate as to why this issue is arising, I am only using the platform currently as a learning tool.

**Comment by marcel-hamer** [comment] 2021-05-29 11:46
I had the same issue after upgrading to 3.10.2. For met it turned out to be the version of Jupyter v2021.5.0 not working correctly.

After reverting to v2021.3.0 everything started working fine again. Maybe it is worth a try.

**Comment by oxy** [comment] 2021-06-01 15:39
Heads up - I'm looking at Jupyter again and will try to land a fix soon, depending on how complex the bug is.

**Comment by ericct** [comment] 2021-06-01 17:04
Workaround reported by @marcel-hamer does not work for me (but using 3.10.0, see below):
- with versions 3.10.1 and 3.10.2 I can no longer select the Python interpreter;
- then, with version 3.10.0, reverting to Jupyter v2021.3.0 has no impact

Actually, the problem is hard to bisect (for me). I've came across a working solution with 3.10.2, but after an un-recorded upgrade path... When trying to remove everything, including user .local settings and install from scratch, I cannot get any combination of code-server and Python/Jupyter extensions that works.

**Comment by oxy** [comment] 2021-06-02 14:40
Hey there, I've pushed new versions of the extensions, can you please install `ms-python.python 2021.5.842923320` and `ms-toolsai.jupyter 2021.6.832593372` and report back?

PS: there appears to be an upstream bug that causes autocomplete to break (without Pylance, which we are not allowed to ship) with the LSP set to Default, so please change the language server to `Jedi` in the Python extension settings.

**Comment by oxy** [comment] 2021-06-02 14:42
@ericct it's possible you were running into a similar bug to the one I ran into while diagnosing this - with the language server set to default, closing and reopening made autocomplete no longer work correctly.

Can you update both extensions, set the LSP to Jedi, and try again?

**Comment by marcel-hamer** [comment] 2021-06-02 17:41
> Hey there, I've pushed new versions of the extensions, can you please install ms-python.python 2021.5.842923320 and ms-toolsai.jupyter 2021.6.832593372 and report back?

For me this fixed the issue.

**Comment by ericct** [comment] 2021-06-02 18:47
> @ericct it's possible you were running into a similar bug to the one I ran into while diagnosing this - with the language server set to default, closing and reopening made autocomplete no longer work correctly.
> 
> Can you update both extensions, set the LSP to Jedi, and try again?

I've just updated the extensions with the versions mentioned and set LSP to Jedi: With interactive code or notebook, the Python environment starts correctly and I can run "Python: Select interpreter".

But then with interactive code and notebook, any cell with output will fail (Chunk load error / timeout behavior)

**Comment by ericct** [comment] 2021-06-02 18:56
But everything seems to be OK so far with v3.10.2 👍

**Comment by rwanito** [comment] 2021-06-03 08:33
Hi !

Is it possible to download ms-python.python 2021.5.842923320 and ms-toolsai.jupyter 2021.6.832593372 offline ?
I've triied to download these extensions but I get an error : cannot access extensions.coder.com because I'm in offline env.

Is where I've downloaded : https://sotnikov-link.github.io/get-vscode-extension-for-offline-install/

Is exists a simple way to download last working extensions for last code-server ?

Thanks !

**Comment by jsjoeio** [comment] 2021-06-03 17:07
We have some docs about installing extensions manually [here](https://github.com/cdr/code-server/blob/main/docs/FAQ.md#installing-an-extension-manually) but you do need to be online to download them. Once they're downloaded though, you should be fine. 

> Is exists a simple way to download last working extensions for last code-server

The latest version of code-server should work with the Python extension (just downloaded now). But the marketplace and code-server are decoupled meaning you can downgrade code-server but the marketplace will download the latest version of the extension. There is an option to download older versions of the extension but if you downgrade code-server, you'll have to test previous versions to see what works.

![image](https://user-images.githubusercontent.com/3806031/120684301-63c33800-c453-11eb-9e49-107fce576754.png)

**Comment by rwanito** [comment] 2021-06-03 19:18
Thanks for your reply !
How can I export the .vsix file ?
I need this to transfert the file to my offline env.

**Comment by jsjoeio** [comment] 2021-06-03 19:27
Hmm...I think when extensions are installed, the .vsix files are unpacked 🤔 So you'd have to download outside of code-server.

You could talk directly to the open-vsx API. Example:
```shell
curl 'https://open-vsx.org/api/foam/foam-vscode' | jq '.files.download' | xargs curl --compressed -L -o foam.vsix
```

And then you'd have the .vsix file and you could put it on a USB drive or something to transfer to your offline env.

**Comment by rwanito** [comment] 2021-06-03 19:38
Thanks!
In openvsx server, the python's version is 2020, is it possible to get the latest ?
(https://open-vsx.org/extension/ms-python/python)
Or maybe is not possible or 2020 is enough ?

It's difficult to manage an offline env ^^

**Comment by jsjoeio** [comment] 2021-06-03 19:43
Ah shoot...that's right. Hmm.. I am not sure how to get the latest 😅 cc @oxy or @code-asher - maybe they can help.

> It's difficult to manage an offline env ^^

I can imagine! Props to you lol

**Comment by oxy** [comment] 2021-06-03 19:46
Ah, right -

You first need to install `ms-toolsai.jupyter` *before* you install `ms-python.python` when you're installing offline.

What happens is that when you install Python, Jupyter is listed as a mandatory dependency, and by default VSCode will try and resolve that against the default gallery. But since the dependency isn't the other way around, installing Jupyter first and Python second should work!

**Comment by rwanito** [comment] 2021-06-03 19:52
Okay all rigthts !

I've triied this :
Downloaded here : https://sotnikov-link.github.io/get-vscode-extension-for-offline-install/
```bash
# code-server --install-extension Téléchargements/jupyter.VSIXPackage
Installing extensions...
[2021-06-03T19:50:50.534Z] error vscode getaddrinfo EAI_AGAIN extensions.coder.com
[2021-06-03T19:50:50.534Z] error vscode Error: getaddrinfo EAI_AGAIN extensions.coder.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
```

Why code-server hits coder.com ?

**Comment by oxy** [comment] 2021-06-07 15:26
@rwanito Could you create another issue for this actually? The current issue (the Python extension not working) was fixed, but installing extensions offline is a separate issue that we'd have to address.

**Closed by oxy** 2021-06-07 15:26 UTC
Labels: bug, extension, high-priority, waiting-for-info
