### ISSUE TITLE
Build on AWS EC2 doesn't work

### ISSUE THREAD

**Issue by pioneerlabs** [cdr/code-server#1095] opened 2019-10-23 23:45 UTC
- `code-server` version: latest
- OS Version:  
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
CloudProvider:AWS
Node:10.16.0

## Description

yarn run v1.19.1
$ yarn && yarn runner build 1.39.2 development
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
success Already up-to-date.
$ cd ./scripts && node --max-old-space-size=32384 -r ts-node/register ./build.ts build 1.39.2 development
[build] Not running inside VS Code
[build] rootPath is "/home/ubuntu/code-server"
[build] outPath is "/home/ubuntu/code-server"
[build] arch is "x86_64"
[build] target is "linux"
[build] vscodeVersion is "1.39.2"
[build] codeServerVersion is "development"
[build] Installing code-server dependencies...took 545ms
[build] Using existing VS Code clone
[build] Using existing VS Code node_modules
[build] Building default extensions...failed
Command failed: yarn gulp compile-extensions-build --max-old-space-size=32384
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'gulp-bom'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ubuntu/code-server/source/vscode-1.39.2-source/build/lib/compilation.js:10:13)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

## Steps to Reproduce

1. git clone
2. yarn build 1.39.2 development

**Comment by sr229** [comment] 2019-10-24 04:33
did you run` yarn` first before doing build steps?

**Comment by sr229** [comment] 2019-10-24 10:18
Duplicate of #1094

**Closed by sr229** 2019-10-24 10:18 UTC
Labels: bug
