### ISSUE TITLE
PlatformIO IDE extension does not work on code-server v3.12.0 from Docker Hub

### ISSUE THREAD

**Issue by narongk** [cdr/code-server#4544] opened 2021-11-23 08:56 UTC
## OS/Web Information

- Web Browser: Chrome
- Local OS: Ubuntu
- Remote OS:MacOS
- Remote Architecture:
- `code-server --version`:3.12.0

## Steps to Reproduce

1.Extension
2.install PlatformIO

## Expected

install completed

## Actual

PlatformIO: Can not find working Python 3.6+ Interpreter. Please install the latest Python 3 and restart VSCode

## Logs
console.ts:137 [Extension Host] /usr/bin/python Error: Error: The Python 3.6.9 (/usr/bin/python) interpreter is not compatible.
Reason: Could not find distutils module

	at /config/extensions/platformio.platformio-ide-2.3.4/node_modules/platformio-node-helpers/dist/index.js:1:769744
	at ChildProcess.a (/config/extensions/platformio.platformio-ide-2.3.4/node_modules/platformio-node-helpers/dist/index.js:1:771334)
	at ChildProcess.emit (events.js:400:28)
	at ChildProcess.emit (domain.js:475:12)
	at maybeClose (internal/child_process.js:1058:16)
	at Socket.<anonymous> (internal/child_process.js:443:11)
	at Socket.emit (events.js:400:28)
	at Socket.emit (domain.js:475:12)
	at Pipe.<anonymous> (net.js:686:12)
## Screenshot
<img width="1431" alt="Screen Shot 2564-11-23 at 15 53 26" src="https://user-images.githubusercontent.com/28731834/142995016-db5e5baa-2716-439e-9874-553567ad45a1.png">

**Comment by jsjoeio** [comment] 2021-11-23 17:46
Duplicate of https://github.com/cdr/code-server/issues/1448

**Closed by jsjoeio** 2021-11-23 17:46 UTC
