### ISSUE TITLE
Jupyter extension is broken in v3.7.1

### ISSUE THREAD

**Issue by cheulyop** [cdr/code-server#2330] opened 2020-11-18 08:56 UTC
EDIT: changed the title since what doesn't work is not only opening ipynb files but the entire Jupyter extension. Below is the original post.

---
I'm running code-server v3.7.1 inside Docker, and I cannot open Jupyter notebook files (.ipynb).

To be precise, I can open them, but they open as raw JSON files instead of in the notebook editor screen (see the attached screenshot).

![Screenshot from 2020-11-18 17-54-45](https://user-images.githubusercontent.com/36708385/99507818-376c3080-29c7-11eb-9044-5fdb5469b7aa.png)

Why might this be happening, and how could I fix this?

- Web Browser: Google Chrome Version 86.0.4240.198 (Official Build) (64-bit)
- Local OS: Ubuntu 18.04
- Remote OS: Ubuntu 18.04
- Remote Architecture: x86_64
- `code-server --version`: v3.7.1

**Comment by cheulyop** [comment] 2020-11-19 04:29
Plus, any jupyter-related command will not work with messages like this one:
```
Command 'Jupyter: Create New Blank Jupyter Notebook' resulted in an error (command 'jupyter.createnewnotebook' not found)
```

**Comment by bruwozniak** [comment] 2020-11-23 10:26
This is a duplicate of https://github.com/cdr/code-server/issues/2341 I think

**Comment by cheulyop** [comment] 2020-11-23 11:26
@bruwozniak yes, it seems they are related

**Comment by code-asher** [comment] 2020-11-23 17:20
I'll close as a duplicate of #2341, if resolving #2341 doesn't fix this we can re-open it then. :)

**Closed by code-asher** 2020-11-23 17:20 UTC
