### ISSUE TITLE
Got aarch64 binary from extension even if code-server runs on x86_64 machine

### ISSUE THREAD

**Issue by left4taco** [cdr/code-server#2724] opened 2021-02-13 14:12 UTC
- Web Browser: Chrome
- Local OS: MacOS BigSur
- Remote OS: Ubuntu 18.04
- Remote Architecture: x86_64
- `code-server --version`: 3.9.0 fc6d123da59a4e5a675ac8e080f66e032ba01a1b

I'm running code-server on a x86_64 machine, exposing the port and setup a SSL certificate. Everything works well regarding editing the code. However, after installing `ms-vscode.cpptools`, 1.2.0, I saw these errors when I open the webpage:

1. The C/C++ extension failed to install successfully. You will need to repair or reinstall the extension for C/C++ language features to function properly.
2. Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Launching server using command /home/<name>/.local/share/code-server/extensions/ms-vscode.cpptools-1.2.0/bin/cpptools failed.
3. Couldn't start client cpptools

What is more interesting is that, this file `~/.local/share/code-server/extensions/ms-vscode.cpptools-1.2.0/bin/cpptools` is actually built for **aarch64**!!

```
$ file ~/.local/share/code-server/extensions/ms-vscode.cpptools-1.2.0/bin/cpptools
/home/<name>/.local/share/code-server/extensions/ms-vscode.cpptools-1.2.0/bin/cpptools: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=8fba084eb8358497b78b28a3543e1821da36842c, with debug_info, not stripped
```

Does anyone see similar problem before? Is there a way to manually install extension so that I can get the correct architecture?

Thanks

**Comment by left4taco** [comment] 2021-02-13 14:18
After manually downloading the vsix file from the release page, everything back to normal. So there must be something is wrong when detecting the architecture of the platform.

https://github.com/Microsoft/vscode-cpptools/releases

**Comment by JammSpread** [comment] 2021-02-13 18:34
This is similar to #2120 where the same issue was found.

**Comment by code-asher** [comment] 2021-03-09 17:22
Closing as a duplicate of https://github.com/cdr/code-server/issues/2120.

**Closed by code-asher** 2021-03-09 17:22 UTC
