### ISSUE TITLE
Sync settings shows "loading..."

### ISSUE THREAD

**Issue by sindhus-in** [cdr/code-server#3905] opened 2021-08-05 14:28 UTC
## OS/Web Information

- Web Browser: Vivaldi 4.1
- Local OS: MacOS 
- Remote OS: MacOS
- Remote Architecture:
- `code-server --version`:

## Steps to Reproduce

Using Macbook Air M1
1. install the latest code-server from brew
2. open code-server on the default port in vivaldi 
3. click on "user" icon to login 

## Expected

Allow me to login to my microsoft account so vscode can sync my settings. 

## Actual

Shows "loading" like so...

<img width="1408" alt="Screenshot 2021-08-05 at 7 56 03 PM" src="https://user-images.githubusercontent.com/85542169/128367138-2aed41c3-f8f6-44be-a9f5-02e388b08859.png">

## Logs

I see the following in `/opt/homebrew/var/logs/code-server.log` file

```
[2021-08-05T14:13:31.522Z] error vscode is not running Error: vscode is not running
    at VscodeProvider.send (/opt/homebrew/Cellar/code-server/3.11.0/libexec/out/node/vscode.js:121:19)
    at VscodeProvider.sendWebsocket (/opt/homebrew/Cellar/code-server/3.11.0/libexec/out/node/vscode.js:117:14)
    at async /opt/homebrew/Cellar/code-server/3.11.0/libexec/out/node/routes/vscode.js:203:5
[2021-08-05T14:13:31.542Z] error vscode is not running Error: vscode is not running
    at VscodeProvider.send (/opt/homebrew/Cellar/code-server/3.11.0/libexec/out/node/vscode.js:121:19)
    at VscodeProvider.sendWebsocket (/opt/homebrew/Cellar/code-server/3.11.0/libexec/out/node/vscode.js:117:14)
    at async /opt/homebrew/Cellar/code-server/3.11.0/libexec/out/node/routes/vscode.js:203:5
```

## Screenshot

included above

## Notes

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment] 2021-08-05 19:03
Duplicate of #https://github.com/cdr/code-server/issues/3418 - please subscribe to that issue. Thanks!

**Closed** 2021-08-07 19:03 UTC
Labels: duplicate
