### ISSUE TITLE
command 'python.setInterpreter' not found

### ISSUE THREAD

**Issue by Mon-ius** [cdr/code-server#1897] opened 2020-07-21 21:06 UTC
Cannot work with lasteset version of vscode-python.

`Command 'Python: Select Interpreter' resulted in an error (command 'python.setInterpreter' not found)`

I am using `code-server 3.4.0 69ad52907e8ea109345831d29da5425cb2a55047` on the power9 HPC.

When installed `ms-python.python-2020.6.91350` or any `ms-python.python-2020.6.X`, the code-sever cannot work with it.

Only ms-python.python-2020.5.X can work with.

**Comment by mike-pt** [comment] 2020-07-22 16:27
Seeing the same here, the python console also doesn't show, and python is not listed for automatic debug config.

I just have the latest didn't try to go back to `ms-python.python-2020.5.X`

**Comment by EzzPrograms** [comment] 2020-07-28 05:24
This is actually a duplicate issue, please look at #1818 and #1837.

Installing a later version actually works and this is an extension issue, and not a code-server issue.

**Comment by code-asher** [comment] 2020-07-28 16:02
Closing as a duplicate of #1837.

**Closed by code-asher** 2020-07-28 16:02 UTC
