### ISSUE TITLE
Add environment variable with server URL

### ISSUE THREAD

**Issue by ribrdb** [cdr/code-server#1939] opened 2020-08-03 14:14 UTC
It would be really cool if code-server could put an env var into the terminals it starts that tells what url is being used to access the server.

In particular I want to use this in scripts that start servers, so I can print out http://localhost:8080 when running under normal vscode, but https://myserver.com/proxy/8080 when running under code server.

I'd also use this to configure the upstreamProxy setting of karma when running under code-server.

**Comment by code-asher** [comment] 2020-08-03 17:53
I think this is a duplicate of https://github.com/cdr/code-server/issues/1510 although with a different use case. We'll add an environment variable with a name like `CODE_SERVER_HTTP_REFERER`.

I'll close so we can track on the other issue but thanks for opening this since it gives additional perspective on the original issue!

**Closed by code-asher** 2020-08-03 17:53 UTC
Labels: feature
