### ISSUE TITLE
Couldn't open the code-server, just opening with a black window

### ISSUE THREAD

**Issue by JinGangRed** [cdr/code-server#290] opened 2019-03-19 09:09 UTC
Open the code-server in the browser, and it opening with a black window. There is nothing. I find the localStorage also has nothing.

## Description

I open the code-server in the browser, and it opening with a black window. There is nothing. I find the localStorage also has nothing. I have changed some browser, such as chrome and IE. It doesn't affect.

**Comment by EvgeniyMakhmudov** [comment] 2019-03-19 14:02
I found the similar situation. In log i find this

> ERROR SHARED stderr {"data":"Uncaught Exception:  Error: Unexpected end of JSON input\n\nSyntaxError: Unexpected end of JSON input\n    at JSON.parse (<anonymous>)\n    at pfs_1.readFile.then.contents (eval at exports.requireModule (/usr/local/bin/code-server:468:27625), <anonymous>:81639:45)\n    at <anonymous>\n    at Timeout.setTimeout [as _onTimeout] (eval at exports.requireModule (/usr/local/bin/code-server:468:27625), <anonymous>:56921:31)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)\n"}

In browser there is 404 on request http://host:8443/__webpack_hmr

Run on last available docker image

**Comment by kylecarbs** [comment] 2019-03-19 15:32
That error shouldn't matter. What version of chrome are you using @JinGangRed ?

**Comment by davefinster** [comment] 2019-03-19 16:38
I've struck this as well. From memory I've always seem the 404 on webpack_hmr, but I've noticed this in the JS console now:

```
 INFO  Loading IDE
webpack-internal:///./packages/logger/out/main.js:1  INFO  Starting socket [1/5]...
/__webpack_hmr:1 Failed to load resource: the server responded with a status of 404 ()
webpack-internal:///./packages/logger/out/main.js:1  INFO  Connected to socket
webpack-internal:///./packages/logger/out/main.js:1  INFO  Start workbench
webpack-internal:///./packages/logger/out/main.js:1  ERROR  Failed "Start workbench" duration=759ms
main.js?f92d:1 duration (i): iexpected: 1000ms: 1553012780091__proto__: Object
main.js?f92d:1 error (Error): Error: [UriError]: Scheme contains illegal characters.
    at _validateUri (uri.ts?336c:38)
    at _URI.URI (uri.ts?336c:175)
    at new _URI (uri.ts?336c:391)
    at Function.URI.revive (uri.ts?336c:367)
    at Object.reviveWorkspaceIdentifier (workspaces.ts?067d:38)
    at CodeRendererMain.reviveUris (main.ts?bd53:89)
    at CodeRendererMain.init (main.ts?bd53:70)
    at new CodeRendererMain (main.ts?bd53:61)
    at main (main.ts?bd53:331)
    at Workbench.eval (workbench.ts?f527:192)
webpack-internal:///./packages/logger/out/main.js:1  ERROR  [UriError]: Scheme contains illegal characters.
```

**Comment by JinGangRed** [comment] 2019-03-20 07:38
@kylecarbs The version of chrome is Version 70.0.3538.77

**Comment by JinGangRed** [comment] 2019-03-20 07:41
There is nothing in the Local Storage and session storage.

**Comment by lifubang** [comment] 2019-03-20 10:28
The same problem:  (version 1.32.0-310)
![3654e6cedee2a1819d80fd6db2ff99d](https://user-images.githubusercontent.com/783424/54677446-daf3a680-4b3d-11e9-96a8-88196fd3db35.png)

**Comment by kylecarbs** [comment] 2019-03-20 14:13
@JinGangRed could you try updating chrome? I'm not certain what API we'd be using that could cause the issue.

**Comment by JinGangRed** [comment] 2019-03-21 01:54
@kylecarbs Thanks for  your replay.
I can load it before on this version of chrome. Now I couldn't open it, not only opening on the chrome, but the Firefox on another machine. 
I think the container of mine is down. This issue has occur, when I created a workspace before. Then I remove the Local Storage and reopen it. It works. But this time, there are nothing in the Local Storage, I have tried clean it. But it doesn't work.
I think it will be better if we create a web admin UI to manage the container.

**Comment by mfmayer** [comment] 2019-03-21 06:05
Same happened to me after adding a folder to the workspace. Black screen after that, even if I restart code-server.

**Comment by hjalmarlucius** [comment] 2019-03-21 11:28
I have the same issue - occurs immediately once I load my usual workspace. This workspace contains three folders - initially with relative paths but it did not work if I changed it to absolute paths either.

**Comment by robsaunders** [comment] 2019-03-24 13:26
Also getting this black screen error; occurs on latest chrome, brave and safari, whenever I add a folder. This seems like a pretty critical bug to me.

**Comment by Boggin** [comment] 2019-03-25 10:01
I get this when in an office where the firewall blocks websockets. 

It's pretty clear from the console that this is the issue in my case as it is retrying and failing to connect to the sockets. I have run separate scripts to demonstrate that the firewall is indeed blocking websockets.

That's not something that can be fixed so perhaps a getting started document could list some pre-requisites for the application.

**Comment by cybersorcerer** [comment] 2019-04-09 16:59
Same here, code-server is running on Ubuntu 18.04. When i connect from my macbook pro using either safari or chrome it works. On my ipad pro it just shows a black browser window after login. I tried safari, chrome and firefox neither works. I just downloaded the latest version and tested, same thing. If you need any kind of help, documentation of the problem let me know i will do my best to get it for you.

**Comment by nol166** [comment] 2019-04-09 17:53
There was an old bug that would show that error if you set a custom workspace. Try going into localstorage and delete the workspace property.

**Comment by JinGangRed** [comment] 2019-04-10 05:22
@nol166  yes. I have delete the workspace property once,and it works. **However, there were nothing in the localstorage now.**

**Comment by AALMA** [comment] 2019-06-17 01:21
Also experiencing this issue from iPad Pro

**Comment by deansheather** [comment] 2019-06-17 10:34
@AALMA Apparently only the new iPad OS works well with code-server. The current iOS either doesn't load code-server or lots of keyboard commands don't work correctly.

**Comment by stammy** [comment] 2019-06-20 18:02
Experiencing this myself on iPadOS Beta 2 in Safari. Just a blank/black screen. I don't run code-server with auth, but I do use an ngrok.io tunnel to provide my basic auth and https. Don't have any issues using ngrok on the same server for hosting other sites so don't think it's related to that?

I am hosting on AWS lightsail for what it's worth.

**Comment by rmchale** [comment] 2019-06-21 21:31
I am seeing the same black screen on iPadOS Beta 2 in Chome/Safari.  I have auth w/no tunnel.

**Comment by brotherko** [comment] 2019-07-01 21:49
> I am seeing the same black screen on iPadOS Beta 2 on iPad pro 1 1 in Chome/Safari. I have auth w/no tunnel.

Same issue. Btw I used to deploy on DO using docker and works perfectly

**Comment by deansheather** [comment] 2019-07-01 22:29
If you're using iPad and seeing a black screen with HTTP authentication through a reverse proxy (not code-server's built-in login screen), this is caused by a webkit bug. The browser won't send the HTTP password with the request to connect to the websocket.

**Comment by NGarate** [comment] 2019-07-02 19:19
I think this issue #89 is the same.
And it's not related code-server it's an old WebKit browser bug [Bug 80362](https://bugs.webkit.org/show_bug.cgi?id=80362)

**Comment by stammy** [comment] 2019-07-02 19:28
Just updated to iPadOS beta 3 - same issue

**Comment by deansheather** [comment] 2019-07-03 01:34
The OP was using Chrome, so I won't close this issue. If you're having issues with iPad/Safari, please discuss or :+1: in #89.

**Comment by rmchale** [comment] 2019-07-03 05:58
For iPad I fixed it with a cert from lets-encrypt.

**Comment by muammar** [comment] 2019-07-26 04:15
> For iPad I fixed it with a cert from lets-encrypt.

Would you mind publishing a post on how to do it?

**Comment by NGarate** [comment] 2019-07-26 13:17
> For iPad I fixed it with a cert from lets-encrypt.

Which version of iOS or iPadOS are you using?

**Comment by muammar** [comment] 2019-07-26 14:40
> > For iPad I fixed it with a cert from lets-encrypt.
> 
> Which version of iOS or iPadOS are you using?
> Are you using HTTP Basic access authentication?

Beta 13.0. I think this is the latest version as I installed it 3 days ago.

**Comment by noodlemind** [comment] 2019-08-23 02:07
I am having the same issue (blank black screen)  trying to access it from the iPad Browsers (Safari and Chrome).
When I try to access is from Windows Desktop (Chrome) it seems to work but doesn't load any of the icons (There was an error on my VPS that says favicon not found).

I was not able to follow the comments along probably. Does this have any fix ?

**Comment by andreeastrattner** [comment] 2019-08-30 12:05
I have the same issue - I can connect and it works great on mac - chrome but on ipad os 13.1 safari I get the following 500 error and a black screen.

![Screenshot 2019-08-30 at 2 04 03 PM](https://user-images.githubusercontent.com/8161141/64019349-32eff980-cb2f-11e9-887c-fe556248a3e9.png)

**Comment by Shadowist** [comment] 2019-09-01 20:58
Weird. I updated to the most recent build of iPad OS 13.1 and ran into the blank page issue on Safari and other App Store browsers (chrome, Firefox, etc). Linux desktop is a virtual machine inside a Synology NAS. I used the self-signed cert from the quick setup documentation.

I got around it by exporting my Let’s Encrypt cert and key from my Synology and slotted in directly to the code-server app (no need to convert formats or anything...pem direct) like another user did. Suddenly it worked.

**Comment by ccssmnn** [comment] 2019-09-25 10:24
> Weird. I updated to the most recent build of iPad OS 13.1 and ran into the blank page issue on Safari and other App Store browsers (chrome, Firefox, etc). Linux desktop is a virtual machine inside a Synology NAS. I used the self-signed cert from the quick setup documentation.
> 
> I got around it by exporting my Let’s Encrypt cert and key from my Synology and slotted in directly to the code-server app (no need to convert formats or anything...pem direct) like another user did. Suddenly it worked.

Stable non-beta version still has this issue. Could you publish a post describing how you solved it?

**Comment by nphase** [comment] 2019-10-15 16:04
Have the same issue on ipad pro 11". tried both chrome and safari

**Comment by sr229** [comment] 2019-10-15 16:09
Hey all, it seems that this has been outdated for a long time ago, and this seems to only affect v1 so I suggest to use v2. iPad users please upgrade your devices to iPadOS since it has been reported to have better compatibility with apps like code-server.

**Closed by sr229** 2019-10-15 16:09 UTC
Labels: bug, needs-investigation
