### ISSUE TITLE
Slim syntax highlighting not working

### ISSUE THREAD

**Issue by Gibbo3771** [cdr/code-server#1246] opened 2020-01-03 13:59 UTC
```
$ codeserver -v
info  2.1692-vsc1.39.2
info  e14362f3224c101585a26bf7ee5fa6e3bf425046
info  x64
```
```
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```

## Description

Pretty easy to reproduce. Slim template highlighting does not work, VSCode on my Mac seems to support it without an extension? There are extensions on the market, however they are not available for codeserver.

The `.slim` file extension is recognised.

Not sure if this a bug, or a config problem, or if I actually need a extension for Slim.

**Comment by nhooyr** [comment] 2020-01-27 06:49
@sr229 have you been able to reproduce this?

**Comment by sr229** [comment] 2020-01-27 13:20
Might be a network issue, I'm able to get syntax right off the bat.

**Comment by nhooyr** [comment] 2020-01-27 18:25
We're just missing the slim extension.

@sr229 how did you install the slim extension.

**Comment by sr229** [comment] 2020-01-27 18:26
I installed it via VISX and checked what's wrong, which how probably our OP has done.

**Comment by Gibbo3771** [comment] 2020-01-30 16:50
@nhooyr nice, guess it will come when it comes then.
@sr229 I didn't install any extension, VSCode is highlighting my slim templates out the box. Doesn't seem right. Phantom extension?

**Comment by nhooyr** [comment] 2020-01-30 17:35
@Gibbo3771 are you sure VS Code is highlighting them out of the box and you didn't install anything? I had to install the Slim extension locally.

**Comment by nhooyr** [comment] 2020-01-30 17:36
Duplicate of #1299

**Comment by nhooyr** [comment] 2020-01-30 17:36
If this is still a problem, please feel free to reopen.

**Closed by nhooyr** 2020-01-30 17:36 UTC
Labels: extension
