### ISSUE TITLE
ws always disconnect

### ISSUE THREAD

**Issue by itheimalitong** [cdr/code-server#2363] opened 2020-11-25 11:14 UTC
Git not  work ，  No source control providers

**Comment by itheimalitong** [comment] 2020-11-25 11:34
Always disconnect

**Comment by nhooyr** [comment] 2020-11-25 16:21
Can you add a screenshot of the problem?

**Comment by itheimalitong** [comment] 2020-11-26 02:10
> Can you add a screenshot of the problem

Repost using rinetd，

**Comment by itheimalitong** [comment] 2020-11-26 02:19
> Can you add a screenshot of the problem?

![Uploading image.png…]()

**Comment by itheimalitong** [comment] 2020-11-26 02:22
![image](https://user-images.githubusercontent.com/29686610/100300540-3479cd00-2fd1-11eb-8cbc-c8b61bf39194.png)

**Comment by itheimalitong** [comment] 2020-11-26 02:23
![image](https://user-images.githubusercontent.com/29686610/100300625-6a1eb600-2fd1-11eb-8560-49b6e229aaa1.png)


> > Can you add a screenshot of the problem
> 
> Repost using rinetd，

![image](https://user-images.githubusercontent.com/29686610/100300645-71de5a80-2fd1-11eb-8b2e-2b662ce3d36a.png)

**Comment by itheimalitong** [comment] 2020-11-26 10:04
> Can you add a screenshot of the problem?

Error received from starting extension host

**Comment by nhooyr** [comment] 2020-11-30 16:56
Closing as a duplicate of #2364

**Closed by nhooyr** 2020-11-30 16:56 UTC
