### ISSUE TITLE
Search in folder stopped working

### ISSUE THREAD

**Issue by elgandoz** [cdr/code-server#1127] opened 2019-10-30 05:19 UTC
- `code-server` version: 2.1662-vsc1.39.2
- OS Version: Centos/RHEL 7

## Description
Searching a string in files, in a non-ignored folder, doesn't return any result, regardless of settings or type.
It looks somehow a regression from https://github.com/cdr/code-server/issues/438.

Reverting to 2.1650-vsc1.39.2, using the exact same configuration, works as expected.
I also tried to remove the configuration (thus starting with a fresh one) to make sure the issue doesn't sit there, but I get the same behavior.

I didn't try on version 2.1655-vsc1.39.2 (yet).

## Steps to Reproduce

1. In the file explorer, right click on a folder > `Find in Folder...`
1. Type a string expected to be found and hit enter
1. The result is empty, even if you extend the search to all files

**Comment by elgandoz** [comment] 2019-10-30 23:18
Thanks for fixing it!

**Comment by roflcoopter** [comment] 2020-01-27 18:39
@code-asher This issue seems to be again present in the latest release.
reverting back to tag 2.1697-vsc1.39.2 makes Find in Folder work again.

**Comment by muhammadnscorp** [comment] 2020-02-19 15:50
@code-asher Find in Folder not working in 
Version: 1.41.1
Code Server Version: 2.1698-vsc1.41.1

**Comment by nhooyr** [comment] 2020-02-19 17:01
Is there an error?

**Comment by kylecarbs** [comment] 2020-02-19 17:38
It's working for me on `2.1698-vsc1.41.1`.

**Comment by muhammadnscorp** [comment] 2020-02-19 18:12
![image](https://user-images.githubusercontent.com/55802613/74862051-66ab1f80-5319-11ea-8328-39de0614799f.png)

**Comment by muhammadnscorp** [comment] 2020-02-19 20:15
Its working on HTTPS but not on HTTP. Dont know if that is an intended behavior, if that is then its working fine.

**Comment by kylecarbs** [comment] 2020-02-20 01:54
Did you remove `/tmp/code-server`?

**Comment by muhammadnscorp** [comment] 2020-02-20 14:20
I tried that and it's working now. thanks @kylecarbs

**Comment by roflcoopter** [comment] 2020-02-20 20:58
This does not work still. Find in folder only applies to files that are open in the editor.
I am on the latest build from docker. No error is being printed

**Comment by kylecarbs** [comment] 2020-02-21 04:02
@roflcoopter does `/tmp/code-server/rg` exist on your machine?

**Comment by roflcoopter** [comment] 2020-02-21 06:11
Yes it's there
```
root@67ec5bfc0290:/tmp/code-server# ls
rg
root@67ec5bfc0290:/tmp/code-server#
```

**Comment by kylecarbs** [comment] 2020-02-21 14:57
@roflcoopter is it executable? I'm not sure how you'd be unable to search in folders without an error appearing 🤔

**Comment by nhooyr** [comment] 2020-02-21 19:38
He also said it only works on open files which is interesting.

**Comment by roflcoopter** [comment] 2020-02-21 19:54
Yes it is executable. I have seen this issue mentioned in the vscode repo, I'm gonna try to setup a fresh install and see if that works.

**Comment by kylecarbs** [comment] 2020-02-21 22:21
That'd be great!

**Comment by roflcoopter** [comment] 2020-02-23 19:58
Got some time to test this out.
I created a new container based off of the official ```codercom/code-server:latest```, all default settings.
I created som files and tried to search, but the results only show up if i have the files opened in the editor still. This is what the trace log says, not sure if it helps.

```
[2020-02-23 19:48:25.217] [remoteagent] [trace] telemetry/searchResultsShown {"properties":{"options.wordSeparators":"`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?","scheme":"file","common.machineId":"redacted","sessionID":"redacted","commitHash":"f51e045cd5483561afc07694f39307fb673b6d1d","version":"2.1698-vsc1.41.1","common.platformVersion":"4.15.0","common.platform":"Linux","common.nodePlatform":"linux","common.nodeArch":"x64","common.product":"code-server","timestamp":"2020-02-23T19:48:25.217Z"},"measurements":{"count":0,"fileCount":0,"options.isRegExp":0,"options.isCaseSensitive":0,"options.isWordMatch":0,"duration":1,"searchOnTypeEnabled":1,"common.timesincesessionstart":145377,"common.sequence":68}}
[2020-02-23 19:48:25.239] [remoteagent] [trace] telemetry/searchResultsShown {"count":0,"fileCount":0,"options":{"isRegExp":false,"isCaseSensitive":false,"isWordMatch":false,"wordSeparators":"`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"},"duration":1,"scheme":"file","searchOnTypeEnabled":true}
[2020-02-23 19:48:25.240] [remoteagent] [trace] telemetry/searchResultsFinished {"properties":{"common.machineId":"redacted","sessionID":"redacted","commitHash":"f51e045cd5483561afc07694f39307fb673b6d1d","version":"2.1698-vsc1.41.1","common.platformVersion":"4.15.0","common.platform":"Linux","common.nodePlatform":"linux","common.nodeArch":"x64","common.product":"code-server","timestamp":"2020-02-23T19:48:25.239Z"},"measurements":{"duration":1,"common.timesincesessionstart":145399,"common.sequence":69}}
[2020-02-23 19:48:25.243] [remoteagent] [trace] telemetry/searchResultsFinished {"duration":1}
[2020-02-23 19:48:25.244] [remoteagent] [trace] telemetry/searchResultsFirstRender {"properties":{"common.machineId":"redacted","sessionID":"redacted","commitHash":"f51e045cd5483561afc07694f39307fb673b6d1d","version":"2.1698-vsc1.41.1","common.platformVersion":"4.15.0","common.platform":"Linux","common.nodePlatform":"linux","common.nodeArch":"x64","common.product":"code-server","timestamp":"2020-02-23T19:48:25.243Z"},"measurements":{"duration":1,"common.timesincesessionstart":145403,"common.sequence":70}}
[2020-02-23 19:48:25.246] [remoteagent] [trace] telemetry/searchResultsFirstRender {"duration":1}
```

**Comment by code-asher** [comment] 2020-03-05 18:02
I'm be curious if 3.0.0 fixes this. We have a `3.0.0` Docker tag if you have some time to check it out. I just ran it and was able to search without any issues (on both HTTP and HTTPS).

**Comment by roflcoopter** [comment] 2020-03-13 06:25
> I'm curious if 3.0.0 fixes this. We have a `3.0.0` Docker tag if you have some time to check it out. I just ran it and was able to search without any issues (on both HTTP and HTTPS).

Sorry for the late reply, but yes 3.0.0 seems to fix it! I Haven't move over to it just yet i just did a quick smoke test. You can close this for now and I'll report back if it doesnt work in the future

**Closed** 2020-03-13 15:12 UTC
Labels: bug
