### ISSUE TITLE
The deactivate() in the extension is never executed.

### ISSUE THREAD

**Issue by david9991** [cdr/code-server#2882] opened 2021-03-15 12:37 UTC
Every time I open the code-server or reload it from the browser, the activate() function in the extension is always executed. But no matter what I do, the deactivate() function will not be executed.
I need to do some clean-up work through deactivate(), how to implement it in my extension?

In my opinion, if the code-server keeps running in the background (extension host also keeps running in the background), should activate() be executed only once when the page is opened for the first time instead of every time the page is opened?

**Comment by code-asher** [comment] 2021-03-15 16:18
I think the reason for this is that VS Code kills the entire extension host when the browser disconnects and spawns a new one every time the browser connects.

**Comment by david9991** [comment] 2021-03-16 00:31
You are right, extension host was killed without call the deactivate().

**Comment by code-asher** [comment] 2021-03-16 15:50
I'll go ahead and close this since it's working as intended. I would prefer if the extension host wasn't killed and restarted like this but that's something we'd need to raise upstream.

**Closed by code-asher** 2021-03-16 15:50 UTC

**Comment by david9991** [comment] 2021-03-17 01:41
A similar case.
https://github.com/microsoft/vscode/issues/70665

**Comment by david9991** [comment] 2021-03-17 03:26
My problem was solved by handling the signal manually... 

```
process.on('SIGINT', () => {
    deactivate();
    ...
});
```
