### ISSUE TITLE
iPad: Scroll only editor when keyboard is open

### ISSUE THREAD

**Issue by neofuture** [cdr/code-server#1031] opened 2019-09-25 13:04 UTC
When scrolling the editor view on an iPad the outer document body attempts to scroll which means the scrolling is hard to perform with touch events

**Comment by sr229** [comment] 2019-09-26 04:13
@neofuture try with Desktop mode, we get reports that desktop mode in iPad OS tends to fix your issues.

**Comment by neofuture** [comment] 2019-09-26 11:56
I have v1 does not scroll properly and v2 doesn’t work at all doesn’t render login correct and does not get passed login

**Comment by mattapperson** [comment] 2019-09-29 01:09
@neofuture what version of iOS iPadOS are you running?

**Comment by frank-dspeed** [comment] 2019-10-01 06:48
@neofuture scrolling got patched in mainline please wait for the next v2 release and test again

**Comment by sr229** [comment] 2019-10-01 13:37
I assigned @code-asher for it so I think by 1.39.0 the scrolling will be fixed.

**Comment by neofuture** [comment] 2019-10-01 13:56
Awesomew work people, sorry only just picked up iPad OS 13.1

**Comment by hahaschool** [comment] 2019-10-15 07:37
Thanks for the awesome work, would also be happy to see *mouse* scrolling would also work properly on iPad OS 13, currently, if I scroll by external mouse's wheel, the whole page, rather than the editor region scrolls.

**Comment by sr229** [comment] 2019-10-15 15:13
We're trying our very best! @code-asher discussed switching upstream to 1.39.1 immediately since that has some fixes we all need.

**Comment by nhooyr** [comment] 2020-01-28 23:44
Just confirmed this works. If this is still a problem, please feel free to reopen.

**Comment by nhooyr** [comment] 2020-01-29 22:07
My bad, this is not fixed, just tested. Only occurs when u have the keyboard open.

**Comment by awahlig** [comment] 2020-03-25 11:28
Any update on this? iPadOS 13.4 added mouse cursor support throughout the OS and Apple is coming out with a keyboard that includes a trackpad so this issue will probably get more exposure.

**Comment by TobiaszCudnik** [comment] 2020-03-25 11:53
Seems fixed in 3.0 pre-releases (iOS 13.3). The ios bottom keyboard bar covers the status bar while typing tho.

**Comment by awahlig** [comment] 2020-03-25 13:09
I just tried the codercom/code-server:3.0.1 docker image and two-fingers scrolling doesn't work on the Magic Trackpad 2 on iPadOS 13.4.

**Comment by TobiaszCudnik** [comment] 2020-03-25 13:29
> two-fingers scrolling doesn't work on the Magic Trackpad 2 on iPadOS 13.4.
This isnt the subject of this issue.

App container scroll is and now it works well.

**Comment by awahlig** [comment] 2020-03-25 16:39
Ah, sorry then. I’ll file a separate issue.

**Comment by nhooyr** [comment] 2020-08-30 23:38
> App container scroll is and now it works well.

Forgot to close this, thanks.

**Closed by nhooyr** 2020-08-30 23:38 UTC
Labels: bug, iPad
