### ISSUE TITLE
https://v1.extapi.coder.com down

### ISSUE THREAD

**Issue by dshakey** [cdr/code-server#1184] opened 2019-11-18 10:50 UTC
- `code-server` version: latest 
- OS Version: MacOS and Centos Docker 

## Description

is https://v1.extapi.coder.com down as can not install any extensions, when i try to manually download, i get 404

![image](https://user-images.githubusercontent.com/34676590/69046522-0f7f7100-09f1-11ea-8478-15e22bc56e0d.png)

## Steps to Reproduce

1. 
1.

**Comment by sr229** [comment] 2019-11-18 12:44
Cannot confirm issue. Endpoint works as intended.

![image](https://user-images.githubusercontent.com/14976516/69053332-269b7e80-0a44-11ea-9f76-6dbf181c16b8.png)

**Comment by sr229** [comment] 2019-11-18 12:45
I checked the network as well and it looks like it resolves properly so I think it was a rather minor outage. Closing.

![image](https://user-images.githubusercontent.com/14976516/69053418-564a8680-0a44-11ea-9bf1-4a8706e87749.png)

**Closed by sr229** 2019-11-18 12:45 UTC
Labels: bug

**Comment by dshakey** [comment] 2019-11-18 18:35
I'm still getting it. Tired it on work wifi, personal WiFi and mobile WiFi. Located in Ireland and always get 404 errors.

**Comment by dshakey** [comment] 2019-11-18 18:39
Also just tired on vpn to USA and still same 404.. I am doing something incorrect.

**Comment by code-asher** [comment] 2019-11-20 16:21
Our marketplace appears to be up and running, however our marketplace doesn't currently implement the manual download endpoint so that won't work. The install button should work though.
