### ISSUE TITLE
Terminal font rendering bug in Firefox and Chrome.

### ISSUE THREAD

**Issue by tidux** [cdr/code-server#4073] opened 2021-08-30 21:05 UTC
## OS/Web Information

- Web Browser: Firefox, Google Chrome, Microsoft Edge
- Local OS: Linux, Windows 10
- Remote OS: Amazon Linux 2
- Remote Architecture: x86_64
- `code-server --version`:  3.11.1 c680aae973d83583e4a73dc0c422f44021f0140e

## Steps to Reproduce

1. open code-server tab in Firefox
2. open terminal
3. type `_______`

## Expected

The underscore characters are visible.

## Actual

The underscore characters are not visible, leaving what appears to be blank spaces.  In Chrome based browsers, adjusting the terminal's line spacing to 1.1 makes the underscores visible, but this does not work in Firefox.

## Logs

Console stdout/stderr:
```
[2021-08-30T20:58:55.509Z] info    - Not serving HTTPS
[2021-08-30T21:02:15.733Z] debug forking vs code...
[2021-08-30T21:02:16.096Z] debug setting up vs code...
[2021-08-30T21:02:16.099Z] debug vscode got message from code-server {"type":"init"}
[2021-08-30T21:02:18.976Z] debug vscode got message from code-server {"type":"socket"}
[2021-08-30T21:02:18.979Z] debug protocol Initiating handshake... {"token":"aae87521-0bbb-4f11-9aac-5b37061ad123"}
[2021-08-30T21:02:19.040Z] debug protocol Handshake completed {"token":"aae87521-0bbb-4f11-9aac-5b37061ad123"}
[2021-08-30T21:02:19.041Z] debug management Connecting... {"token":"aae87521-0bbb-4f11-9aac-5b37061ad123"}
[2021-08-30T21:02:19.042Z] debug vscode 1 active management connection(s)
[2021-08-30T21:02:20.647Z] debug vscode got message from code-server {"type":"socket"}
[2021-08-30T21:02:20.647Z] debug protocol Initiating handshake... {"token":"1e6492e6-71b6-4fda-bf1e-5a1e11924ca3"}
[2021-08-30T21:02:20.884Z] debug got latest version {"latest":"3.11.1"}
[2021-08-30T21:02:20.884Z] debug comparing versions {"current":"3.11.1","latest":"3.11.1"}
[2021-08-30T21:02:20.919Z] debug protocol Handshake completed {"token":"1e6492e6-71b6-4fda-bf1e-5a1e11924ca3"}
[2021-08-30T21:02:20.920Z] debug exthost Connecting... {"token":"1e6492e6-71b6-4fda-bf1e-5a1e11924ca3"}
[2021-08-30T21:02:20.921Z] debug exthost Getting NLS configuration... {"token":"1e6492e6-71b6-4fda-bf1e-5a1e11924ca3"}
[2021-08-30T21:02:20.921Z] debug vscode 1 active exthost connection(s)
[2021-08-30T21:02:20.921Z] debug exthost Spawning extension host... {"token":"1e6492e6-71b6-4fda-bf1e-5a1e11924ca3"}
[2021-08-30T21:02:20.925Z] debug exthost Waiting for handshake... {"token":"1e6492e6-71b6-4fda-bf1e-5a1e11924ca3"}
[2021-08-30T21:02:21.328Z] debug exthost Handshake completed {"token":"1e6492e6-71b6-4fda-bf1e-5a1e11924ca3"}
[2021-08-30T21:02:21.328Z] debug exthost Sending socket {"token":"1e6492e6-71b6-4fda-bf1e-5a1e11924ca3"}
terminate called after throwing an instance of 'Napi::Error'
  what():  Inotify limit reached
IPC "File Watcher (nsfw)" crashed with exit code null and signal SIGABRT
  ERR [File Watcher (nsfw)] terminated unexpectedly and is restarted again...
  ERR [File Watcher (nsfw)] terminated unexpectedly and is restarted again...
terminate called after throwing an instance of 'Napi::Error'
  what():  Inotify limit reached
IPC "File Watcher (nsfw)" crashed with exit code null and signal SIGABRT
  ERR [File Watcher (nsfw)] terminated unexpectedly and is restarted again...
  ERR [File Watcher (nsfw)] terminated unexpectedly and is restarted again...
terminate called after throwing an instance of 'Napi::Error'
  what():  Inotify limit reached
IPC "File Watcher (nsfw)" crashed with exit code null and signal SIGABRT
  ERR [File Watcher (nsfw)] terminated unexpectedly and is restarted again...
  ERR [File Watcher (nsfw)] terminated unexpectedly and is restarted again...
terminate called after throwing an instance of 'Napi::Error'
  what():  Inotify limit reached
IPC "File Watcher (nsfw)" crashed with exit code null and signal SIGABRT
  ERR [File Watcher (nsfw)] terminated unexpectedly and is restarted again...
  ERR [File Watcher (nsfw)] terminated unexpectedly and is restarted again...
terminate called after throwing an instance of 'Napi::Error'
  what():  Inotify limit reached
IPC "File Watcher (nsfw)" crashed with exit code null and signal SIGABRT
  ERR [File Watcher (nsfw)] terminated unexpectedly and is restarted again...
  ERR [File Watcher (nsfw)] terminated unexpectedly and is restarted again...
terminate called after throwing an instance of 'Napi::Error'
  what():  Inotify limit reached
IPC "File Watcher (nsfw)" crashed with exit code null and signal SIGABRT
  ERR [File Watcher (nsfw)] terminated unexpectedly and is restarted again...
  ERR [File Watcher (nsfw)] terminated unexpectedly and is restarted again...
terminate called after throwing an instance of 'Napi::Error'
  what():  Inotify limit reached
IPC "File Watcher (nsfw)" crashed with exit code null and signal SIGABRT
  ERR [File Watcher (nsfw)] failed to start after retrying for some time, giving up. Please report this as a bug report!
  ERR [File Watcher (nsfw)] failed to start after retrying for some time, giving up. Please report this as a bug report!
^C[2021-08-30T21:02:59.332Z] debug child:72071 disposing {"code":"SIGINT"}
```

## Screenshot

![Screenshot 2021-08-30 135602](https://user-images.githubusercontent.com/1330562/131404573-8e69986e-3fc4-4612-b5f9-d97235c825ae.png)

The "command not found" error was produced by typing several underscores and hitting enter.

## Notes

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment] 2021-08-30 21:31
I can't reproduce this in Firefox + macOS. Are you using a custom font in your terminal by chance?

https://user-images.githubusercontent.com/3806031/131408401-dfb9fbd3-54b8-4cbe-b98f-5bd9ecaab881.mov

**Comment by tidux** [comment] 2021-08-31 08:30
No, default options.  Please test on a non-retina display.

**Comment by senyai** [comment] 2021-08-31 11:55
Underscore is not visible in firefox on 133% zoom:

https://user-images.githubusercontent.com/76137/131497615-2398d771-046a-41f2-9b5b-490c2404c239.mp4

Underscore is not visible in firefox when it's on the last row:

https://user-images.githubusercontent.com/76137/131498038-4310f522-29db-4476-aeea-ab901e724c8f.mp4

**Comment by jsjoeio** [comment] 2021-08-31 17:02
> Underscore is not visible in firefox on 133% zoom:

I can't reproduce this unfortunately. Are you using a custom font? 

![image](https://user-images.githubusercontent.com/3806031/131545188-6bb2a094-3ecf-4903-beb0-749f54f8a593.png)

**Comment by senyai** [comment] 2021-09-01 09:20
I can reproduce it on latest linux mint and fedora. Changing the font to custom made underscore visible all the time and by visible I mean:
![image](https://user-images.githubusercontent.com/76137/131645965-6b9a07f3-74e3-43d6-a7d6-bde96b7e5aae.png)
there's something wrong in how the underscore is rendered.

**Comment by senyai** [comment] 2021-09-01 09:27
Got it!
`"terminal.integrated.gpuAcceleration": "off"`
fixes the issue:
![image](https://user-images.githubusercontent.com/76137/131647434-69b69ce7-3e7b-47ef-a86c-0a4f8988ab5b.png)

**Comment by jsjoeio** [comment] 2021-09-01 20:52
Hooray! I'm going to close this. Thanks for posting the solution too!

**Closed by jsjoeio** 2021-09-01 20:52 UTC
