### ISSUE TITLE
iOS copy and cut keyboard shortcuts are not working

### ISSUE THREAD

**Issue by schradeyannik** [cdr/code-server#1015] opened 2019-09-20 20:26 UTC
- `code-server` 1.1156-vsc1.33.1
- OS Version: iPadOS 13.1 Beta 4 (on iPad Pro 2018 12.9)

## Description

The keyboard shortcuts for copying and cutting text don‘t work. Changing the shortcuts in the code-server settings to something different of „cmd+c“ and „cmd+x“ does not help.

## Steps to Reproduce

1. Open and edit a file.
2. Try using „cmd+c“ or „cmd+x“.
3. Change the shortcuts in the settings.
4. Fail again.

**Comment by phoenixsfly** [comment] 2019-09-22 02:45
please use desktop mode in safari.
trun on : Setting—Safari—Request dessktop website

**Comment by sr229** [comment] 2019-09-22 05:55
@schradeyannik AFAIK we do not support Safari in mobile mode, try using the Desktop mode. We have no plans to support mobile UAs due to Monaco's limitation.

**Comment by schradeyannik** [comment] 2019-09-22 09:51
@sr229 @phoenixsfly The desktop mode is activated. The mentioned keyboard shortcuts do not work in desktop mode.

**Comment by mattapperson** [comment] 2019-09-29 01:10
Try using Control + C and Control + V

**Comment by schradeyannik** [comment] 2019-09-29 11:16
@mattapperson This does not work either.

**Comment by nhooyr** [comment] 2020-01-28 18:52
Will test and get back to you.

**Comment by dasalazar1** [comment] 2020-03-21 23:02
Any update on this bug? I’m having the same issue. iOS 13.3 iPad Air version 3.

**Comment by kylecarbs** [comment] 2020-03-23 18:32
@dasalazar1 not much of an update. Seems like more and more people wanna try this workflow, so we might prioritize it.

@code-asher we use the clipboard API right? So maybe we just have to adjust the keybind if they're on an iPad.

**Comment by code-asher** [comment] 2020-03-23 18:41
For the terminal it uses the clipboard API if it can but for the editor
I don't think it does. I think it just uses native paste there.

**Comment by kylecarbs** [comment] 2020-03-23 18:47
Ah. I assume we could patch that quite easily.

**Comment by perelin** [comment] 2020-03-26 13:26
Same behaviour here. iPad Air 3, iOS 13.4

Using a V2 is the only workaround currently? (no copy/paste makes development work defacto impossible :)

**Comment by Brent-Hickey** [comment] 2020-04-04 08:18
Seeing the same behavior. If it is a quick patch would love to see this fixed!

**Comment by pr1metine** [comment] 2020-04-08 11:09
Same for me even when using Chrome.

**Comment by infinitedaremo** [comment] 2020-04-08 18:12
Would love a fix for this.

**Comment by Brent-Hickey** [comment] 2020-04-08 18:37
FYI a simple workaround I’ve used is to highlight the text, cmd+f, and then you can immediately cmd+c out of the search bar. Paste works as expected. This doesn’t solve cut, but it’s pretty usable

**Comment by gavin-bd** [comment] 2020-04-08 19:50
That’s a brilliant temporary “fix”. Thank you. 

Cmd + Shift + F allows you to copy entire blocks too.

**Comment by kylecarbs** [comment] 2020-04-14 15:03
I'm pretty sure this is because WebKit doesn't let us override copy/paste on mobile unfortunately.

**Comment by gavin-bd** [comment] 2020-04-14 15:31
> I'm pretty sure this is because WebKit doesn't let us override copy/paste on mobile unfortunately.

On iOS the copy button is just greyed out. It’s like text selection doesn’t recognise that text has been highlighted in the editor view. Paste does work already if you’ve got something in the clipboard.

**Comment by Mrc527** [comment] 2020-04-27 16:44
Even from the context menu (Right button click) it does not work.

**Comment by Mrc527** [comment] 2020-04-27 16:45
> I'm pretty sure this is because WebKit doesn't let us override copy/paste on mobile unfortunately.

I’m not sure about this, considering that there is a working workaround and some reports V2 was working... Let’s keep finger crossed!

**Comment by demyxco** [comment] 2020-04-27 19:08
Glad to see this is an open issue, why was the clipboard API removed in v3 for editors? V2 works flawlessly on my iPad Pro.

**Comment by code-asher** [comment] 2020-04-27 19:22
Hmm, maybe we should double-check v2. I don't believe we made any changes but it's possible VS Code did. To confirm, `cmd+c`, `cmd+x`, and `cmd+v` work when editing a file in v2 but not in v3?

**Comment by demyxco** [comment] 2020-04-27 19:29
> To confirm, `cmd+c`, `cmd+x`, and `cmd+v` work when editing a file in v2 but not in v3?

Correct. Though in v3, paste gets disabled when switching tabs. It’s probably due to it losing focus from the attempting to reconnect dialog? You have to click the terminal first then the editor to paste again.

**Comment by Mrc527** [comment] 2020-04-28 15:21
Point is, in some places it does work! If you right click on a file and select “copy path” it works. So, to me it looks like it’s only in the code focus where you cannot copy.

Btw, did any of you managed to use the virtual keyboard in the code view? I don’t get it open, maybe it’s linked to this issue here, might be it’s a focus stuff.

**Comment by rpweb** [comment] 2020-04-28 19:21
I guess its also related to the Keyboard layout. MacOS (chrome) works with cmd
<img width="704" alt="Bildschirmfoto 2020-04-28 um 20 50 32" src="https://user-images.githubusercontent.com/7394465/80525872-31aeef00-8992-11ea-8c03-e12bed5551ff.png">

iPad (chrome) with new apple keyboard detects linux layout (MOBILE version) and works with control instead of cmd. control + c + x doesn't work, but control + shift + z + a + v etc. works.
<img width="893" alt="PNG-Bild" src="https://user-images.githubusercontent.com/7394465/80527531-c9154180-8994-11ea-9973-ad215fb54e90.png">

DESKTOP version on iPad (chrome) detects same keyboard as on MacOS (cmd works), but only with + shift + z + a + v. 
Combination with cmd + c + x don't work. (same as on MOBILE version)
<img width="838" alt="PNG-Bild 2" src="https://user-images.githubusercontent.com/7394465/80528371-1cd45a80-8996-11ea-968b-66cf8b96f5ac.png">

Fun fact: When I copy text on MacOS I can paste it immediately on my iPad. Somehow scary as well.

I will do further testing.

**Comment by rpweb** [comment] 2020-04-28 19:26
I could reproduce the issue on MacOS when I emulate iPad in Chrome code-server via inspector!

**Comment by nhooyr** [comment] 2020-04-30 06:57
@rpweb Thats awesome, will definitely help us debug easier.

**Comment by mbreese** [comment] 2020-05-05 17:35
I've been fighting with this for the better part of a week, and I think I understand what is happening. Strangely, what I've seen is that I can paste anything, but I can't copy anything new into the clipboard. If the clipboard already has the information I want, then it can be read with cmd-V, as expected.

I loaded my iPad up in the Safari remote debugger (by plugging the iPad into my computer via usb-c), and was looking for some error messages. I didn't see anything when I tried to use cmd-C. So, I tried programmatically copy/pasting.

What I saw was this: 

![Screen Shot 2020-05-05 at 1 27 58 PM](https://user-images.githubusercontent.com/98979/81096429-5a743e80-8ed4-11ea-8e30-dbaef9bf015e.png)

This led me to start looking for granting permissions to the clipboard in Safari. And unfortunately, I don't think it will be possible. From my reading, I think that the only way for web applications to interact with the clipboard is using the system copy/paste UI. This is a recent update to the iPadOS/Safari code. And this obviously won't work with an editor like code-server/VSCode that is expecting to be able to use keyboard shortcuts.

Here's the update from Webkit that mentions this behavior: https://webkit.org/blog/10247/new-webkit-features-in-safari-13-1/

>The implementation is available through the navigator.clipboard API which must be called within user gesture event handlers like pointerdown or pointerup, and only works for content served in a secure context (e.g. https://). Instead of a permissions-based model for reading from the clipboard, a native UI is displayed when the page calls into the clipboard API; **the clipboard can only be accessed if the user then explicitly interacts with the platform UI**.

**Comment by Mrc527** [comment] 2020-05-05 17:53
> I've been fighting with this for the better part of a week, and I think I understand what is happening. Strangely, what I've seen is that I can paste anything, but I can't copy anything new into the clipboard. If the clipboard already has the information I want, then it can be read with cmd-V, as expected.
> 
> I loaded my iPad up in the Safari remote debugger (by plugging the iPad into my computer via usb-c), and was looking for some error messages. I didn't see anything when I tried to use cmd-C. So, I tried programmatically copy/pasting.
> 
> What I saw was this:
> 
> ![Screen Shot 2020-05-05 at 1 27 58 PM](https://user-images.githubusercontent.com/98979/81096429-5a743e80-8ed4-11ea-8e30-dbaef9bf015e.png)
> 
> This led me to start looking for granting permissions to the clipboard in Safari. And unfortunately, I don't think it will be possible. From my reading, I think that the only way for web applications to interact with the clipboard is using the system copy/paste UI. This is a recent update to the iPadOS/Safari code. And this obviously won't work with an editor like code-server/VSCode that is expecting to be able to use keyboard shortcuts.
> 
> Here's the update from Webkit that mentions this behavior: https://webkit.org/blog/10247/new-webkit-features-in-safari-13-1/
> 
> > The implementation is available through the navigator.clipboard API which must be called within user gesture event handlers like pointerdown or pointerup, and only works for content served in a secure context (e.g. https://). Instead of a permissions-based model for reading from the clipboard, a native UI is displayed when the page calls into the clipboard API; **the clipboard can only be accessed if the user then explicitly interacts with the platform UI**.
> 
> So, the issue maybe a combination of code-server _and_ the version of iPadOS in use. I'm not sure if there is a work around...

Hi @mbreese thanks for your feedback, I really appreciate it. I have a question: why is it possible to copy for instance the path of a file?
<img width="467" alt="image" src="https://user-images.githubusercontent.com/1961697/81098550-cfae3680-8f09-11ea-9da5-ae3bdfd3d6a7.png">
This one works for me on my iPad, updated with the latest iPad OS.

Is this in contradiction with your conclusions? Might be this is not, since this button is acting on an element that is outside of the editor view or maybe because this is not using a keyboard shortcut...

**Comment by mbreese** [comment] 2020-05-05 19:29
> Hi @mbreese thanks for your feedback, I really appreciate it. I have a question: why is it possible to copy for instance the path of a file?
> <img alt="image" width="467" src="https://user-images.githubusercontent.com/1961697/81098550-cfae3680-8f09-11ea-9da5-ae3bdfd3d6a7.png">
> This one works for me on my iPad, updated with the latest iPad OS.
> 
> Is this in contradiction with your conclusions? Might be this is not, since this button is acting on an element that is outside of the editor view or maybe because this is not using a keyboard shortcut...

Yes, that works. But I think the difference is where the source of the clipboard text is. Even above, I mentioned that I could still paste w/ cmd-V, but only something that was clipped from a different app (like notes, email, or the safari url, etc). 

So, what we've shown is that you can 
a) programmatically add data to the clipboard and 
b) programmatically paste data from the clipboard

What you can't do is copy user-data to the clipboard. So, my guess is that it's somewhere in the selection API. If you run (from the console): 

```window.getSelection().toString()```

On Safari on my Mac, I get the correct selected text. On my iPad, I get an empty string (```""```). I think this is where the root issue lies.

You're right that this all seems strange and contradictory. It also seems like it doesn't match the Webkit announcement at all. The rest of it may end up a red herring. I believe that any copy/paste code needs to run in the context of a user event (keydown, pointerdown, etc). The tests I've been doing haven't done that, so maybe that's another issue with the testing?

And strangely, undo/redo also works. I expect that's a similar mechanism as copy/paste.

**Comment by perelin** [comment] 2020-05-12 16:42
I working with the v2 docker container and copy/paste with CMD-C works. (Strangely the codercom/code-server:v2 tag doesn`t exist anymore on docker hub...)
Could it help to analyze what changed between v2 and v3?

**Comment by code-asher** [comment] 2020-05-12 17:09
Ah, we removed the `v2` tag but the individual v2 version tags are still there. Definitely sounds like it's worth checking out.

**Comment by perelin** [comment] 2020-05-14 08:24
I´d love to do it, but I´m afraid I don´t have the necessary expertise :(

**Comment by neoighodaro** [comment] 2020-05-16 10:50
Glad I found this, i thought I may have installed something that caused this behavior. I would absolutely love to see it work. If it did (and still works, maybe someone can confirm this) work in v2, then likely more a code change and less but still possibly an iPadOS issue.

**Comment by perelin** [comment] 2020-05-18 08:08
Can confirm again: works in codercom/code-server:v2 but I haven´t tried any of the other v2 tags

**Comment by kschembri** [comment] 2020-05-18 16:59
Can confirm this is an issue. Tried remapping the copy / paste shortcuts and now I get the error: Command ‘references-view.copy’ not found.

**Comment by neoighodaro** [comment] 2020-05-20 09:06
For those using an iPad, you can temporarily use this app called VS App - code server, they pushed an update to the app that fixes copy/paste. 

You can use your custom code server in the app itself and not have to pay

**Comment by rpweb** [comment] 2020-05-20 09:08
> For those using an iPad, you can temporarily use this app called VS App - code server, they pushed an update to the app that fixes copy/paste.
> 
> You can use your custom code server in the app itself and not have to pay

Nice to hear, but what exactly is the fix? Can't we implement into code-server?

**Comment by neoighodaro** [comment] 2020-05-20 09:10
> > For those using an iPad, you can temporarily use this app called VS App - code server, they pushed an update to the app that fixes copy/paste.
> > You can use your custom code server in the app itself and not have to pay
> 
> Nice to hear, but what exactly is the fix? Can't we implement into code-server?

No idea, it's closed source i believe. Just found out that they pushed the update for this fix and i decided to try if it works with my custom code-server and it did.

**Comment by demyxco** [comment] 2020-05-20 09:12
@neoighodaro nice find! I think the app itself is doing the copy/cut instead of the browser? Also it has the ability to upload folders/files; which is a nice touch. I seen this app a while ago but assumed it was for the app developer’s platform.

**Comment by rpweb** [comment] 2020-05-20 09:21
> > > For those using an iPad, you can temporarily use this app called VS App - code server, they pushed an update to the app that fixes copy/paste.
> > > You can use your custom code server in the app itself and not have to pay
> > 
> > 
> > Nice to hear, but what exactly is the fix? Can't we implement into code-server?
> 
> No idea, it's closed source i believe. Just found out that they pushed the update for this fix and i decided to try if it works with my custom code-server and it did.

Just tested it and it works! Thanks for sharing.

I just firgured out that @ColdGrub1384 is the developer. Maybe he can give us more insides?

**Comment by rpweb** [comment] 2020-05-20 09:24
Unfortunately scrolling is not working.

**Comment by neoighodaro** [comment] 2020-05-20 09:26
Yes thats a regular problem in both code-server and the app, for now i use a combination of touch scroll, shortcuts to jump between scroll pages, and the mini-map.

**Comment by ColdGrub1384** [comment] 2020-05-20 13:28
@rpweb The WebView didn’t seem to receive Copy Paste shortcuts, so I added a listener in the app level that then sends Copy and Paste events. It’s just Swift code, no JavaScript.

That’s the code I have in the WebView:

```swift
class WebView: WKWebView {
    
    override func willMove(toWindow newWindow: UIWindow?) {
        super.willMove(toWindow: newWindow)
        
        let cut = UIBarButtonItem(image: UIImage(systemName: "scissors"), style: .plain, target: self, action: #selector(cut(_:)))
        
        let copyItem = UIBarButtonItem(image: UIImage(systemName: "doc.on.doc"), style: .plain, target: self, action: #selector(copy(_:)))
        
        let pasteItem = UIBarButtonItem(image: UIImage(systemName: "doc.on.clipboard"), style: .plain, target: self, action: #selector(paste(_:)))
                
        let done = UIBarButtonItem(barButtonSystemItem: .done, target: self, action: #selector(endEditing(_:)))
        
        if UIDevice.current.userInterfaceIdiom == .pad {
            inputAssistantItem.trailingBarButtonGroups = []
            inputAssistantItem.leadingBarButtonGroups = [UIBarButtonItemGroup(barButtonItems: [cut, copyItem, pasteItem], representativeItem: nil)]
        } else {
            toolbar = UIToolbar(frame: CGRect(x: 0, y: 0, width: 500, height: 44))
            toolbar?.tintColor = .label
            toolbar?.items = [
                cut,
                copyItem,
                pasteItem,
                UIBarButtonItem(barButtonSystemItem: .flexibleSpace, target: nil, action: nil),
                done
            ]
        }
    }
    
    @objc func _copy(_ sender: Any) {
        NSLog("Copy")
        copy(sender)
    }
    
    @objc func _cut(_ sender: Any) {
        NSLog("Cut")
        cut(sender)
    }
    
    @objc func _paste(_ sender: Any) {
        NSLog("Paste”)
        paste(sender)
    }
    
    override var keyCommands: [UIKeyCommand]? {
        return [
            UIKeyCommand(input: "c", modifierFlags: .command, action: #selector(_copy(_:))),
            UIKeyCommand(input: "x", modifierFlags: .command, action: #selector(_cut(_:))),
            UIKeyCommand(input: "v", modifierFlags: .command, action: #selector(_paste(_:))),
        ]
    }
        
    private var toolbar: UIToolbar?
    
    override var inputAccessoryView: UIView? {
        if UIDevice.current.userInterfaceIdiom == .pad {
            return nil
        } else {
            return toolbar
        }
    }
}
```

I don’t know what’s exactly the problem but that worked. Seems like the keyboard shortcut isn’t detected but sending the event manual works.

**Comment by demyxco** [comment] 2020-05-20 18:34
> The WebView didn’t seem to receive Copy Paste shortcuts, so I added a listener in the app level that then sends Copy and Paste events. It’s just Swift code, no JavaScript.

I called it! v3 does not implement the clipboard API in the editor from v2 because v3's terminal works just fine.

**Comment by rpweb** [comment] 2020-05-20 19:18
> @rpweb The WebView didn’t seem to receive Copy Paste shortcuts, so I added a listener in the app level that then sends Copy and Paste events. It’s just Swift code, no JavaScript.
> 
> That’s the code I have in the WebView:
> 
> ```swift
> class WebView: WKWebView {
>     
>     override func willMove(toWindow newWindow: UIWindow?) {
>         super.willMove(toWindow: newWindow)
>         
>         let cut = UIBarButtonItem(image: UIImage(systemName: "scissors"), style: .plain, target: self, action: #selector(cut(_:)))
>         
>         let copyItem = UIBarButtonItem(image: UIImage(systemName: "doc.on.doc"), style: .plain, target: self, action: #selector(copy(_:)))
>         
>         let pasteItem = UIBarButtonItem(image: UIImage(systemName: "doc.on.clipboard"), style: .plain, target: self, action: #selector(paste(_:)))
>                 
>         let done = UIBarButtonItem(barButtonSystemItem: .done, target: self, action: #selector(endEditing(_:)))
>         
>         if UIDevice.current.userInterfaceIdiom == .pad {
>             inputAssistantItem.trailingBarButtonGroups = []
>             inputAssistantItem.leadingBarButtonGroups = [UIBarButtonItemGroup(barButtonItems: [cut, copyItem, pasteItem], representativeItem: nil)]
>         } else {
>             toolbar = UIToolbar(frame: CGRect(x: 0, y: 0, width: 500, height: 44))
>             toolbar?.tintColor = .label
>             toolbar?.items = [
>                 cut,
>                 copyItem,
>                 pasteItem,
>                 UIBarButtonItem(barButtonSystemItem: .flexibleSpace, target: nil, action: nil),
>                 done
>             ]
>         }
>     }
>     
>     @objc func _copy(_ sender: Any) {
>         NSLog("Copy")
>         copy(sender)
>     }
>     
>     @objc func _cut(_ sender: Any) {
>         NSLog("Cut")
>         cut(sender)
>     }
>     
>     @objc func _paste(_ sender: Any) {
>         NSLog("Paste")
>         paste(sender)
>     }
>     
>     override var keyCommands: [UIKeyCommand]? {
>         return [
>             UIKeyCommand(input: "c", modifierFlags: .command, action: #selector(_copy(_:))),
>             UIKeyCommand(input: "x", modifierFlags: .command, action: #selector(_cut(_:))),
>             UIKeyCommand(input: "v", modifierFlags: .command, action: #selector(_paste(_:))),
>         ]
>     }
>         
>     private var toolbar: UIToolbar?
>     
>     override var inputAccessoryView: UIView? {
>         if UIDevice.current.userInterfaceIdiom == .pad {
>             return nil
>         } else {
>             return toolbar
>         }
>     }
> }
> ```
> 
> I don’t know what’s exactly the problem but that worked. Seems like the keyboard shortcut isn’t detected but sending the event manual works.
> 
> Edit: `copy(_:)`, `paste(_:)` and `cut(_:)` are methods from https://developer.apple.com/documentation/uikit/uiresponderstandardeditactions.
> `WKWebView` implements these methods.
> 
> Well, my guess is that iOS doesn’t detect text as selected, so it doesn’t call `copy(_:)` when cmd+c is pressed so calling it manually works because there is no check, we just send the function. So maybe the problem is that text is not detected as selected?
> 
> As you can see in the code, I didn’t pass the iOS methods directly to the key commands, but I passed a method that called the other method. That’s because passing the methods directly didn’t work, so that would prove that iOS checks if text is selected before calling `copy(_:)` when cmd+c is pressed.

Its a pitty that Apple can't provide a sustainable solution yet. Thank you for sharing your workaround!

**Comment by pr1metine** [comment] 2020-05-21 06:56
Last time I checked Copy and Paste worked on [Theia](https://github.com/eclipse-theia/theia). You guys could give that one a try.

**Comment by demyxco** [comment] 2020-05-21 09:39
@pr1metine tried it and it was meh. Not as refined as code-server.

**Comment by perelin** [comment] 2020-05-21 13:57
Is there any changes of @ColdGrub1384 workaround being implemented in a coming V3?

**Comment by neoighodaro** [comment] 2020-05-21 13:59
That's not possible. Not the same workaround at least. He "fixed" it on app level. Not server level.



Neo Ighodaro
Software Engineer | Twitter | neoighodaro.com

**Comment by mbreese** [comment] 2020-05-21 20:56
After a long trek in Azure-land -- I can confirm that this is also a problem in Microsoft Visual Studio Codespaces as well. When trying that version out on Chrome on my iPad (Safari doesn't work for some reason), copying doesn't work. You can paste text (cmd-V) that was already in the clipboard, but you can't paste new data. Similarly, cmd-Z doesn't work for undo either.

Interestingly, in code-server, you can copy from the terminal; however, in VS Codespaces, you can't copy from that terminal.

This makes me suspect that changes upstream are the primary cause for the lack of copy/paste/undo functionality in code-server as well. Given that this will be the basis for their Github codespaces product, I would wager that these problems will probably also get fixed upstream.  Until then, VS App might be the best "workaround".

**Comment by markuzzi** [comment] 2020-06-11 08:36
Another workaround is installing the extension „Copy Copy Paste“ and assign Cmd+V to its paste action. It gives you an extra „hit return“ after paste, but otherwise works great at least for copy. Cut does not delete the selected text - you have to delete it on your own.

**Comment by daybrush** [comment] 2020-06-23 16:00
This probably looks like a userAgent problem?

* PC Chrome: Working
* PC Chrome iOS Mobile Mode: Not Working
* Safari: Working
* Safari iPhone agent: Not Working
* iPad Desktop Mode: Working
* iPad Mobile Mode: Not Working

### UserAgent (Test PC)
#### Test Code

```html
<head>
...
<script>
Object.defineProperty(navigator, "userAgent", {
  get: () => "Mozilla/5.0 (Macintosh; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1",
});
// iOS "Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1"
// Mac Safari "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15" = $1
</script>
...
</head>
...
```

#### Not Working
* "Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1"
* "Mozilla/5.0 (What; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1"
#### Working
* "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15"
* "Mozilla/5.0 (Macintosh; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1"


### Result
* If userAgent does not have Macintosh, it does not work.
* Probably because the userAgent checks the platform and the Macintosh uses the meta key. On the iPhone platform, it seems to cause the illusion of not using the meta key.

**Comment by neoighodaro** [comment] 2020-06-24 05:07
Interesting

**Comment by daybrush** [comment] 2020-07-02 05:11
iOS Copy & Cut issue.

https://github.com/microsoft/vscode/issues/101564

**Comment by perelin** [comment] 2020-07-26 04:52
I totally missed it, but the issue created by @daybrush on the vscode repository needs upvotes to get considered: microsoft/vscode#101564 

> vscode-triage-bot commented 24 days ago
> This feature request is now a candidate for our backlog. The community has 60 days to upvote the issue. If it receives 20 upvotes we will move it to our backlog. If not, we will close it.

8 Upvotes so far. If everybody from this thread upvotes, we are good.

**Comment by demyxco** [comment] 2020-07-26 04:54
> I totally missed it, but the issue created by @daybrush on the vscode repository needs upvotes to get considered: [microsoft/vscode#101564](https://github.com/microsoft/vscode/issues/101564)
> 
> > vscode-triage-bot commented 24 days ago
> > This feature request is now a candidate for our backlog. The community has 60 days to upvote the issue. If it receives 20 upvotes we will move it to our backlog. If not, we will close it.
> 
> 8 Upvotes so far. If everybody from this thread upvotes, we are good.

9 now.

**Comment by wei** [comment] 2020-07-26 11:45
@perelin Thanks for sharing! 20 upvotes now. 👍👍

**Comment by neoighodaro** [comment] 2020-07-26 15:15
Woo hoo

**Comment by daybrush** [comment] 2020-07-26 18:13
@perelin @wei @demyxco @neoighodaro 

I hope this issue will be resolved quickly. I uploaded the PR, but the vscode cannot be checked.

https://github.com/microsoft/vscode/pull/101702

**Comment by demyxco** [comment] 2020-07-26 18:18
@daybrush thanks, keep us posted.

**Comment by spatinolang-vtr** [comment] 2020-07-27 11:59
> vscode-triage-bot commented 10 hours ago
🙂 This feature request received a sufficient number of community upvotes and we moved it to our backlog. 

microsoft/vscode/issues/101564

Looking good!

**Comment by ethanx94** [comment] 2020-08-16 23:56
This just got merged upstream! 😉

**Comment by daybrush** [comment] 2020-08-17 02:39
@ethanx94 

Nice!!

**Comment by nhooyr** [comment] 2020-08-17 18:49
Awesome, then we just need to update our vs code version!

**Comment by kschembri** [comment] 2020-08-20 16:05
For those of us who are new around here, can someone explain what it takes to get this in code-server?

**Comment by wei** [comment] 2020-08-20 16:20
@kschembri Waiting for https://github.com/microsoft/vscode/wiki/Iteration-Plans Says August 2020 milestone to be released in early September. Then wait for code-server to pull it in. Currently there is an open PR in this repo to bump up vscode to its July 2020 milestone release. We'll just have to wait maybe another 2 months 🤦 .

**Comment by christianjuth** [comment] 2020-08-24 02:03
> * Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15

I was able to get copy/paste working using the iCabMobile browser, which lets you change the user agent. Definitely a hack, but its better than nothing.

**Comment by chrisn-au** [comment] 2020-08-26 22:50
> > * Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
> 
> 
> 
> I was able to get copy/paste working using the iCabMobile browser, which lets you change the user agent. Definitely a hack, but its better than nothing.

Great, feedback. I just paid my AU$4.50 for iCabMobile and have dedicated it to this single purpose. Love how it can be customised. Full screen VSCode on the ipad pro works incredibly (while the macbook is in for service). Looking forward though to copy and paste running in Safari though

**Comment by kschembri** [comment] 2020-08-26 23:08
@chrisn-au or @christianjuth by any chance does scroll work on iCabMobile? See issue #1455

**Comment by christianjuth** [comment] 2020-08-26 23:09
@kschembri unfortunately no

**Comment by nhooyr** [comment] 2020-08-31 10:54
[v3.5.0 with VS Code v1.48.2 has been released, fixing this issue!](https://github.com/cdr/code-server/releases/tag/v3.5.0)

**Comment by jendrikjoe** [comment] 2020-08-31 12:13
I just installed v3.5.0. I can confirm that pasting works. However, I still cannot copy. Anyone else seeing this or is that an issue that only I am facing? 🙂

**Comment by AlfaJackal** [comment] 2020-08-31 16:17
> I just installed v3.5.0. I can confirm that pasting works. However, I still cannot copy. Anyone else seeing this or is that an issue that only I am facing? 🙂

Same here. What now?

**Comment by christianjuth** [comment] 2020-08-31 16:26
Installed v3.5.0. I can't even get copy working by right clicking and selecting copy from the context menu. ☹️

**Comment by nhooyr** [comment] 2020-08-31 16:32
This sucks, was hoping upstream fixed it but I guess not :(

**Comment by wei** [comment] 2020-08-31 16:35
@nhooyr according to microsoft/vscode#101702 it's in August 2020 milestone which will be in a early Sept release.

**Comment by AlfaJackal** [comment] 2020-08-31 16:40
> @nhooyr according to [microsoft/vscode#101702](https://github.com/microsoft/vscode/pull/101702) it's in August 2020 milestone which will be in a early Sept release.

Is it?

**Comment by nhooyr** [comment] 2020-08-31 16:52
@wei I checked and v1.48.2 included the commits that were supposed to fix it.

**Comment by wei** [comment] 2020-08-31 16:54
@nhooyr @AlfaJackal 

`1.48.2`:
https://github.com/microsoft/vscode/blob/1.48.2/src/vs/editor/browser/controller/textAreaHandler.ts

`master`:
https://github.com/microsoft/vscode/blob/master/src/vs/editor/browser/controller/textAreaHandler.ts

You can tell the changes in https://github.com/microsoft/vscode/pull/101702/files are in `master` but not `1.48.2`.

**Comment by daybrush** [comment] 2020-09-02 02:45
@nhooyr 

As @wei said, the linked commit link doesn't seem to be 1.48.2 either.

https://github.com/microsoft/vscode/blob/a0479759d6e9ea56afa657e454193f72aef85bd0/src/vs/editor/browser/controller/textAreaHandler.ts#L184-L187

**Comment by daybrush** [comment] 2020-09-02 02:49
@nhooyr 

As @wei said, it doesn't seem to be fixed in 1.48.2.
We should hope the master's commit is released.

**Comment by wei** [comment] 2020-09-02 03:07
Good news August 2020 milestone is in [endgame](https://github.com/microsoft/vscode/issues/105745). They are targeting next Wednesday/Thursday for release. Let's hope code-server team can bump up vscode version quicker this time 😉

**Comment by NetLS2013** [comment] 2020-09-07 16:54
looks like copy paste work well in the app https://apps.apple.com/us/app/servediter-for-code-server/id1504491325

**Comment by keiqsa** [comment] 2020-09-07 16:56
looks like copy paste work well in the app https://apps.apple.com/us/app/servediter-for-code-server/id1504491325

**Comment by christianjuth** [comment] 2020-09-07 17:15
@keiqsa are you using a self hosted instance of code-server with the Servediter app or their hosted service? I tried to get the app to connect to my self hosted server, but it didn't work. Their app seems really buggy in general.

**Comment by dasalazar1** [comment] 2020-09-07 17:28
@christianjuth It's a little buggy if you mess up the self hosted options. I got caught in a some kinda auth loop a few times and had to uninstall/reinstall to clear the settings. But once it's connected I've run self hosted for a while with no issues. Ended up turning auth off since I only have it exposed in my home network anyway.

**Comment by demyxco** [comment] 2020-09-07 17:30
I use that app heavily due to it having a working copy/paste. My only gripe about it is that the app refreshes when switching to other apps, losing my open terminals and what not.

**Comment by dasalazar1** [comment] 2020-09-07 17:37
@demyxco As far as I know that's an iOS limitation. Something about how long apps can retain state or activity in the background. I've had that complaint from other apps that do terminals. Textastic seems to be able to keep them open a bit longer but still not great.

**Comment by demyxco** [comment] 2020-09-07 17:39
@dasalazar1 right, those other apps uses the location feature to prevent the app from refreshing. Maybe implement the same? The other thing also is scrolling loses it’s scroll momentum but I think that’s an upstream issue.

**Comment by dasalazar1** [comment] 2020-09-07 17:49
@demyxco hmm okay. I didn't know that was the work around. There's issue #1455 for scrolling with trackpad. Not sure about the momentum.

**Comment by pavlovcik** [comment] 2020-09-10 05:36
> Good news August 2020 milestone is in [endgame](https://github.com/microsoft/vscode/issues/105745). They are targeting next Wednesday/Thursday for release. Let's hope code-server team can bump up vscode version quicker this time 😉

My hopes are so high for today, Thursday.

**Comment by cdswyda** [comment] 2020-09-30 16:27
> code-server: v3.5.0
 VS Code: v1.48.2
Commit: de41646fc402b968ca6d555fdf2da7de9554d28a
Date: 2020-08-31T09:43:23Z
Browser: Mozilla/5.0 (iPad; CPU OS 14_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/85.0.4183.109 Mobile/15E148 Safari/604.1

Have same problem

**Comment by code-asher** [comment] 2020-10-07 18:27
Merged the latest VS Code, will be in 3.6.0 very soon. Keep an eye on the milestone to see progress.

**Closed by code-asher** 2020-10-07 18:27 UTC
Labels: bug, iPad

**Comment by enesccinar** [comment] 2021-02-18 20:04
> @keiqsa are you using a self hosted instance of code-server with the Servediter app or their hosted service? I tried to get the app to connect to my self hosted server, but it didn't work. Their app seems really buggy in general.

It's been a while but I wanted you to know that I am using self-hosted server and it works well for me. I've just tried it /w code-server 3.3.1.

**Comment by ManiaciaChao** [comment] 2022-01-02 15:22
For anyone who still faces with such problem, try add these into `keybinding.json`:

```json
  {
    "key": "cmd+c",
    "command": "editor.action.clipboardCopyAction"
  },
  {
    "key": "cmd+v",
    "command": "editor.action.clipboardPasteAction"
  },
  {
    "key": "cmd+x",
    "command": "editor.action.clipboardCutAction"
  },
```

I encountered this when trying to deploy `code-server` instances on several  servers, and solved by modifying shortcuts’ mapping :)

**Comment by ManiaciaChao** [comment] 2022-01-17 07:32
The issue still exists in v4.0.1.

I can't use cmd+[X/C/V] to cut/copy/paste the entire line from PWA on iPad. The only solution here is still `Servereditor` app.

**Comment by ManiaciaChao** [comment] 2022-01-19 05:53
> @ManiaciaChao can you provide a video? I could have sworn this was fixed now

Thanks for your reply :) I've sent the video directly into your Gmail. Plz check.

**Comment by jsjoeio** [comment] 2022-01-19 20:48
@ManiaciaChao can you post it here instead please? That way, everyone can see it!
