### ISSUE TITLE
Can't open folder - Command 'workbench.action.files.openFileFolder' not found

### ISSUE THREAD

**Issue by sestegra** [cdr/code-server#3427] opened 2021-05-20 09:20 UTC
## OS/Web Information

- Web Browser: Chrome (90.0.4430.212 (Official Build) (x86_64)
- Local OS: macOS 11.3.1
- Remote OS: Ubuntu 20.04.2 LTS
- Remote Architecture: x86_64 (sysbox-runc CE 0.3.0)
- `code-server --version`: 3.10.1

## Steps to Reproduce

1. Create `config.yaml`
2. Launch code-server on remote server
2. Launch Chrome on local and open code-server URL
3. Click on "Open folder" on Welcome page

`config.yaml`
``` YAML
bind-addr: 0.0.0.0:8080
auth: none
password:
cert: false
disable-telemetry: true
disable-update-check: true
```

## Expected

Folder selection should appear.

## Actual

An error occurs on Web console

## Logs

Web console log
```
ERR command 'workbench.action.files.openFileFolder' not found: Error: command 'workbench.action.files.openFileFolder' not found
    at h._tryExecuteCommand (https://xxxxxx/static/421237f499079cf88d68c02163b70e2b476bbb0d/usr/lib/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:1735:3364)
    at https://xxxxxx/static/421237f499079cf88d68c02163b70e2b476bbb0d/usr/lib/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:1735:3245
    at async u.open (https://xxxxxx/static/421237f499079cf88d68c02163b70e2b476bbb0d/usr/lib/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:628:17651)
    at async a.open (https://xxxxxx/static/421237f499079cf88d68c02163b70e2b476bbb0d/usr/lib/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:628:19675)
```

code-server log
```
[2021-05-20T09:14:35.962Z] info  code-server 3.10.1 421237f499079cf88d68c02163b70e2b476bbb0d
[2021-05-20T09:14:35.964Z] info  Using user-data-dir ~/.local/share/code-server
[2021-05-20T09:14:35.978Z] info  Using config file ~/.config/code-server/config.yaml
[2021-05-20T09:14:35.978Z] info  HTTP server listening on http://0.0.0.0:8080
[2021-05-20T09:14:35.978Z] info    - Authentication is disabled
[2021-05-20T09:14:35.978Z] info    - Not serving HTTPS
[2021-05-20T09:14:50.709Z] debug forking vs code...
[2021-05-20T09:14:51.146Z] debug setting up vs code...
[2021-05-20T09:14:51.148Z] debug vscode got message from code-server {"type":"init"}
[2021-05-20T09:14:52.471Z] debug vscode got message from code-server {"type":"socket"}
[2021-05-20T09:14:52.473Z] debug protocol Initiating handshake... {"token":"f4417507-5049-4f3c-a858-be6b60b32b42"}
[2021-05-20T09:14:52.528Z] debug protocol Handshake completed {"token":"f4417507-5049-4f3c-a858-be6b60b32b42"}
[2021-05-20T09:14:52.528Z] debug management Connecting... {"token":"f4417507-5049-4f3c-a858-be6b60b32b42"}
[2021-05-20T09:14:52.529Z] debug vscode 1 active management connection(s)
[2021-05-20T09:14:53.174Z] debug vscode got message from code-server {"type":"socket"}
[2021-05-20T09:14:53.175Z] debug protocol Initiating handshake... {"token":"f676146d-4f87-4436-b36b-f97fed0c635d"}
[2021-05-20T09:14:53.328Z] debug protocol Handshake completed {"token":"f676146d-4f87-4436-b36b-f97fed0c635d"}
[2021-05-20T09:14:53.329Z] debug exthost Connecting... {"token":"f676146d-4f87-4436-b36b-f97fed0c635d"}
[2021-05-20T09:14:53.330Z] debug exthost Getting NLS configuration... {"token":"f676146d-4f87-4436-b36b-f97fed0c635d"}
[2021-05-20T09:14:53.330Z] debug vscode 1 active exthost connection(s)
[2021-05-20T09:14:53.331Z] debug exthost Spawning extension host... {"token":"f676146d-4f87-4436-b36b-f97fed0c635d"}
[2021-05-20T09:14:53.336Z] debug exthost Waiting for handshake... {"token":"f676146d-4f87-4436-b36b-f97fed0c635d"}
[2021-05-20T09:14:53.821Z] debug exthost Handshake completed {"token":"f676146d-4f87-4436-b36b-f97fed0c635d"}
[2021-05-20T09:14:53.822Z] debug exthost Sending socket {"token":"f676146d-4f87-4436-b36b-f97fed0c635d"}
```

## Screenshot

N/A

## Notes

This issue can be reproduced in VS Code: No

This issue occurs on code-server 3.10.0 as well.
This issue **doesn't occur** on code-server 3.9.3.

**Comment by jsjoeio** [comment] 2021-05-20 18:54
Thanks for the detailed report! I was able to reproduce locally.

## Screenshot
![image](https://user-images.githubusercontent.com/3806031/119033328-f1862a00-b961-11eb-838b-953068b4d4ff.png)

This appears to be a duplicate of https://github.com/cdr/code-server/issues/2921 so we'll close this one in favor of that one.

**Closed as completed by jsjoeio** 2021-05-20 18:54 UTC
Labels: duplicate
