### ISSUE TITLE
HTTP proxy environment variables support

### ISSUE THREAD

**Issue by fancl20** [cdr/code-server#124] opened 2019-03-08 07:09 UTC
vscode use http_proxy and https_proxy environment variables if the proxy setting not set. It seems not to work when using code-server.

**Comment by kylecarbs** [comment] 2019-03-08 16:23
We'd need to add proper VS Code networking setup to `code-server`. Not sure about this.

Ref: https://code.visualstudio.com/docs/setup/network

**Comment by avindra** [comment] 2019-03-09 01:42
I'm also looking for proxy support (in order to install extensions).

As a workaround, I tried importing the `vsix` file directly, but this error shows up when I do that:

![image](https://user-images.githubusercontent.com/126848/54064477-a77e5700-41e2-11e9-8ea4-f0a12804f3c2.png)

**Comment by coadler** [comment] 2019-03-09 01:45
@avindra see https://github.com/codercom/code-server/issues/92

**Comment by RichardMcSorley** [comment] 2019-04-02 04:22
Also looking forward to this support. Not able to run it on some networks due to this, makes code-server cumbersome to use.

**Comment by fcomte** [comment] 2019-04-05 08:48
Does anybody success to install extension behind a proxy ?
Iam using : version 1.604-vsc1.32.0

**Comment by jrderuiter** [comment] 2019-04-15 13:04
Not yet :(

**Comment by kylecarbs** [comment] 2019-04-24 19:59
I'd be happy to implement this, but would concretely like to understand the importance. Does this just proxy all requests VS Code would normally make?

**Comment by t-d-d** [comment] 2019-04-26 02:04
The only issue I have seen so far is that the installation of extensions doesn't respect the proxy setting, from the UI or via the `--install-extension` command line flag.  Would graetly appreciate a fix for that.

**Comment by jrderuiter** [comment] 2019-04-26 06:55
For me the main issue was also with installing extensions (I get a timeout because code-server doesn't go through the proxy). I also have some issues with icons (file icons, for example) in the browser, but that's probably not related.

**Comment by fancl20** [comment] 2019-04-26 07:34
The problem is that there exist many extensions to download binaries they need not during installing but during the first start up (like official C/C++ extension or Golang extensions). I'm not sure whether they regard the system proxy preference or using vscode setting.

**Comment by t-d-d** [comment] 2019-05-02 00:41
@fancl20 are you aware of the vscode setting for this:
```
  // Use the proxy support for extensions.
  //  - off: Disable proxy support for extensions.
  //  - on: Enable proxy support for extensions.
  //  - override: Enable proxy support for extensions, override request options.
  "http.proxySupport": "override",
```
Maybe this https://github.com/cdr/code-server/pull/545 will help resolve this.  Waiting on a new release to test it.

@jrderuiter regarding the icons, I just raised https://github.com/cdr/code-server/issues/627 .  Agree, I don't think it is related.

**Comment by t-d-d** [comment] 2019-05-02 03:59
@fancl20 I can confirm that the rest-client extension works fine behind a proxy with `http_proxy` set and the above vscode setting.

**Comment by nhooyr** [comment] 2020-01-28 00:14
Related https://github.com/nodejs/node/issues/15620

**Comment by nhooyr** [comment] 2020-02-21 19:52
Let's just use https://www.npmjs.com/package/proxy-from-env ?

**Comment by benjaminbauer** [comment] 2020-04-06 15:56
I am also running code-server behind a proxy. What I find weird is, the extensions marketplace loads w/o any issues:
![image](https://user-images.githubusercontent.com/1436222/78578285-995c9900-782f-11ea-8f0d-88905f132207.png)

but the installation fails:
![image](https://user-images.githubusercontent.com/1436222/78578261-8d70d700-782f-11ea-82af-f4fc3925da51.png)

The error message does not reveal the cause. I even started code-server verbose with `-vvv`, but no errors/warnings or any hints regarding the installation failure of the extension

**Comment by code-asher** [comment] 2020-04-06 16:52
Hmm, the extension list query runs from your browser while the download runs from code-server so that might explain the discrepancy. Were there any logs in VS Code's `output` panel? It would be under `(Log) Remote Extension Host` in the dropdown.

**Comment by benjaminbauer** [comment] 2020-04-07 09:12
@code-asher : I do not get any related output, when the installation of the extension fails in `Log (Remote Extension Host)`

However I get:

in `Log (Window)`:
```
[2020-04-07 11:04:06.029] [window] [trace] RequestService#request https://storage.googleapis.com/vscode-extension-assets/vscode-extensions/vscode/ms-python/python/2020.3.69010/Microsoft.VisualStudio.Code.Manifest
[2020-04-07 11:04:06.120] [window] [trace] RequestService#request https://storage.googleapis.com/vscode-extension-assets/vscode-extensions/vscode/ms-python/python/2020.3.69010/Microsoft.VisualStudio.Services.Content.Details
[2020-04-07 11:04:06.133] [window] [trace] RequestService#request https://storage.googleapis.com/vscode-extension-assets/vscode-extensions/vscode/ms-python/python/2020.3.69010/Microsoft.VisualStudio.Code.Manifest
[2020-04-07 11:04:06.141] [window] [error] getaddrinfo ENOTFOUND storage.googleapis.com: downloading: getaddrinfo ENOTFOUND storage.googleapis.com
    at /home/vagrant/.local/bin/code-server-3.0.2-linux-x86_64/lib/vscode/out/vs/server/entry.js:373:524
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

in `Log (Remote Server)`
```
[2020-04-07 09:06:11.212] [remoteagent] [info] Installing extension: ms-python.python
[2020-04-07 09:06:11.213] [remoteagent] [trace] Started scanning user extensions
[2020-04-07 09:06:11.214] [remoteagent] [trace] Scanned user extensions: 0
[2020-04-07 09:06:11.214] [remoteagent] [trace] Started downloading extension: ms-python.python
[2020-04-07 09:06:11.214] [remoteagent] [trace] ExtensionGalleryService#download ms-python.python
[2020-04-07 09:06:11.214] [remoteagent] [trace] RequestService#request https://storage.googleapis.com/vscode-extension-assets/vscode-extensions/vscode/ms-python/python/2020.3.69010/Microsoft.VisualStudio.Services.VSIXPackage?redirect=true&install=true
[2020-04-07 09:06:11.217] [remoteagent] [trace] RequestService#request https://storage.googleapis.com/vscode-extension-assets/vscode-extensions/vscode/ms-python/python/2020.3.69010/Microsoft.VisualStudio.Services.VSIXPackage?install=true
[2020-04-07 09:06:11.220] [remoteagent] [error] Failed to install extension: ms-python.python getaddrinfo ENOTFOUND storage.googleapis.com
```

Hint: The timestamps are different due to timezone foobar, the logs are take immediately after trying to install the plugin.

**Comment by kylecarbs** [comment] 2020-04-07 15:26
Seems like you aren't able to resolve `storage.googleapis.com`. Is your DNS setup properly?

**Comment by benjaminbauer** [comment] 2020-04-08 15:33
@kylecarbs no, thats not the case. `curl storage.googleapis.com` works just fine, since it respects `http_proxy` and `https_proxy`. When I unset the proxy variables in the ENV I also get  `curl: (6) Could not resolve host: storage.googleapis.com`

**Comment by kylecarbs** [comment] 2020-04-09 01:35
Sorry I misunderstood. code-server doesn't support the `HTTP_PROXY` and `HTTPS_PROXY` environment variables atm. That's why you're getting the issue mentioned.

**Comment by nhooyr** [comment] 2020-04-27 12:45
Part of the problem is definitely that we'd want to use the proxy client side as well but we can't really set it there.

**Comment by nhooyr** [comment] 2020-12-04 21:13
Will be in the next release! I think it's good to add a FAQ entry explaining how it works and how you need to also configure your browser.

**Comment by nhooyr** [comment] 2020-12-08 14:28
Will be in the next release! 🎊 🍻

**Closed by nhooyr** 2020-12-08 14:28 UTC
Labels: feature
