### ISSUE TITLE
Cannot install extension manually

### ISSUE THREAD

**Issue by fan-yu-wang** [cdr/code-server#2294] opened 2020-11-12 09:39 UTC
- Web Browser: Firefox 79.0
- Local OS: Ubuntu-20.04.1
- Remote OS: Ubuntu-20.04.1
- Remote Architecture: amd64
- `code-server --version`: 3.6.2

I was trying to download and install Jupyter manually since the marketplace doesn't have it. But can't install the .vsix file, and the error message was like: "Corrupt ZIP: end of central directory record signature not found".

I downloaded it from here: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter

And I tried to install other extensions:
[Successed] C#: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp
[Successed] Vetur: https://marketplace.visualstudio.com/items?itemName=octref.vetur
[Failed] Go: https://marketplace.visualstudio.com/items?itemName=golang.Go

Any ideas?

![image](https://user-images.githubusercontent.com/58545333/98922884-f4fdac00-250d-11eb-8b09-b71cabef1b4e.png)

**Comment by code-asher** [comment] 2020-11-12 19:16
Hmm so far I haven't had any luck replicating on 3.6.2. Does unzipping
those files manually work?

**Comment by fan-yu-wang** [comment] 2020-11-13 02:53
Can I ask how to unzip and install it? I didn't find any vsix file after the extraction.

It seems like I can only install the extensions that code-server marketplace has, whether automatically or manually...

**Comment by code-asher** [comment] 2020-11-13 17:13
I was thinking of unzipping the extension on the command line. If it
works then it indicates code-server is the problem but if it doesn't
then it means the zip actually is corrupt. For example:

```
$ unzip golang.Go-0.18.1.vsix
```

**Comment by fan-yu-wang** [comment] 2020-11-16 05:58
You're right. I can only unzip some of the files. Maybe it caused by my OS? The file names are not highlighted as expected in the terminal.

![image](https://user-images.githubusercontent.com/58545333/99217742-c8020f80-2813-11eb-89c4-1c3f31a40e85.png)

**Comment by code-asher** [comment] 2020-11-16 19:28
Oh that's interesting. I think `ls` only colors based on the file
extension or permissions so maybe the permissions are different? Could
check with `ls -l`. If the permissions aren't different then I'm not
sure; maybe it's checking the file content which makes the corrupted
files not get colored since they aren't valid archives.

It could be caused by a network glitch causing the download to be
incomplete or corrupted. Does re-downloading help at all?

What do you get if you run `sha256sum *.vsix`? Here's what I've got:

```
6f659add350b4109c19b5ff19c3081f5266313e5b1cf9c01b6d8c312d7fcaa51  golang.Go-0.18.1.vsix
93e6b322c187ce726a81882ae3903af9f146694836542853995ea15f6e9e8035  ms-dotnettools.csharp-1.23.6.vsix
bd388b0abd52bf1c56a19cf8c583bae215da5293ab4a26498520118e20829b2d  ms-toolsai.jupyter-2020.11.358541065.vsix
80886e117c8f007d6ab1f0df9e99df14c1489e1d57b4933bdbb3d325ea01b5aa  octref.vetur-0.30.2.vsix
```

**Comment by fan-yu-wang** [comment] 2020-11-18 05:50
Re-downloaded and it works! Thank you!

**Comment by code-asher** [comment] 2020-11-18 16:48
Glad to hear it! I'll go ahead and close this since I don't think there's anything we can do on the code-server side. If you think of anything though let me know.

**Closed by code-asher** 2020-11-18 16:48 UTC
