### ISSUE TITLE
Changing display language does not create locale.json

### ISSUE THREAD

**Issue by aleleba** [cdr/code-server#2306] opened 2020-11-16 02:00 UTC
Spanish Language pack is not working, when activate and reload it still be in english.

- Web Browser:
- Local OS:
- Remote OS: Docker Container
- Remote Architecture:
- `code-server --version`: 

code-server: v3.6.2
 VS Code: v1.50.0
Commit: 9bde62fbd611a7a91c5f327fa43e0d06f1379169
Date: 2020-11-02T23:35:06Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36

**Comment by code-asher** [comment] 2020-11-16 20:03
We have a bug where changing the display language from the UI doesn't
actually create the necessary locale file. As a workaround for now this
can be done manually. For example:

```
echo '{"locale": "es"}' > ~/.local/share/code-server/User/locale.json
```

The location of this file might be different if you are using a custom
data directory.

**Comment by code-asher** [comment] 2020-12-02 21:11
Turns out this was caused by the same issue that caused https://github.com/cdr/code-server/issues/2274. It should be fixed now!

**Closed by code-asher** 2020-12-02 21:11 UTC
Labels: bug, needs-investigation
