### ISSUE TITLE
[v2] SSL flags are broken

### ISSUE THREAD

**Issue by JonnyBDev** [cdr/code-server#983] opened 2019-09-14 17:04 UTC
## System and version
- `code-server` version: 2.1478-vsc1.38.1 - latest relased
- OS Version: Debian 10 Buster 

## Description
I start code-server via commandline. This is my startup:

/home/vscode/code-server --user-data-dir="/home/vscode/data" --cert="/home/vscode/data/certs/MyCertificate.crt" --cert-key="/home/vscode/data/certs/MyKey.key" --host="XXX.XXX.XXX" --port="XXXX" --auth="password" --disable-telemetry

After starting code-server i can go to the site and load it. The console gives me the following output:

info  Server listening on https://XXX.XXX.XXX:XXX
info    - Using custom password for authentication
info    - Using provided certificate and key for HTTPS

After about 30 seconds code-server just exit. There is no warning and i can't find any log with errors in it. This is the only log i currently have:

(data/logs/../removeagent.log)
[2019-09-14 18:57:35.319] [remoteagent] [info] update#setState idle
[2019-09-14 18:57:43.250] [remoteagent] [info] request.url "/"

## Steps to Reproduce

Use my command with the latest version.

**Comment by sr229** [comment] 2019-09-14 20:38
I can't reliably reproduce this, it might be you missing some things like `net-tools` or `openssl`. If you still have those and it still crashes, try removing the certificate flags and run it as HTTP for now.

**Comment by JonnyBDev** [comment] 2019-09-14 20:56
`net-tools` and `openssl` are already installed and up to date. 
I removed the cert flags for now. Running as HTTP is currently working.
5 minutes w/o a crash.

**Comment by sr229** [comment] 2019-09-14 21:47
For now, workaround for certs is to do it in a reverse proxy. I'll raise this to the team. This seems urgent as well due to the nature of usage of the flags.

**Comment by code-asher** [comment] 2019-09-18 22:00
I'd love to replicate this but haven't had any luck so far. How were those keys generated?

**Comment by sr229** [comment] 2019-11-07 15:13
Requesting further information. Failure to reply means it was fixed in your end and I'll close this automatically after 3 days.

**Closed** 2019-11-18 12:52 UTC
Labels: bug, urgent, v2, waiting-for-info
